### ISSUE TITLE
RoR / SQLite3: no such column: distance / finding object-ids near X

### ISSUE THREAD

**Issue by Mad-Onion** [alexreisner/geocoder#1001]
The call `Event.near("29308 Germany", 100).ids` throws an sql-exception:
`ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: distance`

When I disable sorting by distance via `:order => ""` it works:
```
Event.near("29308 Germany", 100, :order => "").ids
 => [166, 248, 290, 700, 132, 304, 503...
```

I'm using rail 4.2.5.2 with the sqlite3-gem

best regards
Tobias

**Comment by alexreisner** [comment]
The problem, as [described in the README](https://github.com/alexreisner/geocoder#activerecord-1) is that the SELECT clause is being modified by `ids`.
