### ISSUE TITLE
Geocoding with multiple fields

### ISSUE THREAD

**Issue by aymericbouzy** [alexreisner/geocoder#1005]
Hi,
My user may or may not provide me with his address. When he does, I want to use his address to geocode him. When he doesn't, I want to use his ip address to approximate his location.

How would you recommend to do this? I haven't found how in the Readme.

Is there maybe a way to use a block with `geocoded_by` in the same way we can use a block for `reverse_geocoded_by`?

Thanks for your help,

Aymeric

**Comment by craigsheen** [comment]
I haven't tried this but could you not just do a check in the method you pass to `geocoded_by` ?

```
geocoded_by :address_or_ip_address

def address_or_ip_address
  if address.blank?
    #return ip address
  else
    # return address
  end
end
```

**Comment by TrangPham** [comment]
Yes you could use geocoded_by using a block similar to reverse_geocoded_by

See https://github.com/alexreisner/geocoder/blob/30f29bf5818788f67da527e3da0cde27e1bbbf7d/lib/geocoder/models/active_record.rb#L11-L40

Both methods can take a block :)

**Comment by aymericbouzy** [comment]
Thanks for both of your answers, that helps a lot :) Sorry for not having thought of it myself.

**Comment by TrangPham** [comment]
No problem!
