### ISSUE TITLE
Error with freegeoip: response was not valid JSON

### ISSUE THREAD

**Issue by arnlen** [alexreisner/geocoder#1009]
When using the FreeGeoIP provider, I get this error message:

```
Geocoding API's response was not valid JSON: ({"ip":"90.34.122.47","country_code":"FR","country_name":"France","region_code":"O","region_name":"Nord-Pas-de-Calais","city":"Lumbres","zip_code":"62380","time_zone":"Europe/Paris","latitude":50.7069,"longitude":2.1208,"metro_code":0});
```

I guess it's because of the parenthesis.
I've opened this [issue on the freegeoip repository](https://github.com/fiorix/freegeoip/issues/167) to get more info about why the API is returning this payload.

From the Geocoder side: is there something we can do?

**Comment by alexreisner** [comment]
On hold until we see what happens with freegeoip.

**Comment by profeg** [comment]
freegeoip.net is down now.  
Available freegeoip.io
