### ISSUE TITLE
geocoded? returns true even if a single coordinate is nil

### ISSUE THREAD

**Issue by mltsy** [alexreisner/geocoder#1010]
It's an edge case, but if coordinates happen to be editable by users or something, you could end up with a single coordinate being nil.  In this case, I believe the `geocoded?` method of a model should return false, but it returns true, because it's only checking that there are > 0 coordinates present.  It should check for exactly 2.

**Comment by alexreisner** [comment]
Thanks! Totally agree with this. It's also inconsistent with the behavior of `geocoded` and `not_geocoded` scopes: https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/stores/active_record.rb#L20

Unfortunately, fixing it may break some people's apps so I'm not sure whether the change should be made in version 1.3.2 or 1.4.0. Regardless, PR very much welcome.

**Comment by mltsy** [comment]
Yeah, that's true - it probably should wait for 1.4.0
