### ISSUE TITLE
Geocode toponyms inconsistent when searching

### ISSUE THREAD

**Issue by ristovskiv** [alexreisner/geocoder#1013]
This is probably not an issue nor a bug, but I post this because I'm new to geocoding and I can't find a better place to ask this. I have an initializer in a Rails app with 

> Geocoder.configure(timeout: 5, lookup: :google, language: :en,  units: :km)

. Now the language is specifically pointed to be English, but for instance 

> Geocoder.search('Milano, Italy')

.first.city don't return the same output as 

> Geocoder.search('Via Conservatorio, Tricolore, Milano, Italy').first.city

. The first one returns 'Milan' while the second 'Milano'. Even if try something like this

> Geocoder.search('Milano, Italy', params: {language: :en})
> Geocoder.search('Via Conservatorio, Tricolore, Milano, Italy', params: {language: :en})

I still get the same output. If it's possible I need some pointers to solve an issue like this.

**Comment by TrangPham** [comment]
This is really dependent on the api you're using.

For Google Geocoding API here are the results for the two queries:
https://maps.googleapis.com/maps/api/geocode/json?address=Via%20Conservatorio,%20Tricolore,%20Milano,%20Italy&language=en
and 
https://maps.googleapis.com/maps/api/geocode/json?address=Milano,%20Italy&language=en

We are grabbing the locality first as the city.
See https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/results/google.rb#L20-L30

Which according to the Google Geocode API documents: "locality indicates an incorporated city or town political entity."

I'm not sure what the most simple way to solve an issue like this is. 
If you're generally always geocoding the same areas, you could map the resulting city to a confirmed one that you pick.

Something like
``` Ruby
conform_cities = {'Milano':'Milan'}
city = Geocoder.search(address).first.city
city = conform_cities[city] if conform_cities.key? city
``` 

Though this probably is not a very scalable solution.

**Comment by alexreisner** [comment]
@ristovskiv I agree that this is very annoying. Unfortunately I don't think there's anything Geocoder can do to smooth out this particular quirk of Google's geocoding API (which is liable to change any day). If you arrived at a good solution for your app, please let us know!
