### ISSUE TITLE
:ipinfo_io not supported

### ISSUE THREAD

**Issue by hephalump** [alexreisner/geocoder#1017]
Documentation says that ipinfo.io is supported, however, using the gem says:

Geocoder::ConfigurationError: Please specify a valid lookup for Geocoder (:ipinfo_io is not one of: :dstk, :esri, :google, :google_premier, :google_places_details, :yahoo, :bing, :geocoder_ca, :geocoder_us, :yandex, :nominatim, :mapbox, :mapquest, :opencagedata, :ovi, :here, :baidu, :geocodio, :smarty_streets, :okf, :postcode_anywhere_uk, :geoportail_lu, :test, :baidu_ip, :freegeoip, :geoip2, :maxmind, :maxmind_local, :telize, :pointpin, :maxmind_geoip2).

**Comment by alexreisner** [comment]
Coming soon. See #1008.
