### ISSUE TITLE
Exception Errno::ENETUNREACH isn't handled

### ISSUE THREAD

**Issue by Machiaweliczny** [alexreisner/geocoder#1019]
Hey. I've error like this using geocoder 1.2.14
```
Errno::ENETUNREACH: Network is unreachable - connect(2) for "freegeoip.net" port 80
  from net/http.rb:879:in `initialize'
  from net/http.rb:879:in `open'
  from net/http.rb:879:in `block in connect'
  from timeout.rb:88:in `block in timeout'
  from timeout.rb:98:in `call'
  from timeout.rb:98:in `timeout'
  from net/http.rb:878:in `connect'
  from net/http.rb:863:in `do_start'
  from net/http.rb:852:in `start'
  from net/http.rb:583:in `start'
  from geocoder/lookups/base.rb:276:in `make_api_request'
  from geocoder/lookups/base.rb:226:in `fetch_raw_data'
  from geocoder/lookups/base.rb:177:in `fetch_data'
  from geocoder/lookups/freegeoip.rb:25:in `results'
  from geocoder/lookups/base.rb:47:in `search'
  from geocoder/query.rb:11:in `execute'
  from geocoder.rb:22:in `search'
  from geocoder/request.rb:9:in `location'
```

In `lib/geocoder/lookups/base.rb:273` there's make_api_requests
![image](https://cloud.githubusercontent.com/assets/5442370/14249662/11ffcfbc-fa7b-11e5-9af6-1666e0a6ec92.png)
Seems like you are rescuing only `Timeout::Error`

Do you acknowledge this as bug? Or it's supposed to be like that?
I can provide PR that fixes it but need some guidance how you would like it to be handled.

**Comment by Machiaweliczny** [comment]
According to Ruby docs `errno::ENETUNREACH` - "no route to the network is present". Which is true, becasue `freegeoip.net` is down at the moment, but I don't think this is a reason to crash applications.

On master branch you have this issue also - https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/base.rb#L273

**Comment by TrangPham** [comment]
Hi Damian,

Yes please create a PR for this that catches the error and throws one that
had a better error message. Maybe something like check if service is down?

Thanks!

**Comment by jtomaszewski** [comment]
Yup, we could add something like

```rb
      rescue Errno::EHOSTUNREACH, Errno::ETIMEDOUT, Errno::ENETUNREACH
        raise Geocoder::LookupError
```

next to the

```rb
      rescue Timeout::Error
        raise Geocoder::LookupTimeout
```

in the https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/base.rb#L273 . Would that be sufficient?

**Comment by alexreisner** [comment]
@jtomaszewski I think it's important to raise exceptions that indicate whether a request should be tried again as-is or needs to be modified. `LookupError` suggests that there was a problem processing the query, but those three errors are results of network/connectivity issues. Maybe we should add a `Geocoder::NetworkError` exception? @TrangPham: thoughts?

**Comment by TrangPham** [comment]
Agreed that it should be a different error. Geocoder::NetworkError sounds
good

**Comment by abatko** [comment]
Would it be possible to rescue and then try another service (or two) before raising the exception? How can Geocoder be temporarily reconfigured for another service?

```
begin
        _location = request.location 
rescue Geocoder::NetworkError
        # here temporarily change Geocoder configuration to another service
        _location = request.location # try again
end
```

**Comment by TrangPham** [comment]
Hi @abatko 

We've been thinking about the best way to implement a fallback in Geocoder for a while now. Here is an old diff that has one solution: https://github.com/alexreisner/geocoder/pull/746

@alexreisner What are your thoughts? How can we tackle fallbacks now/can we put together a road map for this?

**Comment by alexreisner** [comment]
@TrangPham @abatko yes, would like to get that working. See #351 for discussion. The solutions submitted so far have been (in my opinion) overly complicated, under-tested, and difficult to review, but I'd love to get fallback strategies working for the next minor release. Might require @TrangPham and I to collaborate on a solution as deep familiarity with the gem is needed.

**Comment by abatko** [comment]
[Freegeoip](https://freegeoip.net/) has been down for days. I found [geoip-db](https://geoip-db.com/), and it was easy to create a quick temporary workaround:
```
begin
    _location = request.location
    _latitude = _location.latitude
    _longitude = _location.longitude
rescue Errno::EHOSTUNREACH, Errno::ETIMEDOUT, Errno::ENETUNREACH, Geocoder::NetworkError
    # primary service unreachable, try secondary...
    _page = Net::HTTP.get(URI('https://geoip-db.com/json/geoip.php'))
    _latitude = JSON.parse(_page)['latitude'].to_f
    _longitude = JSON.parse(_page)['longitude'].to_f
end
```

**Comment by patrickemuller** [comment]
@abatko the problem is that geoip-db only show the IP for the origin of the request, and if you made this from your backend probably this won't be the IP of the cliente-side, in this case if you're using Heroku (for example) the IP always will be from the server and not from the customer outside the screen. I couldn't figure any option on the URL of geoip-db to search for a specific IPv4 address.

**Comment by abatko** [comment]
@patrickemuller Right! Thanks for pointing that out. I will have to return to this task.

**Comment by djol** [comment]
I've run into this same problem due to the loss of Freegeoip.

Although I've moved to a different location service, is there an easy way to avoid a geocoded_by model from crashing if geocoder runs into a network error?

I use _geocoded_by_ in my User model to display user locations. When Freegeoip went down, this prevented creating or updating any user records as geocoder was throwing the ENETUNREACH exception.

```
  geocoded_by :current_sign_in_ip do |obj,results|
    if geo = results.first
      obj.city, obj.country, obj.latitude, obj.longitude = geo.city, geo.country, geo.latitude, geo.longitude
      #obj.zipcode = geo.postal_code
    end
  end
```

I don't think wrapping a begin/rescue/end is possible here. Any suggestions of how best to handle geocoder exceptions within a model?

**Comment by zia954** [comment]
same problem here, will it affect other services of Geocoder?

**Comment by TrangPham** [comment]
@zia954 Sorry for getting back to you so late. Yes this error can occur on other services of Geocoder. It most likely means the the service was down when you were trying to query it.
