### ISSUE TITLE
Google provider showing wrong country

### ISSUE THREAD

**Issue by pitops** [alexreisner/geocoder#1023]
I tried to use :google service, i have setup an api key but when i tried to test it locally and even in development, it gets wrong country. Locally using my local ip, it finds me in Iraq, and in production it finds me in Philippines. I am located in Cyprus. The only line of code i use geocoder for is the following

`country = request.location.country_code`
`p "this is your country #{country}"`

in my geocode initializer file
```
Geocoder.configure(
  :timeout=>30,
  :lookup=>:google,
  :ip_lookup=>:google,
  :language=>:en,
  :use_https=>true,
  :api_key=>"my api key",
)
```

**Comment by erdostom** [comment]
I don't think Google provides IP Geocoding. Try a provider listed here https://github.com/alexreisner/geocoder#ip-address-services
