### ISSUE TITLE
SSL error - Google

### ISSUE THREAD

**Issue by jlhonora** [alexreisner/geocoder#1034]
I've been seeing sporadic issues with google's SSL handshake:

`SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A`

I'm using [this fix](https://github.com/jlhonora/geocoder/commit/530fc558a33400aad4dc905cf912f3162f9c950b) in production:

```
diff --git a/lib/geocoder/lookups/base.rb b/lib/geocoder/lookups/base.rb
index eb39893..956f050 100644
--- a/lib/geocoder/lookups/base.rb
+++ b/lib/geocoder/lookups/base.rb
@@ -274,6 +274,12 @@ module Geocoder
         uri = URI.parse(query_url(query))
         Geocoder.log(:debug, "Geocoder: HTTP request being made for #{uri.to_s}")
         http_client.start(uri.host, uri.port, use_ssl: use_ssl?, open_timeout: configuration.timeout, read_timeout: configuration.timeout) do |client|
+          if use_ssl?
+            client.instance_eval {
+              @ssl_context = OpenSSL::SSL::SSLContext.new
+              @ssl_context.set_params({:options=> OpenSSL::SSL::OP_NO_SSLv2 | OpenSSL::SSL::OP_NO_SSLv3 | OpenSSL::SSL::OP_NO_COMPRESSION})
+            }
+          end
           req = Net::HTTP::Get.new(uri.request_uri, configuration.http_headers)
           if configuration.basic_auth[:user] and configuration.basic_auth[:password]
             req.basic_auth(
```

but I'm not sure if it fixes the problem entirely. Besides, there could still be some lookups where SSLv3 (or lower) is needed.

Anyone else experiencing this?

**Comment by jlhonora** [comment]
Related: https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only

Been using that fix in production for a few days now. @alexreisner I can make a PR if you're OK with it...

**Comment by alexreisner** [comment]
Yes, thanks. Open to a pull request on this.

**Comment by alexreisner** [comment]
Is it possible to apply this only to the Google lookup by defining `http_client` there, or does the code need to be executed within the `start` block? If the latter, we'll need to test this with other SSL lookups.

**Comment by jlhonora** [comment]
> Is it possible to apply this only to the Google lookup

That's the best way to proceed in my opinion. But to do this we need a `Net::HTTP` instance (not just the class), since we're redefining the SSL context within that specific instance. Note that `http_client` is a private method, so we'll need to move that in order to override it in any case.

> we'll need to test this with other SSL lookups

Totally agree. As a side node, any ideas on how to test the calls themselves? The test suite redefines the `make_api_request` method, thus removing the option of hitting the servers themselves.

Let's decide on these and I'll open the PR (changes so far are in https://github.com/jlhonora/geocoder)

**Comment by alexreisner** [comment]
Returning an instance instead of a class seems fine, but why do we have to move the method? (Definitely don't want to make it public.)

As for testing, we should really be mocking HTTP requests (using webmock or similar) but the amount of work required to convert the existing tests is pretty large, so that hasn't been done yet. Since this issue is intermittent, it seems hard to test for... Open to suggestions.

**Comment by alexreisner** [comment]
Also, note [proxy configuration tests](https://github.com/alexreisner/geocoder/blob/master/test/unit/proxy_test.rb) when changing `http_client`'s return value from class to instance.

**Comment by jlhonora** [comment]
[Some progress](https://github.com/jlhonora/geocoder/commit/9731db473ed8444a24a94e00011b6a84b7b3c4c6):

1. I ended up not changing the `http_client` method, since `ssl_options` can't be modified outside the `start` block. I ended up making a new method, `configure_ssl` which is called in the `start` block. That way, each lookup can configure ssl (or the client) however it pleases.

2. Currently, the default behavior for `configure_ssl` is no op. I find this a bit insecure, and if a lookup is using e.g. SSLv3 it should enable it explicitly. But this is just my opinion, and a change of this magnitude should be left to the maintainer's decision :)

3. No idea how to easily test this without making major changes in the test suite. Wireshark confirms successful use of TLS 1.2, but I'd definitely like a more robust approach.

**Comment by alexreisner** [comment]
Thanks!

1. I think this looks good. Can you just change the name of the method to `configure_ssl!` (with bang) so it's clearer that it has side effects?
2. Agree that this may not be ideal, but also that it's a big (potentially breaking) change that should probably be handled in a separate issue.
3. Here too, let's create a separate issue for the untested functionality. At some point we'll likely change the way the tests run and that will be a better time to add a test for this.
