### ISSUE TITLE
Mapzen reverse geocoding param error

### ISSUE THREAD

**Issue by alex-gutierrez** [alexreisner/geocoder#1039]
With version 1.3.4 of **geocoder**, when trying to perform a reverse geocode using **:mapzen** as lookup engine, it returns a 400 error.

Inspecting the created URL, the coordinates are included in a `text` parameter:

https://search.mapzen.com/v1/reverse?api_key=search-xxx&size=1&text=[39.57,+-0.48]

This request returns the following error:

> _parameters point.lat and point.lon must both be specified_

According to [Mapzen docs](https://mapzen.com/documentation/search/reverse/), it should be set as separated `point.lat` and `point.lon` parameters:

https://search.mapzen.com/v1/reverse?api_key=search-xxx&size=1&point.lat=39.57&point.lon=-0.48

**Comment by alexreisner** [comment]
Thanks. Open to a pull request for this. I assume it's the same for Pelias? (cc @graphaelli, @TrangPham)

**Comment by graphaelli** [comment]
Saw this but haven't gotten around to writing any code for it yet.  Yes, the issue would be the same for pelias.   we did not implement reverse geocoding since we don't use it.  (cc @ncavig)
