### ISSUE TITLE
Geocoder::Lookup::Test & BigDecimal

### ISSUE THREAD

**Issue by jufemaiz** [alexreisner/geocoder#1042]
Hi guys, discovered a problem trying to stub reverse geocodes. My lat/lng comes from an object which is a number stored in BigDecimal object each.

I've stubbed with the following:
```ruby
Geocoder::Lookup::Test.add_stub(
  [40.7143528,-74.0059731], [
    {
      'latitude'     => 40.7143528,
      'longitude'    => -74.0059731,
      'address'      => 'New York, NY, USA',
      'state'        => 'New York',
      'state_code'   => 'NY',
      'country'      => 'United States',
      'country_code' => 'US'
    }
  ]
)
```

but instead end up getting this error:
```ruby
unknown stub request [#<BigDecimal:7fd795afd6a0,'0.407143528E2',18(45)>, #<BigDecimal:7fd795afcf70,'-0.740059731E2',18(45)>]
```

Any thoughts on a fix or patch?

**Comment by jufemaiz** [comment]
Temporary solution is obviously to use:

```ruby
Geocoder::Lookup::Test.add_stub(
  [BigDecimal('40.7143528'),BigDecimal('-74.0059731')], [
    {
      'latitude'     => 40.7143528,
      'longitude'    => -74.0059731,
      'address'      => 'New York, NY, USA',
      'state'        => 'New York',
      'state_code'   => 'NY',
      'country'      => 'United States',
      'country_code' => 'US'
    }
  ]
)
```

**Comment by lime** [comment]
That workaround was what I was going to suggest. :)

It's not immediately obvious to me that this is something geocoder should take into account. You're stubbing a very particular input, and that happens to be an array of BigDecimals. I mostly stub strings (city or street names).

When stubbing I would imagine it's better to be very exact, rather than trying to guess at what other inputs should be covered.

**Comment by lime** [comment]
Of course it might become frustrating e.g. if you often have to stub both the BigDecimal and the float variant of the same coordinates. In that case you could maybe write your own stubbing helper which creates the multiple variations:
```ruby
def add_coordinate_stub(coordinates, results)
  Geocoder::Lookup::Test.add_stub(coordinates.map(&:to_f), results)
  Geocoder::Lookup::Test.add_stub(coordinates.map(&:to_d), results)
end

**Comment by jufemaiz** [comment]
@lime yep I'll close it out but it's now discoverable for others. Using the stub based on BigDecimal works ok :)
