### ISSUE TITLE
Need to be able to cache the Esri access token

### ISSUE THREAD

**Issue by aaronpk** [alexreisner/geocoder#1049]
Currently, when an api key is configured for the Esri provider (client_id and client_secret), then the gem makes a new HTTP request to the token endpoint on each geocode request, and generates a new token for each. When performing many queries in a row, this is very inefficient.

The Esri token response indicates the lifetime of the token that is returned, so if a cache is configured, the gem should cache the token that is generated for the time indicated.

**Comment by aaronpk** [comment]
I started looking at how to implement this, but ran into a bit of a roadblock. It appears the current `Geocoder::Cache` class has no way to set the lifetime of a cached item. 

I found the [example](https://github.com/alexreisner/geocoder/blob/master/examples/autoexpire_cache_redis.rb) of extending the Cache class to set the expiration date of all items as they are set, but for this, we need to be able to set the expiration per item.

Any suggestions on how to proceed? Should I try to add the concept of expiration to the `Cache` class itself?

**Comment by alexreisner** [comment]
See #1048 for solution.

**Comment by aaronpk** [comment]
This issue is actually about caching the token itself, not caching the geocoded result. Since the Esri provider allows the user to configure it with a client_id and client_secret, and the gem exchanges those for an access token on each geocode request, I would like to be able to cache that token that's generated to reuse it between requests.

**Comment by alexreisner** [comment]
Ah, I see. I think this will be solved by #1047...

**Comment by aaronpk** [comment]
@alexreisner I still need to be able to cache the access token used with Esri requests. The tokens that are generated from the Esri API key are actually valid for up to 24 hours, so the token does not need to change on every request, and we could save an HTTP request by re-using the existing token instead of generating a new one each request. 

As far as I can tell, there is no existing mechanism in the gem I can use for this. I'm open to suggestions, but I need to move forward asap.

My thought was to extend the `Cache` class to add the ability to set the expiration per item. I'm happy to implement this in the simple Ruby instance cache as well as with Memcache and Redis.

**Comment by alexreisner** [comment]
Isn't it sufficient that it gets stored in the configuration? https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/esri.rb#L81

**Comment by aaronpk** [comment]
That will only "cache" it as long as the instance is around. I'm using this in a Sidekiq script, so I actually have multiple instances of the geocoder in many processes across multiple servers. Ideally I can share this token across all of them to speed things up by not generating tokens all the time.

**Comment by alexreisner** [comment]
Ah, I see. I'm open to a PR, as long as it doesn't limit caching back-end choices (ie, don't want to break any existing functionality).
