### ISSUE TITLE
Cache keys should not include API credentials

### ISSUE THREAD

**Issue by aaronpk** [alexreisner/geocoder#1059]
Currently the default cache key for providers is the full query string of the request including the provider's token if set. This is bad for a number of reasons.
- If the token changes, the cache is effectively invalidated
- Storing the token in a cache is a potential security issue since the token may then be accessible to other parts of the system

Including the token in the cache key provides literally no benefit, and only creates potential problems. I would like to see a solution to this in the base lookup that prevents the token from being included in the cache key for all providers.

**Comment by alexreisner** [comment]
Example of one (the only) lookup that doesn't use raw query URL for cache key: https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/esri.rb#L37

Note that fixing this issue will also break existing cache implementations. So we should think about how fixes get released.

**Comment by alexreisner** [comment]
Fixed by c18c0e084496b9dc84ac1fdb5d293da67cc45de8
