### ISSUE TITLE
Can't figure out from documentation how to handle geocoding two sources.

### ISSUE THREAD

**Issue by fergyfresh** [alexreisner/geocoder#1065]
If you consider having a work address and a home address for a user. How would you go about geocoding both of them? I have a similar implementation below in my project and It only geocodes on of them. It only correctly geocodes the `:work` address and the other address `:address` is `nil`. When I originally only had the `:address` and didn't have `:work` it geocoded `:address` correctly. #confused #help

``` ruby
class User < ActiveRecord::Base
  geocoded_by :address
  geocoded_by :work,  :latitude => :work_latitude, :longitude => :work_longitude 
  after_validation :geocode
end 
```

Any insight would be great. I know you are busy, but I would like to know how I could help make this a base feature if it is not already.

**Comment by TrangPham** [comment]
Hi @fergyfresh 

There is currently no built in way to do this, please refer to the answer here: https://github.com/alexreisner/geocoder/issues/397

Hope that helps. 

**Beginner Task**:
create a PR with an amendment to the README with this information (multiple locations in one model). That way others can find it later

**Comment by fergyfresh** [comment]
Would you want a built in way to do this or is the assumed implementation to have an Address model that is geocoded. That way my home and work addresses would be Address ActiveRecord Models that refer to the User model with relationships? 

Or would passing multiple things that need to be geocoded to the geocoded_by method ever be the way you'd want to do things?

It is less than ideal for me to maintain two separate implementations of the same feature, which is effectively what #397 is telling me to do.

**Comment by alexreisner** [comment]
Two separate Address models sounds reasonable but I'm not familiar enough with your app to recommend anything.

Allowing multiple geocoded points per object would alter some fundamental assumptions of the gem. I'm not totally opposed, but it would need to be 100% compatible with the current syntax and avoid introducing significant complexity to the code. My feeling is that it's not a common enough use case to warrant big changes.

**Comment by fergyfresh** [comment]
My ideal implementation would be the following:

```ruby
class User < ActiveRecord::Base
  geocoded_by :address, :work,  :latitude => :work_latitude, :longitude => :work_longitude 
  after_validation :geocode
end 
```

which would allow you to have multiple geocodeable parameters.

`:address` would work like it already does by default mapping longitude to longitude and latitude to latitude, then every additional one would have to specify how it deviates from the default as you wouldn't want to continuously allow the user of the gem to put `geocoded_by :address, :work` and override the first default set with the second.

If I am entirely offbase let me know and I will just do the Address model. Just hate having extra models when it can be done in the other without any stretch.

**Comment by alexreisner** [comment]
Yeah, adding code to support that is not a simple task. For now I'd recommend using what's recommended in #397, basically:

    after_validation :geocode_home_and_work
    def geocode_home_and_work
      self.home_latitude, self.home_longitude = Geocoder.coordinates(home_address)
      # same for work
    end

**Comment by fergyfresh** [comment]
So does the above solution make the `geocoded_by` part of this go away? Forgive me for I am a bit of a novice with the gem.

This is a better solution than I was thinking of originally and is a good middle ground though. Thanks for your time @alexreisner and I appreciate the insight. Any more help is greatly appreciated.

**Comment by alexreisner** [comment]
It does make the `geocoded_by` part go away, however in doing so you lose the ability to do `near` queries with the easy syntax (`User.near` or `user.nearbys`).

**Comment by fergyfresh** [comment]
Hmmm. Interesting. Would this save me at all for doing User.near on home addresses?
```ruby
geocoded_by :address
after_validation :geocode
def geocode
  self.geocode
  self.work_latitude, self.work_longitude = Geocoder.coordinates(work_address)
end
```
Or does this make your eyes bleed and "everyone is now dumber for having to hear my incoherent babbling" [Billy Madison Quote].

**Comment by alexreisner** [comment]
Ha! Yep, that should work.
