### ISSUE TITLE
Search query not in English

### ISSUE THREAD

**Issue by MSprut** [alexreisner/geocoder#1069]
Can I make Geocoder.search query not in English? Thanks.

**Comment by TrangPham** [comment]
Yes - you can do this if the API you are querying supports this functionality. 

For example google api specifications for languages are here: https://developers.google.com/maps/faq#using-google-maps-apis

The way you'd use this with geocoder is to pass the params through:
```Ruby
Geocoder.search('123 rue fake', : language => 'fr')
```

I'll add this to the read me as well

**Comment by MSprut** [comment]
Thanks TrangPham. I tried such method. This method changes language of a reply to the request, but not language of request.  I can be mistaken, but it didn't help me. I tried to send from rails console a request with the address in Russian and the geocoder returned "Invalid request". It turned out that it is necessary to convert the text of request in Russian into the utf8 format.

**Comment by TrangPham** [comment]
Can you please paste your Geocoder config as well as the specific Geocoder.search you are sending? Also what version of Geocoder are you using?

Thanks

**Comment by MSprut** [comment]
irb(main):003:0> Geocoder.config
=> {:timeout=>3, :lookup=>:google, :ip_lookup=>:freegeoip, :language=>:ru, :http_headers=>{}, :use_https=>false, :http_proxy=>nil, :https_proxy=>nil, :api_key=>nil, :cache=>nil, :cache_prefix=>"geocoder:", :basic_auth=>{}, :logger=>:kernel, :kernel_logger_level=>2, :always_raise=>[], :units=>:mi, :distances=>:linear}
---------------------------------------------------------------------------------------------
irb(main):004:0> Geocoder.search("18 Мичурина улица, Луганск")
Geocoding API error: 400 Bad Request
Google Geocoding API error: invalid request.
=> []
--------------------------------------------------------------
irb(main):006:0> Geocoder.search(("18 Мичурина улица, Луганск").encode("utf-8"))
=> [#<Geocoder::Result::Google:0x3829e48 @data={"address_components"=>[{"long_name"=>"18", "short_name"=>"18", "types"=>["street_number"]}, {"long_name"=>"вулиця М?чур?на", "short_name"=>"вулиця М?чур?на", "types"=>["route"]}, {"long_name"=>"Артем?вський район", "short_name"=>"Артем?вський район", "types"=>["political", "sublocality", "sublocality_level_1"]}, {"long_name"=>"Луганськ", "short_name"=>"Луганськ", "types"=>["locality", "political"]}, {"long_name"=>"Луганська м?ськрада", "short_name"=>"Луганська м?ськрада", "types"=>["administrative_area_level_3", "political"]}, {"long_name"=>"Луганська область", "short_name"=>"Луганська область", "types"=>["administrative_area_level_1", "political"]}, {"long_name"=>"Украина", "short_name"=>"UA", "types"=>["country", "political"]}], "formatted_address"=>"вулиця М?чур?на, 18, Луганськ, Луганська область, Украина", "geometry"=>{"bounds"=>{"northeast"=>{"lat"=>48.5562399, "lng"=>39.2777929},
"southwest"=>{"lat"=>48.556057, "lng"=>39.277629}}, "location"=>{"lat"=>48.5561484, "lng"=>39.277711}, "location_type"=>"ROOFTOP", "viewport"=>{"northeast"=>{"lat"=>48.55749743029149, "lng"=>39.2790599302915}, "southwest"=>{"lat"=>48.5547994697085, "lng"=>39.2763619697085}}}, "partial_match"=>true, "place_id"=>"ChIJScP42sHaH0EROIiMZQsI_ZQ", "types"=>["premise"]}, @cache_hit=nil>]

**Comment by TrangPham** [comment]
Ah I see what you mean now. @alexreisner What do you think is the better way to handle this? I'm not sure if automatically encoding everything as utf8 is what we should do

**Comment by MSprut** [comment]
Not to create a new subject I will ask here.
Still there is a problem with operation of the geocoder with Yandex. The geocoder of Google doesn't return many addresses in case of request in Russian, the geocoder of Yandex returns them better, but I won't understand in what a problem. For example:
---------------------------------------------
irb(main):007:0> Geocoder.configure(:lookup=>:yandex)
=> {:timeout=>3, :lookup=>:yandex, :ip_lookup=>:freegeoip, :language=>:ru, :http_headers=>{}, :use_https=>false, :http_proxy=>nil, :https_proxy=>nil, :api_key=>nil, :cache=>nil, :cache_prefix=>"geocoder:", :basic_auth=>{}, :logger=>:kernel, :kernel_logger_level=>2, :always_raise=>[], :units=>:mi, :distances=>:linear}
---------------------------------------------
irb(main):009:0> Geocoder.search("18 Мичурина улица, Луганск")
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Thanks

**Comment by MSprut** [comment]
Geocoder v1.3.7

**Comment by alexreisner** [comment]
@TrangPham I have the same reaction, but I think it should depend on what encoding the particular API accepts. Basically, we need to make sure that the text is converted into a valid query according to the API's rules. If UTF-8 encoding makes this work for Google (in 100% of cases, without major performance hit), then perhaps we should do that.

**Comment by TrangPham** [comment]
Sorry it has gotten a very long time to get back to you @MSprut.

**Beginner Task**
Encode Google's API request with UTF-8 encoding

**Comment by swentling87** [comment]
Trying to get involved in some OS and tried to recreate this issue but I'm finding that Queries made in Russian are going through just fine without forcing a UTF-8 encoding. 
`2.3.3 :001 > Geocoder.search("18 Мичурина улица, Луганск")
 => [#<Geocoder::Result::Google:0x007fc762563430 @data={"address_components"=>[{"long_name"=>"18", "short_name"=>"18", "types"=>["street_number"]}, {"long_name"=>"Michurina Street", "short_name"=>"Michurina St", "types"=>["route"]}....`

`2.3.3 :003 > Geocoder.search("torbochka Сумки и аксессуары")
 => [#<Geocoder::Result::Google:0x007fc762502180 @data={"address_components"=>[{"long_name"=>"24А", "short_name"=>"24А", "types"=>["street_number"]}, {"long_name"=>"Tarasivs'ka Street", "short_name"=>"Tarasivs'ka St", "types"=>["route"]},`

With that said, I've attempted the update anyways and it works on the console. #1189

**Comment by alexreisner** [comment]
I suspect the issue was the encoding being used in @MSprut's console. I can't reproduce. And in any case, forcing encoding is not a good idea.

**Comment by Startouf** [comment]
Hey @TrangPham I was looking for a way to change the language for a request at runtime (not via a class eval config) and was about to open a ticket until I stumbled upon your previous answer that it is possible to use

> , :params => {:language => 'fr'})

I could not find this easily in the repo/wiki/doc, might this be worth editing some wiki to indicate this ? (although it is likely to be provider-specific)

Actually I have another requirement on my application, which is that users must be able to type in either French or English, some I might have to retrieve several translations for the same place at once, is this something that can be done easily (eg. with google ?) should I open a ticket about this ?

**Comment by alexreisner** [comment]
@Startouf this is actually mentioned in [the lookup config section of the README](https://github.com/alexreisner/geocoder#geocoding-service-lookup-configuration) though it's not as clear as it could be. I'll take a look at that.

For using multiple languages, you'd have to look at how your API works but I suspect you're going to have to do one query for each language (ie, I don't think any API will return a single result in multiple languages).
