### ISSUE TITLE
Add suppport for Location IQ

### ISSUE THREAD

**Issue by tinderfields** [alexreisner/geocoder#1070]
http://locationiq.org/ is a new service which offers a generous 30k limit per day on their free plan.

Seems a good provider to support.

**Comment by TrangPham** [comment]
Hi, we welcome you to add a pull-request for this :)

Please look at this PR as an example: https://github.com/alexreisner/geocoder/pull/997

**Comment by gopi-ar** [comment]
Thanks for adding us to the list, @tinderfields ! We don't have any ruby devs on our team to add this PR, though. @TrangPham ours is a much faster version of the OSM Nominatim API, updated daily. The API specs are exactly the same, so perhaps you could just clone the providers?

**Comment by lime** [comment]
@gopi-ar That's good info for anyone who wants to give it a try. :)

It might even make sense to subclass the `Nominatim` provider, the same way as e.g. `Dstk` subclasses `Google`: [lookups/dstk.rb](https://github.com/alexreisner/geocoder/blob/v1.3.6/lib/geocoder/lookups/dstk.rb)

If you want to give it a try, Geocoder is in my opinion one of those libraries that should be easy to approach even for a first-time rubyist. ;) And the maintainers are really helpful in guiding you through any quirks you encounter in your PRs.

**Comment by alexreisner** [comment]
See also, as a guide: c278f94cb096215283bb35e52901159cb1e311ac

**Comment by gopi-ar** [comment]
@lime @alexreisner our intern @aleemuddin13 submitted a PR integrating with LocationIQ. He had a lot of difficulty writing tests (because OSM doesn't require an API key and we do), would appreciate any help from you folks to help finish the PR.

**Comment by jstenhouse** [comment]
Any chance we could get a release cut to include the new LocationIQ lookup? I've been using the master version for a couple weeks now and it's been working great with LocationIQ for my site.

**Comment by alexreisner** [comment]
Resolved by #1088
