### ISSUE TITLE
Bad uri when using Geocoder.search

### ISSUE THREAD

**Issue by Victorgf87** [alexreisner/geocoder#1071]
Hello, I was checking my application and I found this error:
If I call Geocoder.search("1 Twins Way, Minneapolis") then I get 

URI::InvalidURIError: bad URI(is not URI?): http://ipinfo.io/1 Twins Way, Minneapolis/geo from [...]

Any help? Thank you in advance :)

**Comment by alexreisner** [comment]
It looks like you may have configured an IP address lookup (ipinfo.io) as your street address lookup (`:lookup`, instead of `:ip_lookup`). Possible?

**Comment by Victorgf87** [comment]
This is my configuration. But it worked fine before :S

`Geocoder.configure(
  # Geocoding options
  timeout: 3,               # geocoding service timeout (secs)
  lookup: :ipinfo_io,           # name of geocoding service (symbol)
  ip_lookup: :ipinfo_io,           # name of geocoding service (symbol)
  # language: :en,              # ISO-639 language code
  use_https: true,           # use HTTPS for lookup requests? (if supported)
  # http_proxy: nil,            # HTTP proxy server (user:pass@host:port)
  # https_proxy: nil,           # HTTPS proxy server (user:pass@host:port)
  # api_key: "nil",    # API key for geocoding service
  # cache: nil,                 # cache object (must respond to #[], #[]=, and #keys)
  # cache_prefix: 'geocoder:',  # prefix (string) to use for all cache keys

  # Exceptions that should not be rescued by default
  # (if you want to implement custom error handling);
  # supports SocketError and TimeoutError
  # always_raise: [],

  # Calculation options
  # units: :mi,                 # :km for kilometers or :mi for miles
  # distances: :linear          # :spherical or :linear
)`

Should I remove ip_lookup line?
What is your preferred configuration?

**Comment by alexreisner** [comment]
You should remove the `:lookup` line. The above will work for IP addresses but not street addresses. In the README you'll see [Street Address Services](https://github.com/alexreisner/geocoder#street-address-services) and [IP Address Services](https://github.com/alexreisner/geocoder#ip-address-services), which are not interchangeable.

**Comment by Victorgf87** [comment]
Thank you, it's working :) 👍
