### ISSUE TITLE
Is it possible to generate a custom bounding box?

### ISSUE THREAD

**Issue by chintanparikh** [alexreisner/geocoder#1072]
Hi all -

I've read through all the documentation and a bunch of issues but I can't find the answer to this question. I have a Coordinate model with attributes lat, long, and order. A Coordinate belongs_to Location. Now what I want to do is figure out how to generate a bounding box based on these Coordinates. It would work by basically drawing a line between each coordinate ordered by the order attribute (and the last coordinate would have to connect to the first).

Is this possible with this gem?

**Comment by alexreisner** [comment]
I'm not sure I understand this completely, but if the goal is to draw a box around a set of points, all that's needed is to take the min and max of all lats and lons and use them as the bounds for your box.
