### ISSUE TITLE
wrong number of arguments (given 3, expected 0..1)

### ISSUE THREAD

**Issue by dileeppdkr** [alexreisner/geocoder#1079]
After updating ruby and rails on my app , I am getting wrong number of arguments error for ".near method". For ruby 2.0 and rails 4.0 it is working fine.

 Below is my code

` Worker.near(self.coordinates.reverse, radius, {:unit => :miles, :order => :distance})`

My gem file having:

`ruby "2.3.1"`
`gem 'rails', '~> 4.2', '>= 4.2.6'`
`gem 'geocoder', '~> 1.3', '>= 1.3.1'`

Any help would be appreciated.
Thanks.

**Comment by alexreisner** [comment]
Could you copy/paste the full error message please?

**Comment by dileeppdkr** [comment]
Please find the attached image for reference.

![screen shot 2016-06-27 at 6 43 21 pm](https://cloud.githubusercontent.com/assets/6264502/16380864/19680072-3c97-11e6-9230-50141a5b98ed.png)

**Comment by dileeppdkr** [comment]
If I pass one param it is working 👍 
`Worker.near(:home_coordinates => self.coordinates.reverse)`
How I can add extra params like `radius, {:unit => :miles, :order => :distance}`
Thanks.

**Comment by alexreisner** [comment]
Can you send the full backtrace, maybe copy/paste from the server log? I need more context.

**Comment by dileeppdkr** [comment]
Backtrace:

I, [2016-06-27T18:54:06.383041 #33633]  INFO -- : Completed 500 Internal Server Error in 173ms
I, [2016-06-27T18:54:06.383225 #33633]  INFO -- : Completed 500 Internal Server Error in 173ms
F, [2016-06-27T18:54:06.384694 #33633] FATAL -- : 
ArgumentError (wrong number of arguments (given 3, expected 0..1)):
  app/models/job.rb:633:in `closest_workers'
  app/controllers/dashboard_controller.rb:85:in `job'


Code: 
` Worker.near(self.coordinates.reverse, radius, {:unit => :miles, :order => :distance}).where(job_type_params).collect { |w|
      if(w.coordinates.length > 0)
        w[:distance] = Geocoder::Calculations.distance_between(self.coordinates.reverse, w.coordinates)
        w[:home_distance] = Geocoder::Calculations.distance_between(self.coordinates.reverse, w.home_coordinates.reverse)
        w unless w[:home_distance] > ((Rails.env.production?)? w.radius.to_f : radius)
      end
    }.compact.sort_by { |hsh| hsh[:distance] }`

**Comment by alexreisner** [comment]
What does `Worker.class` return? And is it a model with a `geocoded_by` line?

**Comment by dileeppdkr** [comment]
Yes my model contains 
`include Geocoder::Model::Mongoid
  reverse_geocoded_by :home_coordinates`
Worker class returns all the workers .

**Comment by dileeppdkr** [comment]
This is working for me if I use ruby 2.0 and rails 4.0.
I have  updated my ruby to 2.3.1 and rails 4.2, in this case it is not working showing arguments error.

**Comment by alexreisner** [comment]
I think you're calling `near` on a worker, not on a geocoded class.

**Comment by dileeppdkr** [comment]
Common, this is working with Ruby 2.0 and Rails 4.0.
