### ISSUE TITLE
Removing where condition in near

### ISSUE THREAD

**Issue by brfieger** [alexreisner/geocoder#1081]
I would like to run a query which simply orders the objects from closest too farthest and does not put a constraint on the actual location based upon radius. I noticed the behavior of the near method is defined in: https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/stores/active_record.rb

Was wondering what would be the cleanest and easiest way to add a scope "near_without_where" which simply removes the where condition in the query?

**Comment by lime** [comment]
There's [`unscope(:where)`](http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-unscope), which will remove all where conditions.

```ruby
YourClass.near('Helsinki').unscope(:where)
```

Note that if you had any other where conditions (e.g. from a default scope) they will be removed as well, so this might not be the best choice.

---

It does look like it would be possible to use the `distance_from_sql` class method manually, without using `near` at all.

```ruby
YourClass.order(YourClass.distance_from_sql('Helsinki'))
```

This won't add the `distance` attribute the way `near` does, if you need that you'll have to play around a bit with `select` to replicate how `near` works.

**Comment by alexreisner** [comment]
Best way is probably to write a custom ORDER clause using the utilities provided in the [`Geocoder::Sql` module](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/sql.rb).

**Comment by chrise86** [comment]
@brfieger what was the solution you came up with?
