### ISSUE TITLE
Optionals bounds with Google lookup acting weird

### ISSUE THREAD

**Issue by gildasfremont** [alexreisner/geocoder#1091]
This works just fine :
Geocoder.search("Paris", :bounds => [[32.1,-95.9], [33.9,-94.3]])

It returns Paris in Texas 🎉 

Not this :
Geocoder.search("Paris", :bounds => [[48.7, 2.2], [48.9, 2.5]])

It returns Paris in France and Paris in Texas, where it should return only Paris in France 😢

Does it work only in some regions ?

( 👋 @ThomasSertorio)

**Comment by alexreisner** [comment]
[Google's documentation](https://developers.google.com/maps/documentation/geocoding/intro) says that the bounds parameter sets "the bounding box of the viewport within which to bias geocode results." It doesn't exclude matches outside the box, it just demotes them in the ordering of returned results.

**Comment by gildasfremont** [comment]
Thanks for this fast answer Alex and for pointing to Google documentation.

Still it does not seem to work as expected.

I'll take 'Chatelet' as an example as it is a very frequent name for places, streets or cities in France.

When I search for 'Chatelet' 🇫🇷  with no bounds it returns a city in Belgium and only this location. When I search for the same string with bounds in the region of Paris it returns also the city in Belgium and only this location.

Exactly not what happens with the 'Winnetka' 🇺🇸 example of the Google documentation !

Do you have an idea why and where this may come from ?

**Comment by alexreisner** [comment]
Then maybe there is only one city in the geocoding database with the name "Chatelet" (?). I don't think street names are included in the search. When I search for "chatelet" on Google Maps I get some retailers in France, but no towns. In any case, this is not so much a Geocoder issue as a Google API issue. The bounds are being sent correctly with the request, so there's nothing more Geocoder can do.
