### ISSUE TITLE
right_http_connection uses deprecated timeout method, switch to using different gem?

### ISSUE THREAD

**Issue by januszm** [alexreisner/geocoder#1094]
Perhaps you might want to switch to using a different gem for making those connections? right_http_connection was last updated in 2014.

```
pry(#<Geocoder::Lookup::Freegeoip>)> response = make_api_request(query)
.../gems/right_http_connection-1.5.0/lib/base/net_fix.rb:51:in `rbuf_fill': Object#timeout is deprecated, use Timeout.timeout instead.
```

**Comment by alexreisner** [comment]
Interesting...Geocoder doesn't actually depend on that gem. Can you see if it's being required by something else in your app's `Gemfile.lock`?

**Comment by januszm** [comment]
Yeah it seems that ```right_aws``` gem requires it. Funny thing is that it's triggered when I call ```make_api_request``` method from Geocoder.

Anyway, looks like it's not relevant and we can close it.

**Comment by alexreisner** [comment]
My guess is that it replaces some of Net:HTTP's methods.
