### ISSUE TITLE
Split up address on reverse_geocode

### ISSUE THREAD

**Issue by RBIII** [alexreisner/geocoder#1097]
For my project, my main model has fields for different aspects of an address (:address, :city, :state, :country, and :zip_code). However when the reverse geocoding happens after validation it saves the whole address string to the address field.

Is there a way to break it up in the after_validation block or do I need to do it somewhere else?

**Comment by alexreisner** [comment]
You could do it any time after (reverse) geocoding occurs. If your `after_validation` hook calls `geocode` manually, then you can do it in there. Otherwise, if it's in a separate method you'll just have to ensure that it runs after geocoding has completed.
