### ISSUE TITLE
near scope not working

### ISSUE THREAD

**Issue by chrise86** [alexreisner/geocoder#1102]
I have a `Group` model with `latitude` and `longitude` attributes and `reverse_geocoded_by :latitude, :longitude`. When using `Group.near("town name")` it works fine, however when using `Group.near([lat, lng])` (where `lat` and `lng` are valid coordinates) it does not work, and the scope performs the following query:

```
SELECT groups.*, NULL::text AS distance, NULL::text AS bearing FROM "groups" WHERE (false)
```

**Comment by chrise86** [comment]
No idea why, but it's working now :-/ must have been a typo somewhere sorry, but for the life of me I just couldn't get it to work... it's been a long day :(

**Comment by karimmortabit** [comment]
I had the same issue (for a few hours too 🤓 ), my mistake was to include the **radius** in the same array as **lat** and **lng**, like this :

```Place.near([lat, lng, radius])```
Instead of :
```Place.near([lat, lng], radius)```
