### ISSUE TITLE
Random order issue with limit

### ISSUE THREAD

**Issue by chrise86** [alexreisner/geocoder#1111]
Given the following (the `.map(&:id)` is just to represent the result order):

```
Event.near(current_location, 30).map(&:id)
=> [68,  101, 61, 63, 92, 67, 74, 75, 78, 79, 82, 83, 86, 87, 90, 91, 94, 95, 98, 99, 102, 53, 1, 54...]
```

I get the results I expect, however if I was to add a `.limit` to the query, the results set changes:

```
Event.near(current_location, 30).limit(24).map(&:id)
=> [101, 61, 63, 92, 67, 74, 75, 78, 79, 82, 83, 86, 87, 90, 91, 94, 95, 98, 99, 102, 53, 1, 54, 59]
```

These results are incorrect. It seems as though the first object is getting pushed out. The odd thing is, if I was to use something like Kaminari or a mixture of `limit` and `offset`, then the first object (`68`) appears at the end of both page 1 and page 2.

Any idea what is happening here, and why? How can I go about fixing or getting around it?

**Comment by alexreisner** [comment]
Have you tried explicitly setting `.offset(0)`? Is there another gem that could be affecting queries? Can you call `.to_sql` so we can see the actual SQL that's being executed?

**Comment by chrise86** [comment]
Yes, `offset(0)` has no effect.

    Event.near(current_location, 30).to_sql

    "SELECT events.*, 3958.755864232 * 2 * ASIN(SQRT(POWER(SIN((51.695458699999996 - events.latitude) * PI() / 180 / 2), 2) + COS(51.695458699999996 * PI() / 180) * COS(events.latitude * PI() / 180) * POWER(SIN((-3.4218471999999998 - events.longitude) * PI() / 180 / 2), 2))) AS distance, MOD(CAST((ATAN2( ((events.longitude - -3.4218471999999998) / 57.2957795), ((events.latitude - 51.695458699999996) / 57.2957795)) * 57.2957795) + 360 AS decimal), 360) AS bearing FROM \"events\" WHERE (events.latitude BETWEEN 51.261263350667456 AND 52.12965404933254 AND events.longitude BETWEEN -4.122341660694722 AND -2.7213527393052774 AND (3958.755864232 * 2 * ASIN(SQRT(POWER(SIN((51.695458699999996 - events.latitude) * PI() / 180 / 2), 2) + COS(51.695458699999996 * PI() / 180) * COS(events.latitude * PI() / 180) * POWER(SIN((-3.4218471999999998 - events.longitude) * PI() / 180 / 2), 2)))) BETWEEN 0.0 AND 30) ORDER BY distance ASC"

**Comment by u007** [comment]
i found that when i add limit or with offset, the select query erased distance select, and caused invalid sql

**Comment by alexreisner** [comment]
Closing because old and I suspect this is due to another gem modifying queries. However, if this is still an issue and can be isolated to Geocoder, please reopen!
