### ISSUE TITLE
mongoid within_bounding_box error

### ISSUE THREAD

**Issue by chollimee** [alexreisner/geocoder#1113]
I am using mongoid, and within_bounding_box occurs "NoMethodError: undefined method `within_bouding_box'"

Doesn't this gem support mongoid for this feature?

**Comment by alexreisner** [comment]
Sorry, due to a large number of bugs and difficulty of maintenance it became hard to justify overwriting Mongoid's `near` method, which runs spatial queries natively. So the feature was dropped (see #832) for MongoDB-backed objects.
