### ISSUE TITLE
'Google Geocoding API error: request denied' when using api key

### ISSUE THREAD

**Issue by enrico** [alexreisner/geocoder#112]
when specifiying a valid api key :

Geocoder::Configuration.lookup = :google
Geocoder::Configuration.api_key = '...'

I get:

ruby-1.9.2-p290 :001 > results = Geocoder.search("Eiffel Tower")
Google Geocoding API error: request denied.
 => [] 

If I take the api key out, the query succeeds.

**Comment by weiserma** [comment]
I solved this problem by going to the google developers console and enabling the api

Google Maps Geocoding API

**Comment by damienh** [comment]
Just wanted to note that I was able to solve this by passing `use_https`

```
Geocoder.configure(
	:timeout => 15,
	:api_key => "yourkey",
	:use_https => true
	)
```

**Comment by eveevans** [comment]
What I did to solve this was: 

1. Make sure to have service API enable (on Google API Dashboard)
2. Generate  a Javascript Credential for use with Javascript API
3. Generate a Server Credential for use with Server API
4. Configurate initializers for Geocode

**Comment by Startouf** [comment]
I'm running in the same issue only on some staging environment from AWS

Locally, everything works fine with the same API key, but from the AWS Cloud I'm getting `Google API error: request denied`. I'm not really sure of the cause... IP blacklisting maybe ?

**Comment by puneetpandey** [comment]
This thread can prove out to be useful https://stackoverflow.com/a/32998566/649868
