### ISSUE TITLE
Bulk Geocoding

### ISSUE THREAD

**Issue by mayureshmayur** [alexreisner/geocoder#1121]
I want to know what exactly rake _geocode:all CLASS=YourModel_ does?
Is it like if I have data already(address, city, state, country, zip) in my table and after adding latitude and longitude columns if run above command, it will insert values to those added latitude and longitude columns?

**Comment by alexreisner** [comment]
It runs `#geocode` on all the un-geocoded objects. The goal is to assign lat/lon for all objects with an address.
