### ISSUE TITLE
multiple near query in 1?

### ISSUE THREAD

**Issue by u007** [alexreisner/geocoder#1124]
Hi ,

is it possible to add in multiple locations onto near,
or calling it multiple time, and having it return distance_0, distance_1

just a suggestion, sorry im not sure how it will effect other algorithm...
thanks

**Comment by alexreisner** [comment]
Currently this is not possible without running multiple `.near` queries on the group of objects. No plans to add this ability either as it's too far from the core functionality Geocoder seeks to provide.
