### ISSUE TITLE
Geocoding with Google Place Search?

### ISSUE THREAD

**Issue by waruboy** [alexreisner/geocoder#1128]
Hello.

First, thank you very much for the gem. We use it at storemapper.co and very happy with it.

Recently, Google announce that they will make the change to geocoding API that will make it more unsuitable for unambiguous query. For ambiguous search they reccommend using Google Place Search

> We plan to roll out an update to the Geocoding API at the end of November 2016 that will increase the difference between Geocoding and Places performance for ambiguous and unambiguous queries. This change will improve the quality of Geocoding results for unambiguous queries, but will be more likely to return ZERO_RESULTS for ambiguous or incomplete queries where the Geocoding API was unable to find a high quality result. 

https://googlegeodevelopers.blogspot.co.id/2016/11/address-geocoding-in-google-maps-apis.html

As far as I know Google Place Search (not Details) is not supported yet by the gem. Is there any plan to support it? Will be happy to help with PR.

**Comment by alexreisner** [comment]
Thanks! Glad you guys are happy with the gem. Thanks also for the link to the blog post, which I hadn't seen. You're correct that Place Search is not currently supported. I'm open to a PR as long as the Lookup and Result classes follow the basic form of the existing classes (ie, the request and response formats are not significantly different, which they don't appear to be from a quick glance at the documentation).

**Comment by waruboy** [comment]
Cool! let me see what I can do.

**Comment by alexreisner** [comment]
Closed by #1143
