### ISSUE TITLE
Model.near broken in 1.4.1

### ISSUE THREAD

**Issue by fjl82** [alexreisner/geocoder#1130]
I ran into a regression in 1.4.1 in calls to Model.near.

The following used to work:
`Airport.near(some_object, 200).limit(20)`

This results in the following query on 1.4.0:
`SELECT  airport.*, 6371.0 * 2 * ASIN(SQRT(POWER(SIN((36.623276500595736 - airport.latitude) * PI() / 180 / 2), 2) + COS(36.623276500595736 * PI() / 180) * COS(airport.latitude * PI() / 180) * POWER(SIN((-4.494958519935608 - airport.longitude) * PI() / 180 / 2), 2))) AS distance, MOD(CAST((ATAN2( ((airport.longitude - -4.494958519935608) / 57.2957795), ((airport.latitude - 36.623276500595736) / 57.2957795)) * 57.2957795) + 360 AS decimal), 360) AS bearing FROM `airport` WHERE (airport.latitude BETWEEN 34.82463328875828 AND 38.421919712433194 AND airport.longitude BETWEEN -6.736048489496704 AND -2.253868550374512 AND (6371.0 * 2 * ASIN(SQRT(POWER(SIN((36.623276500595736 - airport.latitude) * PI() / 180 / 2), 2) + COS(36.623276500595736 * PI() / 180) * COS(airport.latitude * PI() / 180) * POWER(SIN((-4.494958519935608 - airport.longitude) * PI() / 180 / 2), 2)))) BETWEEN 0.0 AND 200) ORDER BY distance ASC LIMIT 20`

On 1.4.1 it does this:
`SELECT  airport.*, NULL AS distance, NULL AS bearing FROM `airport` WHERE (false) LIMIT 20`

I've reverted my project back to 1.4.0 for now. Would be great if this is fixed in 1.4.2.

**Comment by alexreisner** [comment]
I'm having a hard time reproducing this. Could you please give us some information about your environment? eg: Ruby version, Rails version, Geocoder config

**Comment by XXChester** [comment]
I just upgraded to ruby 2.3.3 and have this problem on both geocoder 1.3.7 and 1.4.1.

**Comment by fjl82** [comment]
Rails 5.0.0.1
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

Geocoder 1.4.1 has the problem, 1.4.0 does not.

configuration:
Geocoder.configure(
    language: :en,
    units: :km,
    lookup: :nominatim,
    use_https: true
)

**Comment by fjl82** [comment]
Had some time to take a look at it today.
Created PR #1134 to fix the issue.

**Comment by alexreisner** [comment]
Is this happening on every single request or intermittently? Does it occur when you call `.near` with an array of coordinates as opposed to an object? (Are you certain that the objects you're passing to the method have both latitude and longitude values?)

**Comment by theaxel** [comment]
Have the same problem when switching from 1.4.0 to 1.4.1

ruby 2.1.2
activerecord 4.2.7.1
pg 0.19.0

Sample request:
model.near(lat, lot, radius, :units => :km)

**Comment by markmcdonald51** [comment]
Not sure if this is working with the latest version of Rails....I am getting a Fixnum error

Model.near([params[:lat], params[:lon]], 15).limit(30)

ArgumentError: Unsupported argument type: 0 (Fixnum)
from /home/hounddog/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/relation/where_clause_factory.rb:27:i
n `build'

**Comment by alexreisner** [comment]
@markmcdonald51 can you please copy/paste the full backtrace as well as the exact line of code that's causing the problem? And is this happening on every single request or intermittently?

**Comment by kbroderick** [comment]
I'm seeing the same problem—geocoder 1.4.1, no results returned on .near when there should be, and the generated SQL is

SELECT  markets.*, NULL AS distance, NULL AS bearing FROM `markets` WHERE `markets`.`dormant` = 0 AND `markets`.`dps` = 1 AND (false) LIMIT 5

from

@nearby = Market.where(dormant: false, dps: true).near([latitude, longitude], 75).limit(5)

Removing the .where call removes the WHERE clause but otherwise generates the same, non-working, SQL call.

I'm running under Ruby 2.4.0 and Rails 5.0.1.

**Comment by alexreisner** [comment]
@TrangPham Any luck reproducing this? Or any theories on what's going on here?

**Comment by macfanatic** [comment]
I can confirm that on Ruby 2.3.2 and Rails 5.0.1 downgrading from 1.4.1 to 1.4.0 of geocoder resolves the issue.

For me, something as simple as failed:

```ruby
Address.near([lat, lng], 20).to_sql
# => SELECT * FROM address WHERE (false)
```

**Comment by TrangPham** [comment]
Here are the two commits which I think could have affected this from 1.4.0 to 1.4.1:
https://github.com/alexreisner/geocoder/commit/1c306367588f61b418a0f41f049f73cfd9f94897 OR https://github.com/alexreisner/geocoder/commit/e0ad6c4286f3f7d5ff1707ef1a80f66a59a65b42

Of which I think the second one is more likely to have caused this. Though there are unit tests for these and the unit tests continue to pass...

What I think might be happening is either `full_distance` in Geocoder::Sql is not being called, therefore returning NULL for that part of the query, or perhaps it's failing silently and returning NULL (doubt it though?). I tired to trace the blames on the different files. And nothing changed in sql.rb or store/active_record.rb recently...

**Comment by alexreisner** [comment]
@TrangPham: I agree that those two commits are good candidates. I can't reproduce this at all, which I feel should be a clue, but I'm unsure of how to read it.

@macfanatic et al: Could anyone who's experiencing this problem please try installing from the `fix-1130` branch and see if that fixes the problem? Just put this in your Gemfile:

    gem 'geocoder', github: "alexreisner/geocoder", branch: "fix-1130"

**Comment by macfanatic** [comment]
@alexreisner Using your referenced branch seems to fix the problem, as in I saw no change and are tests still pass (which failed on 1.4.1).

**Comment by kbroderick** [comment]
@alexreisner  I can also confirm that the referenced branch resolves the issue for me—Model.near works as expected.

**Comment by alexreisner** [comment]
@macfanatic , @kbroderick Thank you!

@TrangPham It looks like 1c30636 was the issue, though I can't say I fully understand why. I guessed that commit because it modifies `coordinates_present?` which, if returning `false` incorrectly, could cause the problems that were reported. But I don't understand the kind of inputs that would cause it to return false unexpectedly. Would be good to find them and add a test to prevent this from happening in the future, since it's obviously quite subtle.

New gem release coming shortly.

**Comment by kbroderick** [comment]
@alexreisner if it helps, the method where I was seeing the issue starts off pretty simply:

    latitude = params[:latitude]
    longitude = params[:longitude]

    @nearby = Market.where(dormant: false, dps: true).near([latitude, longitude], 75).limit(5)

It's called via JavaScript:

```
if ("geolocation" in navigator) {
    navigator.geolocation.getCurrentPosition(function(position) {
      loadNearbyMarkets(position.coords.latitude, position.coords.longitude);
    });
}

function loadNearbyMarkets(lat, long) {
    jQuery.get("/nearby_markets_html", {latitude: lat, longitude: long}, function( data ) { 
        jQuery(".nearby").append(data);
        jQuery(".check_out .button").on("click", function() {
            jQuery(".other-nearby").toggle();
        });
    });
}
```

**Comment by alexreisner** [comment]
@kbroderick was it happening with all values or only some?

**Comment by kbroderick** [comment]
@alexreisner All that I've tried. Unfortunately, we don't have any good testing on the JavaScript side of the house, but under 1.4.1, I was told that our geolocation was not working, and on investigation (using a different set of values than those tried by either the staff member who reported it to me or the franchisee who initially noted it), I was getting an empty return set from the near query regardless of whether the provided location was within 75 miles of one of our markets or not. My testing was done using the "sensors" fake-GPS setting under Chrome, as I'm not physically located close enough to one of our markets to trigger the check.

**Comment by alexreisner** [comment]
I think I've found the issue: it occurs when the values in the coordinates array are strings instead of floats. All in this thread who have provided enough application code for me to confirm the theory are getting lat/lon values in the controller, which means they're strings.

**Comment by alexreisner** [comment]
078733d22dca783c9b3519d2475605fbb9b60a9d adds a test which fails under 1.4.1 but passes under 1.4.0 and 1.4.2.

**Comment by macfanatic** [comment]
Ah, yes our `lat` and `lng` are indeed coming from the `params` hash unmodified and would be strings as well.  Our controller tests were setup with string values in the params as well.

**Comment by leconganh1995** [comment]
hello

**Comment by leconganh1995** [comment]
Please help me
![image](https://user-images.githubusercontent.com/29689700/84007831-28ef0700-a99b-11ea-9c92-ed81e24b0a7f.png)
![image](https://user-images.githubusercontent.com/29689700/84007992-62277700-a99b-11ea-9251-7d1b8991f417.png)
![image](https://user-images.githubusercontent.com/29689700/84008021-6bb0df00-a99b-11ea-9d1c-4a7ef40ab162.png)

**Comment by leconganh1995** [comment]
Please help me
![image](https://user-images.githubusercontent.com/29689700/84011733-c0a32400-a9a0-11ea-841d-f2b599c9669e.png)
![image](https://user-images.githubusercontent.com/29689700/84011757-c8fb5f00-a9a0-11ea-9dc6-ce3748896904.png)
![image](https://user-images.githubusercontent.com/29689700/84011795-d87aa800-a9a0-11ea-8ff6-3da5c6d32497.png)
