### ISSUE TITLE
Geocoder with Google Place Autocomplete

### ISSUE THREAD

**Issue by nikkisaumya** [alexreisner/geocoder#1135]
<img width="789" alt="screen shot 2016-12-23 at 11 50 13 am" src="https://cloud.githubusercontent.com/assets/13282411/21448224/25b546ea-c906-11e6-969d-a2023a3fd77f.png">
Geocoder gem does not resolve coordinates for certain addresses (for eg : "Barbeque nation Indiranagar Bangalore, India ") chosen from the Google Place Autocomplete

**Comment by TrangPham** [comment]
This is an issue with the underlying service you're using to geocode. If that service does not return values for a location, geocoder would not return anything either. 

The best way to check is to use the API call directly using curl or your browser to ping the API service.

**Comment by indokathan** [comment]
Also having an issue here. It seems that a few weeks ago, this was working just fine - but isn't now. Changing the lookup service doesn't change behavior.

**Comment by Sampha** [comment]
Hey, indokathan!
I tried running through the same examples that you did and received the proper co-ordinates

Are you still having this issue?

`irb(main):001:0> Geocoder.coordinates("barbeque nation indiranagar bangalore")
=> [12.96252, 77.64143899999999]
`
