### ISSUE TITLE
SmartyStreets look up does not work with addresses

### ISSUE THREAD

**Issue by joshuasiler** [alexreisner/geocoder#1136]
Currently the geocode call will only work with a zip code, not with an address.

**Comment by alexreisner** [comment]
Looks like the SmartyStreets API URL changed. Fixed in 2f3489c546831386609b567f40214bb4d05227fe. Try installing from master and see if that fixes the problem.

**Comment by joshuasiler** [comment]
Looks that works. Also it appears SmartyStreets has realized their error and re-enabled the previous working URL.

**Comment by alexreisner** [comment]
Ha! Thanks for the update.
