### ISSUE TITLE
How can I use near or not_geocoded condition?

### ISSUE THREAD

**Issue by dtelaroli** [alexreisner/geocoder#1137]
I want use OR condition to optional geocodification.

**Comment by TrangPham** [comment]
Hi @dtelaroli I'm not sure I understand what you're asking. Could you clarify?

**Comment by dtelaroli** [comment]
I have some not geocoded items in my database.
I want find items using coordinates or items not geocoded.

Something like this:
```
Venue.near_or_not_geocoded([40.71, -100.23], 20)
```

For now, i'm using two queries to find, because the API does not have that option.
```
Venue.near([40.71, -100.23], 20) + Venue.not_geocoded
```

Sorry for my bad english.

**Comment by alexreisner** [comment]
As of Rails 5 you can do this:

    Venue.near([40.71, -100.23], 20).or(Venue.not_geocoded)

**Comment by dtelaroli** [comment]
Thanks

Em 28 de jun de 2017 19:03, "Alex Reisner" <notifications@github.com>
escreveu:
