### ISSUE TITLE
latitude and longitude update issue when update address with  invalid address

### ISSUE THREAD

**Issue by uzaif313** [alexreisner/geocoder#1138]
hi 
i have encounter one problem while working with geocoder.
-if i have a new record with valid address it will fetch latitude and longitude.but once i update that address in with invalid address it contain old latitude and longitude and **invalid address** store in DB with **old address** latitude and longitude. 

  `geocoded_by :full_address,:latitude => :lat, :longitude => :lon`

  ```
def full_address
    address+" "+city+"  "+state+" "+zip
  end
```

**Comment by alexreisner** [comment]
You'll need to check whether the address has changed in the logic for triggering a geocode. See #892 for an example.
