### ISSUE TITLE
Internationalization of results on a per request basis

### ISSUE THREAD

**Issue by rosskevin** [alexreisner/geocoder#1144]
Feature request: public api for resolved hash data based on given locale.

I'm using react and grabbing the ip-based location for my region/subregion selector from the server.  I'm having to meddle inside the geoip2 result in a way that works - but I'd rather use a public api to resolve results.

Here's what I need to do, since the locale could be different on each request:
```ruby
FALLBACK_LOCALE = 'en'

def resolve_location
  ip_location = request.location

  # this is private, so we need to get inside of it - we want to internationalize results for our client
  ip_location = ip_location.instance_variable_get(:@data)
  ip_location = ip_location.to_hash
  
  # use the passed locale, otherwise fallback when getting name
  locale = I18n.locale.to_s

  location = {}
  ip_location.each do |key, value|
    location[key.to_sym] = {
        code: value['iso_code'] || value['code'],
        name: value['names'][locale] || value['names'][FALLBACK_LOCALE]
    }
  end
  location
end
```

Since this works, I'm not pressing to spend time on a PR, but if a result api refactoring is in the future, please consider this case.

**Comment by alexreisner** [comment]
Thanks for this. Could you explain exactly what you'd like easier access to? Having a little trouble separating Geocoder-specific stuff from the app logic.

**Comment by rosskevin** [comment]
With any `result` you should be either able to set/override the locale.  Currently`result` is hard coded to use the system default locale.

See:
https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/results/geoip2.rb#L57

**Comment by musialik** [comment]
Hi!
If this is still something you want implemented and no one else is working on this, I'd like to give it a try.

**Comment by TrangPham** [comment]
Thanks for this implementation! Looks good to me :)
