### ISSUE TITLE
Access to raw API data after geocode success? (ActiveRecord)

### ISSUE THREAD

**Issue by cpruitt** [alexreisner/geocoder#1146]
This might smell a little too much like scope creep as it's not strictly related to lat/lng geocoding but...

Currently, when using `geocode` with ActiveRecord, the process of looking up the address and then assigning lat/lng coordinates is all dome automatically, which is great. It would be extremely useful (to me anyway) to be able to somehow access the raw API results returned by the geocoding service after a successful lookup. The issue I'm trying to solve is basically this:

Our application accepts user-provided address data. Multiple users may enter the same address, but enter it in a different format (e.g. 12345 DeVille St. vs. 12345 Deville Street). If I am correct about this, I believe some geocoding API's (e.g. google) return detailed information about the address being looked up along with the coordinate data. It would be nice to geocode the record and then be able to update the address with the normalized values returned by the API. If we could do that then all addresses in the system would be consistently formatted and complete. Doing it at the time of the geocode would avoid unnecessary additional API calls just for address normalization.

So my first question would be, is there a way to accomplish this now (even if it means defining my own geocode method)? I looked into it a bit but didn't see anything that seemed straightforward.

My second question would be, if it can't be done now, is that something that should be possible and what would be involved in adding the feature?

**Comment by alexreisner** [comment]
Does the [Advanced Geocoding](https://github.com/alexreisner/geocoder#advanced-geocoding) section of the readme help?

**Comment by cpruitt** [comment]
@alexreisner Well... It only helps in terms of providing exactly what I'm looking for in pretty much exactly the way I was hoping to be able to implement it. 🙂

Honestly, I've looked at that part of the readme several times in the past. No idea how I missed it this time. Maybe the `reverse_geocode_by` example threw me off and I skimmed past it. In any case, thanks!

**Comment by alexreisner** [comment]
Ha! No worries, glad that helped.
