### ISSUE TITLE
Anyway to search with the combination of Country Codes and zip codes? 

### ISSUE THREAD

**Issue by brentluna** [alexreisner/geocoder#1151]
I use your gem  for finding the city and state/province of a given Country code and zipcode. However when a country code shares the same abbreviation of a US State, it treats it as a US State, providing  incorrect info. Is there anyway around this? Wasn't able to find anything in the documentation about it. Thanks

**Comment by TrangPham** [comment]
@brentluna Which geocoding service are use using? This is probably due to how that service will treat the country code. The service may have options which you can pass to it to ensure it treats the country code as a country code and not a US state code.
