### ISSUE TITLE
who calls cache.keys?

### ISSUE THREAD

**Issue by asafdav2** [alexreisner/geocoder#1152]
let me start by stating I read the readme that asks not to use GitHub issues to ask questions about usage. this is, however, more of an implementation question.

A bit of background - I'm using auto-expiring cache, a slight modification of the [example](https://github.com/alexreisner/geocoder/blob/master/examples/autoexpire_cache_redis.rb).
As the comment says, I have `keys` method in the cache that simply delegates to `redis.keys`. 

I figured I could make this more efficient by utilizing the geocoder prefix; there is no need to bring in all Redis keys. While this change was easy to do, I had trouble testing myself because I couldn't locate who in the Geocoder code calls the `cache.keys` method.

**Comment by alexreisner** [comment]
The example cache doesn't implement all the features of the default cache, in which [the `urls` method calls `keys`](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/cache.rb#L74).

**Comment by asafdav2** [comment]
i see. guess it was the comment in initializer.rb that threw me off
see [PR](https://github.com/alexreisner/geocoder/pull/1154)
