### ISSUE TITLE
Geocoder::Result::Google#subpremise and Geocoder::Result::Google#premise Support

### ISSUE THREAD

**Issue by jufemaiz** [alexreisner/geocoder#1155]
Looking to include the support for subpremise in the Geocoder::Result::Google response.

For example: https://maps.googleapis.com/maps/api/geocode/json?&address=4%2F12%20Webster%20Rd%20Stafford%20QLD%204053

`
{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "4",
               "short_name" : "4",
               "types" : [ "subpremise" ]
            },
            {
               "long_name" : "12",
               "short_name" : "12",
               "types" : [ "street_number" ]
            },
            {
               "long_name" : "Webster Road",
               "short_name" : "Webster Rd",
               "types" : [ "route" ]
            },
            {
               "long_name" : "Stafford",
               "short_name" : "Stafford",
               "types" : [ "locality", "political" ]
            },
            {
               "long_name" : "Brisbane City",
               "short_name" : "Brisbane",
               "types" : [ "administrative_area_level_2", "political" ]
            },
            {
               "long_name" : "Queensland",
               "short_name" : "QLD",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "Australia",
               "short_name" : "AU",
               "types" : [ "country", "political" ]
            },
            {
               "long_name" : "4053",
               "short_name" : "4053",
               "types" : [ "postal_code" ]
            }
         ],
         "formatted_address" : "4/12 Webster Rd, Stafford QLD 4053, Australia",
         "geometry" : {
            "location" : {
               "lat" : -27.4185937,
               "lng" : 153.0150797
            },
            "location_type" : "ROOFTOP",
            "viewport" : {
               "northeast" : {
                  "lat" : -27.4172447197085,
                  "lng" : 153.0164286802915
               },
               "southwest" : {
                  "lat" : -27.4199426802915,
                  "lng" : 153.0137307197085
               }
            }
         },
         "partial_match" : true,
         "place_id" : "Ei00LzEyIFdlYnN0ZXIgUmQsIFN0YWZmb3JkIFFMRCA0MDUzLCBBdXN0cmFsaWE",
         "types" : [ "subpremise" ]
      }
   ],
   "status" : "OK"
}
`

**Comment by alexreisner** [comment]
You can access this via `result.data`, which gives you access to the whole hash of returned data.
