### ISSUE TITLE
Typo on wiki path. 

### ISSUE THREAD

**Issue by prwhitehead** [alexreisner/geocoder#1158]
The wiki regarding creating a localhost override has a typo in the file path. 

It should be "config/initializers/geocoder.rb" not "config/initilizers/geocoder.rb".

https://github.com/alexreisner/geocoder/wiki/Provide-a-hardcoded-IP-to-%60development%60-and-%60test%60-environments

**Comment by alexreisner** [comment]
Thanks--fixed!
