### ISSUE TITLE
geocoding api not responding fast enough

### ISSUE THREAD

**Issue by edap** [alexreisner/geocoder#1160]
I've this error only in production, on dev machine it is super fast. I've seen this answer on SO, http://stackoverflow.com/questions/26093393/geocoding-api-not-responding-fast-enough-for-ip-address, but I'm not searching by IP. This is what I'm doing in my model:

```ruby
  reverse_geocoded_by :latitude, :longitude  do |obj,results|
    if geo = results.first
      obj.city    = geo.city
      obj.zip = geo.postal_code
      obj.state = geo.state
      obj.country = geo.country_code
    end
  end
  after_validation :reverse_geocode
```

And this is my geocoder config file

```ruby
Geocoder.configure(
  timeout: 15,                 # geocoding service timeout (secs)
  lookup: :google,            # name of geocoding service (symbol)
  api_key: 'myKey',               # API key for geocoding service
)
```

Any suggestion?

**Comment by frugardc** [comment]
I am seeing this as well.  When I take the URL that is used for GET and paste it into a browser, it works just fine, and quite fast.  Might Google be doing something to block non-browser requests?

**Comment by alexreisner** [comment]
Google enforces per-second and per-day query limits. It sounds like maybe your servers are hitting these limits? If you're using a key this explanation doesn't completely make sense, but there might be some (new?) per-IP throttling (?). In any case, this sounds like a problem with server environment, not a Geocoder gem issue. Are your servers handling a lot of requests? Have you recently run any bulk geocoding tasks?

**Comment by frugardc** [comment]
I shouldn't be hitting the limit.  I think something may have changed with the keys and what API's are enabled or something.  I seem to go in circles trying to figure out the proper way to use the various keys.  I guess it is possible they started enforcing something that they weren't before.  If no one else is seeing the issue, it is probably just account related on my side.

**Comment by stephenprater** [comment]
I am seeing this issue as well - it's a keyed account and I know I'm not hitting the limit, so not sure what's going on here.

**Comment by stephenprater** [comment]
@frugardc do you have an HTTPS proxy?  This turned out to be some weird interaction between our proxy and the `Net::HTTP::Proxy` constructor in the gem for us.  We had to be super specific about what we passed into the `https_proxy` config when we set up Geocoder - like it had to be a FQDN WITHOUT the protocol.

**Comment by JIAZHEN** [comment]
I see this issue on my production too. Any solution?

**Comment by mzaccari** [comment]
I had the same problem with Google on production, but not locally or on staging. In my case it had to do with `https://maps.googleapis.com` sometimes resolving to a `172.217.x.x` IP address, such as `172.217.2.42` and `172.217.4.10`, and production had a route that kept `172.0.0.0/8` internal, causing our geocode lookups to hang. Adding a route for `172.217.0.0/16` to the internet fixed it.

**Comment by alexreisner** [comment]
Closing this for now, as it seems unlikely it's a Geocoder bug.

**Comment by silvermind** [comment]
had the same problem: was a IP v6 production config issue:

https://stackoverflow.com/questions/16040158/rails-mailer-netopentimeout-execution-expired-exception-on-production-serve
