### ISSUE TITLE
Skip certain columns when using "near"

### ISSUE THREAD

**Issue by saifuddin** [alexreisner/geocoder#1161]
Hi, looks like I'm stupid, but I can't figure out how to skip certain columns on the SQL calls. Currently, geocoder will return all columns (e.g. `places.*`). Is there a way to skip certain columns?

Awesome gem, btw!

**Comment by TrangPham** [comment]
You can use the `select` option. See: https://github.com/alexreisner/geocoder/blob/6589b9b2cd6d1cdda06bd1f598fe9ad070d8e5a9/lib/geocoder/stores/active_record.rb#L106

``` ruby
Venue.near('Omaha', 20, :select => "id, column1, column2")
```
