### ISSUE TITLE
Configured :host parameter apparently ignored

### ISSUE THREAD

**Issue by lifepillar** [alexreisner/geocoder#1163]
Hi,
I want to query my own Nominatim server at localhost, as follows:

```ruby
gem 'geocoder'
Geocoder.configure(:lookup => :nominatim, :host => 'localhost/nominatim')
Geocode.search('Sunset Boulevard')
```

but geocoder apparently still tries to connect to OpenStreetMap, i.e., the value of `:host` seems to be ignored. Is that a bug or a misconfiguration on my part?

**Comment by TrangPham** [comment]
Hi @lifepillar 

This is how you should be configuring:
https://github.com/alexreisner/geocoder/blob/6589b9b2cd6d1cdda06bd1f598fe9ad070d8e5a9/test/unit/lookups/nominatim_test.rb#L24

Thanks!

Please reopen if that doesn't work for you.
