### ISSUE TITLE
Google bounds example in README doesn't work

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [alexreisner/geocoder#1171]
```ruby
require 'geocoder'
Geocoder.search("Paris", :bounds => [[32.1,-95.9], [33.9,-94.3]])
```

```
=> [#<Geocoder::Result::Google:0x007fc9bb14d6d8 @data={"address_components"=>[{"long_name"=>"Paris", "short_name"=>"Paris", "types"=>["locality", "political"]}, {"long_name"=>"Paris", "short_name"=>"Paris", "types"=>["administrative_area_level_2", "political"]}, {"long_name"=>"Île-de-France", "short_name"=>"Île-de-France", "types"=>["administrative_area_level_1", "political"]}, {"long_name"=>"France", "short_name"=>"FR", "types"=>["country", "political"]}], "formatted_address"=>"Paris, France", "geometry"=>{"bounds"=>{"northeast"=>{"lat"=>48.9021449, "lng"=>2.4699208}, "southwest"=>{"lat"=>48.815573, "lng"=>2.224199}}, "location"=>{"lat"=>48.856614, "lng"=>2.3522219}, "location_type"=>"APPROXIMATE", "viewport"=>{"northeast"=>{"lat"=>48.9021449, "lng"=>2.4699208}, "southwest"=>{"lat"=>48.815573, "lng"=>2.225193}}}, "place_id"=>"ChIJD7fiBh9u5kcRYJSMaMOCCwQ", "types"=>["locality", "political"]}, @cache_hit=nil>]
```

Should have been Paris, TX, got Paris, France.

**Comment by TrangPham** [comment]
According to google search Paris, FR Lat long is 48.8N, 2.35E
And Paris,TX lat long is 33.66N, 95.55W 

I double checked the example via the command line, and also got the same result. 

Thanks for opening this issue. I will try to debug it. Any help debugging is welcomed too. Based on my gut feeling, I think the issue is that the bounds are not being applied at all somehow.

**Comment by alexreisner** [comment]
@TrangPham please do investigate, but note this from Google's documentation: "The bounding box of the viewport within which to bias geocode results more prominently. This parameter will only influence, not fully restrict, results from the geocoder."

**Comment by TrangPham** [comment]
It seems this is due to the google api and not geocoder. 

running `https://maps.googleapis.com/maps/api/geocode/json?address=Paris&bounds=32.1,-95.9|33.9,-94.3` in your browser manually will also result in Paris France and not Paris Texas.
