### ISSUE TITLE
Any known performance issues to geocode by delegation?

### ISSUE THREAD

**Issue by leoi11** [alexreisner/geocoder#1173]
I have 3 simple models:

```
class Building < ActiveRecord::Base
  has_many :rooms

  geocoded_by :address
  after_validation :geocode
end

class Room < ActiveRecord::Base
  belongs_to :building
  has_many :chairs
end

class Chair < ActiveRecord::Base
  belongs_to :room
end
```

Now I want chairs and rooms objects to be geocoded, but I want to keep my database normalized by not duplicating `latitude` and `longitude` columns onto `rooms` and `chairs`.
So I change Room and Chair to delegate address and lat and long:

```
class Room < ActiveRecord::Base
  belongs_to :building
  has_many :chairs

  delegate :address, to: Building
  delegate :latitude, to: Building
  delegate :longitude, to: Building

  geocoded_by :address
end

class Chair < ActiveRecord::Base
  belongs_to :room

  delegate :address, to: Room
  delegate :latitude, to: Room
  delegate :longitude, to: Room

  geocoded_by :address
end
```

My question is, is there any known performance issue with this?
An assumption I made in my system is that Room and Chair does not have its own address because it always belongs_to the same building, but with this assumption I'm left with the above implementation.

**Comment by alexreisner** [comment]
This looks fine to me. As long as you're not running `geocode` multiple times, the only performance issues are those associated with the delegation of any method.
