### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by lucasgerard** [alexreisner/geocoder#1174]
Hey,

I'm suddenly getting the error below while calling `Geocoder.search(ip)`, any idea why? Thanks!

- Geocoder version is (1.4.3)
- config/initializers/geocoder.rb:

```
Geocoder.configure(
  # geocoding service request timeout, in seconds (default 3):
  :timeout => 30
)
```

- error:
```
Geocoding API's response was not valid JSON: <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.11.8</center>
</body>
</html>
```

**Comment by firec0der** [comment]
Seems like a setting of the proper host will solve your problem.
```ruby
Geocoder.configure(
  timeout: 30,
  freegeoip: { host: "freegeoip.net" }
)
```

**Comment by firec0der** [comment]
Related issue: https://github.com/alexreisner/geocoder/issues/1172

**Comment by lucasgerard** [comment]
Great, it works again, thanks for your quick reply!

**Comment by juhguu** [comment]
Wow! Thanks, @firec0der
