### ISSUE TITLE
request.location.ip not working?

### ISSUE THREAD

**Issue by Aravind6** [alexreisner/geocoder#1182]
I am using geocoder gem for my rails app. getting user ip using request.location.ip is working fine last 4 months. Recently it is stopped working. now i am getting the ip ::1 and location is reserved when i am running the localhost.  Can anyone help me?

**Comment by TrangPham** [comment]
Hi could you please provide some more information to help repro the issue?

Specifically gem version and rails version. Also did you update recently?

**Comment by Aravind6** [comment]
Hi we are using Rails 5.0.2 and geocoder gem is (1.4.3)

**Comment by alexreisner** [comment]
Please upgrade to gem version 1.4.4. Freegeoip changed their server config a couple weeks ago.
