### ISSUE TITLE
Fix: Call To Deprecated Method Object#timeout

### ISSUE THREAD

**Issue by rohitbansal0689** [alexreisner/geocoder#1183]
Hey Admin

During using the Gecoder gem, I got the issue 274:in `make_api_request': Object#timeout is deprecated, use Timeout.timeou. 

I am making  40 parallel queries using "state-country" which initiate  this request http://maps.googleapis.com/maps/api/geocode/json?address=West+Virginia%2C+United+States&language=en&sensor=false  

Thanks

**Comment by TrangPham** [comment]
Beginner Task: Switch to using `Timeout.timeout` 
See https://github.com/nahi/httpclient/pull/287/files for an example of how to handle this.

**Comment by swentling87** [comment]
Hey! I'll take a shot at this one, first time with open source.

**Comment by TrangPham** [comment]
YAY thanks! And welcome to OS :D Please feel free to ask for any clarifications needed!

**Comment by swentling87** [comment]
So in researching this I'm finding that the code for Geocoder makes no call of the function timeout() and that it is likely related to a gem dependency that may need to be updated. @rohitbansal0689 can you post more of the warning here? Specifically the next couple of lines as it appears this is method is called in a related gem/dependency that may need a version update.

**Comment by rohitbansal0689** [comment]
@swentling87 here are the logs 

/usr/local/rvm/gems/ruby-2.3.1@rails4/gems/geocoder-1.2.9/lib/geocoder/lookups/base.rb:274:in `make_api_request': Object#timeout is deprecated, use Timeout.timeout instead.

Geocoder: HTTP request being made for http://maps.googleapis.com/maps/api/geocode/json?address=California%2C+United+States&language=en&sensor=false

/usr/local/rvm/gems/ruby-2.3.1@rails4/gems/geocoder-1.2.9/lib/geocoder/lookups/base.rb:274:in `make_api_request': Object#timeout is deprecated, use Timeout.timeout instead.

Geocoder: HTTP request being made for http://maps.googleapis.com/maps/api/geocode/json?address=Alabama%2C+United+States&language=en&sensor=false

/usr/local/rvm/gems/ruby-2.3.1@rails4/gems/geocoder-1.2.9/lib/geocoder/lookups/base.rb:274:in `make_api_request': Object#timeout is deprecated, use Timeout.timeout instead.

Geocoder: HTTP request being made for http://maps.googleapis.com/maps/api/geocode/json?address=Alaska%2C+United+States&language=en&sensor=false

/usr/local/rvm/gems/ruby-2.3.1@rails4/gems/geocoder-1.2.9/lib/geocoder/lookups/base.rb:274:in `make_api_request': Object#timeout is deprecated, use Timeout.timeout instead.

Geocoder: HTTP request being made for http://maps.googleapis.com/maps/api/geocode/json?address=Arizona%2C+United+States&language=en&sensor=false

/usr/local/rvm/gems/ruby-2.3.1@rails4/gems/geocoder-1.2.9/lib/geocoder/lookups/base.rb:274:in `make_api_request': Object#timeout is deprecated, use Timeout.timeout instead.

Geocoder: HTTP request being made for http://maps.googleapis.com/maps/api/geocode/json?address=Arkansas%2C+United+States&language=en&sensor=false

**Comment by alexreisner** [comment]
Looks like 1.2.9. This was fixed in subsequent gem versions of Geocoder.

**Comment by rohitbansal0689** [comment]
@alexreisner yeah it seems due to old version of gem. I have updated the version to "1.4.3" . Thanks for your help.

**Comment by TrangPham** [comment]
Thanks @swentling87 for helping look into this! Your help is appreciated :) Feel free to pick out another task and we'd be glad to help you make more OS contributions!
