### ISSUE TITLE
I am using geocoder gem to fetch the ip address of the user(while they logging-in), till a month before it works well. but, now it is not working , can anybody help to overcome this issue. thanks in advance.

### ISSUE THREAD

**Issue by Aravind6** [alexreisner/geocoder#1184]
even i updated the gem version to 'geocoder', '~>  1.4.4'

**Comment by theMark** [comment]
I've noticed the same thing. It stoped working a few weeks ago.  I'm getting a null response when I make a Geocoder call.

**Comment by alexreisner** [comment]
Can anyone experiencing this issue please post 1) your geocoder version, 2) your configured IP lookup, and 3) a command that causes a null response (eg: `Geocoder.search("...")`)

**Comment by kandelchy** [comment]
I had the same problem, you will need to upgrade your gem to the new version 1.4.4

**Comment by alexreisner** [comment]
Closing--assuming this was due to the recent change in Freegeoip, and fixed in 1.4.4.
