### ISSUE TITLE
Method .near doesn't look across 180th Meridian

### ISSUE THREAD

**Issue by kolomeetz** [alexreisner/geocoder#1195]
If I have multiple POIs in Eastern and Western Hemisphere, method `.near` with coords near 180th Meridian will find only points from the hemisphere the coordinates belong to.

For example, if I search anything within 2000 Km from Nothern Island, New Zealand, I won't find far east islands belong to NZ, because they are across the 180th Meridian.

I created small demo project to reproduce the bug: https://github.com/kolomeetz/geocoder-near-meridian.

**Comment by kolomeetz** [comment]
sorry misclicks :-(

**Comment by alexreisner** [comment]
Unfortunately this is a shortcoming of the [Haversine formula](https://en.wikipedia.org/wiki/Haversine_formula) which Geocoder uses to calculate distances. I'm not sure it can be fixed without using a different algorithm, and I'm not aware of a great alternative.
