### ISSUE TITLE
getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by luizkowalski** [alexreisner/geocoder#1198]
now and then, I see this error on our backend: 

```
ActionView::Template::Error: getaddrinfo: Name or service not known
```
it comes from this line:

```
actual_country: request.location.nil? ? nil : request.location.data[:country_code2]
``` 

seems like Geocoder is having trouble to find the country code for the ip, funny thing is that we use `maxmind_local` to do search, because we do **a lot** of searches....

this call actually, comes from users behind a VPN (we are a vpn company) so I'm not sure what could be causing this error...
1) could be that even using the maxmind_local configuration, geocoder is still trying to do another api call?
2) maybe, because these users are behind a vpn I should use `safe_location` instead?

**Comment by alexreisner** [comment]
Do you have the full backtrace? Would be useful to see where exactly the `getaddrinfo` (a SocketError) is being raised.

**Comment by luizkowalski** [comment]
This is the most important part:
```
SocketError: getaddrinfo: Name or service not known
  from geoip.rb:857:in `getaddress'
  from geoip.rb:857:in `lookup_ip'
  from geoip.rb:365:in `city'
  from geocoder/lookups/maxmind_local.rb:33:in `results'
  from geocoder/lookups/base.rb:47:in `search'
  from geocoder/query.rb:11:in `execute'
  from geocoder.rb:22:in `search'
  from geocoder/request.rb:11:in `location'
  from app/views/users/_info.jb:16:in `_app_views_users__info_jb__4602458887819602780_92896600'
```

**Comment by alexreisner** [comment]
This is coming from [the GeoIp gem](https://github.com/cjheath/geoip/blob/master/lib/geoip.rb#L857), which [calls IPSocket.getaddress](https://docs.ruby-lang.org/en/2.1.0/IPSocket.html) for IPv6 addresses. I think any fix for this would have to be implemented on the GeoIp gem.
