### ISSUE TITLE
Freegeoip host now incorrect

### ISSUE THREAD

**Issue by danarnold** [alexreisner/geocoder#1202]
It seems that Freegeoip changed its hostname from freegeoip.io to freegeoip.net. This means that right now, Geocoder with ip_lookup set to freegeoip won't work, since the host is hardcoded in to be freegeoip.io. I updated the host with the `freegeoip: { host: .... }` configuration syntax, and it's working fine for me now. However, I figured I'd let you know so you can update the gem with the new host.

Geocoder version: 1.4.4
Rails version: 5.0.0.1

**Comment by alexreisner** [comment]
Are you still experiencing this? I can't seem to reproduce it. [The freegeoip.io host seems to work fine.](https://freegeoip.io/json/97.123.32.13)

**Comment by danarnold** [comment]
Yeah, it seems to be up again. However, we've seen some downtime over the last few weeks of that host (as well as SSL conflicts that led to requests that couldn't complete), and there was definitely some unavailability yesterday for a few hours while I figured out what was wrong, fixed it, and deployed the changes to our apps.

It seems to me that the .net host is canonical and that .io is a mirror. If you look at [the project's github](https://github.com/fiorix/freegeoip), they reference the code as "the web server that empowers freegeoip.net," without any mention of the .io host. Also, when you search it on Google, the .net host is the one that comes up. I realize these aren't very scientific methods of determining which is the best host, but in my opinion, it does seem to indicate that .net would be a better choice.

**Comment by alexreisner** [comment]
Hmm...I agree that .net *appears* to be the correct host. See also [this freegeoip issue](https://github.com/fiorix/freegeoip/issues/165). Several months ago the .net host was down for more than a week, which is when I switched Geocoder to .io. I think it makes sense to switch back now. Going to do that in a moment. Thanks!
