### ISSUE TITLE
Stub geocoder with address_components in rspec

### ISSUE THREAD

**Issue by VoTaiTri** [alexreisner/geocoder#1203]
i try to write rspec to test some code work with gem Geocoder. With `location` is a `Geocoder::Result::Google` object, my code like : 

```ruby
address = location.address_components_of_type(:sublocality_level_1).first&.dig('long_name')
```
and i implement stub a point like (refer [here](https://github.com/alexreisner/geocoder#testing-apps-that-use-geocoder) ) : 
```ruby
Geocoder.configure(lookup: :test)
Geocoder::Lookup::Test.set_default_stub(
  [
    {
       'latitude'     => 35.6691084,
       'longitude'    => 139.6009546,
        'address'      => 'Address',
       'state'        => 'State',
        'city'         => 'City',
       'types'        => ['political'],
        'address_components' => [
        {
          'types' => ['sublocality_level_1'],
          'long_name' => 'level_1',
        }
      ]
    },
  ]
)
```
i try to byebug when run rspec and check, i get : 
```
(byebug) location.class
Geocoder::Result::Test
(byebug) location.address_components
[{"types"=>["sublocality_level_1"], "long_name"=>"level_1"}]
(byebug) location.respond_to?(:address_components_of_type)
false
```
`location.respond_to?(:address_components_of_type)` return false, and i can't call `location.address_components_of_type(:sublocality_level_1).first&.dig('long_name')` as my expect.

`location` when run rspec is a `Geocoder::Result::Test` object.

so, can you help me to resolve this issue? many thanks

***
Geocoder version: 1.4.3
Rails version: 5.0.2

**Comment by alexreisner** [comment]
Sorry for the delay. This is explained by a note added here: 9ea50a86a1ef762269f4c8d09e5934afd5acd93c

Basically, the Test lookup returns stubbed results. I'm not saying it *should* but unfortunately right now that's what it does.
