### ISSUE TITLE
Configuring API Key for Geocoding and IP Lookup Services

### ISSUE THREAD

**Issue by tylerbodway** [alexreisner/geocoder#1204]
I noticed there is only one `Geocoder.configure(api_key: "")` 

What if you are using a Geocoding Service with an API Key requirement as well as an IP Lookup service with an API Key requirement? How do you define these separate credentials?

Example:
```rb
Geocoder.configure(
  lookup: :google,
  ip_lookup: :ipapi_com,
  api_key: "" # Geocoder or IP ?? I need both
)
```

**Comment by alexreisner** [comment]
Please see [the readme under "Configure Multiple Services"](https://github.com/alexreisner/geocoder#configure-multiple-services).

**Comment by tylerbodway** [comment]
Perfect, I apologize for not catching that. Thanks!
