### ISSUE TITLE
Unable to match distance values

### ISSUE THREAD

**Issue by swaruprs** [alexreisner/geocoder#1211]
**Distance between Eiffel Tower and Empire State Building**

Geocoder::Calculations.distance_between([47.858205,2.294359], [40.748433,-73.985655])
 => **3619.77359999382** # in configured units (default miles)

    def geodistance
      render json: Geocoder::Calculations.distance_between([47.858205,2.294359], [40.748433,-73.985655])
    end

**In my case** I am getting the value to be:
 => **3648.3340765758867**

Unit configurations are unchanged, not sure what can go wrong!

**Comment by alexreisner** [comment]
I'm not sure why the number in the README doesn't match (I'm getting the same result as you are). That part of the README was written a long time ago, and code has probably changed since then. I wouldn't worry about this 29-mile difference.

**Comment by swaruprs** [comment]
@alexreisner I have a follow up in this case.

These distance values are differing from that I get in google map.
ex: 
      
      Geocoder::Calculations.distance_between([12.936992, 77.627002], [12.848925, 77.651733]) 

=> 6.3087039709946735 (default: miles) or 10.152874887374361 in kms

GMap result: 13.9 KMs. 

since I am adding nearby users feature in my project, where I say this user is 10 kms away and in google map that is 13.9 kms away, that will surely lead to a some amount of frustration.

Please share some lights

**Comment by swaruprs** [comment]
Please keep it open, I have a follow up query

**Comment by alexreisner** [comment]
Google Maps is giving you the distance via roads. Geocoder is giving distance via straight line.

**Comment by swaruprs** [comment]
The location proximity apps, are they using these straight line distance?

I am using distance as a radius from user point for suggesting places of interest and updating how far these places are. What will be a good approach this case?

What distance do these other proximity apps use?
