### ISSUE TITLE
NoMethodError (undefined method `near' for #<Class:#>)

### ISSUE THREAD

**Issue by swaruprs** [alexreisner/geocoder#1212]
Near method works if **address** column and **reverse_geocoded_by** are included which is not needed in this class as latitude and longitude comes from rest client. 

Error after commenting out  **address** and **reverse_geocoded_by**
NoMethodError (undefined method `near' for #<Class:#>):

    create_table :locate do |t|
      t.integer :user_id
      # t.string :address
      t.float :latitude
      t.float :longitude

      t.timestamps
    end

    class Locate < ApplicationRecord

	    # reverse_geocoded_by :latitude, :longitude
        # after_validation :reverse_geocode, unless: -> (obj) { obj.address.present? },
	            #   if: -> (obj) { obj.latitude.present? and obj.latitude.present? and ( obj.latitude_changed? || obj.longitude_changed? ) }
    end

    def near
      center = @user.locate
      render json: Locate.near([center.latitude, center.longitude], 5, units: :km)
    end

**Comment by alexreisner** [comment]
The `geocoded_by` and `reverse_geocoded_by` statements are what add the `near` method to a class. You need one or the other, so that Geocoder knows what columns to look at for latitude and longitude values. I'm not sure what you mean about coordinates coming from a rest client. To use `near`, they must be stored in your database.

**Comment by swaruprs** [comment]
The coordinates are stored in database by:
`Locate.create(latitude: params[:latitude], longitude: params[:longitude])` 

The rest client sends the json request `params[:latitude]` and `params[:longitude]`.
That adds this latitude and that longitude float numbers and stores in this locates table. 
Why do I need the `geocoded_by` or the `reverse_geocoded_by` in this case, that for sure can save GoogleAPI quota usage.

**Comment by alexreisner** [comment]
Ah, I see. No geocoding will run (ie, Google API will not be accessed) without calling the `geocode` or  `reverse_geocode` methods. Leave `reverse_geocoded_by` and remove the `after_validation` line and you should be fine.

**Comment by swaruprs** [comment]
there it is ;) 
thanks dude
