### ISSUE TITLE
make_api_request deprecation on Object#timeout in Ruby 2.4.0

### ISSUE THREAD

**Issue by cilim** [alexreisner/geocoder#1213]
I tried using the `near` method from geocoder, but I only get errors and nothing is returned from the database.

```
/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/geocoder-1.1.9/lib/geocoder/lookups/base.rb:228:in `make_api_request': Object#timeout is deprecated, use Timeout.timeout instead.
```

Changing `timeout(configuration.timeout) do` to `Timeout.timeout(configuration.timeout) do` in `geocoder/lookups/base.rb` on line 228 fixes the problem.

### Steps to reproduce

I just tried to run the default `near` method:
```ruby
Job.near(user_location, MAX_USER_JOB_RANGE)
```

### Environment info

* Geocoder version: 1.1.9
* Rails version: ruby 2.4.1p111
* Database: Postgresql

**Comment by cilim** [comment]
After a big more debugging my tests aren't failing when I comment out the `after_validation` callback in my model:

```ruby
class Job < ApplicationRecord
  reverse_geocoded_by :latitude, :longitude
  # after_validation :reverse_geocode
end
```

**Comment by alexreisner** [comment]
Please upgrade to a more recent version of Geocoder. This has been fixed.
