### ISSUE TITLE
Sample configuration for ipinfo_io as provider with TOKEN as request param

### ISSUE THREAD

**Issue by dikey94** [alexreisner/geocoder#1219]
I'm looking for a sample configuration of Geocoder with ipinfo.io. I know i can set a :ip_lookup => :ipinfo_io but how to put a token?

Thanks

**Comment by TrangPham** [comment]
Hi thanks for bringing this up! It's not noted on the readme for the lookup. Here's the class: https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/ipinfo_io.rb

It's expecting it as the API key. 
Please feel free to create a PR to update the read me. :) 

Thanks!

**Comment by TrangPham** [comment]
Beginner-task:

Update the READ ME section for ipinfo.io to include :api-key => TOKEN
