### ISSUE TITLE
Travis Tests failing 

### ISSUE THREAD

**Issue by TrangPham** [alexreisner/geocoder#1224]
Travis tests are failing for some of the builds in matrix due to gem dependency issues causing bundle install not to complete correctly See: https://travis-ci.org/alexreisner/geocoder/builds/277296105

**Comment by TrangPham** [comment]
Issues in the build:
`An error occurred while installing byebug (9.1.0), and Bundler cannot continue.`
- 2.1.2

`The program 'bundle' is currently not installed. To run 'bundle' please ask your administrator to install the package 'bundler'`
  - jruby-19mode

**Comment by TrangPham** [comment]
Found out that a bunch of older versions of Ruby are no longer supported. Updating our travis test matrix to reflect that: #1225

**Comment by TrangPham** [comment]
We also should update our travis to work with newer versions of jruby: https://github.com/jruby/jruby/wiki/Roadmap

**Comment by alexreisner** [comment]
Hmm...I don't think we should do this quite so suddenly. "Unsupported" Ruby versions aren't dead, they're just not receiving security updates. They may still be in (wide) use, and removing versions from the test matrix is tantamount to dropping support for them, which requires a minor version bump, and so should probably be merged into a separate branch (eg, `1.5.0`).

I think we can drop 1.9.3 support in the next minor release, and I'm open to arguments for dropping 2.0.x support as well, although I'm a little less comfortable with that, given that compatibility and ease of use are core Geocoder features. For the others, we should introduce version-specific gemfiles and select compatible versions of gems (eg, `byebug`).

And, when we do drop 1.9.3 support, we can also remove `gemfiles/Gemfile.ruby1.9.3`. Yay!

**Comment by TrangPham** [comment]
Okay. That makes sense. Let’s revert #1225 for now then and continue to
talk about what we should do.

**Comment by alexreisner** [comment]
Yes! Thanks for raising this issue. We need to fix the tests as it makes contributing more confusing.

**Comment by alexreisner** [comment]
@TrangPham I agree: let's drop 1.9.3 support. If you want to go ahead and do it, just make the commit in a `1.5.0` branch, in case we need to do another release before we get 1.5.0 polished.

**Comment by TrangPham** [comment]
I've reverted #1225 from master for now. I will continue to look at the travis tests soon
