### ISSUE TITLE
NoMethodError for ActiveRecord::Relation

### ISSUE THREAD

**Issue by aprofromindia** [alexreisner/geocoder#1228]
BEFORE POSTING AN ISSUE, PLEASE MAKE SURE THE PROBLEM IS NOT ADDRESSED IN THE README!

### Expected behavior
Fetches location within 20 miles

### Actual behavior

`undefined method `near' for #<ActiveRecord::Relation []>`

### Steps to reproduce

`GemFile` ->  gem 'geocoder', '~> 1.4.4'

model.rb
`
class Model < ActiveRecord::Base
end`

schema.rb
`create_table "models", force: true do |t|
    t.string   "category"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.float    "latitude"
    t.float    "longitude"
  end`

models_controller.rb

def index
  @models = Model.all
  @models = @models.where('category like ?', '%#{params[:category]}#%') if 
  params[:category].present?
  @models = @models.near(' [?] 20', params[location])

  @models
end

### Environment info

* Geocoder version: 1.4.4
* Rails version: 4.1 
* Database (if applicable): PG

If I cannot call the `near` method on a relation, how can i achieve the same please?

**Comment by alexreisner** [comment]
You need to have a `geocoded_by` statement in your model. Please see the readme for more details.

**Comment by aprofromindia** [comment]
@alexreisner - do I need to add the geocoded_by statement when I am providing the latitude and longitude separately please?
