### ISSUE TITLE
Automatic reverse geocoding is not working

### ISSUE THREAD

**Issue by mityakoval** [alexreisner/geocoder#1229]
### Expected behavior
Reverse geocoding assigns the results to the specific fields of the model when using hooks.

### Actual behavior
Reverse geocoding returns an empty array when using hooks.

### Steps to reproduce
in the model: 

```
include Geocoder::Model::Mongoid
after_validation :reverse_geocode

field :coordinates, type: Array
field :city, type: String
field :country, type: String
field :street, type: String
field :postal_code, type: String

reverse_geocoded_by :coordinates do |obj, results|
    logger.info results.inspect # this line prints out '[]'
    if res = results.first
      obj.city = res.city
      obj.street = res.address
      obj.country = res.country
      obj.postal_code = res.postal_code
    end
  end
```

```
rake db:mongoid:create_indexes
```

```
irb > p = Place.create(coordinates: [59.917028, 10.752694])
```
This line creates an object only with the `coordinates` field.

```
irb > p.reverse_geocode # returns nil
```

I have checked this with `Gecoder.search([59.917028, 10.752694])` and it worked perfectly.

### Environment info

* Geocoder version: 1.4.4
* Rails version: 5.0.6
* Database (if applicable): MongoDB v3.4.9
* Mongoid version: 6.1.1

**Comment by TrangPham** [comment]
Hi I'm no expert in Mongoid (in fact I don't use it at all). I'm curious though from what I understand, `create` might not be running the validations (tried to google this and got no good answer). But it seems like `save` and `create!` should run the validations. Could you try to use these and see if the geocoding methods are still not run?

**Comment by mityakoval** [comment]
Hi! Your edit is correct. Basically, the difference between `create` and `create!` is that the latter raises the validation error if one occurs, whereas the former one doesn't. The same rule applies to `save!`.

http://www.rubydoc.info/github/mongoid/mongoid/Mongoid/Persistable/Creatable/ClassMethods

**Comment by mityakoval** [comment]
Hi! Figured it out. Apparently, I misunderstood the lat and lon order for Mongoid. As soon as I reversed them, it worked.

Bottom line:
This works
```
irb> p = Place.create(coordinates: [longitude, latitude])
```

And this one does not:
```
irb> p = Place.create(coordinates: [latitude, longitude])
```
