### ISSUE TITLE
.near query not working properly. Result get blank array.

### ISSUE THREAD

**Issue by krunalbabaria** [alexreisner/geocoder#1238]
**I want to find location using near query with radius.**
My database query is this : -> Location.near([19.15, 72.93] , 60, :units => :km)

### Expected behavior

Appropriate result which is get location withing 60 km from my current location. [19.15, 72.93]

### Actual behavior

It gives below result in response.
#<ActiveRecord::Relation []>

### Environment info

* Geocoder version:  
* Rails version:  Rails 5.1.1
* Database (if applicable):  postgres

**Comment by alexreisner** [comment]
Are you sure you have geocoded objects in your database within 60 km of [19.15, 72.93]?
