### ISSUE TITLE
.within_bounding_box generating wrong SQL on box crossing 180th meridian

### ISSUE THREAD

**Issue by ptrskorupa** [alexreisner/geocoder#1243]
I want to get users within a bounding box. There is a single user with [56, -179] coords. Then I call `User.within_bounding_box([[-70, 178], [-71, -178]])`. This generates the following query:

> `SELECT "users".* FROM "users" WHERE (users.latitude BETWEEN -70 AND -71 AND users.longitude BETWEEN 178 AND 180 OR users.longitude BETWEEN -180 AND -178)`

Since `BETWEEN` operator takes precedence, then `AND` and, lastly, `OR`, I believe this query is equivalent to:

> `SELECT "users".* FROM "users" WHERE ((users.latitude BETWEEN -70 AND -71 AND users.longitude BETWEEN 178 AND 180) OR (users.longitude BETWEEN -180 AND -178))`

The first condition (on the left side of OR) is not true, but the second is - resulting in a relation object with _all_ users between longitude -180 and -178 regardless of their latitude. This works fine if the user has a positive longitude (e.g., 179), because both conditions are then false.

### Expected behavior
Should return an empty relation object, since the user is not inside the box.
SQL query should be:
> `SELECT "users".* FROM "users" WHERE (users.latitude BETWEEN -70 AND -71 AND (users.longitude BETWEEN 178 AND 180 OR users.longitude BETWEEN -180 AND -178))`

### Actual behavior
Returns a relation object containing the aforementioned user.

### Steps to reproduce
1. Create a record with random latitude and negative longitude that is near the 180th meridian.
2. Call .within_bounding_box with latitude excluding the user but longitude crossing the 180th meridian, so that the SQL WHERE clause is split with an OR, and longitude range including the user.

### Environment info

* Geocoder version: 1.4.4
* Rails version: 5.1.4
* Database (if applicable): PostgreSQL 9.6.5

**Comment by alexreisner** [comment]
Hmm...you may be onto something, but it also looks like you're passing the wrong coordinates to the method. It requires [SW, NE] and it looks like you're giving it [NW, SE]. Or is my math wrong? If not, can you try it with [SW, NE] and see if it works (ie, `[[-71, 178], [-70, -178]]`)?

**Comment by ptrskorupa** [comment]
You're right, I messed up the coordinates. However, this issue still persists if I fix these coords - `User.within_bounding_box([[-71, 178], [-70, -178]])` gives

> SELECT "users".* FROM "users" WHERE (users.latitude BETWEEN -71 AND -70 AND users.longitude BETWEEN 178 AND 180 OR users.longitude BETWEEN -180 AND -178)

which differs from the previous queries only in latitude operands for `BETWEEN` (it was `-70 AND -71`, now it's `-71 AND -70` and works properly), and the result still contains the user. Even with this fixed it still looks like a genuine issue to me.

**Comment by ptrskorupa** [comment]
As a side note, this is how [geokit-rails](https://github.com/geokit/geokit-rails) handles the same query - calling `User.in_bounds([[-71, 178], [-70, -178]])` generates this SQL:

> SELECT "users".* FROM "users" WHERE (users.latitude>-71 AND users.latitude<-70 AND (users.longitude<-178 OR users.longitude>178))

which handles this a bit differently, but explicitly uses parentheses to enforce the correct order of operations.

**Comment by alexreisner** [comment]
Ah, sorry, I see what you mean now. I've fixed the issue with 317832ca2b7ec234fca6039184686d921bac925d. Let me know if that doesn't do it. And thanks for pointing this out!

**Comment by ptrskorupa** [comment]
Works great now! Thank you for your time.
