### ISSUE TITLE
Find all objects within custom area

### ISSUE THREAD

**Issue by meliborn** [alexreisner/geocoder#1245]
Can't find it in README.
Let's say I have a custom area like this 
![](https://monosnap.com/file/FeynNeenhLjMOZAdwW67Aa9CmyNFt5.png)
And coordinates of this area:
![](https://monosnap.com/file/WlsJk2hS8k8QBTthGC6IeRsAsJbpPE.png)

How could I find all objects within this area?

**Comment by alexreisner** [comment]
Geocoder only supports search within a circle (of specified radius). For searching within more complex shapes, you'll need to use the geo-spatial features of your database. See [the rgeo gem](https://github.com/rgeo/rgeo) for details.
