### ISSUE TITLE
Query: How to find the address is invalid and display errors-message in the form

### ISSUE THREAD

**Issue by shivabhusal** [alexreisner/geocoder#1246]
I searched for a long time but could not find how to validate the user input address. Lets say if user inputs address like 'aaaaaaaaaaaaaaaaaaaaaaaaa' then this doesnot resolve to any coordinates; and lat/lng should be nil. but I found that `geocode` method doesnot update `lat/lng' fields if the result is nil.

And I found no way to validate the user input address. if there any way to validate the address in active record?

**Comment by alexreisner** [comment]
Validating addresses is complicated. In this case it sounds like what you want to do is be sure the stored lat/lon values are always overwritten when a lookup returns zero results. You can do this by passing a custom block to the `geocode` method, as shown [in the readme](https://github.com/alexreisner/geocoder#advanced-geocoding).
