### ISSUE TITLE
Geocoder test stubs do not behave like result objects they stub out

### ISSUE THREAD

**Issue by abevoelker** [alexreisner/geocoder#1249]
### Expected behavior
Test stubs should behave like the result objects they are stubbing out

### Actual behavior
Test stubs don't respond to all methods that result objects should have

### Steps to reproduce

```ruby
if Rails.env.test?
  Geocoder.configure(lookup: :test, ip_lookup: :test)
else
  Geocoder.configure(lookup: :google, ip_lookup: :freegeoip)
end

Geocoder::Lookup::Test.add_stub(
  "96.37.127.78", [{
    "ip"=>"96.37.127.78",
    "country_code"=>"US",
    "country_name"=>"United States",
    "region_code"=>"WI",
    "region_name"=>"Wisconsin",
    "city"=>"La Crosse",
    "zip_code"=>"54601",
    "time_zone"=>"America/Chicago",
    "latitude"=>43.7982,
    "longitude"=>-91.1286,
    "metro_code"=>702,
  }]
)

result = Geocoder.search("96.37.127.78", ip_address: true).first
result.class # => Geocoder::Result::Test
expect(result.state_code).to eq("WI")
# RSpec::Expectations::ExpectationNotMetError: 
# expected: "WI"
#      got: nil

```

### Environment info

* Geocoder version: 1.4.4
* Rails version: N/A

The problem is that by using the `:test` IP lookup strategy, the stubbed objects are actually `Geocoder::Result::Test` instances rather than the type of instance that the real application would be receiving (e.g. `Geocoder::Result::Freegeoip` for my application), and so the behavior is different.

For my own project, I have found it simpler to remove my use of Geocoder's built-in test stubbing and simply use rspec's:

```ruby
GEOCODER_LACROSSE_IP = Geocoder::Result::Freegeoip.new({
  "ip"=>"96.37.127.78",
  "country_code"=>"US",
  "country_name"=>"United States",
  "region_code"=>"WI",
  "region_name"=>"Wisconsin",
  "city"=>"La Crosse",
  "zip_code"=>"54601",
  "time_zone"=>"America/Chicago",
  "latitude"=>43.7982,
  "longitude"=>-91.1286,
  "metro_code"=>702,
})

allow(Geocoder).to receive(:search).and_call_original
allow(Geocoder).to receive(:search).with("96.37.127.78", ip_address: true).and_return([GEOCODER_LACROSSE_IP])

result = Geocoder.search("96.37.127.78", ip_address: true).first
result.class # => Geocoder::Result::Freegeoip
expect(result.state_code).to eq("WI") # true
```

It might be simpler for Geocoder to advise users to use their testing library's stubbing functionality and save the need for a custom stubbing solution which may deliver surprising behavior.

**Comment by alexreisner** [comment]
I agree with this. The built-in testing functionality represents one approach, and in many cases it's better to use external stubbing functionality and something like VCR to avoid network calls. We should probably add a brief note about this in the README.

**Comment by alexreisner** [comment]
Added: 9ea50a86a1ef762269f4c8d09e5934afd5acd93c
