### ISSUE TITLE
Geocode with radius meters / precision

### ISSUE THREAD

**Issue by Dorian** [alexreisner/geocoder#1251]
### Expected behavior

I would like to be be able to get the precision / radius in meters around the location, e.g. the whole city for Paris, only the building for a precise address

### Actual behavior

Can't seem to find this info.

### Environment info

* Geocoder version: 1.4.5
* Rails version: 5.2.beta2

**Comment by alexreisner** [comment]
Not all APIs return this info. Please call the `#data` method of any `Geocoder::Result` object to get the full parsed response and see if it contains what you're looking for.
