### ISSUE TITLE
Multiple Params with Geocoder.search

### ISSUE THREAD

**Issue by angkiki** [alexreisner/geocoder#1260]
As the title states, I'm having trouble looking for a way to run the function `Geocoder.search` with multiple params. I'll elaborate on the current issue I'm facing:

Users submit their postal code through a form. I perform `Geocoder.search(users_postal_code)` and return their street name. This works fine for most instances. However, for certain postal codes, I end up receiving the street names of a different country than the one desired (Singapore in this instance). Is there a way in which I could perform the search (using only postal codes) and be able to specify a country to search in? 

I've gone through the documentation on [the geocoder website](http://www.rubygeocoder.com/) but only single parameters were specified. 

On the github's readme, I've only found 1 instance in which multiple params were given, which is:
```
# with Google:
Geocoder.search("Paris", :bounds => [[32.1,-95.9], [33.9,-94.3]])
```
Which led me to try the following variations in an attempt to input multiple parameters:
```
Geocoder.search("123456", country: "SG")
Geocoder.search("123456", country: "Singapore")
Geocoder.search("SG", postal_code: "123456")
Geocoder.search("Singapore", postal_code: "123456")
```
All of which do not seem to work. I've tried googling for a solution and also attempted to scrutinize the documentation for one, but I have yet to find a solution. I do apologise if I overlooked one. 

For what its worth, I attempted to obtain a solution on [stackoverflow](https://stackoverflow.com/questions/48605469/rails-5-geocoder-gem-search-with-multiple-parameters) prior to opening this issue.

### Environment info

* Geocoder version: 1.4.5 
* Rails version: 5.1.4

**Comment by alexreisner** [comment]
The answer varies depending on what API you're using. You'll need to find out what parameters are available for limiting geographic area. With Google I'd recommend using `:bounds`, as you saw in the README.
