### ISSUE TITLE
freegeoip.io is broken or has been shut down

### ISSUE THREAD

**Issue by ndbroadbent** [alexreisner/geocoder#1262]
When I call `.geocode` to look up the the location of an IP address, I started getting this error:

```
Geocoder: HTTP request being made for https://freegeoip.io/json/104.131.36.95
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
```

(I set `Geocoder.config[:kernel_logger_level] = ::Logger::DEBUG` to find the host.)

I was also getting an SSL error in Chrome when I visited `https://freegeoip.io/`. It's giving me an SSL cert for couchpotato.freegeoip.io. When I ignore the SSL warning, it shows the couch potato UI (same site as https://couchpotato.freegeoip.io/).

So I think this site has been taken down, or maybe the server is broken temporarily. What's the best alternative in the meantime?

* Geocoder version: 1.4.4
* Rails version: 5.1.4
* Database (if applicable): Postgres

**Comment by ndbroadbent** [comment]
I switched to ipinfo.io for now: https://github.com/alexreisner/geocoder#ipinfoio-ipinfo_io

**Comment by nratter** [comment]
@ndbroadbent try upgrading the gem to 1.4.5. Per the Changelog (https://github.com/alexreisner/geocoder/blob/master/CHANGELOG.md), it will use freegeoip.net instead of freegeoip.io
