### ISSUE TITLE
How to use geocoded_by with place_id and then access the results data

### ISSUE THREAD

**Issue by kriskhaira** [alexreisner/geocoder#1264]
Hi. I'd like to use geocoded_by to geocode by a Google Place ID, and then save the address in the result into an attribute to cache it. How would I go about doing that? 

I looked at geocoded_by but don't see how I can tell it that I'm geocoding by place_id.

**Comment by duhaime** [comment]
@alexreisner is it possible to get a Google Maps record given a `place_id`? 

I realize that kind of query isn't geocoding per se, but it's something I'd expect this library to handle

**Comment by duhaime** [comment]
Ah, I see:

```
Geocoder.search("ChIJD7fiBh9u5kcRYJSMaMOCCwQ", :google_place_id => true)
```
