### ISSUE TITLE
Use https for nominatim.openstreetmap.org

### ISSUE THREAD

**Issue by grischard** [alexreisner/geocoder#1267]
The nominatim geocoding service at nominatim.openstreetmap.org is available over https, and [will soon start redirecting all http requests to https](https://lists.openstreetmap.org/pipermail/geocoding/2018-January/001918.html).

Some ruby http libraries don't follow redirects by default.

Would it please be possible to update the "SSL support" line in the readme to 'mandatory' and make all nominatim requests over https?

### Expected behavior

All requests to openstreetmap are made to https://nominatim.openstreetmap.org

### Actual behavior

Requests to openstreetmap are made to http:// or https://nominatim.openstreetmap.org depending on the user configuration. By default, they're made over http.

### Steps to reproduce

Using `:nominatim`, look up a street address.

### Environment info

* Geocoder version: latest master
* Rails version: any
* Database (if applicable): n/a

**Comment by alexreisner** [comment]
Done. Thanks for this!

**Comment by felix-rafael** [comment]
Hi,

I would like to discuss about undoing these changes. We use a custom nominatim host, and for now it doesn't have HTTPS enabled, updating our local version to this one resulted in none of our nominatim requests working and I had to monkey patch it in my project.

I would suggest forcing the `use_https` to true by default for nominatim, so I can just set `use_https` to `false` at my own risk.

Thanks in advance.

**Comment by alexreisner** [comment]
@felix-rafael sorry about that, and thanks for letting us know. This has been fixed by 26d57fd35f6815ea2140602293f6732e1807aa18. New gem release coming soon.
