### ISSUE TITLE
OpenSSL::SSL::SSLError: hostname "freegeoip.io" does not match the server certificate

### ISSUE THREAD

**Issue by calvinsug** [alexreisner/geocoder#1270]
Hi, i have been using geocoder for 4 months, and i used it without any problem. The problem occurs maybe around 2-3 days ago, and i just realized it today. 

The problem occurs when i use this code:

`geocodes = Geocoder.search request.ip`

Here's the log says when it executes above code:
`OpenSSL::SSL::SSLError: hostname "freegeoip.io" does not match the server certificate
`

When i try to use it in rails console,
`Geocoder.search("204.57.220.1")`
 it also runs the same errors like above.

Any solution to overcome this problem?

**Comment by diegotoral** [comment]
I can confirm this problem. It's happening more frequently these days (3 times in the last two days).

**Comment by naellis89** [comment]
It looks like it is trying to hit "http://freegeoip.io/" and it is down right now.  A simple patch so this returns something reasonable during network outages would be really cool.

**Comment by alexreisner** [comment]
Upgrading to gem version 1.4.5 or higher should resolve this.
