### ISSUE TITLE
Freegeoip Deprecations

### ISSUE THREAD

**Issue by Heath101** [alexreisner/geocoder#1279]
First off, thanks for this great project!!

Secondly, has there been any work done to handle the **Important Announcement** section which was outlined on the freegeoip github page [https://github.com/apilayer/freegeoip/](https://github.com/apilayer/freegeoip/)?  Most importantly that an api key will now be required, to use the service.

Since freegeoip is the default IP lookup strategy, I just wanted to see if this was on the radar to be upgraded, or if I just missed a solution that allows to me to add my api_key.

**Comment by alexreisner** [comment]
Thanks for letting me know about the Important Announcement--I wasn't aware of it. I'm open to a pull request which adds support for the API key. I'm also going to change Geocoder's default lookup to one that doesn't require a key, possibly IPInfo.io.

**Comment by Heath101** [comment]
@mc962 I am working on a PR for this, but it is slow going as I am only able to give it a few hours a week.

**Comment by mc962** [comment]
I think a post-install message would be good, as well as a deprecation notice when using the freegeoip lookup (maybe allow it to accept an option to silence the log message for it for those that don't care).

I think there can't be too many places to let people know they are using deprecated services.

Were you planning on changing the name of freegeoip / adding a new service in it's place? My understanding is that ipstack is taking over the freegeoip project, and so it would probably be more accurate to use their name  for the service (although it would break some compatibility).

**Comment by Heath101** [comment]
Yeah I think a new service would be the best option, as the api is now capable of returning better errors, and response codes.

**Comment by alexreisner** [comment]
Sorry for the slow reply @Heath101, and thanks for working on this. I think a post-install message would be good (explaining that `:freegeoip` is deprecated and will be discontinued on July 1st, 2018), and maybe showing the same warning whenever the lookup is loaded. After July 1st, we'll just remove `:freegeoip` entirely. Thanks!

**Comment by Heath101** [comment]
@alexreisner I should have PR for this in the next couple of days.

**Comment by Heath101** [comment]
@alexreisner I'm not sure where the best place is to put the warning for when the lookup is loaded.  Are you thinking just in the actual `lib/geocoder/lookups/freegeoip.rb` file itself (maybe right under the require statements), such that when the lookup spawn method dynamically requires in this file it will log out the warning just once?  Or are you thinking whenever a `Geocoder::Lookup::Freegeoip` is instantiated?  Seems like that would be really verbose, but it may be more appropriate for this warning to be super chatty, so that it gets noticed/fixed.

**Comment by Heath101** [comment]
I'm actually going to submit a PR for this without the warning ( it will include the post install message ).  We can continue this discussion on the PR comments I think.
