### ISSUE TITLE
undefined method 'geocoded_by' with rake assets:precompile

### ISSUE THREAD

**Issue by cmezak** [alexreisner/geocoder#128]
I know there have been issues in the past with this error message, but this one seems different. I get this undefined method message when I attempt to run rake assets:precompile for my rails 3.1 app. The full output is:

```
** Invoke assets:precompile (first_time)
** Execute assets:precompile
rake aborted!
undefined method `geocoded_by' for User(Table doesn't exist):Class

Tasks: TOP => environment
```

geocoder is in my gemfile. Restarting the app server isn't relevant in this case, so what else is there to do?

Thanks,
- Charlie

**Comment by modusss** [comment]
So, this gem is dead ? Here doesn't work anyway.
