### ISSUE TITLE
Geocoder return nill

### ISSUE THREAD

**Issue by Tioneb12** [alexreisner/geocoder#1280]
BEFORE POSTING AN ISSUE, PLEASE MAKE SURE THE PROBLEM IS NOT ADDRESSED IN THE README!

### Actual behavior

model : 
  
  def full_address
    [name, address, address2, zip_code, city].compact.join(', ')
  end

return nothing 

### Environment info
Rails 5.1.5
Ruby 2.4.3
webpack 4.4.1

**Comment by NorseGaud** [comment]
In my case, I just need the ipstack.com api functionality so I made an unoffical gem for it: https://github.com/NorseGaud/ipstack in case anyone is interested

**Comment by alexreisner** [comment]
Closing this in favor of #1279.

@NorseGaud - nice work on the gem.
