### ISSUE TITLE
location.state_code is always nil

### ISSUE THREAD

**Issue by gerbil802** [alexreisner/geocoder#1285]
### Expected behavior

state_code is nil even when country_code is "US"

### Actual behavior

state_code should return the state code, e.g. "NY"

### Environment info

* Geocoder version: 1.4.7
* Rails version: 4.0.1
* Database (if applicable):  n/a

**Comment by alexreisner** [comment]
What lookup are you using? Not all lookups return state data for all queries.

**Comment by gerbil802** [comment]
How do I know which lookup I'm using?

**Comment by alexreisner** [comment]
They all provide different data, and in different parts of the world, too. Please see the documentation for the various services to figure out which is best for what you need.
