### ISSUE TITLE
ERR unknown command '[]'

### ISSUE THREAD

**Issue by kshnurov** [alexreisner/geocoder#1286]
`Redis#[]` was [removed](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md) in redis-rb 4, `Geocoder::Lookup.get(:google).cache.expire(:all)` fails here: https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/cache.rb#L71

**Comment by alexreisner** [comment]
Thanks for spotting this!

**Comment by kshnurov** [comment]
@alexreisner you're welcome, thanks for quick respond!
