### ISSUE TITLE
Make maxmind_geoip2 result return time zone

### ISSUE THREAD

**Issue by yogodoshi** [alexreisner/geocoder#1291]
Hello, I'm not very familiarized with contributing to open source so I'm sorry if I'm breaking any protocols or not following best practices 😛

That being said, I wanted to get the time_zone from `Geocoder::Result::MaxmindGeoip2`. From [their docs](https://dev.maxmind.com/geoip/geoip2/web-services/):
<img width="908" alt="screen shot 2018-05-11 at 2 20 38 am" src="https://user-images.githubusercontent.com/412144/39889414-03011f40-54c2-11e8-91ad-1ca853c1ca96.png">

Are you planning on implementing it really soon or should/can I open a PR for it? :)

And thanks for making this awesome gem 👍

**Comment by alexreisner** [comment]
Thanks for this! I would accept a PR which adds a `time_zone` method. But note that even without a specific method you can access the data using: `result.data['time_zone']`.

**Comment by yogodoshi** [comment]
@alexreisner I tried but the data method is private, would you prefer a PR to make it public? 🤔

**Comment by alexreisner** [comment]
Oh, I see. That's a bug, and yes, a PR would be great. All that needs to be done is to delete that method from the result class. It's already defined [in the base class](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/results/base.rb#L6).

**Comment by SpiffyStores** [comment]
This seems to cause a bug when using maxminddb. I haven't had time to investigate fully, but the MaxMindDB::Result object does not support fetch, so the removal of the to_hash breaks things when called from geocoder.

**Comment by alexreisner** [comment]
@SpiffyStores you're right, thanks. In f8d5eeb247c42d71dc7d5f9191d47484c2e469be I've restored `#data` as a public method.
