### ISSUE TITLE
How to get POI types/labels?

### ISSUE THREAD

**Issue by kriskhaira** [alexreisner/geocoder#1293]
There are "labels" that appear in Google Maps for many locations that do not seem to be available in the output of `Geocoder.search()`. `search()` returns only supported types that correlate with the list here:
https://developers.google.com/places/supported_types

Examples:

## One Tree Hill, New Zealand

- [Google Maps](https://www.google.com/maps/place/One+Tree+Hill/@-36.8999982,174.7658237,14z/data=!3m1!4b1!4m5!3m4!1s0x6d0d4899e69055f1:0x8a8b250ea6fd9f5!8m2!3d-36.9!4d174.7833333) displays the words "Mountain Peak". Screenshot: https://cl.ly/2M1X272S1s0g
- `Geocoder.search("One Tree Hill, New Zealand")` returns an object with the types `"establishment", "natural_feature"`

## Merdeka Square, Malaysia

- [Google Maps](https://www.google.com/maps/place/Merdeka+Square/@3.1477582,101.6912348,17z/data=!3m1!4b1!4m5!3m4!1s0x31cc49cd98881539:0x340bf906bc763359!8m2!3d3.1477582!4d101.6934235) displays the words "Tourist Attraction"
- `Geocoder.search("Merdeka Square, Malaysia")` returns an object with the types `"establishment", "point_of_interest"`

## Tokyo Tower, Japan

- [Google Maps](https://www.google.com/maps/place/Tokyo+Tower/@35.6585805,139.7432442,17z/data=!3m2!4b1!5s0x60188bbd90bf26cf:0x4ceb5b05598646d0!4m5!3m4!1s0x60188bbd9009ec09:0x481a93f0d2a409dd!8m2!3d35.6585805!4d139.7454329) displays the word "Tower"
- `Geocoder.search("Tokyo Tower, Japan")` returns an object with the types `"establishment", "point_of_interest", "premise"`

How can I access that information?

**Comment by alexreisner** [comment]
What you see in Maps is an amalgamation of data from many sources, not just Google's geocoding API. Some of it may be available from other Google services but a lot of it is just not on any of their public APIs. You can inspect the entire set of data returned by calling the `#data` method on your `Result` objects.
