### ISSUE TITLE
Bug / Regression in 1.4.8: NoMethodError: undefined method `fetch' for #<MaxMindDB::Result>

### ISSUE THREAD

**Issue by feliperaul** [alexreisner/geocoder#1295]
I confirmed that this error appears in 1.4.8, not present in 1.4.7 and below.

results = Geocoder.search("201.81.167.245")

pry(main)> results[0].country
NoMethodError: undefined method `fetch' for #<MaxMindDB::Result:0x00007fb9c1b139d8>
from /Users/user/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/geocoder-1.4.8/lib/geocoder/results/geoip2.rb:35:in `country'

### Actual behavior

Up until 1.4.7, the bug doesn't exist and it returns the city or "" if not found. 

### Environment info

* Geocoder version:  1.4.8
* Rails version: 5.2.0
```
[5] pry(main)> Geocoder.config
=> {:timeout=>3,
 :lookup=>:google,
 :ip_lookup=>:geoip2,
 :language=>:"pt-BR",
 :http_headers=>{},
 :use_https=>false,
 :http_proxy=>nil,
 :https_proxy=>nil,
 :api_key=>nil,
 :cache=>nil,
 :cache_prefix=>"geocoder:",
 :basic_auth=>{},
 :logger=>:kernel,
 :kernel_logger_level=>2,
 :always_raise=>[],
 :units=>:mi,
 :distances=>:linear,
 :geoip2=>{:file=>"infrastructure/geolocation/GeoLite2-City.mmdb"}}
[6] pry(main)> 
```

**Comment by alexreisner** [comment]
This was discussed in #1291. It's been fixed and a new gem version will be released soon. (Thanks for reporting it, though!)
