### ISSUE TITLE
Checking lat and long with in the specified range of lat and long (Feature)

### ISSUE THREAD

**Issue by hanishjadala** [alexreisner/geocoder#1300]
Hi, using this gem can I check the lat and long are with in the range of specified lat and long. I mean lets say I have a country range which has lat and long and any lat and long which I give as input should check those input lat and long and give me result that it is with in the specified lat and long only.

**Comment by alexreisner** [comment]
If you need to do calculations using complex (non-rectangular) borders and points then you probably need to use the [rgeo gem](https://github.com/rgeo/rgeo). However, if you have lat/lon coordinates you can use Geocoder to get the corresponding physical address, which will include the country they're in. Does that answer your question?

**Comment by hanishjadala** [comment]
@alexreisner thanks for your response, but this issue what am facing is I have a city or county coordinates and if user enters any address which has its own coordinates and I should validate that user coordinates are with in the limit of the city or country specified. I need this kind of verification of the coordinates of address which user enter.

**Comment by alexreisner** [comment]
rgeo gem will help you determine whether a point (single lat/lon) is within an area corresponding to a city or country (set of lat/lon points which form a perimeter).

Geocoder, via reverse geocoding, will tell you what city or country a point is in without the need to have the perimeter data stored locally.
