### ISSUE TITLE
Prescribed Test stubs are not complete, don't populate data model on callbacks

### ISSUE THREAD

**Issue by jpowell** [alexreisner/geocoder#1302]
### Expected behavior

With the `test` lookup, I should get the same behavior as any normal `Lookup` result when running the `geocode` method on callback as prescribed, populating the data model. My example is in `after_validation` (`active_record` store) from README.

### Actual behavior

The `test` lookup, utilized as prescribed by the stubs in the README documentation, does not return a result that has populated `latitude` and `longitude` methods. The stub does not convert `coordinates` into `latitude` and `longitude` on result stubbing.

### Steps to reproduce

Add a stub just as you're told to in the [README documentation](https://github.com/alexreisner/geocoder#testing)

### Environment info

* Geocoder version: 1.4.9
* Rails version: 5.1.5
* Database (if applicable): Postgres
* Lookup (if applicable): test

### Proposed Solutions

1. Update documentation to reflect need for proper stubbing to be used (including `latitude` & `longitude`) for callbacks to populate attributes accordingly
2. Stubbing could ensure proper data is passed to the stub methods and raise exceptions when
3. Fill in the gaps on stubbing depending on input. For example, per the README, if `coordinates` is passed, populate `latitude` and `longitude` from it.

**Comment by alexreisner** [comment]
Thanks! This is also discussed in #1258 and I completely agree. Your solution number 3 is the one to go with. The only reason I've held off fixing is because it will break some people's tests, so it will be part of the next minor release (1.5.0), hopefully coming soon.

Added the fix in a `v1.5` branch: b284f71965982ed1c404638012492ca2aee2c379

**Comment by jpowell** [comment]
Sweet - thanks!
