### ISSUE TITLE
maxmind_geoip2 .address returning ISO-3166-2 number

### ISSUE THREAD

**Issue by basex** [alexreisner/geocoder#1312]
When calling the function address, maxmind_geoip2 is filling the city name with the ISO-3166-2 Administrative Division number.

http://www.geonames.org/PT/administrative-division-portugal.html

### Expected behavior

`Porto, Porto 4000-000, Portugal` or `Porto 4000-000, Portugal`

### Actual behavior

`Porto, 13 4000-000, Portugal`

### Steps to reproduce

`Geocoder.search('94.63.1.1').first.address`

```ruby
Geocoder.search('94.63.1.1').first.data   
=> {"city"=>{"geoname_id"=>2735943, "names"=>{"de"=>"Porto", "en"=>"Porto", "es"=>"Oporto", "fr"=>"Porto", "ja"=>"ポルト", "pt-BR"=>"Porto", "ru"=>"Порту"}}, "continent"=>{"code"=>"EU", "geoname_id"=>6255148, "names"=>{"zh-CN"=>"欧洲", "de"=>"Europa", "en"=>"Europe", "es"=>"Europa", "fr"=>"Europe", "ja"=>"ヨーロッパ", "pt-BR"=>"Europa", "ru"=>"Европа"}}, "country"=>{"is_in_european_union"=>true, "iso_code"=>"PT", "geoname_id"=>2264397, "names"=>{"ru"=>"Португалия", "zh-CN"=>"葡萄牙", "de"=>"Portugal", "en"=>"Portugal", "es"=>"Portugal", "fr"=>"Portugal", "ja"=>"ポルトガル共和国", "pt-BR"=>"Portugal"}}, "location"=>{"accuracy_radius"=>10, "latitude"=>41.1496, "longitude"=>-8.611, "time_zone"=>"Europe/Lisbon"}, "maxmind"=>{"queries_remaining"=>261164}, "postal"=>{"code"=>"4000-000"}, "registered_country"=>{"is_in_european_union"=>true, "iso_code"=>"PT", "geoname_id"=>2264397, "names"=>{"fr"=>"Portugal", "ja"=>"ポルトガル共和国", "pt-BR"=>"Portugal", "ru"=>"Португалия", "zh-CN"=>"葡萄牙", "de"=>"Portugal", "en"=>"Portugal", "es"=>"Portugal"}}, "subdivisions"=>[{"iso_code"=>"13", "geoname_id"=>2735941, "names"=>{"en"=>"Porto", "es"=>"Oporto", "pt-BR"=>"Porto", "de"=>"Porto"}}], "traits"=>{"autonomous_system_number"=>12353, "autonomous_system_organization"=>"Vodafone Portugal - Communicacoes Pessoais S.A.", "domain"=>"vodafone.pt", "isp"=>"Vodafone Portugal", "organization"=>"Vodafone Portugal", "ip_address"=>"94.63.1.1"}}
```

### Environment info

* Geocoder version: 1.4.9
* Rails version: N/A
* Lookup (if applicable): maxmind_geoip2

**Comment by alexreisner** [comment]
Thanks for bringing this up. The `address` method is provided for interface consistency only--when used with services that don't return a formatted address, Geocoder can't provide one. International address formatting is very complicated and beyond the scope of the gem, unfortunately.

**Comment by basex** [comment]
I understand, thanks for the quick reply.

My only suggestion is removing the ISO number from the address.
