### ISSUE TITLE
ipstack doesn't support HTTPS on their free tier (needs a protocol config option)

### ISSUE THREAD

**Issue by abevoelker** [alexreisner/geocoder#1313]
The :ipstack lookup provider needs a config option to set the protocol (:protocol? :use_ssl? :supported_protocols?), because unfortunately ipstack treats HTTPS as a paid upgrade feature. I could've made a PR in the time it took to write this up but I won't be giving :clown_face: :clown_face: :clown_face: that treat security as a feature my money or free labor.

### Expected behavior

```ruby
irb(main):001:0> r = Geocoder.search("172.217.9.78", ip_address: true).first
=> # useful data here
```

### Actual behavior

```ruby
irb(main):001:0> r = Geocoder.search("172.217.9.78", ip_address: true).first
Ipstack Geocoding API error: Access Restricted - Your current Subscription Plan does not support HTTPS Encryption.
=> nil
```

### Steps to reproduce

1. Sign up for a free ipstack API key
2. Use `:ipstack` for IP lookups:

```ruby
Geocoder.configure(
  ip_lookup: :ipstack,
  ipstack: { api_key: "foo" },
)
```

### Environment info

* Geocoder version: 1.4.9
* Rails version: 5.1.4
* Database (if applicable): N/A
* Lookup (if applicable): `:ipstack`

**Comment by alexreisner** [comment]
Thanks for pointing this out!

**Comment by djabif** [comment]
is https something you will offer in the free tier?

**Comment by alex198211** [comment]
The free tier does not allow HTTPS access. See https://ipstack.com/product. How do we tell Geocoder to use plain http instead of https?

**Comment by alex198211** [comment]
Ipstack Geocoding API error: Access Restricted - Your current Subscription Plan does not support HTTPS Encryption.

**Comment by alex198211** [comment]
OK after spending a couple hours digging through the code I figured that if you add "use_https":false it will work with the free plan that does not allow https. Although I'm considering upgrading to a paid plan if they update their DB frequently (and respond to customer support messages fast enough). Sadly during this process my dog was getting pissed at me for ignoring him for so long and bit a coin-sized piece of meat off my back so now I'm writing this while getting patched up. Typing this just in case it might save someone's pecker someday if the docs / faqs don't get updated in the meanwhile.

**Comment by JulesPrimo** [comment]
Got the same problem, just to be extra clear for the next one, you need to update the Geocoder configuration with `use_https: false`.

```
Geocoder.configure(
    lookup: :google,
    ip_lookup: :ipstack,
    language: :fr,
    use_https: true,
    api_key: ENV["GOOGLE_MAP_API_KEY"],
    units: :km,
    ipstack: {
        api_key: ENV["IPSTACK_API_KEY"],
        use_https:false,
    }
)
```

**Comment by alexreisner** [comment]
No change necessary here. Just set `Geocoder.configure(use_https: false)`.
