### ISSUE TITLE
Facing issue of NoMethodError (undefined method `ip' for nil:NilClass) on  geocoder version 1.4.8

### ISSUE THREAD

**Issue by shantilal-narola** [alexreisner/geocoder#1314]
I am facing issue on server of not getting ip from request.location.ip and request.location.country. But before July month it is working.
### Expected behavior
I need http request location.ip and location.country so i can identified user region and restrict them to using site. 

Code: 
     logger.debug "======#{request.location.ip}"
    logger.debug "======#{request.location.country}"

Error: NoMethodError (undefined method `ip' for nil:NilClass)

Please help me soon to resolved this issue 
* Geocoder version:  i have tried 1.4.4, 1.4.5, 1.4.8, 1.4.9
* Rails version: 5.1
* Database (if applicable): postgres

**Comment by alexreisner** [comment]
It sounds like you're using freegeoip, which has been discontinued. Please see [this announcement](https://github.com/alexreisner/geocoder/wiki/Freegeoip-Discontinuation) for more info.
