### ISSUE TITLE
Facing issue of Google API error: request denied. after added ip_lookup as ipstack

### ISSUE THREAD

**Issue by shantilal-narola** [alexreisner/geocoder#1316]
I am facing error of Google API error: request denied. and not getting request.location.latitude and request.location.longitude

### Expected behavior
I need latitude and longitude when user signup in site with devise authentication.
Before configuring api key and ip_lookup of ipstack, all is working fine. But as i knew freegeoip was discontinued so i have made account in ipstack and added api key of ipstack in geocoder.rb file

config/initializers/geocder.rb file 

Geocoder.configure(
ip_lookup: :ipstack,
api_key: "API_KEY"
)

Please help me as soon as possible. Thanks in advance :)

* Geocoder version: 1.4.9
* Rails version: 5.1
* Database (if applicable): Postgres
* Lookup (if applicable): Ipstack

**Comment by alexreisner** [comment]
This is probably happening because you've set your IPStack api key as the *global* api key, so it's being used for Google as well as IPStack. To set it for IPStack only:

    Geocoder.configure(
      ip_lookup: :ipstack,
      ipstack: { api_key: "API_KEY" }
    )
