### ISSUE TITLE
Default google provider is no longer accessible without API key

### ISSUE THREAD

**Issue by morgoth** [alexreisner/geocoder#1320]
Default configuration no longer works out of the box as "New pricing changes went into effect on July 16, 2018"

https://developers.google.com/maps/documentation/geocoding/usage-and-billing

**Comment by alexreisner** [comment]
Thanks for pointing this out! It has already been fixed by c3de75f57c99d96c81e37f9c0f0670bed39d61ac, to be released in version 1.5.0.
