### ISSUE TITLE
ipstack as ip_lookup?

### ISSUE THREAD

**Issue by gerbil802** [alexreisner/geocoder#1321]
### Expected behavior

ipstack should be configured via `ip_lookup: :ipstack`

### Actual behavior

script fails and prints:
```
Geocoder::ConfigurationError: Please specify a valid lookup for Geocoder (:ipstack is not one of: :location_iq, :dstk, :esri, :google, :google_premier, :google_places_details, :google_places_search, :bing, :geocoder_ca, :geocoder_us, :yandex, :nominatim, :mapbox, :mapquest, :mapzen, :opencagedata, :ovi, :pelias, :pickpoint, :here, :baidu, :geocodio, :smarty_streets, :okf, :postcode_anywhere_uk, :geoportail_lu, :ban_data_gouv_fr, :test, :latlon, :amap, :baidu_ip, :freegeoip, :geoip2, :maxmind, :maxmind_local, :telize, :pointpin, :maxmind_geoip2, :ipinfo_io, :ipapi_com, :ipdata_co, :db_ip_com).
```

### Steps to reproduce

Define `ip_lookup: :ipstack` in `config/initializers/gecoder.rb`

### Environment info

* Geocoder version: 1.4.9
* Rails version: 4.0.1
* Database (if applicable): n/a
* Lookup (if applicable): n/a

**Comment by alexreisner** [comment]
Are you sure you're using version 1.4.9? That looks like the list of lookups from 1.4.8.

**Comment by gerbil802** [comment]
Wow it was 1.4.7. Turns out 1.4.9 was installed but not in use.
Thank you!

**Comment by gerbil802** [comment]
by the way, what's the difference between `ip_lookup` and `lookup`?  (i'm specifically interested in `request.location`)
