### ISSUE TITLE
Feature: shortest path method

### ISSUE THREAD

**Issue by sportsbook123** [alexreisner/geocoder#1325]
Amazing work! Filing this under best kept secrets of the Ruby world.

Any plans to add support to calculate a "shortest path" between two cities or points? eg:

```
# euclidean distance
Geocoder.search("my_lat, my_long").first.distance_to( Geocoder.search("Eiffel Tower").first, :straight_line )

# https://developers.google.com/maps/documentation/distance-matrix/start
Geocoder.search("my_lat, my_long").first.distance_to( Geocoder.search("Eiffel Tower").first, :google )
# + storing results to the database for later use in order to minimize API cost
```

TIA

**Comment by alexreisner** [comment]
You can do this:

    Geocoder::Calculations.distance_between(point1, point2)

where each point is an array of coordinates, an address to search for, or a geocoded object. It uses the Haversine formula, which is basically Euclidean distance along the surface of a sphere. Is that what you're asking about?

**Comment by sportsbook123** [comment]
Hi Alex,

Thank you for your reply. Your distance_between feature is awesome! I was also looking for a "distance by road" wrapper around big daddy's Maps API, something we can use to accurately plan routes, eg straight line (or similar) distance between Paris and London = 350km, while by road is significantly higher, 460km.

Cheers!

**Comment by alexreisner** [comment]
Ah, yes. There's some discussion of that at #815. I'm not completely opposed to supporting directions, but it would introduce an entirely new kind of data which would need to be modeled. And big daddy's 
not the only option so we'd need to base it on the designs of all available routing APIs (eg, [MapQuest](https://developer.mapquest.com/documentation/directions-api/route/get/))... It's kind of a big project.

**Comment by sportsbook123** [comment]
Thank you! will look into some of the other gems as well!
