### ISSUE TITLE
Maxmind authentication

### ISSUE THREAD

**Issue by sportsbook123** [alexreisner/geocoder#1326]
```
        raise(
          Geocoder::ConfigurationError,
          "When using MaxMind GeoIP2 you MUST specify a service name and basic_auth: " +
          "Geocoder.configure(:maxmind_geoip2 => {:service => ...}, " +
          ":basic_auth => {:user ..., :password => ...}), " +
          "where service is one of: #{services.inspect}"
        )
```

Shouldn't this instead be...

`Geocoder.configure(:maxmind_geoip2 => {:service => ..., :basic_auth => {:user ..., :password => ...} } )`

... just in case someone is using multiple providers?

**Comment by alexreisner** [comment]
Yes, you're right about that error message.

I can't get it to work without username and password (401, as expected). What config are you using, exactly?

**Comment by sportsbook123** [comment]
`Geocoder.configure(:ip_lookup => :maxmind_geoip2, :maxmind_geoip2 => {:service => :city, :basic_auth => { :user => "foo", :password => "bar" } } )`

**Comment by alexreisner** [comment]
(Weird. I can't reproduce that. I always get the error.)

**Comment by alexreisner** [comment]
Error message improved in c077f83de477f1e2d3b7faf0a45a550e03d16029
