### ISSUE TITLE
Search near multiple locations

### ISSUE THREAD

**Issue by christianmeichtry** [alexreisner/geocoder#1329]
I don't believe there a way to search `near` multiple locations ? How could this be implemented ?

I imagine a syntax similar to this :

`Venue.near(['Omaha, NE, US', 'Dallas, TX, US'])`

**Comment by alexreisner** [comment]
Would this do what you're looking for?:

    Venue.near('Omaha, NE, US').or(Venue.near('Dallas, TX, US'))
