### ISSUE TITLE
Support plus codes

### ISSUE THREAD

**Issue by drinckes** [alexreisner/geocoder#1330]
Hi - I wonder if you'd be interested in supporting plus codes in forward requests, and returning them in reverse requests?

Plus codes are an open source project by Google (I'm the founder/lead), to generate an address for any location. This is because most people in the world don't have a street address, so they can't express where they are to for deliveries, emergency services etc.

Plus codes work by encoding latitude and longitude into a string like 6CRWM9WX+PF (this can be done offline), and then merging it with reverse geocode data to get an address: "M9WX+PF Kumasi, Ghana".

To geocode this address, you need to geocode "Kumasi, Ghana" and you can then recover the original code and location.

We have a [ruby library](https://github.com/google/open-location-code/tree/master/ruby) done, and we can find people to do the work, but wanted to make contact to see what you thought about including support for this open source addressing solution?

**Comment by alexreisner** [comment]
In principle, yes, I'm interested in supporting plus codes. But if I understand correctly, Google's API already returns plus codes in search results, and can accept plus codes in queries. What exactly do you have in mind?

**Comment by drinckes** [comment]
That's true. But it would be good to also support people who want to use Nominatim or the other APIs - we don't Google to be the only provider.

What I envisaged as a minimum is to support the codes in searches - if your search is a plus code, decode it and return it's lat/lng (basically, treat it as you would treat any other reverse geocode of an address):

```
results = Geocoder.search("8FW4V75V+8Q")
results.first.coordinates
=> [48.858312,2.294438]  # latitude and longitude of the code center
results = Geocoder.search("V75V+8Q Paris")
results.first.coordinates
=> [48.858312,2.294438]  # latitude and longitude of the code center
```
The first is easy - if the query term matches a regex you can just decode it using the library - you don't need to make any API calls. For the second one, you need to:
1. split the query into the code and "Paris"
1. geocode "Paris"
1. and use that lat/lng to recover the original code and decode it (both using the library).

### EVERYTHING FROM HERE IS OPTIONAL

It would also be nice to be able to return the plus code address for a location. This is essentially a conversion operation and I'm not sure how you would include it in the results. That's because the results are normally a list of objects that are **near** the lat/lng, but in this case we want to return the code **of** the lat/lng as well.

For example, if we search for the lat/lng of the above code:
```
results = Geocoder.search([48.858312,2.294438])
results.first.address
=> "5 Avenue Anatole France, 75007 Paris, France"  # the nearest address
```
`results.first.plus_code.global_code` and `results.first.plus_code.compound_code` should probably be reserved for the plus code of the address, not the lat/lng. Anyway, `results` might be empty.

But then how would we return the plus code for the lat/lng?

Google and Mapbox both use a field outside of the results list for this kind of thing, but I don't know if that's an option for you without a ton of refactoring?

**Comment by alexreisner** [comment]
After thinking about this a lot, while I think it's an interesting idea, it's (1) a lot of code for a non-core feature and (2) would operate in a way that's inconsistent with the rest of the gem. Currently, doing a search means making an API call, with no supplemental info coming from any other source. Your proposal adds a potentially surprising/confusing behavior for a use case that just doesn't seem all that common. Since it's possible to configure different APIs for different types of queries, someone can configure Google's API to handle plus codes, or if they need to do it locally they can use your gem. What you're suggesting just seems outside the project's scope. Sorry!
