### ISSUE TITLE
Restrict search to countries

### ISSUE THREAD

**Issue by arjunmenon** [alexreisner/geocoder#1332]
Hey
Is there a way to restrict city search to particular countries?

If there is mis-spelling, the gem can return possible city names. This would be helpful since the lookup has to search for the name in a particular country db only.

Also, there are many cities with similar name but in different countries like Paris or Delhi. This would help to the use case.
I can specify the country like "Paris, US" but if I misspell "Pariiss, US" it would return error. Better would be it returns suggestions for similar city names in the specified country, US.

**Comment by alexreisner** [comment]
Some geocoding APIs support this, and some don't. Google allows you to "bias" results to certain regions (see link to their documentation in the readme).
