### ISSUE TITLE
warning: ambiguous first argument; put parentheses or a space even after `/' operator

### ISSUE THREAD

**Issue by gurgeous** [alexreisner/geocoder#1333]
There's an error with ruby -w:

```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]

$ ruby -w lib/geocoder/lookups/base.rb
lib/geocoder/lookups/base.rb:167: warning: ambiguous first argument; put parentheses or a space even after `/' operator
```

This error will pop up every time you run with warnings, such as the default `rake test` in Rails. Easy fix (add parens). I was going to submit a PR but I got a little bogged down installing the mysql dependency.

If you have the time and the desire, consider adopting Rubocop. That will catch and autocorrect this and many similar problems. Thanks for the great gem!

**Comment by alexreisner** [comment]
Thanks for pointing that out!
