### ISSUE TITLE
Every Request (Almost) Always Raising Query Limit Error

### ISSUE THREAD

**Issue by mjohnson324** [alexreisner/geocoder#1346]
Recently I've been seeing "Google API error: over query limit." a lot. With only a few exceptions I raise this error in my rails app regardless of the number of queries that have already been fired and I don't know how to fix this.

### Context
The app simulates ZocDoc and can be used to search for doctors. Fake doctors are added via seeding for demoing the app. Part of this involves geocoding their addresses via the following lines in the Doctor model:

```ruby  
geocoded_by :location, latitude: :lat, longitude: :lng
after_validation :geocode
attr_accessor :location
```

### Expected behavior
I run this line and expect geocoding to be successful:

```ruby
doc_hibbert = Doctor.create!(location: '51 W 51st St, New York, NY', address: '51 W 51st St, New York, NY' first_name: 'Julius', last_name: 'Hibbert', education: 'Johns Hopkins University School of Medicine', degree: 'MD', address: '51 W 51st St, New York, NY')
```

### Actual behavior
With few exceptions I instead raise 'Google API error: over query limit.'

- I don't think it's a model error because I was able to successfully geocode 3 doctors (out of 57) on my last try.
- There was no pattern to the geocoding. The only successful attempts were for doctors 18, 44 and 46.
- This is not related to the rate of requests either. This error was raised immediately for the very first geocoding attempt in the seed file and hits me with individual queries.
- Nor is this related to the number of requests in a day. This is a website I designed during a bootcamp and it gets very little traffic. The last time I attempted geocoding was almost a week ago and the behavior was identical (high chance of failure, small chance of success, random). I raised this error starting with my first geocoding attempt in several days.

### Steps to reproduce
Geocode an object. I also get the same error if I attempt something like this in the rails console:

```ruby
Doctor.first.update(location: Doctor.first.address)
```
That's just an example of how I tried manually geocoding one doctor afterwards, and how I was updating doctors when I encountered the same error because of rate limits. The update failed due to the error but the commit was successful.

### Environment info

- Geocoder version: 1.4.9
- Rails version: 5.1.3
- Ruby: 2.5.1
- Database: PostgreSQL 10.5
- Lookup: ipinfo_io (the default)
- OS: Ubuntu 18.04

**Comment by alexreisner** [comment]
Closing, because this sounds like it has to do with your environment, not the gem, but if you post your `Geocoder.configure` block I might be able to suggest something. Are you using an API key and a paid Google API account? (This is required as of a few months ago.)

**Comment by mjohnson324** [comment]
Thanks for the response. I'll need to evaluate my options.

**Comment by viktorsmari** [comment]
Came here because of the same problem. Maybe information about Google now requiring billing etc. should be added to the readme for a while?
