### ISSUE TITLE
How to check if query will hit the cache?

### ISSUE THREAD

**Issue by slhck** [alexreisner/geocoder#1347]
This is more of a support question.

I would like to write a method that reverse-geocodes a larger batch of latitude/longitude points. I have caching enabled. Intuitively I would have done a loop like so:

```
scope :not_yet_reverse_geocoded, -> {
  where(city: nil, country: nil)
}

...

self.not_yet_reverse_geocoded.find_each do |obj|
    sleep 1
    obj.reverse_geocode
    obj.save
end
```

However, this means that for objects with the same lat/lon, I will definitely hit the cache, so I wouldn't have to wait one second before proceeding to the next.

Is there a way to query whether a `reverse_geocode` lookup will hit the cache or not? Like so:

```
query = Geocoder::Query.new([obj.latitude, obj.longitude])
cache_url = [Geocoder.config[:cache_prefix], query.url].join
```

The above almost does what I want, namely checking if the `cache_url` is in the respective cache, except that it also contains my authentication token, which is not cached:

```
irb(main):037:0> Redis.new(url: ENV['REDIS_URL']).keys('geocoder*').last
=> "geocoder:https://locationiq.org/v1/reverse.php?accept-language=en&addressdetails=1&format=json&lat=XXXXX&lon=XXXXX"
irb(main):038:0> cache_url
=> "geocoder:https://locationiq.org/v1/reverse.php?accept-language=en&addressdetails=1&format=json&key=XXXXXXXXXXXX&lat=XXXXX&lon=XXXXX"
```

Is there any other way to check that?

**Comment by slhck** [comment]
I found a workaround that has the same effect but is conceptually different – basically works like this inside the loop:

```
ret = obj.reverse_geocode
if not ret.cache_hit
    sleep 1
end
```

**Comment by alexreisner** [comment]
You found it! The `#cache_hit` method is definitely the best way to do this, as long as you don't need to check whether the result is cached *before* you make the request which it seems like you don't.
