### ISSUE TITLE
Geocoder doesnt return result for search 'San Francisco'

### ISSUE THREAD

**Issue by thaiden** [alexreisner/geocoder#1350]
Geocoder seems not returning any results for string 'San Fancisco'

### Expected behavior
```ruby
Geocoder.search("San Francisco")
=> [#<Geocoder::Result::Google:0x00007f99c0a55918
```

### Actual behavior
```ruby
Geocoder.search("San Francisco")
[]
```

### Steps to reproduce
```ruby
Geocoder.search("San Francisco")
```

### Environment info

* Geocoder version: '1.5.0'
* Rails version: Rails 5.2.1

**Comment by thaiden** [comment]
One thing worth mentioning is that running `geocode 'San Francisco'` in bash works
```bash
$ geocode 'San Francisco'
Latitude:         37.7792808
Longitude:        -122.4192363
Full address:     San Francisco, San Francisco City and County, California, USA
City:             San Francisco
State/province:   California
Postal code:
Country:          USA
Map:              https://www.openstreetmap.org/?lat=37.7792808&lon=-122.4192363&zoom=15&layers=M
```

**Comment by thaiden** [comment]
looks like its google issue https://developers.google.com/maps/documentation/geocoding/intro. Apologies

**Comment by milushov** [comment]
@thaiden did you figured out how to use google lookup?

**Comment by thaiden** [comment]
@milushov I did, my issue was mostly due to an actual bug in geodata in google. We had open a ticket against them to resolve it.
