### ISSUE TITLE
mapzen lookup

### ISSUE THREAD

**Issue by MeterSoft** [alexreisner/geocoder#1351]
coordinates = Geocoder.coordinates("London", lookup: :mapzen)
Geocoder::ResponseParseError: Geocoder::ResponseParseError

geocoder 1.5.0
Rails 5.0

**Comment by posiczko** [comment]
Sadly, Mapzen is no more. It is pining for the fjords. It is dead. https://mapzen.com/blog/shutdown/

**Comment by alexreisner** [comment]
Thanks @posiczko!

**Comment by alexreisner** [comment]
Removed Mapzen lookup: bb4af670adafe4dac9abd05f51eeff542a85528b
