### ISSUE TITLE
Pelias Lookup only returns a single result

### ISSUE THREAD

**Issue by jsantos** [alexreisner/geocoder#1353]
I was working with Geocoder using the Pelias Lookup (to connect to my own service), and noticed that all the time, a single result was being returned (I wanted to do something more with the full set of results).

After digging a bit, I found an hardcoded parameter in the request, built on `lib/geocoder/lookups/pelias.rb`:

```ruby
def query_url_params(query)
  params = {
    api_key: configuration.api_key,
    size: 1
  }.merge(super)
   ...
end
```

As we can see, there's a `size: 1` parameter being introduced on the request, making pelias only return a single result. 

I looked into the other Lookups and haven't found this (at least on Google, Mapbox and a couple others.

Despite being a single result, it's still returned as as array. Any particular reason why this limit is here? I didn't found anything on the original pull requests which introduced Pelias/Mapzen support (#1000 and #1051).

If removing this constraint is not an issue, I can submit a PR for this.

Thanks in advance!

**Comment by jsantos** [comment]
My use case here is similar to what the Mapbox lookup does by default (sort results based on a specific criteria): https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/mapbox.rb#L52

**Comment by alexreisner** [comment]
Thanks for this. That looks like a bug to me. Definitely open to a PR.
