### ISSUE TITLE
APIs need update, some coordinates extremely erroneous.

### ISSUE THREAD

**Issue by Broseph1878** [alexreisner/geocoder#1359]
[not sure where to post this, but this seems like a valid issue that needs to be addressed]

### Expected behavior
Should find suburb "Mahogany Creek" (Postcode 6072) in my state (Western Australia).
Should return proper coordinates (~[-32, 116]).

### Actual behavior
Returns coordinates for locations in other states, no matter how many reductions I make in the query.

### Steps to reproduce
Search:
- MAHOGANY CREEK, WA, Australia, 6072
- Mahogany Creek, Australia, WA, 6072
- 6072, Australia, WA

Return (respectively):
-12.3972191 | 130.911714
-27.4896774 | 153.0688414
-25.2303005 | 121.0187246

### Environment info

* Geocoder version: 1.5.0
* Rails version: 5.2.1
* Database (if applicable): pg 1.1.3       (PostgreSQL)
* Lookup (if applicable): N/A

**Comment by alexreisner** [comment]
This has to do with the lookup you're using. Some lookups are better at parsing search queries, some give better results in particular regions, and some have parameters you can set to constrain the search area. There's nothing the gem itself can do here. It's an API issue.
