### ISSUE TITLE
How to override the default rounding of geocoder, if i want to store lat/lng of 15digits

### ISSUE THREAD

**Issue by mike1011** [alexreisner/geocoder#1360]
I have been looking to store lat/lng the way i get them from google api , for example: , `latitude"=>"19.253077836712087", "longitude"=>"73.13388757622681"`, but its been rounded off by geocoder everytime by the callback  - `after_validation :geocode`, because if I comment it out, the lat/lng are stored exactly and in full length.
Is there a way to override the rounding size, which I think default with precision of 6.?

**Comment by alexreisner** [comment]
What type of database column are you using for lat/lon? Is it capable of storing the full, unrounded numbers?

**Comment by mike1011** [comment]
Yes, i am sharing a snippet of `address.rb`, which I use to store the geo specific data.
```

      ##special care for geospatial coordinates
      t.float :latitude, {:precision=>16, :scale=>10}
      t.float :longitude, {:precision=>16, :scale=>10}
```

**Comment by alexreisner** [comment]
Geocoder doesn't touch the values received from APIs, so I suspect the rounding is going on at the database level, somehow. It looks like your columns support up to 10 digits after the decimal point. However, my main question is why you want to do this. As mentioned [in the README](https://github.com/alexreisner/geocoder#numeric-data-types-and-precision), with 5 decimal places you get precision to around 1 meter. Even that seems like more than enough where street address is concerned.

**Comment by mike1011** [comment]
Thanks @alexreisner , I have already went through the Documentation describing briefly about accuracy, but I just want to store the exact lat/lng without rounding them out.Even if I update my migration to store a precision of 15 after the decimals, they get rounded too.

Just want to understand can I prevent this from happening?

**Comment by alexreisner** [comment]
It's hard to guess why that's happening, but all Geocoder does is assign the coordinates as received from the API, so I don't think Geocoder is the issue.
