### ISSUE TITLE
Rate limit exceed

### ISSUE THREAD

**Issue by thetnswe** [alexreisner/geocoder#1363]
Geocoding API error: 429 Too Many Requests
Geocoding API's response was not valid JSON: Rate limit exceeded. Upgrade to increase your usage limits at https://ipinfo.io/pricing, or contact us via https://ipinfo.io/contact

Can someone let me know what's the limit and if I exceed, how can I upgrade?

**Comment by alexreisner** [comment]
Don't the links you posted answer your question?

**Comment by alexreisner** [comment]
Set the `:api_key` using `Geocoder.configure`, as explained [in the readme](https://github.com/alexreisner/geocoder#geocoding-service-lookup-configuration).

**Comment by thetnswe** [comment]
Oh! Thanks alot.. I missed that part in readme. :)
