### ISSUE TITLE
Smarter caching 

### ISSUE THREAD

**Issue by hahmed** [alexreisner/geocoder#1364]
Let’s say the points returned from geocoder for a location are `[51.526648, -0.080776]` and stored in the cache, another request is made and the location returned is `[51.529158, -0.069631]`. 

How do I be smart about caching so I don’t hit the api lookup service (google for example) for second query?

**Comment by alexreisner** [comment]
Not sure what you're asking. The cache basically maps API URLs (queries) to responses. It doesn't care what the response is. If you issue the same query twice, it should hit the cache the second time.

**Comment by hahmed** [comment]
Sorry, let me clear up what I'm asking.

Let's say we searched for a place *query1*:
 `48.8582, 2.2945` which gave us back: "Eiffel Tower, 5 Avenue Anatole France, 75007 Paris, France"

Then we did another search *query2*

`48.863021, 2.287626` which gave us back: "Eiffel Tower, 5 Avenue Anatole France, 75007 Paris, France"

**Comment by alexreisner** [comment]
Ah, I see. I think the only way around that is to use something like PostGIS to store the shapes of the countries and run all queries on your local database. If you're using Geocoder and an API, I don't think there's any solution--it requires too much pre-query knowledge.

**Comment by hahmed** [comment]
Hey @alexreisner finally published a post about how I got this to work for me, just thought I should share in case it helps anyone. 

https://i.amharoon.com/2018/11/28/geocoder.html

**Comment by alexreisner** [comment]
Nice--and thanks for the kind words about the gem!
