### ISSUE TITLE
ipinfo.io URL param token -> access_key

### ISSUE THREAD

**Issue by pmn4** [alexreisner/geocoder#1365]
### Expected behavior
IPInfo.io lookups with a valid API Key should return valid JSON

### Actual behavior
Incorrect URL param is used, causing an error to be returned.

### Steps to reproduce
Using `ip_lookup: :ipinfo_io` with a valid API key, attempt to make a request. The URL param `token` will be used, where ipinfo.io expects `access_key`.
https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/ipinfo_io.rb#L39

_([ipinfo.io documentation](https://ipstack.com/documentation))_

### Environment info

* Geocoder version: 1.5.0
* Rails version: 4.2.6
* Database (if applicable): n/a
* Lookup (if applicable): ipinfo.io

**Comment by pmn4** [comment]
I am guessing that ipinfo.io has transitioned from `token` to `access_key` and still supports both. Since this library will still need to support both, the solution may, unfortunately, be to add a new Lookup class.

**Comment by alexreisner** [comment]
Hmm...that documentation is for IPStack, not IPInfo.io.

**Comment by coderholic** [comment]
Our (IPinfo) auth param is still `token`, or we support headers. See https://ipinfo.io/developers#authentication
