### ISSUE TITLE
Here Places API - No member street_address

### ISSUE THREAD

**Issue by kyle-s-autobrain** [alexreisner/geocoder#1369]
BEFORE POSTING AN ISSUE, PLEASE MAKE SURE THE PROBLEM IS NOT ADDRESSED IN THE README!

### Expected behavior
result.street_address availability when using here

### Actual behavior
result.street_address is available when using Google, but not available for Here

### Steps to reproduce
Get a result from here and try to use .street_address

### Environment info

* Geocoder version: 1.5.0
* Rails version: 5.1.4

**Comment by alexreisner** [comment]
See #1370.
