### ISSUE TITLE
Geocoder seems to crash specs when run via guard, but not when specs are run directly?

### ISSUE THREAD

**Issue by burlesona** [alexreisner/geocoder#137]
I have a strange situation I can't quite understand.

When I run my specs with `rspec spec` they all pass. However, as of today, when I run guard and it calls the specs, it crashes with the following error:

```
.../.rvm/gems/ruby-1.9.2-p180@fourth_env/gems/activerecord-3.1.1/lib/active_record/base.rb:1088:in `method_missing': undefined method `geocoded_by' for #<Class:0x00000104fae240> (NoMethodError)
```

Now, the offending line is in my app's `photo.rb` model:

```
geocoded_by :location, :latitude  => :lat, :longitude => :lng
```

`geocoder` is listed in my gemfile and part of my gemset etc. I re-ran bundler to double check this.

Whether I run `rspec spec` or `bundle exec rspec spec` it all passes, and whether I run `guard` or `bundle exec guard` it fails.

My app has never had issues with geocoder in the past.

I'm really baffled as to why there would be an error when running specs under guard that isn't present when running specs directly. Has anyone ever encountered an error like this before?

Using: `guard 0.8.8`, `rspec-rails 2.6.1`, `geocoder 1.0.4`

**Comment by mustela** [comment]
It seems this issue is present again 

```
     Failure/Error: geocoded_by :to_s

     NoMethodError:
       undefined method `geocoded_by' for #<Class:0x007fa3042f1828>
     # /Users/mustela/.rvm/gems/ruby-2.2.4/gems/activerecord-4.2.5.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'

```

Using: `guard 2.13.0 rspec-rails 3.4.2, geocoder 1.3.0`

Specs run all just fine using `rspec` but not when using `guard`
