### ISSUE TITLE
IP address doesn't work 

### ISSUE THREAD

**Issue by ir-usmanasif** [alexreisner/geocoder#1373]
Ip address search is giving exception.
### Expected behavior
results = Geocoder.search("172.56.21.89")
results.first.coordinates
=> [30.267153, -97.7430608]
results.first.country
=> "United States"

### Actual behavior
Geocoder.search("172.56.21.89")
Geocoder::ResponseParseError: Geocoder::ResponseParseError
	from /app/vendor/bundle/ruby/2.2.0/gems/geocoder-1.5.0/lib/geocoder/lookups/base.rb:185:in `raise_error'
	from /app/vendor/bundle/ruby/2.2.0/gems/geocoder-1.5.0/lib/geocoder/lookups/base.rb:212:in `rescue in parse_json'
	from /app/vendor/bundle/ruby/2.2.0/gems/geocoder-1.5.0/lib/geocoder/lookups/base.rb:206:in `parse_json'
	from /app/vendor/bundle/ruby/2.2.0/gems/geocoder-1.5.0/lib/geocoder/lookups/base.rb:219:in `parse_raw_data'
	from /app/vendor/bundle/ruby/2.2.0/gems/geocoder-1.5.0/lib/geocoder/lookups/base.rb:195:in `fetch_data'
	from /app/vendor/bundle/ruby/2.2.0/gems/geocoder-1.5.0/lib/geocoder/lookups/ipinfo_io.rb:32:in `results'
	from /app/vendor/bundle/ruby/2.2.0/gems/geocoder-1.5.0/lib/geocoder/lookups/base.rb:46:in `search'
	from /app/vendor/bundle/ruby/2.2.0/gems/geocoder-1.5.0/lib/geocoder/query.rb:11:in `execute'
	from /app/vendor/bundle/ruby/2.2.0/gems/geocoder-1.5.0/lib/geocoder.rb:22:in `search'
	from (irb):16
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.7.1/lib/rails/commands/console.rb:65:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.7.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.7.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.7.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.7.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /app/bin/rails:4:in `require'
	from /app/bin/rails:4:in `<main>'irb(main):017:0> 

### Steps to reproduce
Geocoder.search("172.56.21.89")

### Environment info

* Geocoder version: 1.4.5/1.5.0
* Rails version: 5.0
* Database (if applicable): PG
* Lookup (if applicable):

**Comment by alexreisner** [comment]
Is this still happening? I can't reproduce and suspect it may have been a temporary problem with IPInfo.io.
