### ISSUE TITLE
IP address-based geocoding on mobile cellular networks is inaccurate

### ISSUE THREAD

**Issue by dylanjha** [alexreisner/geocoder#1374]
I searched around and I am surprised I didn't find some discussion about this already, if there is one and I didn't see it, please forgive me :).

When on a mobile cellular network (like T-Mobile or Verizon LTE, for example) `request.location` does not return an accurate result - one example is a user in Los Angeles being located in Texas, another example is a user in San Francisco being located in Washington.

These examples were done with the ipstack service, but when visiting https://www.whatismyip.com/ the location is the same.

I expect this is simply a shortcoming of geocoding based on IP, and there may be no way to get an accurate result. Or, is there a different service that will return an accurate result?

Services like Mixpanel and Amplitude are able to detect the user's location accurately when on mobile cellular networks, I'm guessing they are determining that based on IP address, so I think this should be possible.

### Expected behavior

The `Geocoder::Result` is accurate

### Actual behavior

The `Geocoder::Result` is in-accurate, off by thousands of miles

### Steps to reproduce

Run a rails server, use [ngrok](https://ngrok.com/) to expose it to the public internet. From a mobile device connected to a cellular network (not wifi) make a request to the rails server via the ngrok URL and check the `request.location` result.

### Environment info

* Geocoder version: 1.4.9
* Rails version: 5.1.4
* Lookup (if applicable): ipstack

**Comment by alexreisner** [comment]
Yes, this has been my experience too--extremely low precision on cell networks. Unfortunately I don't think there's anything that can be done about it. Services that have higher precision are likely using JavaScript, device GPS, or some other means of determining location (access to private databases?). As far as I know, there's no public IP geocoding service that's better than the ones currently supported by Geocoder. If there are, I'd be happy to add support for them.
