### ISSUE TITLE
 By default Geocoder will rescue any exceptions raised by calls to a geocoding service and return an empty array

### ISSUE THREAD

**Issue by meetme2meat** [alexreisner/geocoder#1378]
According to [README](https://github.com/alexreisner/geocoder/blob/master/README.md#error-handling) 
> By default, Geocoder will rescue any exceptions raised by calls to a geocoding service and return an empty array

Well, this holds mostly true for all exception except the [`Geocoder::NetworkError`](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/base.rb#L311). It [seems like](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/base.rb#L196-L202)(no rescue for **Geocoder::NetworkError**) system would raises `Geocoder::NetworkError` instead of returning an empty array in response which break the README.md declaration.

### Expected behavior
  Geocoder.search would raise `Geocoder::NetworkError`.

### Actual behavior
   Geocoder.search api should return [] (an empty array)
  

### Environment info

* Geocoder version:  1.5.0
* Rails version: 5.0.0.1

**Comment by alexreisner** [comment]
Good catch. Yes, this should be fixed.

**Comment by philosoralphter** [comment]
Any idea in what version this was introduced?

**Comment by dsandstrom** [comment]
@philosoralphter Looks to be added in v1.5.2 https://github.com/alexreisner/geocoder/commits/v.1.5.2
