### ISSUE TITLE
Nifty - Scaffold

### ISSUE THREAD

**Issue by Tacoholic** [alexreisner/geocoder#1385]
I am trying to get the Geocoder tool up and running in my new app I am creating.  However, I have come across an issue.  When I following the documentation and type "rails g nifty:scaffold location address:string latitude:float longitude:float", I am getting the following message which is attached in the jpeg.  Do you know what the issue may be?  

![snip20190227_2](https://user-images.githubusercontent.com/46233361/53539608-dbb59180-3ad7-11e9-863b-bb2fc53f426c.png)

**Comment by alexreisner** [comment]
Looks like the error is coming from nifty scaffold, not geocoder.

**Comment by Tacoholic** [comment]
I did some more investigating and saw that my rails doesn't support nifty.
