### ISSUE TITLE
[QUESTION] How to GROUP BY and get first record?

### ISSUE THREAD

**Issue by joemasilotti** [alexreisner/geocoder#1388]
I have two tables, `Beer`, and `Serving`. `Serving` has the coordinate information. I am trying to get the closest beers to a location from the servings. Said another way, group the servings by `beer_id` and return the one with the smallest `distance` from the group.

### Expected behavior

```ruby
Serving.near(location, 50, select: "min(distance), beer_id")
  .group(:beer_id)
  .map(&:beer_id)
# => [12,52434, 234, 4523, 2312, ...] # the closest of each beer ID
```

### Actual behavior

```ruby
Serving.near(location, 50, select: "min(distance), beer_id")
  .group(:beer_id)
  .map(&:beer_id)

ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "distance" does not exist
LINE 1: SELECT min(distance), beer_id, 3958.755864232 * 2 * ASIN(SQR...
```

Here's the generated query:
```
  Serving Load (0.9ms)  SELECT min(distance), beer_id, 3958.755864232 * 2 * ASIN(SQRT(POWER(SIN((41.1148179 - servings.latitude) * PI() / 180 / 2), 2) + COS(41.1148179 * PI() / 180) * COS(servings.latitude * PI() / 180) * POWER(SIN((-74.1495889 - servings.longitude) * PI() / 180 / 2), 2))) AS distance, MOD(CAST((ATAN2( ((servings.longitude - -74.1495889) / 57.2957795), ((servings.latitude - 41.1148179) / 57.2957795)) * 57.2957795) + 360 AS decimal), 360) AS bearing FROM "servings" WHERE (servings.latitude BETWEEN 40.39115898444576 AND 41.83847681555424 AND servings.longitude BETWEEN -75.11012154848267 AND -73.18905625151733 AND (3958.755864232 * 2 * ASIN(SQRT(POWER(SIN((41.1148179 - servings.latitude) * PI() / 180 / 2), 2) + COS(41.1148179 * PI() / 180) * COS(servings.latitude * PI() / 180) * POWER(SIN((-74.1495889 - servings.longitude) * PI() / 180 / 2), 2)))) BETWEEN 0.0 AND 50) GROUP BY "servings"."beer_id" ORDER BY distance ASC
```

Any help would be greatly appreciated. Thanks in advance!

### Environment info

* Geocoder version: 1.5.0
* Rails version: 5.1.6.2
* Database (if applicable): Postgres

**Comment by alexreisner** [comment]
Because `distance` is defined in the SELECT clause, the column alias [isn't available for the GROUP clause](https://stackoverflow.com/questions/3841295/sql-using-alias-in-group-by). You have to specify the whole distance calculation, which you can get from the [`distance_sql` method](https://github.com/alexreisner/geocoder/blob/8c000fdf7ee7a8bac9b9bb17429e94d2b371f4da/lib/geocoder/stores/active_record.rb#L155-L164).

**Comment by joemasilotti** [comment]
Awesome, thank you! I was able to get it working with the following.

```
Serving.near(location, 50, select: "min(#{Serving.distance_sql(*location)}) AS distance, beer_id", order: false, select_distance: nil, select_bearing: nil)
  .group(:beer_id)
  .order("distance")
  .map { |s| [s.beer_id, s.distance] }
```

**Comment by alexreisner** [comment]
Great! Thanks for sharing your solution.
