### ISSUE TITLE
Support for autocomplete API

### ISSUE THREAD

**Issue by antogon** [alexreisner/geocoder#1389]
Hi @alexreisner ,

 Wondering if support for suggestions/autocomplete APIs ([here.com](https://developer.here.com/documentation/geocoder-autocomplete/topics/quick-start-get-suggestions.html), [google](https://developers.google.com/maps/documentation/javascript/places-autocomplete)) has ever been considered as a feature for `geocoder`?  Would you entertain a PR to add that functionality if I raised one?

**Comment by alexreisner** [comment]
See #1383.
