### ISSUE TITLE
Feature Request - Add geocoded table/model reference to near() method

### ISSUE THREAD

**Issue by joshm1204** [alexreisner/geocoder#1393]
FEATURE REQUEST: (as referenced in this closed issue: https://github.com/alexreisner/geocoder/issues/1391

Add geocoded table/model reference to Near(), so you do not need to query directly on the geocoded model.

User.joins(profile:[:address, :activity,:hobbies].near(location,distance, :address)

**Comment by alexreisner** [comment]
For now, if I understand correctly, you can accomplish this with a WHERE clause generated by the [`distance_sql` method](https://github.com/alexreisner/geocoder/blob/8c000fdf7ee7a8bac9b9bb17429e94d2b371f4da/lib/geocoder/stores/active_record.rb#L155-L164) and specifying the table name in the column names (eg, `user.latitude`).

**Comment by joshm1204** [comment]
Yes, I think so, basically the near command gets a 

> NoMethodError (undefined method `near' for #<Profile::ActiveRecord_Relation:0x00007fdd7627abb8>)

So to address this issue, you recommended creating a custom where clause. I have a few questions, which I think would be helpful for others in this situation too.

Where does this part of the where clause come from? 

```
   WHERE (addresses.latitude BETWEEN 38.6728005337783 AND 39.2517276662217 
   AND addresses.longitude BETWEEN -95.62737134757229 AND -94.8828282524277 
```
    
I see that Geocoder::Sql.send("full_distance",0.38962264e2, 0.952551e2,'addresses.latitude','addresses.longitude') will generate

```
    AND (3958.755864232 * 2 * ASIN(SQRT(POWER(SIN((38.9622641 - addresses.latitude) * 
    PI() / 180 / 2), 2) + COS(38.9622641 * PI() / 180) * COS(addresses.latitude * 
    PI() / 180) * POWER(SIN((-95.2550998 - addresses.longitude) * PI() / 180 / 2), 2)))) 

```
and I assume this is the distance 0 to 20 miles/km:

` BETWEEN 0.0 AND 20) ORDER BY distance ASC`

**Comment by joshm1204** [comment]
My overall solutions, but I feel there is a problem with my bounding box.

    def find_near(lat,lon, radius)
      Geocoder::Calculations.bounding_box([lat,lon]
      Geocoder::Sql.send("full_distance",lat, lon,'addresses.latitude','addresses.longitude')
      bounding = Geocoder::Calculations.bounding_box([lat,long]
    
      "WHERE (addresses.latitude BETWEEN #{bounding[1]} AND #{bounding[2]} 
      AND addresses.longitude BETWEEN #{bounding[3]} AND #{bounding[4]} 
      AND #{distance}
      BETWEEN 0.0 AND #{radius})"
    end
