### ISSUE TITLE
FEATURE REQUEST: rake geocode:all CLASS=YourModel (Real batching processing)

### ISSUE THREAD

**Issue by joshm1204** [alexreisner/geocoder#1394]
I noticed that when I  use `rake geocode:all CLASS=YourModel` for batch geocoding, it takes a really long time, and looking at the code, if I understand it correctly, it seems to make a separate call for each geocoded record.

If it is making multiple call to the service, I would like to make a feature require to allow "REAL" batch geocoding, sending one large json of  addresses and getting it's lat and longitude in one call rather then thousands.

This would be substantially faster and more efficient.

Geocoder version:  4.1
Ruby : 2.6.1
Rails version:  5.2.2
Database (if applicable): Postgres
Lookup (if applicable):  Google

**Comment by alexreisner** [comment]
Please see #1044.
