### ISSUE TITLE
How to get country full name?

### ISSUE THREAD

**Issue by vtrkanna** [alexreisner/geocoder#1395]
SOME COUNTRIES ARE GIVING SHORT SAMES, LIKE USA, ETC.

USUALLY **USA** IS NOT FULL NAME, ITS SHORT NAME

What wrong in this code?
`Geocoder.search("33.77834525,-84.4210908621225")`

Did i missed anything?

**Note: Google geo code its giving long name and short names.**

`{
               "long_name" : "United States",
               "short_name" : "US",
               "types" : [ "country", "political" ]
            },`

https://developers.google.com/maps/documentation/geocoding/intro#reverse-example

### Expected behavior
`"address"=>
     {"address29"=>"Quality Technology Services",
      "house_number"=>"1033",
      "road"=>"Jefferson Street Northwest",
      "neighbourhood"=>"Bellwood",
      "suburb"=>"Rockdale",
      "city"=>"Atlanta",
      "county"=>"Fulton County",
      "state"=>"Georgia",
      "postcode"=>"30318",
      "country"=>"united states america",
      "country_code"=>"us"},`

### Actual behavior
`"address"=>
     {"address29"=>"Quality Technology Services",
      "house_number"=>"1033",
      "road"=>"Jefferson Street Northwest",
      "neighbourhood"=>"Bellwood",
      "suburb"=>"Rockdale",
      "city"=>"Atlanta",
      "county"=>"Fulton County",
      "state"=>"Georgia",
      "postcode"=>"30318",
      "country"=>"USA",
      "country_code"=>"us"},`

### Environment info

* Geocoder version:  1.5
* Rails version:  5.0.7
* Database (if applicable):  POSTGRESQL
* Lookup (if applicable):

**Comment by alexreisner** [comment]
If you want access to the full dataset returned by the API, try `result.data`, eg:

    results = Geocoder.search("33.77834525,-84.4210908621225")
    results.first.data['address']['country']

If the data you want isn't in the `data` hash, you'll need to try a different API.

**Comment by vtrkanna** [comment]
Instead of  **United States of America / United States** it's returning **USA**

`"country"=>"USA"`

**USA** is not country name

@alexreisner
