### ISSUE TITLE
Autocomplete / suggestions list

### ISSUE THREAD

**Issue by krzkrzkrz** [alexreisner/geocoder#1399]
Does this library support an autocomplete feature? For example with Google Maps Places API. I can type `stadium`. I get a list of suggestions. Is there support for such a thing here?

I've recently come across https://github.com/alexreisner/geocoder/pull/1383
It seems, the consensus around having such a feature is beyond the scope of this library. But wondering if anything has changed since then

**Comment by alexreisner** [comment]
#1383 is still the latest discussion. I acknowledge the usefulness of the feature but I don't yet see a way to add it that doesn't add a significant amount of complexity to the gem.

**Comment by krzkrzkrz** [comment]
Understood, guess would have to roll out a custom implementation. Will close this ticket for now
