### ISSUE TITLE
Rails request.location gives  Geocoder::RequestDenied

### ISSUE THREAD

**Issue by valentinbotog** [alexreisner/geocoder#1401]
BEFORE POSTING AN ISSUE, PLEASE MAKE SURE THE PROBLEM IS NOT ADDRESSED IN THE README!

### Expected behavior

request.location to return my location information

### Actual behavior

gives Geocoder::RequestDenied

### Environment info

* Geocoder version: 1.4.9
* Rails version: 4.2.5.1
* Database (if applicable): MongoDB
* Lookup (if applicable):  :ip_lookup => :telize

Geocoder.configure(
  # geocoding options
  :timeout   => 15,           # geocoding service timeout (secs)
  :lookup    => :google,
  :ip_lookup => :telize,
  :language  => :en,
  :use_https => true,
  :api_key   => Rails.application.secrets.google_api_server_key,
  :sensor    => false,
  :cache     => Rails.cache,  # cache object (must respond to #[], #[]=, and #keys)
  # :cache_prefix => "geocoder:", # prefix (string) to use for all cache keys

  # API errors are not being raised by default by Geocoder
  # In order NOT to cache errored requests we need to raise error when it occurs
  :always_raise => [
    Geocoder::OverQueryLimitError,
    Geocoder::RequestDenied,
    Geocoder::InvalidRequest,
    Geocoder::InvalidApiKey
  ],

  # calculation options
  :units     => :mi,       # :km for kilometers or :mi for miles
  # :distances => :linear    # :spherical or :linear
)

**Comment by alexreisner** [comment]
This looks like a temporary condition on the Telize server. Is there any indication it's a Geocoder bug?

**Comment by valentinbotog** [comment]
I changed the ip_lookup from :telize to :freegeoip and now I get request.location as nil . I forgot to tell you that the rails app is on heroku, maybe that's an issue also.

btw, thanks for the fast answer

**Comment by alexreisner** [comment]
It still doesn't sound like a Geocoder bug. Freegeoip was discontinued. Please make sure you're using the latest gem version and try `:ipinfo_io`.

**Comment by valentinbotog** [comment]
Thanks for the info. I will close this ticket since I managed to skip the error.
