### ISSUE TITLE
Interface for storing bounds in ActiveRecord model

### ISSUE THREAD

**Issue by tylerklose** [alexreisner/geocoder#1403]
In an application where there's a model whose locality represents an area rather than a single point, the latitude and longitude attributes from the result aren't all that useful. For example, we need to be able to calculate whether or not a given point (or boundary) exists within a given `ServiceArea`.

Our `ServiceArea` model has 4 relevant attributes: `zip_code`, `city`, `state`, `country`. I'd like to store the bounds as returned by the Google lookup:
```ruby
# frozen_string_literal: true

class ServiceArea < ApplicationRecord
  geocoded_by :address,
              south: :southern_boundary,
              west: :western_boundary,
              north: :northern_boundary,
              east: :eastern_boundary

  ...

  def address
    [zip_code, city, state, country].compact.join(", ")
  end

  ...

end
```

This is currently not possible. I introduced a monkey patch into our application to solve this issue for us. I wanted to discuss the problem and the quick and dirty solution before forking the repo and opening up PR. Here's the monkey patch:

```ruby
# frozen_string_literal: true

module Geocoder
  module Model
    # Methods for invoking Geocoder in an ActiveRecord model.
    module ActiveRecord
      # Set attribute names and include the Geocoder module.
      def geocoded_by(address_attr, options = {}, &block)
        geocoder_init(
          geocode: true,
          user_address: address_attr,
          latitude: options[:latitude] || :latitude,
          longitude: options[:longitude] || :longitude,
          south: options[:south] || :south,
          west: options[:west] || :west,
          north: options[:north] || :north,
          east: options[:east] || :east,
          geocode_block: block,
          units: options[:units],
          method: options[:method],
          lookup: options[:lookup],
          language: options[:language],
          params: options[:params]
        )
      end
    end
  end

  module Store
    # Add geocoding functionality to any stored object
    module Base
      # Heavily influenced by #geocode
      def geocode_bounds
        do_lookup(false) do |o, results|
          return if results.empty?

          result = results.first
          south, west, north, east = result.bounds

          if south && west && north && east
            o.__send__  "#{self.class.geocoder_options[:south]}=",  south
            o.__send__  "#{self.class.geocoder_options[:west]}=", west
            o.__send__  "#{self.class.geocoder_options[:north]}=", north
            o.__send__  "#{self.class.geocoder_options[:east]}=", east
          end

          result.bounds
        end
      end
    end
  end
end
```

### Environment info
* Geocoder version: 1.5.1
* Rails version: 6.0.0.rc1
* Database (if applicable): PostgreSQL
* Lookup (if applicable): Google

**Comment by alexreisner** [comment]
Thanks for sharing this! Very cool monkey patch. Unfortunately I would probably not merge a PR for this functionality because it seems quite specific to your application (area is assumed to be a rectangle), but I think this can be a useful guide for anyone wanting to do something similar and not wanting to use rgeo (which can handle regions of any shape).

**Comment by tylerklose** [comment]
This functionality is more so specific to the Google Maps API since they only return the southwest and northeast corners. [OpenStreetMap](https://nominatim.openstreetmap.org/details.php?place_id=200372087) (`nominatim`) returns a polygon. This will likely be insufficient for the final our final solution as well. A more complete solution would allow for storing for bounds of any type. The easiest solution would probably be to store the `result.bounds` as JSON/JSONB since each lookup service will represent bounds in their own unique way
