### ISSUE TITLE
SQL Error when calling .count

### ISSUE THREAD

**Issue by Bdoom** [alexreisner/geocoder#1405]
### Expected behavior
I have a "Location" model for my users which stores their address, and other lat/long data. However, I'm trying to be able to get all other "locations" within that table that are near my current users location within a 5 mile radius. 

So I'm doing the following:     @locations = Location.near([current_user.location.latitude, current_user.location.longitude], 5)

It works! But if I try to call:
@locations.count

The error below occurs.

### Actual behavior
ActiveRecord::StatementInvalid (Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*, 3958.755864232 * 2 * ASIN(SQRT(POWER(SIN((38.7135 - locations.latitude) * PI(' at line 1: SELECT COUNT(locations.*, 3958.755864232 * 2 * ASIN(SQRT(POWER(SIN((38.7135 - locations.latitude) * PI() / 180 / 2), 2) + COS(38.7135 * PI() / 180) * COS(locations.latitude * PI() / 180) * POWER(SIN((-78.1594 - locations.longitude) * PI() / 180 / 2), 2))) AS distance, MOD(CAST((ATAN2( ((locations.longitude - -78.1594) / 57.2957795), ((locations.latitude - 38.7135) / 57.2957795)) * 57.2957795) + 360 AS decimal), 360) AS bearing) FROM `locations` WHERE (locations.latitude BETWEEN 38.64113410844458 AND 38.785865891555424 AND locations.longitude BETWEEN -78.25214312704786 AND -78.06665687295215 AND (3958.755864232 * 2 * ASIN(SQRT(POWER(SIN((38.7135 - locations.latitude) * PI() / 180 / 2), 2) + COS(38.7135 * PI() / 180) * COS(locations.latitude * PI() / 180) * POWER(SIN((-78.1594 - locations.longitude) * PI() / 180 / 2), 2)))) BETWEEN 0.0 AND 5))

### Steps to reproduce
Mentioned above.

### Environment info

* Geocoder version: 
* Rails version: Rails 5.2.3
* Database (if applicable): MySQL 
* Lookup (if applicable): IDK what this means

**Comment by alexreisner** [comment]
As it says in the README, please use `@locations.count(:all)`.
