### ISSUE TITLE
Geocoder.search("Sam Francisco") returns "Damascus, Syria" which is inconsistent

### ISSUE THREAD

**Issue by Mywe4ka** [alexreisner/geocoder#1409]
### Expected behavior

`Geocoder.search("Sam Francisco")` should return any matching result.

For example: "San Francisco, US" or "Sam, Sweden" or "Francisco, IN" etc.

### Actual behavior

`Geocoder.search("Sam Francisco")` returns `"Damascus, Syria"`. 

### Steps to reproduce

1. Set bing lookup and ipstack as Ip_lookup.

2. Run `Geocoder.search("Sam Francisco")`

Results are:

```
 [#<Geocoder::Result::Bing:0x00007f82a7d08dc0
  @cache_hit=true,
  @data=
   {"__type"=>"Location:http://schemas.microsoft.com/search/local/ws/rest/v1",
    "bbox"=>[33.44552993774414, 36.22713851928711, 33.57463073730469, 36.40776062011719],
    "name"=>"Damascus, Syria",
    "point"=>{"type"=>"Point", "coordinates"=>[33.51655960083008, 36.317081451416016]},
    "address"=>{"countryRegion"=>"Syria", "formattedAddress"=>"Damascus, Syria", "locality"=>"Damascus", "countryRegionIso2"=>"SY"},
    "confidence"=>"Low",
    "entityType"=>"PopulatedPlace",
    "geocodePoints"=>[{"type"=>"Point", "coordinates"=>[33.51655960083008, 36.317081451416016], "calculationMethod"=>"Rooftop", "usageTypes"=>["Display"]}],
    "matchCodes"=>["Ambiguous", "UpHierarchy"]}>,
```

### Environment info

* Geocoder version: geocoder (1.4.9)
* Rails version: rails (5.2.3)
* Database (if applicable): postgress - pg (0.21.0)

**Geocoder.configure(**
* lookup:  :bing,
* ip_lookup: :ipstack,
* language: :en,
* use_https: false

)

**Comment by alexreisner** [comment]
Ha! Unfortunately there's nothing Geocoder can do about that. Apparently that's how Bing handles the request. Solution: try a different `:lookup`. The default (Nominatim) returns a more reasonable location.
