### ISSUE TITLE
Geocoder.search returns empty result for some addresses

### ISSUE THREAD

**Issue by GeoffreyBourboin** [alexreisner/geocoder#1410]
### Expected behavior

Running in rails console
`Geocoder.search("24 rue de Chaligny,Paris")` should return response with latitude longitude and more infos...

### Actual behavior

empty result

```
irb(main):002:0> Geocoder.search("24 rue de chaligny,Paris")
=> []
```

### Steps to reproduce

Run in rails console : `Geocoder.search("24 rue de Chaligny,Paris"`)

### Environment info

Geocoder version: 1.5.1
Rails version: 6

**Comment by GeoffreyBourboin** [comment]
Any workaround or something ?

**Comment by alexreisner** [comment]
Sorry, looks like you'll need to configure a different `:lookup` with better coverage in the Paris area. Please see the [API guide](https://github.com/alexreisner/geocoder/blob/master/README_API_GUIDE.md) for choices.

**Comment by GeoffreyBourboin** [comment]
It's not only for Paris it doesn't work too for this adress for exemple :
84 poruthota road, negombo, Sri Lanka.

Le lun. 30 sept. 2019 à 20:50, Alex Reisner <notifications@github.com> a
écrit :

**Comment by alexreisner** [comment]
Yes, I understand. But this is an issue with the API, not with the Geocoder gem. All the APIs have very different coverage areas. You'll have to pick the one that works best for your application.
