### ISSUE TITLE
Redis expiration example seems overcomplicated

### ISSUE THREAD

**Issue by joncass** [alexreisner/geocoder#1421]
Thanks for a great gem!
Is there a reason the [Redis autoexpiring cache](https://github.com/alexreisner/geocoder/blob/master/examples/autoexpire_cache_redis.rb) can't be implemented as a child class of `Redis`? i.e. something like
```
class AutoexpireCacheRedis < Redis
  def []=(url, value)
    super
    expire(url, 86_400)
  end
end
```

**Comment by alexreisner** [comment]
It could definitely be a subclass of `Redis`. All those methods are written out just for the example, to show what you need to implement.

**Comment by joncass** [comment]
Ah gotcha. Personally, I found it a bit confusing that the example was written like that, and assumed that there was some reason it had to list out all the methods. Would you be interested in a PR that simplified the example, or would you rather leave it as-is (or make your own updates)?

**Comment by alexreisner** [comment]
OK, maybe the best thing would be to append a sentence to the comment at the top of the file: "Alternatively, this class could inherit from `Redis`..." Would that clarify it?

**Comment by joncass** [comment]
Yeah, I think that would be helpful

**Comment by joncass** [comment]
:+1: thanks for the quick turnaround
