### ISSUE TITLE
is there a way to search by postal code as allowed in google api

### ISSUE THREAD

**Issue by Faisal-nfl** [alexreisner/geocoder#1422]
https://maps.googleapis.com/maps/api/geocode/json?address=&components=postal_code:06877&sensor=false&key=

### Actual behavior
I don't see any option to search by postal_code though actual google api allows it

* Lookup (if applicable): 
Google

#Update 
I tried something like this
`results = Geocoder.search('K1G 9L1', components: [:postal_code])`

its returning results but not sure if its the actual way

**Comment by alexreisner** [comment]
Yes, that's the right way to do it! The lookup will do the best it can with whatever address (or portion of address) you give it.
