### ISSUE TITLE
OpenSSL::SSL::SSLError when using Google

### ISSUE THREAD

**Issue by reggieb** [alexreisner/geocoder#1425]
### Expected behavior
```ruby
Geocoder.search('Paris')
```
Outputs:
```
[#<Geocoder::Result::Pickpoint:0x000056466ffe3538 ... >]
```
When set to use pickpoint. (Also google works fine on another computer).

### Actual behavior

On current Linux PC I get, with `:google` set as **lookup**:

```
Traceback (most recent call last):
        1: from (irb):1
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: tlsv1 alert access denied)
```

I've tried `rvm reinstall 2.6.5 --disable-binary` as other similar issues suggested that should fix it.

Googling for this error brings up people having issues with connecting to rubygems getting a similar error. One check suggested is to run `ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'`. This includes a basic HTTPS check. That passes on this computer.

### Environment info

* Geocoder version: 1.5.2
* Rails version: 6.0.0 (Ruby 2.6.5p114 - via RVM)
* Lookup (if applicable): google
* OS: Linux Mint 19.1 Cinnamon 4.15.0-66-generic

**Comment by clarkritchie** [comment]
👀 Also seeing this behavior.

**Comment by alexreisner** [comment]
I've been unable to reproduce this, and it seems like an environment-specific issue, not a Geocoder issue, so I'm going to close. However, some troubleshooting thoughts: Does it work with a different version of Ruby? Do you get the error with APIs other than Google?
