### ISSUE TITLE
Heroku - Geocoding API not responding fast enough (use Geocoder.configure(:timeout => ...) to set limit).

### ISSUE THREAD

**Issue by galharth** [alexreisner/geocoder#1427]
### Expected behavior

`Geocoder.search("Paris") 
`

should return:

`[#<Geocoder::Result::Google:0x00007f889e945060 @data={"address_components"=>[{"long_name"=>"Paris", "short_name"=>"Paris", "types"=>["locality", "political"]}, {"long_name"=>"Paris", "short_name"=>"Paris", "types"=>["administrative_area_level_2", "political"]}, {"long_name"=>"Île-de-France", "short_name"=>"Île-de-France", "types"=>["administrative_area_level_1", "political"]}, {"long_name"=>"France", "short_name"=>"FR", "types"=>["country", "political"]}], "formatted_address"=>"Paris, France", "geometry"=>{"bounds"=>{"northeast"=>{"lat"=>48.9021449, "lng"=>2.4699208}, "southwest"=>{"lat"=>48.815573, "lng"=>2.224199}}, "location"=>{"lat"=>48.856614, "lng"=>2.3522219}, "location_type"=>"APPROXIMATE", "viewport"=>{"northeast"=>{"lat"=>48.9021449, "lng"=>2.4699208}, "southwest"=>{"lat"=>48.815573, "lng"=>2.224199}}}, "place_id"=>"ChIJD7fiBh9u5kcRYJSMaMOCCwQ", "types"=>["locality", "political"]}, @cache_hit=nil>]
`
### Actual behavior

`Geocoder.search("Paris") 
`
returns:

`Geocoding API not responding fast enough (use Geocoder.configure(:timeout => ...) to set limit).
`

Also QUOTAGUARDSHIELD proxy don't get any requests and ipinfo_io don't get any requests (I checked on their dashboards)

### Steps to reproduce

I use this config on my heroku app with QUOTAGUARDSHIELD addon:

```
  Geocoder.configure(
    google: {
        api_key: ENV["GOOGLE_API_GEOCODE_SERVER_KEY"],
        use_https: true,         
        https_proxy: ENV['QUOTAGUARDSHIELD_URL'],
        timeout: 30
    },
    ipinfo_io: {
      api_key: ENV["IPINFO_IO_API_KEY"],
      use_https: true,         
      https_proxy: ENV['QUOTAGUARDSHIELD_URL'],
      timeout: 30
    },
    lookup: :google,         
    ip_lookup: :ipinfo_io,     
  )


```

### Environment info

* Geocoder version: 1.5.2
* Rails version: 6.0.0
* Database (if applicable): postgres
* Lookup (if applicable): ipinfo_io

**Comment by alexreisner** [comment]
Do you have any way of confirming that the request really isn't being sent? If QuotaGuard is timing out, they may not be logging the request.

**Comment by galharth** [comment]
> Do you have any way of confirming that the request really isn't being sent? If QuotaGuard is timing out, they may not be logging the request.

I don't see any requests in the google cloud api either.. I don't know any other way to confirm otherwise? I can do any steps you tell me to do if needed...

**Comment by galharth** [comment]
@alexreisner any clue? really stuck here, thanks 🙏

**Comment by alexreisner** [comment]
@galharth I'm not sure what could be going on, but it seems like an issue with your environment, rather than Geocoder. You might want to try posting on StackOverflow, where more people will see it.
