### ISSUE TITLE
"Here" introduced new urls and a single API key

### ISSUE THREAD

**Issue by stephanpavlovic** [alexreisner/geocoder#1429]
It looks like "Here" is using new urls and also a new authentication method, I have found no informations about when they will remove the legacy url but fo new REST/JS Apps you can not even generate an app code anymore....

https://developer.here.com/documentation/geocoder/topics/dev_guide/request-constructing.html

https://developer.here.com/documentation/authentication/dev_guide/topics/api-key-credentials.html

**Comment by alexreisner** [comment]
Thanks! Definitely open to a pull request, if anyone wants to handle this.

**Comment by stephanpavlovic** [comment]
I will try to handle this

**Comment by stephanpavlovic** [comment]
I think I will provide something one the weekend.
One quick question @alexreisner: I guess I nee to make it work in parallel for both, the old and the new way. Is this also the case in one of the other lookup services, so I can have a look how you handle such a case there?

**Comment by alexreisner** [comment]
Thanks, and good question, but I don't think it needs to work both ways. If the new URL and key format are working, we can just remove support for the old format.

**Comment by alexreisner** [comment]
Fixed by #1430.
