### ISSUE TITLE
The Google Places Details API requires a key to be configured: "key"

### ISSUE THREAD

**Issue by sunwooz** [alexreisner/geocoder#1431]
### Expected behavior
Expected using an api key will let me use the geocoding service

### Actual behavior
Get error: The Google Places Details API requires a key to be configured: "key"

### Steps to reproduce
Configure geocoder in config/initializer/geocoder.rb
```
Geocoder.configure(
    # Geocoding options
    timeout: 15,                 # geocoding service timeout (secs)
    # lookup: :nominatim,         # name of geocoding service (symbol)
    # ip_lookup: :ipinfo_io,      # name of IP address geocoding service (symbol)
    language: :en,              # ISO-639 language code
    use_https: true,           # use HTTPS for lookup requests? (if supported)
    api_key: Rails.application.secrets.google_places_api_key,
)
```
I tried using 'api_key' and 'key', both returns the same error.
```
results = Geocoder.search('ChIJS7N-Pi5B1moR6PzOCBk0Ob4', lookup: :google_places_details)
```
### Environment info

* Geocoder version: 1.5.2
* Rails version: 5.2.4.1
* Database (if applicable): 
* Lookup (if applicable): google_places_search and google_places_details

**Comment by alexreisner** [comment]
Do you get the error if you set `lookup: :google_places_details` in your call to `Geocoder.configure`?

**Comment by sunwooz** [comment]
That worked! Thanks @alexreisner 
I noticed that google_places_details needs a 'fields' query parameter to fetch the opening_hours of a place. How do I include that? I couldn't find a mention of it inside the gem itself.

**Comment by alexreisner** [comment]
Great! And you should be able to pass the fields parameter by passing a `:params` option to the lookup method, eg: `Geocoder.search('...', params: {fields: '...'})`
