### ISSUE TITLE
Question: PostGIS support?

### ISSUE THREAD

**Issue by emmx** [alexreisner/geocoder#1434]
It's not clear from the documentation if this gem supports PostGIS for querying locations in PostgreSQL or not. I've read in [1] and some other places that it is possible, however no details are given, and there are only a few mentions of it in the entire repository.

This would be really nice if we can add support for things like `Location.where(category: "foo", ...).near("New York City")` that uses PostGIS behind the scenes instead of doing distance calculations in the `SELECT` query, which I'm guessing is less efficient.

In the example above, should I be using Geocoder to transform "New York City" to a coordinate and then [2] to filter `Locations` near that coordinate?

[1] https://stackify.com/rails-geocoder-a-guide-to-managing-locations-in-your-apps/
[2] https://github.com/rgeo/activerecord-postgis-adapter

**Comment by alexreisner** [comment]
Geocoder does not support PostGIS. The gem for that is [rgeo](https://github.com/rgeo/rgeo). But yes, for transforming "New York City" into coordinates before running your local filter, Geocoder is what you want.
