### ISSUE TITLE
Tencent Lookup: Duplicate WHEN Clause

### ISSUE THREAD

**Issue by alexreisner** [alexreisner/geocoder#1435]
In the Tencent lookup there's a [duplicate WHEN clause where status codes are handled](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/tencent.rb#L37-L45) (311 appears twice).

@Anders-E I can't read the Tencent documentation--would you mind taking a look?

**Comment by Anders-E** [comment]
Looking into it now.

**Comment by Anders-E** [comment]
Seems they've updated their status codes. I created a pull request: #1436 

Thanks for letting me now about this bug

**Comment by alexreisner** [comment]
And thank _you_ for the quick fix!
