### ISSUE TITLE
Generators are not exposed to rails

### ISSUE THREAD

**Issue by rjaus** [alexreisner/geocoder#1440]
BEFORE POSTING AN ISSUE, PLEASE MAKE SURE THE PROBLEM IS NOT ADDRESSED IN THE README!

Docs state this should work: https://github.com/alexreisner/geocoder/blob/master/README.md#geocoding-service-lookup-configuration

`rails generate geocoder:config`
Outputs:
```
Running via Spring preloader in process 400
Could not find generator 'geocoder:config'. Maybe you meant 'generator', 'controller' or 'resource'
Run `rails generate --help` for more options.
```

### Expected behavior
`rails generate`
Output geocoder generators

### Actual behavior
`rails generate`
Shows no generators related to geocoder

Output:
```
Running via Spring preloader in process 327
Usage: rails generate GENERATOR [args] [options]

General options:
  -h, [--help]     # Print generator's options and usage
  -p, [--pretend]  # Run but do not make any changes
  -f, [--force]    # Overwrite files that already exist
  -s, [--skip]     # Skip files that already exist
  -q, [--quiet]    # Suppress status output

Please choose a generator below.

Rails:
  application_record
  assets
  channel
  controller
  generator
  helper
  integration_test
  jbuilder
  job
  mailer
  migration
  model
  resource
  scaffold
  scaffold_controller
  system_test
  task

ActiveRecord:
  active_record:application_record

Coffee:
  coffee:assets

Js:
  js:assets

Sidekiq:
  sidekiq:worker

TestUnit:
  test_unit:generator
  test_unit:plugin
```

### Steps to reproduce
`rails generate`

### Environment info

* Geocoder version: 1.6.1
* Rails version: 5.2.3
* Database (if applicable): 
* Lookup (if applicable):

**Comment by alexreisner** [comment]
Thanks for reporting this. It works with Rails 4.2.x so it seems like the way to expose generators changed in Rails five point something.

**Comment by rjaus** [comment]
Hmmm. I've got it working now.  I think it may have been an issue with my docker setup.  Or possible the server restart issue I've seen in other issues.

`gem install geocoder`
`touch  tmp/restart.txt`

Unsure which one resolved the issue.  I had rebuilt the images multiple times, bundle install was definitely installing the geocoder gem.

Generators are now exposed, everything working as per usual.
