### ISSUE TITLE
Could not find generator 'geocoder:config'. && uninitialized constant Geocoder

### ISSUE THREAD

**Issue by pur100** [alexreisner/geocoder#1442]
Hello,

I have Geocoder installed, v 1.6.1 but I cannot generate the initializer nor use the service. 

I tried different installation processes without success.

Any ideas ? 

Thx,
Hugo

### Environment info

* Geocoder version: 1.6.1
* Rails version: 6
* Database (if applicable): 
* Lookup (if applicable):

**Comment by alexreisner** [comment]
Possibly related to #1440?

**Comment by pur100** [comment]
Tried this without success ...

Just installed the gem and used it without any issue on another rails app. 

Do you think I should try and rebuild my app ?!

**Comment by alexreisner** [comment]
Closing this because it doesn't seem like a Geocoder issue. If you manually `require 'geocoder'` does it fix the uninitialized constant problem?
