### ISSUE TITLE
Google Geocoding API limitations incorrect

### ISSUE THREAD

**Issue by creativetags** [alexreisner/geocoder#1445]
On your [API page](https://github.com/alexreisner/geocoder/blob/master/README_API_GUIDE.md) you say "You must not use or display the Content without a corresponding Google map" but Google now says "You can display Geocoding API results on a Google Map, or without a map. If you want to display Geocoding API results on a map, then these results must be displayed on a Google Map. If your application displays data from the Geocoding API on a page or view that does not also display a Google Map, you must show a Powered by Google logo with that data."
https://developers.google.com/maps/documentation/geocoding/policies

**Comment by alexreisner** [comment]
Great catch. Thanks! Just updated API guide.
