### ISSUE TITLE
Search with query >200 chrs : undefined method `any?' for nil:NilClass

### ISSUE THREAD

**Issue by gloaec** [alexreisner/geocoder#1455]
### Expected behavior

If search char limit is exceeded an appropriate error should be thrown (or empty array should be returned if higher buffer supported).

### Actual behavior

    undefined method `any?' for nil:NilClass
    $HOME/.rvm/gems/ruby-2.6.0/gems/geocoder-1.6.1/lib/geocoder/lookups/ban_data_gouv_fr.rb:25:in `any_result?'

### Steps to reproduce

Didn't dig any further tbh, but you can reproduce using ridiculously long parameter (>200 chrs) for lookup :

```ruby  
Geocoder.search("012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890")
```

### Environment info

* Geocoder version: 1.6.1
* Rails version: 6.0.2.1
* Database (if applicable): Postgresql 12
* Lookup (if applicable): ban_data_gouv_fr

**Comment by alexreisner** [comment]
Thanks for reporting this. Looks like this error would also occur in other cases where no result was returned. Should be fixed in master.
