### ISSUE TITLE
Geocoding address to coordinates are incorrect.

### ISSUE THREAD

**Issue by nolyoi** [alexreisner/geocoder#1456]
### Expected behavior
To be given correct long/lat for given address.

### Actual behavior
The long/lat given is up to 500m off (15 mins walking time).

### Steps to reproduce
I've noticed this issue in Vietnam. Addresses that I geocoded in the U.S. were geocoded perfectly. However, when doing viet addresses they are way off. The odd part is, when entering any of these addresses in google maps, the correct location is given. However, when entering them into the geocoder, ive noticed theyre off by about 300-500m which is a lot in a dense city.

Try geocoding one of these addresses. You'll notice the location is incorrect. Compare with the correct location in maps.

"150 Phạm Văn Bạch, phường 15, Quận Tân Bình, Thành Phố, Hồ Chí Minh, VN"
"150 Phạm Văn Bạch,Thành Phố, Hồ Chí Minh, VN"
"150 Phạm Văn Bạch,Hồ Chí Minh, VN"

### Environment info

* Geocoder version: 1.6.3
* Ruby version: 2.7.x
* Rails version: N/A. Using Sinatra 2.0.8.
* Database (if applicable): sqlite3
* Lookup (if applicable):

**Comment by alexreisner** [comment]
The Geocoder gem provides access to [more than 40 geocoding APIs](https://github.com/alexreisner/geocoder/blob/master/README_API_GUIDE.md) ("lookups"). The APIs convert addresses to lat/lon coordinates. If you're getting coordinates, Geocoder is working. If those coordinates aren't what you're looking for, you might want to try a different API. Each lookup will perform differently in different parts of the world.
