### ISSUE TITLE
'near()' not working

### ISSUE THREAD

**Issue by leconganh1995** [alexreisner/geocoder#1458]
Expected behavior
SQL =>
@where_to_buys = WhereToBuy.near('CA', 100).order("distance").limit(30)

Generates this SQL and log file =>
Completed 200 OK in 84ms (Views: 16.1ms | ActiveRecord: 0.3ms)
Started GET "/?utf8=%E2%9C%93&wtbnear=91000&country=United+States&storetype=All&productline=Any&button=" for 2001:ee0:4b78:2e40:9db0:b70:1c01:c95d at 2020-06-15 05:23:22 -0400
Processing by WhereToBuysController#index as HTML
  Parameters: {"utf8"=>"✓", "wtbnear"=>"91000", "country"=>"United States", "storetype"=>"All", "productline"=>"Any", "button"=>""}
  Rendering where_to_buys/index.html.erb within layouts/application
  Rendered where_to_buys/_form.html.erb (0.6ms)
  [1m[36mWhereToBuy Load (0.3ms)[0m  [1m[34mSELECT  where_to_buys.*, NULL AS distance, NULL AS bearing FROM `where_to_buys` WHERE (false) ORDER BY distance LIMIT 30[0m
  Rendered where_to_buys/_results.html.erb (1.0ms)
  Rendered where_to_buys/_online.html.erb (0.2ms)
  Rendered where_to_buys/_legend.html.erb (0.2ms)
  Rendered where_to_buys/_ad1.html.erb (0.2ms)
  Rendered where_to_buys/_map.html.erb (0.6ms)
  Rendered where_to_buys/index.html.erb within layouts/application (5.3ms)
Completed 200 OK in 100ms (Views: 15.2ms | ActiveRecord: 0.3ms)

-----------

Geocoder.configure(
  timeout: 15,                 # geocoding service timeout (secs)
  lookup: :google,         # name of geocoding service (symbol)
  api_key: '...'
  
)

### Environment info

* Geocoder version:  1.6.3
* Rails version: 5.2.4.3
* Ruby 2.3.3
* Database (if applicable): mysqld  Ver 10.1.45-MariaDB for Linux on x86_64 (MariaDB Server)
* Lookup (if applicable): google

**Comment by alexreisner** [comment]
What does `Geocoder.search('CA')` return?

**Comment by leconganh1995** [comment]
`Google API error: request denied (API keys with referer restrictions cannot be used with this API.).
 => [] `

**Comment by leconganh1995** [comment]
But when I use the sql query, it returns the correct map

![image](https://user-images.githubusercontent.com/29689700/84754659-e22c8d00-afea-11ea-8296-1525b05b0176.png)

`WhereToBuy.where(id:1)`

**Comment by alexreisner** [comment]
Google has a lot of similar APIs with similar-sounding names. It's confusing. Make sure you're using this one: https://developers.google.com/maps/documentation/geocoding/usage-and-billing

Also, I'm not sure that map is correct: isn't it showing Pennsylvania ("PA"), not California ("CA")?

(Closing, because I don't think this is an issue with the gem.)
