### ISSUE TITLE
Google places search cost cannot be controlled

### ISSUE THREAD

**Issue by maximilientyc** [alexreisner/geocoder#1460]
Google has an API endpoint for its Place search services which allows you to control which fields are going to be available in the response. Using this restriction allows you to control the price of API calls made to the Places API.

This gem uses the [Text search requests](https://developers.google.com/places/web-service/search#TextSearchRequests) for the `google_places_search` component. Here is what Google is saying about this endpoint: 

```
Nearby Search and Text Search return all of the available data fields for the selected place 
(a subset of the supported fields), and you will be billed accordingly.
There is no way to constrain Nearby Search or Text Search to only return specific fields. 
To keep from requesting (and paying for) data that you don't need, use a Find Place request instead.
```

I would suggest we migrate to using the [Find place requests](https://developers.google.com/places/web-service/search#FindPlaceRequests) endpoint, so we can specify which data we want to have in the response given by Google, and as a consequence only pay for what we need.

**Behavior proposal**

The component should request for the following parameters to be included in the response: `business_status, formatted_address, geometry, icon,name, permanently_closed, photos, place_id, plus_code, types`. This will exclude fields coming from `Atmosphere Data` and `Contact Data`.

You need to be able to override the default values for the `fields` param, by giving for example: `formatted_address,open_now` which combines data coming from `Basic Data` and `Contact Data`.

For the detailed pricing visit this page: https://cloud.google.com/maps-platform/pricing/sheet/?_ga=2.64143597.318188449.1594045771-1706466804.1555340798

**Comment by alexreisner** [comment]
Thanks, and yes, I agree with this approach. Definitely open to a pull request.

**Comment by maximilientyc** [comment]
I’m going to start working on something, will keep you updated using this thread 👌

**Comment by maximilientyc** [comment]
is being fixed through: https://github.com/alexreisner/geocoder/pull/1461

**Comment by zjwhitehead** [comment]
This is nice and flexible. We did a more hardcoded approach originally 
https://github.com/rvshare/geocoder/commit/3e6273afceb1535718e08955df379c94efa747ef#diff-5a1e50427808e6aade11666cf82b1dceR7

**Comment by alexreisner** [comment]
Yes, thanks again for the good work @maximilientyc!
