### ISSUE TITLE
use the same geocoding "service" twice?

### ISSUE THREAD

**Issue by j-ro** [alexreisner/geocoder#1467]
This is probably more of a help question than a bug report, but is it possible to use the same geocoding "service" twice?

I am woking with two different external geocoding services, which will be used in different circumstances in the app, both of which conform to the pelias standard for their API. Ideally I'd be able to do something like in the configuration file:

```
:first_geocoder => { :service => :pelias, :endpoint => endpoint1, :api_key => 'mykey1' , :use_https => true}
:second_geocoder => { :service => :pelias, :endpoint => endpoint2, :api_key => 'mykey2' , :use_https => true}
```

Is there a way to accomplish this?

**Comment by pdobb** [comment]
@j-ro As always, you should write an adapter class in your local code that abstracts the specifics of any 3rd-party service -- such as geocoding -- you're using. Then you can also do things like have that adapter use 2 different services behind the scenes, or whatever. Here's a simple example of just using one service (this one). It uses the singleton pattern to ensure only one instance is ever created, but that's just a development detail. Take it or leave it.

```ruby
class MyGeocoder
  include Singleton

  def self.init
    if disable_api_lookup?
      NullGeocoder.instance
    else
      instance
    end
  end

  def self.disable_api_lookup?
    Rails.env.test?
  end

  # Look up the coordinates of the given street or IP address.
  def coordinates(address, **options)
    ::Geocoder.coordinates(address, **options)
  end
end

class NullGeocoder
  include Singleton

  def coordinates(*)
    []
  end
end
```

Then call it with:
```ruby
$ MyGeocoder.init.coordinates("123 Main St, New York, NY")
```

**Comment by j-ro** [comment]
Thanks for the suggestion @pdobb! I'll see if I can adapt for our use case!
