### ISSUE TITLE
ESRI API Gives 400 Bad request

### ISSUE THREAD

**Issue by cubones-momma** [alexreisner/geocoder#1468]
BEFORE POSTING AN ISSUE, PLEASE MAKE SURE THE PROBLEM IS NOT ADDRESSED IN THE README!

### Expected behavior

When giving an address to search, get search results back

### Actual behavior

400 Bad Request

### Steps to reproduce

Give any address to the Geocoder.search method

### Environment info

* Geocoder version: 1.4.4
* Rails version: 5.2
* Database (if applicable): 
* Lookup (if applicable): 

Also while trying other API's such as nominatim looks like they also give bad results. Perhaps they need to be updated?

**Comment by alexreisner** [comment]
This looks specific to ESRI and I believe the problem is that they stopped accepting HTTP requests. You should be able to use it by using HTTPS:

    Geocoder.configure(lookup: :esri, use_https: true)

I will remove the HTTP option from the ESRI lookup. Thanks for reporting this!
