### ISSUE TITLE
Logging - enabled by default, or at least document

### ISSUE THREAD

**Issue by richardonrails** [alexreisner/geocoder#1477]
Took me a bit to figure out to add `logger: Rails.logger` to the geocoder.rb config file since it was undocumented.
I was thinking that by default, this project should do some logging similar to how Rails itself logs database queries by default.

**Comment by alexreisner** [comment]
I understand that this isn't obvious. However, the gem needs to work outside of Rails so we shouldn't add any defaults that will cause errors in a generic context. This might be best addressed by adding a note about `Rails.logger` in the README.
