### ISSUE TITLE
Accuracy and Margin Of Error On: Geocoder::Calculations

### ISSUE THREAD

**Issue by interpegasus** [alexreisner/geocoder#1487]
### Expected behavior
I would expect having a small margin of error.

### Actual behavior
When computing the latitude and longitude going forward and then backwards to a point C between A and B, the results are different. I was expecting to get less margin of error.

### Steps to reproduce
1. Let A,B be two locations. And C a point between A,B:    A---------C----------B

**Distance A-B** = 72.61192668985049
**Distance A-C** = 45.55846074230942 
**Distance C-B** = 27.05346594754107

**Location A**: latitude: "42.352613334156665", longitude: "-71.07107332742494"
**Location B**: latitude: "42.35322666751383", longitude: "-71.07137666076997"
**degrees**: 333.69 
**degrees_backwards**: (333.69 + 180) % 360 = 153.69000000000005

**Geocoder::Calculations**
```
live_virtual_location_forward = Geocoder::Calculations.endpoint([42.352613334156665, -71.07107332742494], heading=333.69 , 45.55846074230942/1000, {units: :km})
live_virtual_location_backward = Geocoder::Calculations.endpoint([42.35322666751383, -71.07137666076997], heading=153.69000000000005, 27.05346594754107/1000, {units: :km})

# Margin Error: I would expect the margin_of_error to be close to 0 ideally. And also I would expect the value of -
# live_virtual_location_forward to be equal to live_virtual_location_backward.

#  margin_error = 7.895626311482931 m
margin_error =distance_in_meters(live_virtual_location_forward, live_virtual_location_backward) 


  def distance_in_meters(c1, c2)
    return Geocoder::Calculations.distance_between(c1, c2, {units: :km}) * 1000
  end
```
### Environment info

* Geocoder version: geocoder (1.6.4)
* Rails version: 6
* Database (if applicable): Mongoid
* Lookup (if applicable): NA

**Comment by alexreisner** [comment]
The short answer is that there are a lot of different methods for calculating distance along the surface of a planet. The more accurate the method, the more complex the code. Geocoder uses the [Haversine formula](https://en.wikipedia.org/wiki/Haversine_formula), which uses relatively simple code but assumes the Earth is a sphere, which isn't quite right. So there will be some error in distance calculations. If you need a smaller margin of error than 7 meters over a distance of 72 kilometers you probably need to implement a more precise distance formula (eg, [Vincenty's](https://en.wikipedia.org/wiki/Vincenty%27s_formulae)).
