### ISSUE TITLE
Issue when merging on geocoded models

### ISSUE THREAD

**Issue by bradherman** [alexreisner/geocoder#1489]
### Expected behavior

I extracted our users data into a location object so I can independently update/retrieve locations without invalidating caches or serializing whole User records when updating maps.  I created a `Location` model that just holds `latitude` and `longitude`.  When merging `Location` with `User` like this:  `User.where(...).joins(:location).merge(Location.all)`, we see an `ActiveRecord_Relation` of `Users` as expected.  When merging using the `Location.near` query, we would expect the same.

```
[#<User:0x00007fd8a352b858
  id: "3dfcebd5-c63d-4a37-b818-c5fc9f8a9a9e",
  email: "email@email.com",
  auth_tokens: [],
  unconfirmed_email: nil,
  ...
```

### Actual behavior

However when merging against the `Location.near` query, we actually get `User` records with no `id` and only `latitude` and `longitude`:

```
#<User:0x00007fd88d23fe70
  id: nil,
  latitude: 0.3777587e2,
  longitude: -0.12245316e3,
  created_at: Tue, 09 Feb 2021 01:22:52 UTC +00:00,
  updated_at: Tue, 09 Feb 2021 01:22:52 UTC +00:00>,
```

### Steps to reproduce

Create a `User` model and a `Location` model belonging to `User`.  Query `User.anything.joins(:location).merge(Location.anything)`, then query `User.anything.joins(:location).merge(Location.near(address))`

### Environment info

* Geocoder version: 1.6.4
* Rails version: 6.0.3.4
* Database (if applicable): Postgresql

**Comment by alexreisner** [comment]
So, I think this is partially explained in [the README](https://github.com/alexreisner/geocoder#activerecord): "Because the SELECT clause is modified [by the `near` scope], anything else that modifies the SELECT clause may produce strange results." I think in your case you will need to manually specify which User attributes you want to select, and make sure the `near` scope isn't overriding those attributes. Does that make sense?

**Comment by bradherman** [comment]
Ahh yeah I think so.  I figured it had something to do with that, but wasn't quite sure.  Thanks!  Will give it a shot and report back

**Comment by bradherman** [comment]
Update:  Modifying the query to `User.where(...).joins(:location).merge(Location.new(@geocoded_object)).select(*User.column_names)` works... Note that the `select` needs to go at the end, otherwise it drops the `id` column for some reason

**Comment by bradherman** [comment]
Now just need to figure out how I can sort the drivers by the distance from the location join and I'm all set :+1:

**Comment by alexreisner** [comment]
OK, great. I'm glad that helped.
