### ISSUE TITLE
Geocoder Fail on Cache Fail

### ISSUE THREAD

**Issue by prattprattpratt** [alexreisner/geocoder#1491]
BEFORE POSTING AN ISSUE, PLEASE MAKE SURE THE PROBLEM IS NOT ADDRESSED IN THE README!

### Expected behavior
Geocoder to work even if cache fails.

### Actual behavior
If cache fails, Geocoder fails.

### Steps to reproduce
1. Configure Geocoder with invalid cache - e.g., cache: Redis.new(url: 'redis://foo@cod.redisfoogo.com:11433/')
2. Try to geocode - Geocoder.coordinates('New York City, New York, USA')
3. Watch it burn

### Environment info

* Geocoder version: 1.6.3
* Rails version: 5.2.4.2
* Database (if applicable): 
* Lookup (if applicable): google

**Comment by prattprattpratt** [comment]
Redistogo had some scheduled maintenance last week and during those 10 minutes, the search functionality on our site was down. As a workaround, I'm implementing the cache on my own (setting Geocoder.configure.cache to nil). It was convenient to use the built-in cache though! I'd love to be able to use it again.

**Comment by lime** [comment]
Would skipping the cache in case of failure be a reasonable default? Caching bugs are difficult to debug in general, I wonder whether silent failures would make it harder for people to get the config right. Well, maybe not entirely silent, a logged warning helps of course.

I can absolutely see how the typical user would prioritize availability over performance, in which case skipping the cache is reasonable. At the same time, API query limits might make that tradeoff look a bit different.

**Comment by lime** [comment]
Personally, I'm an avid fan of using [Moneta](https://github.com/moneta-rb/moneta) to get full control over how a particular cache behaves. Here, the `Moneta::Fallback` middleware would probably do what you need.

For the typical user of course, using a plain `Redis.new`, `Hash.new` etc. should have the reasonable default behaviour, whichever that's determined to be.

**Comment by alexreisner** [comment]
For purposes of discussion, I just pushed [a branch](https://github.com/alexreisner/geocoder/tree/rescue_from_cache_error) with the simplest possible solution.

@lime I agree with your thoughts: I think this solution could make cache configuration harder. I'm certainly not committed to it.

@prattprattpratt Thanks for reporting this. You can try out the solution by using this in your Gemfile: `gem 'geocoder', git: 'git://github.com/alexreisner/geocoder.git', branch: 'rescue_from_cache_error'`

**Comment by lime** [comment]
I gave your branch a try out of curiosity, and I'd say it actually feels like pretty reasonable behaviour.

```ruby
> require "geocoder";
> require "redis";
> Geocoder.configure(cache: Redis.new(url: "redis://invalid.test"));
> Geocoder.coordinates('New York City, New York, USA')
Geocoder cache read error: Error connecting to Redis on invalid.test:6379 (SocketError)
Geocoder cache write error: Error connecting to Redis on invalid.test:6379 (SocketError)
=> [40.7127281, -74.0060152]
```

Intermittent cache errors would pass without breaking functionality, while still leaving some sort of trace. If you mess up the config on your first attempt, you're likely to notice the warnings at one point or another.

And I guess you could argue the case both ways, that those who _really_ depend on the cache to avoid hitting API limits or the like are the ones who should customize their cache to do exactly what they want. Even then, they probably don't want _breakage_, and are better served by setting up a in-memory cache or other fallback around the Redis connection.

**Comment by alexreisner** [comment]
Thanks @lime. And I agree. It's not an ideal solution but I think it's better than the current behavior. I think I'm going to merge and close this issue. But if anyone wants to discuss or code up a more sophisticated approach to this problem I'm open to discussing it.

**Comment by alexreisner** [comment]
Also @prattprattpratt I'm curious what you ended up doing, and whether this patch is sufficient for your needs.

**Comment by alexreisner** [comment]
For reference, since the branch no longer exists, here's the relevant commit: cad79309f888f46e92dc91d5cdf54c4ec5f8c142

**Comment by prattprattpratt** [comment]
@alexreisner 
I ended up using a global variable 🤷‍♂️ so this: `Geocoder::Lookup.get(:google).cache&.[]=` became this:  `$redis_geocode_cache&.[]=`
Just tried using that commit and it worked perfectly for my needs. What are the odds of that getting released?

**Comment by alexreisner** [comment]
@prattprattpratt thanks for reporting back. New gem version was actually released just now.

**Comment by prattprattpratt** [comment]
Thanks @alexreisner!
