### ISSUE TITLE
Self-hosting is broken (for osmnames, at least, because `:host` config is ignored)

### ISSUE THREAD

**Issue by entrity** [alexreisner/geocoder#1507]
~BEFORE POSTING AN ISSUE, PLEASE MAKE SURE THE PROBLEM IS NOT ADDRESSED IN THE README!~ Done

### Expected behavior
Specifying a `:host` in `Geocoder.configure(...)` should result in an instance of `Geocoder::Lookup::Osmnames` making requests to the given host instead of to `'geocoder.tilehosting.com'`. 

Indeed, the documentation at https://github.com/alexreisner/geocoder/blob/master/README_API_GUIDE.md#osm-names-osmnames states:

> To use self-hosted service, set the `:host` option in Geocoder.configure.

### Actual behavior
Api requests still go to `'geocoder.tilehosting.com'`.

Indeed, if you look at the the definition of `Geocoder.config_for_lookup` (`geocoder-1.6.7/lib/geocoder/configuration.rb`), you'll see the following, which throws away the `:host` specification because it's not in `Geocoder::Configuration::OPTIONS`.

```ruby
def self.config_for_lookup(lookup_name)
  data = config.clone
  data.reject!{ |key,value| !Configuration::OPTIONS.include?(key) }
  if config.has_key?(lookup_name)
    data.merge!(config[lookup_name])
  end
  data
end
```

### Steps to reproduce
In a Rails project, `rails generate geocoder:config`, then modify the file generated at `config/initializers/geocoder.rb` to read:

```ruby
Geocoder.configure(
  lookup: :osmnames,
  host: 'localhost:8888',
  key: '',
)
```

Then in the rails console, run:
```ruby
puts Geocoder::Configuration.instance.data[:host] # Verify that `:host` IS present and speciried as `localhost:8888`
puts Geocoder.config_for_lookup(:osmnames) # Verify that `:host` is not one of the keys
puts Geocoder::Configuration::OPTIONS # Verify that `:host` is not in the list
Geocoder.search [24.7763, 121.02] # It should be apparent that this didn't go to localhost:8888
```

### Environment info

* Geocoder version: 1.6.7
* Rails version: 6.1.3
* Database (if applicable): 
* Lookup (if applicable): osmnames

**Comment by alexreisner** [comment]
What a clear and complete issue report! Thanks very much. Just fixed.
