### ISSUE TITLE
Support for Amazon Location Service

### ISSUE THREAD

**Issue by mplewis** [alexreisner/geocoder#1511]
AWS recently launched [Amazon Location Service](https://aws.amazon.com/location/) which provides geocoding and reverse geocoding.

I would be happy to try and implement the Amazon client for Geocoder. Are you interested in adding support for Amazon Location Service?

**Comment by alexreisner** [comment]
Yes, definitely open to a PR for adding ALS.

**Comment by alexreisner** [comment]
#1509 is a good example for adding a new lookup.

**Comment by mplewis** [comment]
Sounds great. I'll open a PR linked to this issue.
