### ISSUE TITLE
Geocoder::ConfigurationError (Please specify a valid lookup for Geocoder (:amazon_location_service is not one of

### ISSUE THREAD

**Issue by khalidMahmod** [alexreisner/geocoder#1527]
BEFORE POSTING AN ISSUE, PLEASE MAKE SURE THE PROBLEM IS NOT ADDRESSED IN THE README!

### Expected behavior
Geocoder Should Work

### Actual behavior
Getting Error: Geocoder::ConfigurationError (Please specify a valid lookup for Geocoder (:amazon_location_service is not one of: :location_iq, :dstk, :esri, :google, :google_premier, :google_places_details, :google_places_search, :bing, :geocoder_ca, :yandex, :nationaal_georegister_nl, :nominatim, :mapbox, :mapquest, :uk_ordnance_survey_names, :opencagedata, :pelias, :pickpoint, :here, :baidu, :tencent, :geocodio, :smarty_streets, :postcode_anywhere_uk, :postcodes_io, :geoportail_lu, :ban_data_gouv_fr, :test, :latlon, :amap, :osmnames, :baidu_ip, :abstract_api, :freegeoip, :geoip2, :maxmind, :maxmind_local, :telize, :pointpin, :maxmind_geoip2, :ipinfo_io, :ipregistry, :ipapi_com, :ipdata_co, :db_ip_com, :ipstack, :ip2location, :ipgeolocation).)

### Steps to reproduce
# config/initializers/geocoder.rb

Geocoder.configure(
    lookup: :amazon_location_service,
    amazon_location_service: {
        index_name: '###',
        api_key: {
            access_key_id: '###',
            secret_access_key: '###',
        }
    }
)

### Environment info

* Geocoder version: 1.6.7
* Rails version: 6.1.4
* Database (if applicable): Postgres
* Lookup (if applicable): amazon_location_service

**Comment by alexreisner** [comment]
Sorry about that. The README seen on Github is for the current HEAD. The `:amazon_location_service` lookup was just added and will be available in the next gem version (coming very soon).
