### ISSUE TITLE
SSL certificate has expired

### ISSUE THREAD

**Issue by vanboom** [alexreisner/geocoder#1529]
We are using ipinfo_io for reverse geocoding.  Today we are receiving an error 

```
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired))
```

The SSL cert for our application is current and valid.  But it seems somewhere in the chain the app is attempting to validate against an old expired certificate. 

ipinfo_io calls using curl from the command line work fine: 
```
curl https://ipinfo.io/8.8.8.8/city
Mountain View
```

But the error occurs when `reverse_geocode` is called from within the app.  Any advice would be greatly appreciated.  Thanks for a great gem!

**Comment by emilianodellacasa** [comment]
I can confirm the problem on my application too

**Comment by willtcarey** [comment]
In our application it doesn't actually seem to be happing with ipinfo.io. It looks like it's the default street address lookup, nominatim. Here's a chunk of code which will reproduce the issue.

```ruby
uri = URI.parse("https://nominatim.openstreetmap.org")
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.get(uri.request_uri)
```

**Comment by willtcarey** [comment]
The issue that we've narrowed this down to is our server's `ca-certificates` package being out of date. Running an update on that package makes the geocoder calls successful.
```
yum update ca-certificates # Our server is CentOS. Should be a similar package for apk/apt-get
bin/rails c
Model.first.geocode # This call is now successful.
```

**Comment by vanboom** [comment]
@wiltcarey - thank you!  Our server is Ubuntu 16.04 and may be affected by this: https://ubuntu.com/security/notices/USN-5089-1

Still researching - but with the older OS version, a simple `sudo update-ca-certficates` does not resolve the issue.  

Our 20.04 servers do not have this issue.

**Comment by vanboom** [comment]
To fix on Ubuntu 16.04, related to https://ubuntu.com/security/notices/USN-5089-1

1. Edit /etc/ca-certificats.conf
2. Comment out the line pertaining to DST_Root_CA_X3
3. Run `update-ca-certificates`
Note that the offending cert has been removed...

```Updating certificates in /etc/ssl/certs...
0 added, 1 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```

Many thanks to @willtcarey for pointing us in the cert direction!

**Comment by alexreisner** [comment]
Thanks @vanboom and @willtcarey for posting your solutions!

**Comment by alexreisner** [comment]
@ilasno Good question. This exception isn't caught because I haven't encountered it before! I'd be open to a pull request that rescued from this exception and printed some useful advice (like what's been posted above).

**Comment by Nowaker** [comment]
`OpenSSL::SSL::SSLError` means Geocoder is running in a very old environment that is missing the latest CA certificates OR is running an outdated version of OpenSSL. One or the other will trigger the error. Connecting to any HTTPS endpoint with a cert issued by Let's Encrypt will trigger the same error. Any HTTP client is affected equally - not just Geocoder. A possible workaround for that is `OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE` in initializers.

Based on the above, I believe this is not a Geocoder issue. But we can sure offer some accommodations to workaround the issue but they should be optional (default off). Along with, if verify is enabled (default), it should still rescue a potential `OpenSSL::SSL::SSLError`, and raise a Geocoder exception with a friendly error like `TLS verification error. This may be caused by old CA certs or outdated OpenSSL version. Please upgrade your system or workaround by disabling TLS verify with Geocoder.configure(verify: OpenSSL::SSL::VERIFY_NONE)`.

**Comment by ilasno** [comment]
Wow, really appreciate the quick and thoughtful responses on this @Nowaker @alexreisner . My $.02:

While probably rare, isn't it true that `OpenSSL::SSL::SSLError `could also occur if the _geocoding provider_'s certificate has expired?  If so, this would still not be a Geocoder issue, but it may then fall into the 'not resolvable by a developer' category.  Admittedly, 'it sometimes indicates action required by a developer' remains true, though.

As a developer, i'd agree with 'rescuing and re-raising an error with a helpful message, but not in favor of adding the config option'.

That just leaves my (perhaps newbish) question: How would i 'enclose your geocoding in a rescue block' if the geocoding is triggered by:
`geocoded_by :address_for_geocoding`
in my model? I don't see an explicit call to 'geocode' that i can wrap in a rescue block.

**Comment by dylanbromby** [comment]
Not to split hairs, but @vanboom states you should comment the cert reference but you actually need to deselect it.

This:

`!mozilla/DST_Root_CA_X3.crt`

Not this:

`#mozilla/DST_Root_CA_X3.crt`

So:

1.  `vi /etc/ca-certificates.conf`
2. Deselect DST_Root_CA_X3
3. `update-ca-certificates`

This fixed the issue for us on Ubuntu 16.04. And for those running Docker, remember to update `/etc/ca-certificates.conf` in your container vs. your host 😉 .

**Comment by vanboom** [comment]
@dylanbromby you are correct - apologies for the typo ;)

**Comment by basicfeatures** [comment]
Unfortunately having the same problem: https://gist.github.com/basicfeatures/90c861bf9e8ee89f888d439f4cb9cbfe - any clues?

**Comment by dylanbromby** [comment]
> Unfortunately having the same problem: https://gist.github.com/basicfeatures/90c861bf9e8ee89f888d439f4cb9cbfe - any clues?

Have you tried the steps in my post above?

**Comment by MrGurns** [comment]
@basicfeatures You might need to restart your passenger/apache/nginx.
Worked for me once i restarted passenger.

**Comment by basicfeatures** [comment]
@dylanbromby @MrGurns Hi! I run OpenBSD which has its own rewrite of OpenSSL (LibreSSL). Turned out I was running a slightly older release of OpenBSD and a simple upgrade took care of the problem 👍 Thanks guys!
