### ISSUE TITLE
Rails 7 compatibility

### ISSUE THREAD

**Issue by duarme** [alexreisner/geocoder#1537]
Hello there, we've been using this glorious gem since Rails 4. We're now upgrading to Rails 7 and we noticed that it's not supported yet. Is there already work in progress to support it, or are you waiting for contributions? 🙂

**Comment by alexreisner** [comment]
Hello, and thanks for bringing this up. No work (that I'm aware of) has been done for Rails 7 yet. This might be a good place to start building a to-do list.

**Comment by izaguirrejoe** [comment]
@duarme Curious, what about geocoder doesn't work right now in Rails 7? Currently using it in a Rails 7 app but only for near queries on the database. Thinking of using it for IP Address geolocating, but now I'm hesitant.

**Comment by alexreisner** [comment]
I'm not aware of any issues using Geocoder with Rails 7. If anyone has specific problems, please create issues for them. I'm going to close this (and update the README).
