### ISSUE TITLE
Adding Expiration date through cache_options results in a TTL of -1 in Redis Cache

### ISSUE THREAD

**Issue by nzraad** [alexreisner/geocoder#1559]
Adding Expiration date through `cache_options` results in a TTL of -1, versus following the example below actually adds the correct TTL. https://github.com/alexreisner/geocoder/blob/934a5a9782bc1407dd64dc6dfb9f67bb89936156/examples/autoexpire_cache_redis.rb#L6-L30

### Expected behavior
According to the [documentation](https://github.com/alexreisner/geocoder#geocoding-service-lookup-configuration), you could add the expiration to the cache options in the geocoder initializer.

```rb
# config/initializers/geocoder.rb
Geocoder.configure(
  cache: Redis.new,
  cache_options: {
    expiration: 2.days, # Redis ttl
  }
)
```

### Actual behavior
Following the configuration above will result in a TTL in Redis as -1

### Steps to reproduce
1. In geocoder initializers, add expiration in `cache_options`.
```rb
# config/initializers/geocoder.rb
Geocoder.configure(
  cache: Redis.new,
  cache_options: {
    expiration: 2.days, # Redis ttl
  }
)
```
2. Trigger geocoder on an API request.
3. Check Redis for new cached API Request.
4. TTL is showing -1.
![CleanShot 2022-01-10 at 09 48 48@2x](https://user-images.githubusercontent.com/10695827/148795541-958b7f0c-c536-4d68-a8af-c09ea4adf148.png)

### Environment info

* Geocoder version: `1.6.3` & `1.7.2`
* Rails version: Ruby `2.7.4` & Rails `6.1.4.3`
* Database (if applicable): through Docker
<img width="781" alt="CleanShot 2022-01-10 at 09 54 06@2x" src="https://user-images.githubusercontent.com/10695827/148796307-9d5c7608-16b0-492e-bf21-5e306d51deb0.png">

* Lookup (if applicable): `ipinfo` (Paid API Key)

**Comment by alexreisner** [comment]
Thanks for reporting this. I'll get back to you as soon as I have a chance to investigate. (@shqear93 any ideas?)

**Comment by nzraad** [comment]
Also, our current implementation allows us to add TTL into Redis is as follows:
```rb
class AutoExpireCache
  def initialize(store, ttl = 1.day)
    @store = store
    @ttl = ttl
  end

  def [](url)
    @store.read(url)
  end

  def []=(url, value)
    @store.write(url, value, expires_in: @ttl)
  end

  def expire
    @store.expire
  end
end

Geocoder.configure(
  ip_lookup: :ipinfo_io,   
  api_key: ##############,
  cache: AutoExpireCache.new(Rails.cache)
)
```

**Comment by alexreisner** [comment]
Hmm, I think #1532 made the caching examples obsolete. We should probably remove those.

**Comment by shqear93** [comment]
@nzraad actually I did the same steps you mentioned, and I have it was working fine, the newly created redis record had the correct TTL, and I double checked the code from `master` branch and the TTL was actually arriving to Redis service

**Comment by shqear93** [comment]
@nzraad I think you triggered the link first time without expiration config, then you added the expiration to the initializer, in this case it won't update the current record in redis so you have to remove it from redis first and try again, please try and let me know if it worked

**Comment by nzraad** [comment]
Okay, looking into it more, it appears using `Rails.cache` is the reason it does not add the TTL key correctly. I will keep testing it out to see if that is the only configuration issue that is not allowing it to pass the TTL.

**Comment by shqear93** [comment]
@nzraad I think we should close this if you figure it out
