### ISSUE TITLE
geocoder 1.7.4 broken

### ISSUE THREAD

**Issue by ollym** [alexreisner/geocoder#1568]
https://github.com/alexreisner/geocoder/commit/c32da2ed4499976c48cf23cb9bb7b951b6852757

Released in geocoder 1.7.4 just broke our app.

We happen to have a top level class called `Google` totally unrelated to geocoder, and also

```ruby
Geocoder.configure(
  lookup: :google
)
```

So tell me - how do I after this patch how do i make sure it picks the `Google` geocoder module instead?

**Comment by ollym** [comment]
The short term fix is to do this in your initialiser:

```ruby
require 'geocoder/lookups/google'

Geocoder.configure(
  lookup: :google
)
```

**Comment by ollym** [comment]
@januszm yes, this is using Rails w/ Zeitwerk

The problem is `Geocoder::Lookup.const_get('Google')` will discover `::Google` if it's defined (which it is in my case) because `require "geocoder/lookups/google"` is no longer being called first.

I suggest you change this

```ruby
def lookup_instance_from(name)
  class_name = classify_name(name)
  begin
    Geocoder::Lookup.const_get(class_name)
  rescue NameError
    require "geocoder/lookups/#{name}"
  end
  Geocoder::Lookup.const_get(class_name).new
end
```

To this:

```ruby
def lookup_instance_from(name)
  class_name = classify_name(name)
  begin
    require "geocoder/lookups/#{name}"
  rescue LoadError
  end
  Geocoder::Lookup.const_get(class_name).new
end
```

**Comment by januszm** [comment]
@ollym  could you please paste the exact error message you're getting?

I could not reproduce this on Rails 7 application with Zeitwerk. I defined an almost empty `Google` class, put `Geocoder.configure(lookup: :google)` and everything went well, I could use both the Geocoder and the Google class.

**Comment by ollym** [comment]
```
NoMethodError
undefined method `new' for Google:Module Geocoder::Lookup.const_get(class_name).new
```

Google in our case is already defined by `google-cloud-trace` gem

**Comment by ollym** [comment]
@januszm @alexreisner Something simple to reproduce it:

```ruby
require 'geocoder'

module Google
end

Geocoder.search('Some Address', lookup: :google)
```

**Comment by januszm** [comment]
So in your case `Google` is a module. I still can't reproduce this, with the debugger inside the gem code:

```ruby
> Geocoder.search('Some Address', lookup: :google)

From: /lib/geocoder/lookup.rb:142 Geocoder::Lookup#instantiate_lookup:

    138: def instantiate_lookup(name)
    139:   class_name = classify_name(name)
    140:   binding.pry
    141:   begin
 => 142:     Geocoder::Lookup.const_get(class_name)
    143:   rescue NameError
    144:     require "geocoder/lookups/#{name}"
    145:   end
    146:   Geocoder::Lookup.const_get(class_name).new
    147: end

> class_name
=> "Google"
```

This could be a problem if we used `Object.const_get`, but since we're already calling this method from Geocoder, it resolves correctly:

```ruby
> Object.const_get("Google")
=> Google

> Geocoder::Lookup.const_get("Google")
=> Geocoder::Lookup::Google
```

Perhaps we should prepend `Geocoder::Lookup::` to the `class_name` variable when we const_get it.
 I'll give it another try later today.

**Comment by januszm** [comment]
@ollym  I was able to reproduce it in `development` environment, with eager loading off. It works fine in production or with eager_load true.

**Comment by januszm** [comment]
Indeed. We have several options, including requiring all predefined lookups, but I guess there was a reason we only spawn what's necessary, so this should do the trick:

```ruby
def instantiate_lookup(name)
  class_name = "Geocoder::Lookup::#{classify_name(name)}"

  require "geocoder/lookups/#{name}" unless defined?(class_name)
  Geocoder::Lookup.const_get(class_name).new
end
```

It would be great to have a test case with a "Dummy" application where we could define at least one module with a name conflict with one of the lookups, but at the moment I don't have enough time to do such a test.

**Comment by alexreisner** [comment]
Thanks @januszm! I just merged your PR and will release a new gem version within the hour.
