### ISSUE TITLE
ActionView::Template::Error (undefined method `i18n_scope' for Geocoder::Store::ActiveRecord:Module):

### ISSUE THREAD

**Issue by MtnBiker** [alexreisner/geocoder#1573]
This is more of a heads up, because I imagine the cause is elsewhere based on some comments I found trying to sort this out.

### Expected behavior

Page loads

### Actual behavior

Error showing up at Heroku in logs and page doesn't load.

`ActionView::Template::Error (undefined method `i18n_scope' for Geocoder::Store::ActiveRecord:Module):`

### Steps to reproduce

Nothing to do with geocoder on the page and other pages load. I had a similar error for simple_form and had to add `  config.i18n_scope = 'simple_form'` to config (well I just had to uncomment it. A SWAG since that was where I found `config.i18n_scope` 

### Environment info

* Geocoder version:  geocoder (1.7.5)
* Rails version:  rails (6.0.4.7)
* Database (if applicable): pg
* Lookup (if applicable):

**Comment by alexreisner** [comment]
@MtnBiker did you ever figure out the cause of this error?
