### ISSUE TITLE
Question about autoexpire cache

### ISSUE THREAD

**Issue by olimart** [alexreisner/geocoder#1603]
Hi,
The Readme points to `examples/autoexpire_cache.rb` but this file no longer exists.
So, I think the mention should be removed/updated.
https://github.com/alexreisner/geocoder/blob/master/README.md?plain=1#L379

However, I'm interested about options to implement auto expiry.
Is there a new way of doing this?

**Comment by alexreisner** [comment]
Good catch, thanks for raising this. The recommended way of auto-expiring is now to let the cache store handle it. You can do this via the `:cache_options[:expiration]` config key, as shown in [the lookup config section of the README](https://github.com/alexreisner/geocoder#geocoding-service-lookup-configuration). But I agree that this could be mentioned explicitly in place of the current reference to deleted example.

**Comment by olimart** [comment]
@alexreisner Thanks for the reply.
Also, is the `Geocoder::CacheBypass` class something we can rely on.
https://github.com/alexreisner/geocoder/blob/master/examples/cache_bypass.rb

It seems we need to bring it over our app codebase given it does not seem to be part of the gem. Unless there is another option (I'm interested to NOT raise exception if cache is not available).

**Comment by alexreisner** [comment]
Yes, that class will allow you to suppress cache exceptions, and you'll have to copy it into your app to use it.

**Comment by olimart** [comment]
Thank you 🙏
