### ISSUE TITLE
Tests are running on Ruby 2.7, which is end-of-life

### ISSUE THREAD

**Issue by carlwiedemann** [alexreisner/geocoder#1612]
The GitHub action added in https://github.com/alexreisner/geocoder/pull/1581 is only running tests on Ruby 2.7.

Ruby 2.7 is end-of-life as of this month, and Ruby 3.x has been stable for over 2 years.

The gemspec file declares this Gem to be compatible with any version of Ruby >= 2.0.0.

It seems to me that the GitHub action should use a matrix build strategy on all currently supported stable versions of Ruby, i.e. 3.0, 3.1, and 3.2.

Keeping 2.7 in the matrix is probably fine since there are many people who still aren't on 3.x yet.

I'll plan to open a PR for this unless there are any objections.

**Comment by alexreisner** [comment]
No objections to a PR for that. Thank you.

**Comment by carlwiedemann** [comment]
Opened https://github.com/alexreisner/geocoder/pull/1615

**Comment by alexreisner** [comment]
Addressed by #1624
