### ISSUE TITLE
Intermittent issue with Geocoder.search API

### ISSUE THREAD

**Issue by sgmamsys** [alexreisner/geocoder#1640]
BEFORE POSTING AN ISSUE, PLEASE MAKE SURE THE PROBLEM IS NOT ADDRESSED IN THE README!

### Expected behavior
I am taking a random IP address
Geocoder.search("103.164.199.142")[0].data["timezone"]  = "Asia/Kolkata"

### Actual behavior

Geocoder.search("103.164.199.142")[0].data["timezone"] = Geocoding API's response was not valid JSON

### Steps to reproduce

This issue is occuring randomly since yesterday.

### Environment info

* Geocoder version:  1.6.7
* Rails version: 
* Database (if applicable): 
* Lookup (if applicable):

**Comment by alexreisner** [comment]
There seems to be an intermittent issue with the Ipinfo.io service. You might want to try using [a different IP lookup](https://github.com/alexreisner/geocoder/blob/master/README_API_GUIDE.md#ip-address-lookups). If problems with Ipinfo.io get worse, we could consider changing the default IP address lookup, but I'm not ready to do that yet.
