### ISSUE TITLE
Links for Data Science Toolkit (:dstk) are broken

### ISSUE THREAD

**Issue by mokolabs** [alexreisner/geocoder#1641]
### Expected behavior
The links for Data Science Toolkit (:dstk) should be online.

### Actual behavior
The links for Data Science Toolkit (:dstk) are offline and appear to have been offline for at least two years.

### Steps to reproduce
Click on links in README_API_GUIDE.md

### Suggested fix
Replace offline links with direct links to the Data Science Toolkit on GitHub.

**Comment by alexreisner** [comment]
Thanks! I agree with this in principle, however I can't find any evidence that the online API is operational anymore. The domain seems to be down. It can run as a self-hosted service too. I'm wondering if it should be listed as self-hosted only. What's the GitHub link you have in mind?

**Comment by alexreisner** [comment]
As far as I can tell, this lookup is defunct. Removed in 7318823ea51043fe8f2d60ada42a7a61f0550f5b.
