### ISSUE TITLE
Pass the session token to Google Place Details API

### ISSUE THREAD

**Issue by calebeso** [alexreisner/geocoder#1650]
### Expected behavior
Make possible to pass the token session as an extra parameter to the `:google_places_details` provider

I actually did not find any information about the session token parameter in the docs, how can I use with lookup? 

I actually tried this way: `lookup.search(params[:placeid], params: { sessiontoken: params[:session_token])`, but I'm not sure if its working since I tried this way to pass the `fields` parameter and keep returning all the fields. 

Same for the configuration file: 

`    fields: %w[address_components adr_address formatted_address geometry place_id]`

Anyone ever faced the same behaviour?

**Comment by alexreisner** [comment]
Sorry, I'm not sure I understand this question. Can you explain what you're trying to achieve?
