### ISSUE TITLE
NoMethodError: private method `archive_edition' called for Geocoder::MaxmindDatabase:Module

### ISSUE THREAD

**Issue by fidalgo** [alexreisner/geocoder#1651]
### Expected behavior
Being able to extract the archive

### Actual behavior
Failed to invoke que task

### Steps to reproduce
`rails geocoder:maxmind:geolite:extract PACKAGE=city --trace`

```
** Invoke geocoder:maxmind:geolite:extract (first_time)
** Execute geocoder:maxmind:geolite:extract
bin/rails aborted!
NoMethodError: private method `archive_edition' called for Geocoder::MaxmindDatabase:Module (NoMethodError)

    archive_filename = "#{Geocoder::MaxmindDatabase.archive_edition(p)}.zip"
                                                   ^^^^^^^^^^^^^^^^
Did you mean?  archive_filename
```

### Environment info

* Geocoder version: 1.8.2
* Rails version:  7.1
* Database (if applicable): 
* Lookup (if applicable):

**Comment by alexreisner** [comment]
Looks like this method was created/made private in #1600. I just made it public in #1652. Until the next version is released, you can try it out by installing the gem from the repo (in your Gemfile: `gem 'geocoder', git: 'git://github.com/alexreisner/geocoder.git', ref: '05faae32'`).
