### ISSUE TITLE
can geoip2 lookup be configured using a remotely stored mmdb file?

### ISSUE THREAD

**Issue by deadroxy** [alexreisner/geocoder#1654]
### Usage question
Rather than an issue, I have a question I cannot determine the answer to.

I am using the `geocoder` and `maxminddb` gems successfully in development to geocode IPs for my site's analytics. I've written a rake task to download the `GeoLite2-City.mmdb` database from MaxMind to refresh the information twice weekly. The task stores the downloaded file in the application's `tmp/` directory, and the geocoder configuration file (see below) successfully loads that file in development.

```
Geocoder.configure(
  ip_lookup: :geoip2,
  geoip2: {
    file: "tmp/GeoLite2-City.mmdb"
  }
)
```
I am aware that local address lookups like `geoip2` are new and not yet production ready. However, I have been trying to get it to work in production on my personal site to see if it _could_ work. Deploying to Heroku I realized that this strategy will fail because of Heroku's ephemeral data store. Running the application across multiple dynos means that a file stored in `tmp/` _might_ or _might not_ be present when the application loads. In order to persist a file that I download through a rake task, I will need to upload it S3 or some other external datastore. That's easy enough, but I'm not sure how I would actually configure the geocoder gem to ingest a remotely stored file.

Is there a way to configure geoip2 lookup to load a file from S3 (rather than local storage)? Any tips on implementing this approach on Heroku would be appreciated!

### Environment info

* Geocoder version: 1.8.3
* Rails version: 7.0.3.1
* Database (if applicable): 
* Lookup (if applicable): geoip2 (GeoLite2)

**Comment by deadroxy** [comment]
For anyone looking to do something similar, I seem to have found a solution. I modified my rake task for refreshing the MaxMind GeoLite2 database to store the ~50Mb `.mmdb` file in an AWS S3 bucket using v3 of the [aws-sdk-ruby](https://github.com/aws/aws-sdk-ruby) gem.

```
object = Aws::S3::Resource.new.bucket(ENV['GEO_BUCKET']).object('GeoLite2-City.mmdb')
object.upload_file(open(mmdb_file_location))
```

Then I updated the configuration for the geocoder to download the database file from the S3 bucket into the `tmp/` folder when the application loads.

```
Geocoder.configure(
  ip_lookup: :geoip2,
  geoip2: {
    file: Aws::S3::Resource.new.bucket(ENV['GEO_BUCKET']).object('GeoLite2-City.mmdb').download_file('tmp/GeoLite2-City.mmdb') ? "tmp/GeoLite2-City.mmdb" : ''
  }
)
```

Doing it this way forces the download happens when the application launches, which seems to ensure the file is present in Heroku's ephemeral storage at the necessary moment to load it into memory.

It is currently working in production for me, but I am not sure how stable it is. If anyone has any critiques or better practice to offer, please share!

**Comment by alexreisner** [comment]
@deadroxy interesting solution! Thanks for sharing!

**Comment by deadroxy** [comment]
Thanks @alexreisner - I'll close this issue out, since I'm not sure if there is a more robust solution yet!

**Comment by RyanTG** [comment]
Just want to say thank you, @deadroxy. That's a neat solution, and so far it's working for us! This is our first time using mmdb and I was surprised that we couldn't just store it and access it from s3.

**Comment by deadroxy** [comment]
Glad it is working for you @RyanTG! I've had this running in production for a year and a half and it _mostly_ works, haha ;]

**Comment by RyanTG** [comment]
warning from the s3 gem.

```
Called deprecated method `download_file` of Aws::S3::Object. Use `Aws::S3::TransferManager#download_file` instead.
Method `download_file` will be removed in next major version.
```

I'll share if I figure out how to solve it. My first attempts were no good, but at least it's just a warning.

**Comment by RyanTG** [comment]
This seems to work:
```
transfer_manager = Aws::S3::TransferManager.new

transfer_manager.download_file(
                'tmp/GeoLite2-City.mmdb',
                bucket: ENV['GEO_BUCKET'],
                key: 'maxmind/GeoLite2-City.mmdb',
              )
