### ISSUE TITLE
"wrong constant name Master::Area" when rake geocode:all

### ISSUE THREAD

**Issue by dtaniwaki** [alexreisner/geocoder#203]
Hi,
Your gem is very nice.

But I found the rake task doesn't support geocoded class under module like "AAA::MyClass".
The rake task failed because of line 6 in "lib/tasks/geocoder.rake".

``` ruby
Object.const_get(class_name)
```

I think it should be

``` ruby
class_name.constantize
```

Could you support it?

**Comment by tinamason** [comment]
So how can I get error to go away

**Comment by tinamason** [comment]
Somebody help? Its been 8 days! Since X'mas eve
