### ISSUE TITLE
Geocoding API's response was not valid JSON

### ISSUE THREAD

**Issue by gigdates** [alexreisner/geocoder#217]
I am getting this error after upgrading to geocoder (1.1.1) 

Calls like this is returning NIL. I have had others try it and it is confirmed.

Geocoder.search("64.234.74.25").first.city

NoMethodError (undefined method `city' for nil:NilClass):

At first I thought it was Yahoo freaking up so then I applied for a Bing key and that is still giving me the same issue.

**Comment by kittrCZ** [comment]
I'm seeing this issue when I try to call Bing API in loop(like 180 requests for Geo in less than a minute). Do you guys have any suggestions on how to actually implement system which would call Bing Geo API quite frequently. Should I start using queue and populate these calls separately for every object. I have right now around 90k records in DB and I need to obtain geolocation for them. Any advices?
