### ISSUE TITLE
get city, country and ip from a visitor on production mode with rails 3.2

### ISSUE THREAD

**Issue by hyperrjas** [alexreisner/geocoder#239]
I have installed http://www.rubygeocoder.com/ in a project rails in a production server but this gem in my production server not works fine for me...

I write these methods in views in my development environment and works fine:

```
<%= request.ip %>   
<%= request.location.city %>    
<%= request.location.country %>
```

and I get:  `127.0.0.1 Reserved`    

this result its usually because I am working in localhost.

However after make a deploy with capistrano in the production server in linode I get error with these methods, I can see in my production log the next error:

```
Completed 500 Internal Server Error in 909ms

ActionView::Template::Error (undefined method `location' for #<ActionDispatch::Request:0x00000005aa8570>):
```

Why I get this error in my production server for these methods?

Thank you!

**Comment by krupali1810** [comment]
Hello @alexreisner !

I want location details while visitor is visiting website.

I have tried Geocoder.search("") query using ip address as parameter. But it doesn't work for production environment.

Can u help me to resolve this? How to get location details in production environment?

**Comment by adrianvalenz** [comment]
@krupali1810 I'm trying to figure out the same thing. @alexreisner

**Comment by arpit016** [comment]
@krupali1810  @adrianvalenz  Did any of you figure out how to do it where I can pass the IP address as the parameter and get the location or country?

**Comment by arpit016** [comment]
@adrianvalenz  @krupali1810 I figured it out. The syntax to get location details from IP is as follows:
Geocoder.address("pass_the _ip_address")

**Comment by TrangPham** [comment]
I'm glad that you were able to help each other. Feel free to submit a PR to
update the README so that this is clear to others too.

Thanks!
