### ISSUE TITLE
Using :through in a belongs_to relation

### ISSUE THREAD

**Issue by 23tux** [alexreisner/geocoder#26]
Hi,

I don't know if this is really a bug, or only not implemented. But is it possible to use a :through statement in geocoded_by? For example, I have two models, a User and a Location model, and I want to get nearby users of a user.

class User < ActiveRecord::Base
  belongs_to :location
  geocoded_by :location, :through => :location
end

class Location < ActiveRecord::Base
  has_many :users
  geocoded_by :address, :latitude  => :lat, :longitude => :lon
end

(btw: I know this isn't really the right syntax, just to make myself clear)
So that I can do sth like this:

User.first.nearbys(30);

I don't know if this is possible, but it would be great! ;)
thx!

**Comment by nickmeagher** [comment]
+1 @mgates your solution worked for me as well! Thank you!

**Comment by alexreisner** [comment]
Due to complexity, this is not going to be added to the gem, sorry! @mgates thanks for the workaround!
