### ISSUE TITLE
I can use postgis?

### ISSUE THREAD

**Issue by danieldocki** [alexreisner/geocoder#261]
Today I got this with sqlite3:

``` ruby
geocoded_by :address
before_save :geocode

def address
  [street, number, neighborhood, postal_code, city.name, state.name].compact.join(', ')
end
```

and data base of the columns I have longitude and longitude, but I'll use in production postgis. I can now use the geocoder with postgis to store a point?

I know I'll have to change the database structure for it to work with postgis, the problem is that I did not find how to store that point with geocoder and postgis.

Thanks

**Comment by avishai** [comment]
Update for 2019/upgrading from older versions of postgis: add this to an initializer:

```
RGeo::ActiveRecord::SpatialFactoryStore.instance.tap do |config| 
    config.default = RGeo::Geographic.spherical_factory(srid: 4326) 
end
```
and you should be all set.
