### ISSUE TITLE
geocode on associations

### ISSUE THREAD

**Issue by andreteves** [alexreisner/geocoder#294]
I have the following association:

```
class Vendor < ActiveRecord::Base

    has_many :addresses, :dependent => :destroy
    ....

end

class Address < ActiveRecord::Base

    belongs_to :vendor

    geocoded_by :address

    after_validation :geocode

    def address
        [street, city, state].compact.join(', ')
    end

end
```

I need to be able to search vendor by name, price, etc but I would like to include only those vendors within a certain distance from a given address - I'm trying to use geocoder gem for that.

I tried several variations of: 

```
vendors = Vendor.where(price: xx).where(name: yy) 
vendors = vendors.joins(:addresses).near(zz)
```

But I always get an error "NoMethodError: undefined method `near' for #Class:0x6356ef8"

Can somebody please point me into the right direction?

Thanks,
Andre

**Comment by rgallison** [comment]
I also had this problem and also solved it a bit differently:

`@locations = Location.includes(:vet).where( "vets.brand = ?", brand ).references(:vet).near(@coords, 100).order('distance')'

I needed both the location address and the association.  I also needed to restrict the records based on the associations brand property.  Unfortunately, adding that where clause prevents distance from being added to the records.  but the following returns with distances:

`@locations = Location.includes(:vet).near(@coords, 100).order('distance')`

Hope this helps someone

**Comment by bkeepers** [comment]
You can use `merge` on AR scopes to perform this in a single query:

```ruby
vendors = Vendor.where(price: xx).where(name: yy).joins(:addresses).merge(Address.near(zz))
```
