### ISSUE TITLE
Region support for Models

### ISSUE THREAD

**Issue by dmasur** [alexreisner/geocoder#324]
I have the problem that i have to geocode only postal_codes from time to time. That postal_codes arent unique over the world and google sets them to other countries. Only with the Region setting for google they stay on the right place.

I did the change in my pull request: https://github.com/alexreisner/geocoder/pull/323

its turned down, cause this shouldnt be a global setting.

Are there other ways around?

**Comment by rarruda** [comment]
Is it still the case that its not possible to configure region / bounds for the google API when geocoding in a model?

**Comment by alexreisner** [comment]
@rarruda you can do it like this:

    after_validation :geocode_with_region

    def geocode_with_region
      results = Geocoder.search("...", :params => {:region => "..."})
      self.latitude = ...
      ...
    end

**Comment by rarruda** [comment]
Thanks @alexreisner ! Works wonders!

**Comment by rarruda** [comment]
Thanks! Works wonders! 

But I'd like to suggest documenting this solution in README.md. :)

**Comment by alexreisner** [comment]
Example added to README (see b4e6603159f3dbf72e16b7994f114ab0697f9070).
