### ISSUE TITLE
Error when calculating distance between two points

### ISSUE THREAD

**Issue by toptierlabs** [alexreisner/geocoder#333]
I am getting the following error very often:

wrong argument type Class (expected Module) vendor/bundle/ruby/1.9.1/gems/geocoder-1.1.4/lib/geocoder/lookups/base.rb:106:in `include?'

This is the trace:

------------------------------- Backtrace:

vendor/bundle/ruby/1.9.1/gems/geocoder-1.1.4/lib/geocoder/lookups/base.rb:106:in include?' vendor/bundle/ruby/1.9.1/gems/geocoder-1.1.4/lib/geocoder/lookups/base.rb:106:inraise_error' vendor/bundle/ruby/1.9.1/gems/geocoder-1.1.4/lib/geocoder/lookups/google.rb:18:in results' vendor/bundle/ruby/1.9.1/gems/geocoder-1.1.4/lib/geocoder/lookups/base.rb:29:insearch' vendor/bundle/ruby/1.9.1/gems/geocoder-1.1.4/lib/geocoder/query.rb:11:in execute' vendor/bundle/ruby/1.9.1/gems/geocoder-1.1.4/lib/geocoder.rb:20:insearch' vendor/bundle/ruby/1.9.1/gems/geocoder-1.1.4/lib/geocoder.rb:27:in coordinates' vendor/bundle/ruby/1.9.1/gems/geocoder-1.1.4/lib/geocoder/calculations.rb:307:inextract_coordinates' vendor/bundle/ruby/1.9.1/gems/geocoder-1.1.4/lib/geocoder/calculations.rb:79:in distance_between' app/models/user.rb:1524:indistance_to'

Any help?

**Comment by jeromedalbert** [comment]
@garyfoster I feel like it should be the default too, although it maybe depends on what you use the gem for.

Adding `always_raise: :all` in the geocoder initializer hash makes geocoding errors always explicit, when possible.
