### ISSUE TITLE
Within_bounding_box: sw_corner and ne_corner

### ISSUE THREAD

**Issue by Jeewes** [alexreisner/geocoder#340]
Can <code>within_bounding_box</code> be used with sw_corner and ne_corner coordinates? If yes, how? And if not, why?

Currently docs says: <code> bounding_box(center_point, distance)</code>. What kind of square will you get if you know only <code>center_point</code> and <code>distance</code> - only thing you get is circle.

**Comment by rohit-initcoder** [comment]
@alexreisner thanks it worked for me (y)
