### ISSUE TITLE
Order by distance

### ISSUE THREAD

**Issue by burlesona** [alexreisner/geocoder#42]
I can't seem to figure out how to order `near` results by distance from the search coordinates. How do you do that?

**Comment by nekliw** [comment]
I have the same issue w/ :order => :distance. Any solutions?

**Comment by alexnofoget** [comment]
Type  :order => 'distance' instead :order => :distance

**Comment by Baril27** [comment]
+1 on this issue.

My original query on rails 3 was:
```
scope = scope.near(coords, radius, order: 'distance').limit(100)
```
When I migraded to rails 4 I started to get
```
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR: column "distance" does not exist
```
So I had to change my query to get it to work. Now its:
```
scope = scope.near(coords, radius, order: '').limit(100)
```
Any news on this issue?

**Comment by rohanpujaris** [comment]
+1 on this issue. I am using geocoder gem 1.2.14 and rails 4.2.5. Though removing order: :distance solves the issue. Also by default its ordered by distance so no worry till now.

**Comment by MaxPleaner** [comment]
This issue is closed, but many like myself are still encountering the issue. In fact it is a newly emerged issue for me. Is there a different issue thread which is active or contains a confirmed solution?

**Comment by looser990** [comment]
I had the same issue, but I don't even use Geocoder, so maybe worthwhile mentioning. 
I'm on Ruby 1.9.3 with rails 4.0.1
And I have a query for search + ordering for models User and Billing Infos. Users has one to many Billing infos and I'm searching through address/city/zip on Billing info, something along lines:
```
User.select('id, name, lastname, CONCAT(users.firstname, \' \', users.lastname) as fullname').
inclues(:billing_infos).
where("billing_infos.address like %#{address} and 
billing_infos.zip like %#{zip}% and
billing_infos.city like %#{city}%").
references(:billing_infos).order("#{sort_column} #{sort_direction}") 
```
Witch yields `unknown_column` for `fullname` if I try to order by it, but when I just change joins instead of includes it works as expected.
I know it seems it is offtopic but I have feeling this is somehow connected so maybe it will help you guys.

Regards.

**Comment by mikedhart** [comment]
Just thought I'd leave a note on this - I hit this issue when using pluck. When I don't use pluck, it works fine.

Was: ContactPoint.near([c.latitude, c.longitude], Centre::DEFAULT_RADIUS).pluck(:id)
Now: ContactPoint.near([c.latitude, c.longitude], Centre::DEFAULT_RADIUS).map(&:id)

Not ideal, but a small price to pay for such a good gem.

**Comment by alexey** [comment]
@mikedhart +1
`.map` instead of `.pluck` solve this issue, but i recommend to use `.select(:id).map(&:id)` for better selection

**Comment by mikedhart** [comment]
@alexey agreed.

**Comment by shivabhusal** [comment]
and, how would you alter the direction of order? 
I mean, I want to show the farthest item at the top (as selected by the user) and toggle.
## context
```ruby
@stores = Store.near(params[:search], 50, :unit => :kilometers, :order => :distance)
```

**Comment by hugoh1995** [comment]
Having same issue, just realized it wasnt ordering by distance for this entire time, what's going on?

**Comment by el-quick** [comment]
The @alexnofoget works for me:

> Type :order => 'distance' instead :order => :distance

Geocoder should allow us to use Model.order(:distance) as well.

**Comment by hugoh59** [comment]
Why has this issue been closed ?
