### ISSUE TITLE
request.location.country returns "Reserved" on Production

### ISSUE THREAD

**Issue by nqtien310** [alexreisner/geocoder#589]
I tried to print out the result of

```
request.location.country
```

on Production , it returns my correct country name for the first try , but on my second try , it'll return "Reserved" 

Is there anyway to fix this problem ? Really appreciate any help 

Best

**Comment by ascoppa** [comment]
Hey @nqtien310 you are not using tcp mode right? I already have those lines in default but it ain't working ... I guess it could be cause I'm using tcp mode on port 443?
