### ISSUE TITLE
Saving multiple locations (Latitude and Longitude) in same Model

### ISSUE THREAD

**Issue by MohdAnas** [alexreisner/geocoder#590]
i have two columns in table i.e start_location and end_location and i want to calculate the latitude and longitude for both location( both location contains full address). But by using geocoder  i am able to calculate only one latitude and longitude as it is specified in the documentation. Can i calculate latitude and longitude for both locations?

Thanks in Advance

**Comment by bood-pvb** [comment]
It does not works for me.
