### ISSUE TITLE
Sensis support

### ISSUE THREAD

**Issue by DanielHeath** [alexreisner/geocoder#603]
I've implemented sensis geocoder support here:

http://github.com/danielheath/geocoder-sensis

I'd be happier to see it merged into core rather than kept as an extension though.

**Comment by TrangPham** [comment]
I can't seem to find information about the sensis geocoding services via googling - I saw a couple results which could be related. Looks like it's a service which you must host yourself? (based on the code in geocoder-sensis)

It looks like there are people who are using this API though: https://rubygems.org/gems/geocoder-sensis/versions/0.0.4

Adding to beginners tasks:
- Port Sensis lookup over into Geocoder (see #591 as example) 
- Add tests
- Add documentation in read me

**Comment by alexreisner** [comment]
Closing, as this API no longer seems to exist.
