### ISSUE TITLE
Object.near in rails join merge not working as excepted

### ISSUE THREAD

**Issue by suras** [alexreisner/geocoder#627]
example
  locations = Location.near([params[:latitude], params[:longitude]], params[:radius], :units => :km)

books.joins(:location).merge(locations)

produces this sql

 SELECT locations.*, 6371.0 \* 2 \* ASIN(SQRT(POWER(SIN((12.9398981 - locations.latitude) \* PI() / 180 / 2), 2) + COS(12.9398981 \* PI() / 180) \* COS(locations.latitude \* PI() / 180) \* POWER(SIN((77.6275559 - locations.longitude) \* PI() / 180 / 2), 2))) AS distance, CAST(DEGREES(ATAN2( RADIANS(locations.longitude - 77.6275559), RADIANS(locations.latitude - 12.9398981))) + 360 AS decimal) % 360 AS bearing FROM `books` INNER JOIN `locations` ON `locations`.`id` = `books`.`location_id` WHERE (locations.latitude BETWEEN 12.930904883940814 AND 12.948891316059187 AND locations.longitude BETWEEN 77.61832835502157 AND 77.63678344497843 AND 6371.0 \* 2 \* ASIN(SQRT(POWER(SIN((12.9398981 - locations.latitude) \* PI() / 180 / 2), 2) + COS(12.9398981 \* PI() / 180) \* COS(locations.latitude \* PI() / 180) \* POWER(SIN((77.6275559 - locations.longitude) \* PI() / 180 / 2), 2))) <= '1') ORDER BY distance ASC
and gives result as
 [#<Book id: 10, created_at: "2014-03-30 14:47:03", updated_at: "2014-03-30 15:20:52">]

but it should produce something like

 SELECT `books`.\* FROM `books` INNER JOIN `locations` ON `locations`.`id` = `books`.`location_id` WHERE `locations`.`id` IN (10, 7)

**Comment by dkniffin** [comment]
I know this is an old issue, but it came up in google results, and there was no workaround, so I thought I'd share mine.

In my case, I've got an `Order` that `has_one :address`, and the `Address` model is geocoded by this gem. Now, I want to find all orders that are near a user-provided lat/lon/radius. I originally created a scope on `Order` that did:
```rb
scope :near, ->(*args) { joins(:address).merge(Address.near(*args)) } 
```

That _kind of_ worked, except that it didn't return all the attributes for the `Order`s. So, instead, I used this one:
```rb
  scope :near, ->(*args) {
    nearby_addresses = Address.near(*args)
    joins(:address).where(addresses: { id: nearby_addresses.map(&:id) })
  }
```

It's certainly not as performant, but it's functional at least
