### ISSUE TITLE
Undefined method `near' for #<Supplier:0x5ae8110>

### ISSUE THREAD

**Issue by codinatrix** [alexreisner/geocoder#629]
This code gives me "Undefined method `near'" in Rails 4.0.4, Ruby 1.9.3.

```
class Supplier < ActiveRecord::Base

  validate :within_driving_distance
  geocoded_by :address
  before_validation :geocode

  def within_driving_distance
    unless self.near([56.87963, 14.80671], 200)
      errors.add :base, "That address is more than 200 miles away."
    end
  end
end
```

Everything else works. It grabs the address and sets the latitude and longitude as it should. If I insert `self.geocoded?` before `self.near`, it returns true. Could anyone please tell me why?

**Comment by amruthans** [comment]
undefined method `near' for #<Class:0x00000004faebd8>




		if params[:radius].present? && params[:lat].present? && params[:long].present?
			venues = Venue.near([params[:lat], params[:long]], params[:radius])
			@events = @events.include(:venues).where(venue_id: venues.pluck(:id))
		end
		if params[:page].present? && params[:limit].present?
