### ISSUE TITLE
Any way to extract timezone from results?

### ISSUE THREAD

**Issue by firedev** [alexreisner/geocoder#640]
Thanks for `geocoder`, but now my users demand to see timezones for requests. Is there a way to extract time zone from geocoded data? There are some services capable of doing it according to this [StackOverflow post](http://stackoverflow.com/questions/41504/timezone-lookup-from-latitude-longitude) but it would be great to have this added to `geocoder` so I can extract data in one call.

**Comment by swrobel** [comment]
For anyone else who ends up where, tzwhere seems to be abandoned, but the [timezone](https://github.com/panthomakos/timezone) gem is maintained.
