### ISSUE TITLE
maxmind_local 'file' hardcoded to 'city'

### ISSUE THREAD

**Issue by jsqu99** [alexreisner/geocoder#649]
Is this a bug? https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/maxmind_local.rb#L33

There's no way to search for country using the .dat option.

**Comment by moofish32** [comment]
Just a friendly ping that this issue appears closed.

**Comment by TrangPham** [comment]
@alexreisner Can this issue be closed?

**Comment by alexreisner** [comment]
Ah, yes. Thanks @TrangPham and @moofish32 for the poke.
