### ISSUE TITLE
Additional parameters for Bing

### ISSUE THREAD

**Issue by fokcep** [alexreisner/geocoder#765]
How can I pass additional parameters to bing lookup?

For example I want to get country code i.e. need to pass include=ciso2

Is it possible in the current version?

**Comment by fokcep** [comment]
Is there a way to pass additional param to geocoded_by method in a model?

i.e. something like

geocoded_by :address, :include => "ciso2" do |obj, results|
.......


thanks

**Comment by alexreisner** [comment]
Not currently, though I'm open to a pull request for this functionality. For now you have to write a custom geocoding method, eg:

    after_validation :geocode
    def geocode
      if coords = Geocoder.coordinates(address, :params => {:include => "ciso2"})
        self.latitude, self.longitude = coords
      end
    end
