### ISSUE TITLE
request.location nil and timeout error

### ISSUE THREAD

**Issue by shefalee1** [alexreisner/geocoder#770]
request.location given nil often and getting timeout error still after adding geocoder configuration timeout to 20. 
And one more thing , Geocoder.search("23.3.4.5") when trying this , getting error 
Geocoding API's response was not valid JSON.
 => [ ]

**Comment by glacerenza** [comment]
Is it possible that with Telize as Ip Lookup, request.location is not working?

**Comment by ImtiazEmu** [comment]
@ahmadhasankhan , I got the same problem. I'm using telize and its not giving me the right location? Do I need to use a different ip_lookup? Google is accurate but once in a month google update their service (I believe) and the day they are updating, the service is unavailable for that day. 
Could you recommend me a better solution? Thanks in advance!

**Comment by aashish** [comment]
I am having same problem. 
```ruby
 :004 >   Geocoder.configure(ip_lookup: :telize) 
 => {:timeout=>20, :lookup=>:yandex, :ip_lookup=>:telize, :language=>:en, :http_headers=>{}, :use_https=>false, :http_proxy=>nil, :https_proxy=>nil, :api_key=>nil, :cache=>nil, :cache_prefix=>"geocoder:", :always_raise=>[], :units=>:km, :distances=>:linear} 
 :005 > Geocoder.search("hyderabad")
Geocoding API's response was not valid JSON.
 => [] 
 :006 > 
 :007 >   g =Geocoder.search("137.118.141.50")

Geocoding API's response was not valid JSON.
 => [] 

```

**Comment by alexreisner** [comment]
@aashish please see #950. You'll need to install from `master` until new gem is released (which will be very soon).
