### ISSUE TITLE
Handling IP address-like ZIP code

### ISSUE THREAD

**Issue by kenn** [alexreisner/geocoder#776]
We run a ZIP code search using Google:

```ruby
Geocoder.search(zip_code, params: { components: "country:#{country}"})
```

Today, we got an exception because a ZIP code "4.1.0.2" was entered by a user (the country was Philippines) and recognized as an IP address, and processed with `Freegeoip`, which doesn't have the `types` method in a result as Google does.

I don't think "4.1.0.2" is a normal format people would type in (I assume that there's no IPv4-like ZIP code format exists in the world.), and I don't want to waste my time investigating it again in the future.

Possible solutions:

- Set `:ip_lookup => :google` config - The user probably get a random result from Google (with above case, [this](http://maps.googleapis.com/maps/api/geocode/json?address=4.1.0.2&components=country%3APH&language=en&sensor=false)), but at least I won't get bogus notification on `NoMethodError`.
  - or create a pull request to add an option to disable IP lookup - the consequence is same as `:ip_lookup => :google`
- Monkey patch the `ip_address?` method and raise a specific error that can be used to turn into a validation error - more desirable result.
  - or create a pull request to add an option to raise a specific error.

Anyone experienced this, and if so, what's your recommendation?

**Comment by alexreisner** [comment]
This should be solved by #798 and 0a0d359.
