### ISSUE TITLE
Geocode don't work in production. (Production console response: Geocoding API's response was not valid JSON.)

### ISSUE THREAD

**Issue by nonato** [alexreisner/geocoder#783]
I set up a geocoder Address model, for when the form is submitted, it get the coordinates of the address and it works well in "development". But when test "production", the Geocode not get the coordinates of the new address, and continues the old coordinates, or null.

Below some returns via Console (In Production):

2.0.0-P481: 005> Geocoder.search ('Madrid')
Geocoding API's response was not valid JSON.
  => []

2.0.0-P481: 006> Geocoder :: Lookup.get (: google) .query_url (Geocoder :: Query.new ("Madrid"))
  => "Http://maps.googleapis.com/maps/api/geocode/json?address=Madrid&language=en&sensor=false"

====================================================

Now some returns via Console (In Development):

2.0.0-p481 :001 > Geocoder.search('Madrid')
 => [#<Geocoder::Result::Google:0x8972b58 @data={"address_components"=>[{"long_name"=>"Madrid", "short_name"=>"Madrid", "types"=>["locality", "political"]}, {"long_name"=>"Madrid", "short_name"=>"Madrid", "types"=>["administrative_area_level_4", "political"]}, {"long_name"=>"Área Metropolitalitana y Corredor del Henares", "short_name"=>"Área Metropolitalitana y Corredor del Henares", "types"=>["administrative_area_level_3", "political"]}, {"long_name"=>"Madrid", "short_name"=>"M", "types"=>["administrative_area_level_2", "political"]}, {"long_name"=>"Community of Madrid", "short_name"=>"Community of Madrid", "types"=>["administrative_area_level_1", "political"]}, {"long_name"=>"Spain", "short_name"=>"ES", "types"=>["country", "political"]}], "formatted_address"=>"Madrid, Madrid, Spain", "geometry"=>{"bounds"=>{"northeast"=>{"lat"=>40.5635903, "lng"=>-3.5249115}, "southwest"=>{"lat"=>40.3120639, "lng"=>-3.8341618}}, "location"=>{"lat"=>40.4167754, "lng"=>-3.7037902}, "location_type"=>"APPROXIMATE", "viewport"=>{"northeast"=>{"lat"=>40.5635903, "lng"=>-3.5249115}, "southwest"=>{"lat"=>40.3120639, "lng"=>-3.8341618}}}, "types"=>["locality", "political"]}, @cache_hit=nil>] 

2.0.0-p481 :002 > Geocoder::Lookup.get(:google).query_url(Geocoder::Query.new("Madrid"))
 => "http://maps.googleapis.com/maps/api/geocode/json?address=Madrid&language=en&sensor=false" 

Any suggestions of what might be happening?

Thanks Very much

**Comment by alexreisner** [comment]
How does your production environment differ from your dev environment? Is there a proxy or anything about the network that would cause Google to respond differently? Maybe try accessing the Google API url through the production console and see what it's returning.

**Comment by nonato** [comment]
Thanks for the reply.

I have 2 different configured options:

# PRODUCTION
config.consider_all_requests_local = false
config.action_controller.perform_caching = true

# DEVELOPMENT
config.consider_all_requests_local = true
config.action_controller.perform_caching = false


=============================================

This may have influenced?

I'm sorry my lack of knowledge. How do I test you suggested?
"try accessing the Google API url through the production console"
??


Thank you very much,

**Comment by alexreisner** [comment]
Try using [OpenURI](http://ruby-doc.org/stdlib-2.1.2/libdoc/open-uri/rdoc/OpenURI.html) to download the query URL (http://maps.googleapis.com/maps/api/geocode/json?address=Madrid&language=en&sensor=false).

**Comment by nonato** [comment]
I try this:


2.0.0-p481 :003 > Geocoder::Lookup.get(:google).send(:fetch_raw_data, Geocoder::Query.new("Madrid"))
 => "{\n   \"results\" : [\n      {\n         \"address_components\" : [\n            {\n               \"long_name\" : \"Madrid\",\n               \"short_name\" : \"Madrid\",\n               \"types\" : [ \"locality\", \"political\" ]\n            },\n            {\n               \"long_name\" : \"Madrid\",\n               \"short_name\" : \"Madrid\",\n               \"types\" : [ \"administrative_area_level_4\", \"political\" ]\n            },\n            {\n               \"long_name\" : \"Área Metropolitalitana y Corredor del Henares\",\n               \"short_name\" : \"Área Metropolitalitana y Corredor del Henares\",\n               \"types\" : [ \"administrative_area_level_3\", \"political\" ]\n            },\n            {\n               \"long_name\" : \"Madrid\",\n               \"short_name\" : \"M\",\n               \"types\" : [ \"administrative_area_level_2\", \"political\" ]\n            },\n            {\n               \"long_name\" : \"Community of Madrid\",\n               \"short_name\" : \"Community of Madrid\",\n               \"types\" : [ \"administrative_area_level_1\", \"political\" ]\n            },\n            {\n               \"long_name\" : \"Spain\",\n               \"short_name\" : \"ES\",\n               \"types\" : [ \"country\", \"political\" ]\n            }\n         ],\n         \"formatted_address\" : \"Madrid, Madrid, Spain\",\n         \"geometry\" : {\n            \"bounds\" : {\n               \"northeast\" : {\n                  \"lat\" : 40.5635903,\n                  \"lng\" : -3.5249115\n               },\n               \"southwest\" : {\n                  \"lat\" : 40.3120639,\n                  \"lng\" : -3.8341618\n               }\n            },\n            \"location\" : {\n               \"lat\" : 40.4167754,\n               \"lng\" : -3.7037902\n            },\n            \"location_type\" : \"APPROXIMATE\",\n            \"viewport\" : {\n               \"northeast\" : {\n                  \"lat\" : 40.5635903,\n                  \"lng\" : -3.5249115\n               },\n               \"southwest\" : {\n                  \"lat\" : 40.3120639,\n                  \"lng\" : -3.8341618\n               }\n            }\n         },\n         \"types\" : [ \"locality\", \"political\" ]\n      }\n   ],\n   \"status\" : \"OK\"\n}\n" 



===================================================

Is the correct response?

**Comment by alexreisner** [comment]
Yes, that looks like valid JSON. Are you sure your configured lookup is `:google`?

**Comment by nonato** [comment]
Forgive me.
In my last answer I had not seen your suggestion of OpenURI

I will try now.

thank you

**Comment by nonato** [comment]
Yes,

2.0.0-p481 :009 > Geocoder::Configuration.lookup = :google
 => :google 
2.0.0-p481 :010 > Geocoder.search('Madrid')
Geocoding API's response was not valid JSON.
 => [] 
2.0.0-p481 :011 > 


Still not working =/

You want me to test with OpenURI?

Can reveal something different?

**Comment by alexreisner** [comment]
If you ran `fetch_raw_data` in production and got a JSON response, using OpenURI is not going to give us any more information. I'm kind of baffled by this.

**Comment by nonato** [comment]
Is there anything I can do to help?

Some information?

Some test?

**Comment by nonato** [comment]
I also realized that when I put <% = Geocoder.search ("Madrid")%> directly in a "view" in development, it returns the correct location information.

But when I switch to "production", the <% = Geocoder.search ("Madrid")%> returns "[ ]"

Helped?

**Comment by nonato** [comment]
I discovered a detail.

In production.rb, when I change the "config.cache_classes" option to false, the command "Geocoder.search ('Madrid')" in the console works normal.

It could have something to do?

thank you

**Comment by alexreisner** [comment]
Well, that is pretty odd. Good information to have. My advice is to keep thinking about the ways your production system is different from development, not just in the code but in the rest of each system's configuration and connection to the Internet. (Are you running both production and development environments on the same machine?)

**Comment by nonato** [comment]
Yes, I'm running both production and development environments on the same machine.

The order in my gem file may have influenced?

**Comment by alexreisner** [comment]
Unless your final production environment is this machine I'd suggest not worrying about whether production env works.

**Comment by nonato** [comment]
Ok. I will test in final machine and post the results.

Thank you very much

**Comment by nonato** [comment]
I did the tests in the VM that will host the system, and when the "config.cache_classes" is set to "false", the Geocoder works normally. But when I set "config.cache_classes" to "true", not work again.

Is there any way to just remove the Geocoder or Address class of "config.cache_classes" ??

Is this the best solution?

======================================================

My gemfile

source 'https://rubygems.org'


gem 'rails', '3.2.18'
gem "bundler"
gem 'mysql2'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'jquery.fileupload-rails'
end


gem 'jquery-rails',   '~> 2'
gem 'jquery-ui-rails', '=4.2.1'
gem "authlogic"
gem "paperclip", "~> 3.0"
  
gem "meta_search"
gem "squeel"
gem 'tinymce-rails', "3.5.8.1"
gem 'tinymce-rails-langs', "0.1"
gem 'whenever',">= 0.6.2", :require=>false
gem "cancan" , ">= 1.5.1"
gem 'will_paginate', '~> 3.0.0'
gem "uuid", "~> 2.3.7"
gem "rmagick", :require => "RMagick2"
gem "barby", ">= 0.5.1"
gem 'gruff'
gem "win32-open3-19", :platforms => :mingw
gem 'wicked_pdf'
gem "rubyzip", "~> 0.9.9"
gem 'sidekiq'
gem 'sinatra', :require => nil
gem 'slim'  
gem "chunky_png"
gem "rqrcode"  
  
gem "axlsx"
gem 'webrick', '1.3.1'
  
gem "delocalize"
gem 'meiomask-rails'

gem 'iconv'
gem 'rabl'
gem 'jplayer-rails'
gem 'youtube_it'

gem 'gmaps4rails'
gem 'underscore-rails'
gem 'geocoder'
gem "validate_url"
gem 'tinymce-rails-imageupload', '3.5.8.6'

======================================================


thanks a lot

**Comment by alexreisner** [comment]
Closing, because I'm pretty sure this is not a geocoder bug.
