### ISSUE TITLE
Geocoding multiple addresses

### ISSUE THREAD

**Issue by taylorscollon** [alexreisner/geocoder#784]
I have searched high and low for a solution to this without luck, so I'm now posting here... 

This approach to geocoding multiple addresses on the same model doesn't work as it only geocodes the last method: 

    geocoded_by :start_address, latitude: :start_latitude, longitude: :start_longitude
    geocoded_by :end_address, latitude: :end_latitude, longitude: :end_longitude

I have tried to write a custom method to solve this:

    geocoded_by :geocode_user_addresses
    after_validation :geocode
  
    def geocode_user_addresses
    home_address_joined = [home_address, city].compact.join(', ')
    work_address_joined = [work_address, city].compact.join(', ')
    home_coordinates = Geocoder.search(home_address_joined)
    work_coordinates = Geocoder.search(work_address_joined)
    self.home_latitude = home_coordinates.latitude
    self.home_longitude = home_coordinates.longitude
    self.work_latitude = work_coordinates.latitude
    self.work_longitude = work_coordinates.longitude
    end

That gives me this error when I try to geocode the addresses:

    undefined method `latitude'

Is this a geocode problem? Thanks

**Comment by alexreisner** [comment]
That should work except that `Geocoder.search(home_address_joined)` returns an array of Geocoder results objects. Try calling `latitude` on the first result, instead of the array.

**Comment by niuage** [comment]
@alexreisner so this should be removed from the documentation right?

```ruby
geocoded_by :start_address, latitude: :start_latitude, longitude: :start_longitude
geocoded_by :end_address, latitude: :end_latitude, longitude: :end_longitude
```

**Comment by alexreisner** [comment]
@niuage correct! Thanks. I just removed it.

**Comment by niuage** [comment]
@alexreisner thanks, that was quick!

Any plan on supporting that? Maybe I'm just considering the simplest case here, but it doesnt seem like it would be too difficult to support. It would just be a matter of keeping an array of "location fields" coupled with their options, and then iterating over it when `geocode` is called?

**Comment by alexreisner** [comment]
Yeah, it's not totally simple. For example, what should the `#geocoded?` method return if one set of coordinates is set but not the other? I think the answer is probably `false`, but this takes some thought (and some code) and I'm sure there are other issues like this as well. I'm open to a pull request if you want to take a stab at it.

**Comment by niuage** [comment]
Yeah, I see. Just to answer this one example (and maybe it would fit others), I would say that it should return false, if any of the fields are not geolocated. All these methods could also now accept a list of field names.

```ruby
# if the start address wasnt geocoded, but the end address was

trip.geocoded?
# => false
trip.geocoded? :start_address, :end_address
# => false
trip.geocoded? :start_address
# => false
trip.geocoded? :end_address
# => true
```
