### ISSUE TITLE
Error: APP_PATH already initialized

### ISSUE THREAD

**Issue by zavan** [alexreisner/geocoder#785]
Hi, I'm struggling for hours with an error.

When I put `gem 'geocoder'`, run `bundle install` and then `rails server`, I'm getting:

`bin/rails:6: warning: already initialized constant APP_PATH /path/to/bin/rails:6: warning: previous definition of APP_PATH was here Usage: rails COMMAND [ARGS] `

Without the geocoder gem it works well.

Any idea on what may be happening?

**Comment by sbonami** [comment]
Reset `spring`:

```
$ bin/spring binstub --remove --all
$ bundle exec spring binstub --all
```

**Comment by zavan** [comment]
It works. Thank you!
