### ISSUE TITLE
Is it possible and should I set parallel_requests on Geocoder whe using Maxmind (Rails 4/geocoder/maxmind)

### ISSUE THREAD

**Issue by misner** [alexreisner/geocoder#786]
I have opted for Maxmind among Geocoder's choices to do ip lookup (given ip i find the country):

/config/initializers/geocoder.rb

    Geocoder.configure({  
        ip_lookup: :maxmind,
        :maxmind => { :service => :country },
        :api_key => ENV['MAXMIND_APIKEY'],
        # this is very important option for configuring geocoder with API key
        :use_https => true,
        # geocoding service request timeout, in seconds (default 3):
        timeout: 3,
        # use cache in order not to send every page load a request to maxmind
        cache:  Rails.cache
    })

I saw that when people use directly a Maxmind ruby gem , they have the option of setting the option parameter parallel_requests : see http://www.rubydoc.info/gems/geoip2/frames

I haven't seen anything about how to set concurrent requets. Should I do it ? how?

Can i just add this to my initializer like below?

    Geocoder.configure({  
     parallel_requests: 5
    })

thanks

**Comment by alexreisner** [comment]
The way to do this is just to configure the gem as shown in the geoip2 documentation. I think adding such configuration to geocoder is overkill.

**Comment by misner** [comment]
Hi I'm a newbie and don't really understand.

Could you be more explicit?
I'd like to continue using in my files geocoder great functions and methods.

- So do you mean I have to use geocoder gem , but also AT THE SAME TIME add geoip gem to my gem file and in that case inside geoip configure, set 
{ parallel_requests: 5 }.
Would these parameters apply on my existing codes where I use geocoder country methods ?

- or do you mean i should remove geocoder gem and replace it by geoip gem (and in that case use geoip methods), if I want to use { parallel_requests: 5 }.

- or do you mean I can actually use { parallel_requests: 5 }. directly inside Geocoder.configure ?

thanks for your help
M.

**Comment by alexreisner** [comment]
Sorry, I think I misunderstood how the parallel requests worked in the geoip2 gem. Basically that configuration is not relevant to Geocoder as it has no parallel lookup feature. If you want to do parallel lookups you'll have to execute multiple requests at the same time (in multiple threads, or whatever).

**Comment by misner** [comment]
SoThanks for your answer. It means i can't use use { parallel_requests: 5 }. directly inside Geocoder.configure so what way could I use geoip's parralel requets configuration while keeping using geocoder cool methods i already use in my code ? is it possible to use both at the same time ?
