### ISSUE TITLE
Negative coordinates not working

### ISSUE THREAD

**Issue by chrisvel** [alexreisner/geocoder#789]
I have a model with attributes address, city, country, latitude, longitude. I am trying to find rows near famous cities in Europe and everything that has a negative value fails. For example, (from rails console): ``` m = Mymodel.near("London") ``` retrieves nothing, although I have hundreds of entries. ``` m = Mymodel.near("Rome") ``` fetches everything successfully (same as Vienna, Athens etc.). 

Here is my model class:

```
geocoded_by :get_full_address
  after_validation :geocode
  
  def get_full_address
    [address, city, pobox, country].compact.join(', ')
  end
```

Also, latitude and longitude are zeroed by me, as I want to fill them later.

Do you have any idea why negative values fail to show nearby entries ?
I am one step to a great achievement of mine and I am hitting my head to the wall !

**Comment by alexreisner** [comment]
If stored latitude and longitude values are zero, geocoder does not know where they are in relation to anything else. To use `near`, your objects must be geocoded.

**Comment by chrisvel** [comment]
So what's the solution ? Geocoder translates the full address of every row to lat/long coordinates on the fly and that's how it compares to the destination (.near....)

**Comment by alexreisner** [comment]
Every translation of address to coords takes a network call, which is slow and unreliable (compared to local data). It's not feasible to do on-the-fly lookups for each query. Run `rake geocode:all CLASS=YourModel` and you'll see how long it takes. When it's done, your rows will have coordinates in them and you'll be able to run `near` queries.

**Comment by chrisvel** [comment]
Well it takes 10 seconds for 380 rows and in the end nothing happens: the latitute and longtitude fields remain zero.

**Comment by chrisvel** [comment]
So the solution was to run an update on the latitude and longtitude columns, setting them both as NULL and then ``` rake geocode:all ``` all of them. Thanks a lot !
