### ISSUE TITLE
Geocoder returns incorrect location on Geocoder.search(<ip address>)

### ISSUE THREAD

**Issue by ianseyer** [alexreisner/geocoder#796]
Hi.

My IP address is 12.249.54.122.

Upon visiting http://whatismyipaddress.com/, I see that it CORRECTLY resolves my location to Austin, TX.

However, when I perform Geocoder.search("12.249.54.122"), it tells me that that IP address is in Kansas.

Why the discrepancy? Obviously, that is a quite a wrong location.

My code is as vanilla as could be:
Geocoder.search("12.249.54.122") is all I'm doing, and here is the full result:

[#<Geocoder::Result::Freegeoip:0x007fd5f976aa08 @data={"ip"=>"12.249.54.122", "country_code"=>"US", "country_name"=>"United States", "region_code"=>"", "region_name"=>"", "city"=>"", "zip_code"=>"", "time_zone"=>"", "latitude"=>38, "longitude"=>-97, "metro_code"=>0}, @cache_hit=nil>]

My actual IP addres coordinates are [30.2414 , -97.7687]

**Comment by alexreisner** [comment]
Note this: http://whatismyipaddress.com/geolocation-accuracy

Every geolocation service has different degrees of accuracy. The default IP geolocation service for Geocoder is FreeGeoIp which, as the name suggests, is free. If you want more accurate results you might need to use one of the non-free services.
