### ISSUE TITLE
Naming of :maxmind_geoip2 Lookup

### ISSUE THREAD

**Issue by alexreisner** [alexreisner/geocoder#801]
The ambiguity of MaxMind's product names (and their tendency to change them) make this lookup a difficult one to name. At first I thought it should be called something like `:maxmind_precision` because `geoip2` is the name of a local database format in addition to the name of an API, which is confusing. I believe ultimately the name of this service should be simply `:maxmind` and the current one should be renamed to `:maxmind_legacy`, but we can't do that right away without breaking people's apps.

I think the next patch release of the gem should add `:maxmind_legacy` and a warning about the upcoming name change when someone uses the current `:maxmind`. Then we rename `:maxmind_geoip2` to `:maxmind` in version 1.3.0 (or even later).

At the moment I'm still considering renaming this new service to `:maxmind_precision` but I'm not sure it makes much difference.

Just posting this issue to get feedback from anyone interested.

Once the names are decided, the new lookup should be added to the README.

**Comment by TrangPham** [comment]
Agreed that the naming is very confusing and the lookups you mentioned `:maxmind`, `:maxmind_geoip2`  should be renamed.

I also think `:geoip2` should be renamed to `:geoip2_local` as it is using configuratoin[:file] (make it similar to `:maxmind_local`

**Comment by alexreisner** [comment]
Yes, I agree with that as well. All local lookups should probably have a `_local` suffix.

**Comment by TrangPham** [comment]
This issue has several parts to it. The beginner task covers one part of the issue.

Beginner task: 

1) Rename `:geoip2` lookup to `:geoip2_local` 

2) Create lookup/geoip2.rb as a subclass of lookup/geoip2_local.rb and override name method

```ruby
class Geoip2 < Geoip2Local
  def name
    "Geoip2"
  end
```

You may also have to do the same thing with results. i.e. create results/geoip2.rb as a subclass of results/geoip2.rb

3) Add a deprecation warning to lookup/geoip2.rb

**Comment by alexreisner** [comment]
This no longer seems as important as it once did, and renaming lookups causes problems for people. Plus, companies can always foil us by changing their product names. It's futile to try to keep up. Closing my own dumb issue.
