### ISSUE TITLE
How to get all parameters of google maps request?

### ISSUE THREAD

**Issue by phlegx** [alexreisner/geocoder#803]
Hi!

I want to get more information of a request. I start a search by doing:

```console
2.1.4 :000 > Geocode.search('AN ADDRESS HERE')
```

Now I want to retrieve the following parameter:

- place_id

FYI This parameters are deprecated after mid of 2015:

- id 
- reference

This parameters are not on the ```Geocoder::Result::Google``` instance object. Why? Any idea how to get this information?

**Comment by alexreisner** [comment]
You can access the parsed raw response using the hash: `Geocoder::Result::Google#data`. However, Google geocoder doesn't include a `place_id` in its response (see [sample response](https://github.com/alexreisner/geocoder/blob/master/test/fixtures/google_madison_square_garden)).

**Comment by phlegx** [comment]
@alexreisner ok thx!
