### ISSUE TITLE
Unrecognized character in SQL query generated by geocoder method

### ISSUE THREAD

**Issue by ewamarciniak** [alexreisner/geocoder#809]
HI,
I am trying to use custom column names (instead the latitude/longitude) on my model but the geocoded method returns an error. Can you please tell me if this is a bug or am I implementing the gem incorrectly? 

The error returned from ```User.geocoded ``` query
```SELECT "users".* FROM "users"  WHERE (users.latitude IS NOT NULL AND users.{:latitude=>:last_location_lat, :longitude=>:last_location_long} IS NOT NULL)
SQLite3::SQLException: unrecognized token: "{": SELECT "users".* FROM "users"  WHERE (users.latitude IS NOT NULL AND users.{:latitude=>:last_location_lat, :longitude=>:last_location_long} IS NOT NULL)```
In the model:
```
reverse_geocoded_by :latitude, :latitude  => :last_location_lat, :longitude => :last_location_long
```

Thanks for your help,

Ewa

**Comment by ewamarciniak** [comment]
Sorry, I have changed this to

```reverse_geocoded_by :last_location, :latitude  => :last_location_lat, :longitude => :last_location_long```

but it still gives me similar error:

```SELECT "users".* FROM "users"  WHERE (users.last_location IS NOT NULL AND users.{:latitude=>:last_location_lat, :longitude=>:last_location_long} IS NOT NULL)
SQLite3::SQLException: unrecognized token: "{": SELECT "users".* FROM "users"  WHERE (users.last_location IS NOT NULL AND users.{:latitude=>:last_location_lat, :longitude=>:last_location_long} IS NOT NULL)```

**Comment by alexreisner** [comment]
Try this:

    reverse_geocoded_by :last_location_lat, :last_location_long
