### ISSUE TITLE
add ORM testing (in multiple environments) to test suite

### ISSUE THREAD

**Issue by TrangPham** [alexreisner/geocoder#813]
See the comment on #811 

We want to be able to test against multiple versions of Rails and different databases. "Ideally we want to run real queries on a real database, and do so in multiple versions of rails (3.0.x, 3.1.x, 3.2.x, 4.0.x, 4.1.x, 4.2.x) and against multiple database types (PostgreSQL, MySQL, SQLite, MongoDB)"

**Comment by TrangPham** [comment]
@alexreisner I've created an issue so that we can start the discussion. Please feel free to change the title and top comment as you see fit.

I was looking into possibly using Travis CI to run different test environments. Travis CI has support for this as mentioned here: http://docs.travis-ci.com/user/languages/ruby/#Testing-against-multiple-versions-of-dependencies-(Ruby-on-Rails%2C-EventMachine%2C-etc) What do you think of this solution?

**Comment by alexreisner** [comment]
Yes, Travis is already being used to test against all supported Ruby versions and that is definitely the approach we want to take for Rails versions as well. This may all be as simple as un-stubbing ActiveRecord (loading the real thing), creating some test objects (ideally using FactoryGirl), and running database queries (using `near` and other methods).

**Comment by TrangPham** [comment]
Agreed - I think it would be simpler than originally thought. 

Would the testing be done in the geocoder project itself or would we be updating the geocoder_test project?

**Comment by alexreisner** [comment]
The tests in the geocoder_test project are the ones we should start with. Would love to move them over to Geocoder and get rid of geocoder_test.

**Comment by TrangPham** [comment]
@alexreisner I was able to run the tests in the geocoder_test/rails30, though some of them are failing for me. I think the next step would be to get geocoder_test to run in travis-ci and then to have it run with multiple gemfile configurations.

What do you think about that?

**Comment by alexreisner** [comment]
Yeah, some of the tests fail. And it's partly for that reason that I think the best first step is actually to get just one test that queries the DB running in the main repository. (Then we can selectively bring in the tests from geocoder_test, and we may end up discarding some of them.) How does that sound?

**Comment by TrangPham** [comment]
Okay that sounds like a plan :)

**Comment by TrangPham** [comment]
@alexreisner What are the next steps for this issue? To migrate over the tests that are in `geocoder_test/base/test`?

**Comment by alexreisner** [comment]
Yes, we need to bring in the remaining tests, and I think we should use FactoryGirl instead of fixtures. Ideally we bring in the Mongo tests too.

The other major thing to do is to test against multiple versions of Rails. This is going to increase the size of the test matrix, obviously, but I think it's important.

**Comment by TrangPham** [comment]
I'm working on changing the build matrix for travis ci. The rails versions I'm working on including are 3.2 and 4.1 currently. 

```
  In Gemfile:
    mongoid (= 2.6.0) ruby depends on
      activemodel (~> 3.1) ruby
    rails (>= 4.1) ruby depends on
      activemodel (4.1.0)
```
Would it be okay if I moved the mongoid tests into their own folder and just did one build on travis for them?

**Comment by alexreisner** [comment]
There's no need to stick with that old version of Mongoid, which was selected back when Ruby 1.8 was still supported (see ca231420909b).

**Comment by TrangPham** [comment]
@alexreisner Should we close this issue?

**Comment by alexreisner** [comment]
Yes! Thank you!!
