### ISSUE TITLE
Geocoder call to Google returning 302 redirect only in production

### ISSUE THREAD

**Issue by nosolopau** [alexreisner/geocoder#814]
Hi!

First of all, thanks for your awesome work. I'm finding a weird problem and I was wondering if somebody here could help me :).

The problem is that Google is returning a 302 redirection with HTML code to the lookup request. For example:

    irb(main):002:0> Geocoder::Lookup.get(:google).send(:fetch_raw_data, Geocoder::Query.new("28005, Spain"))
    => "<HTML><HEAD><meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<TITLE>302 Moved</TITLE></HEAD><BODY>\n<H1>302 Moved</H1>\nThe document has moved\n<A HREF=\"http://ipv6.google.com/sorry/IndexRedirect?continue=http://maps.googleapis.com/maps/api/geocode/json%3Faddress%3D28005%252C%2BSpain%26language%3Den%26sensor%3Dfalse&amp;q=CGMSECoAGkh4BQEREdgKdv8IF3EYtLHWpwUiGQDxp4NLaWV3kRhjcdK_RmdGhGzZBE1ksho\">here</A>.\r\n</BODY></HTML>\r\n"

Any ideas?

**Comment by nosolopau** [comment]
Since the redirection points to `ipv6.google.com` I guess that is somehow related with IPv4/IPv6, is there a way to force the gem to use IPv4?

**Comment by craigsheen** [comment]
We had this too just now, but this seems to be fixed now.

**Comment by nosolopau** [comment]
O_o is working again. This is not usual :). Thanks, @craigsheen!
