### ISSUE TITLE
Google Directions

### ISSUE THREAD

**Issue by lipanski** [alexreisner/geocoder#815]
hi :dancers: 

I've written a Google Directions extension for Geocoder (currently as a monkey patch in our project). I've seen an issue around here concerning Google Directions, where you mentioned that it was not in the scope of this gem. however I'd say lots of people use the Google Maps APIs in a combined fashion so I'd be happy if you'd reconsider - especially because there will be no effort on your side but to review and hopefully merge my code :)

so the interface I imagined is pretty much the same as for the other lookups:

```ruby
# Search by address strings (departure, destination)
Geocoder.search(["Oranienstr. 25, 10999 Berlin", "Berlin Hauptbahnhof"], lookup: :google_directions)

# Search by coordinates
Geocoder.search([[12.0, 11.0], [10.0, 9.0]], lookup: :google_directions)

# Mixed search (to be tested)
Geocoder.search(["Oranienstr. 25, 10999 Berlin", [10.0, 9.0]], lookup: :google_directions)

# Search with waypoints
Geocoder.search(["Oranienstr. 25, 10999 Berlin", "Berlin Hauptbahnhof", "Tegel Airport"], lookup: :google_directions)

# Various options like language, alternatives, units will also be enabled in all of these calls.
```

you could also alias this call to someth more fancy like `Geocoder.directions("pickup", ..., "dropoff")` but I'm happy with the above suggestion as a starter.

the produced result contains the estimated distance, the estimated duration, the steps, the polyline, reverse geocoded address strings (in case coordinates are supplied) and coordinates (in case strings are supplied) + other stuff.

what do you think?

**Comment by alexreisner** [comment]
That all looks good, but I think it's still outside the scope of Geocoder. Sorry! Why not start your own gem?

**Comment by lipanski** [comment]
thanks for the quick answer. there are some things in `geocoder` that my Directions code would be needing anyway - like passing the API key / Google Premier keys, caching or handling errors in a unified way (cause they're pretty much the same errors like for all other Google lookups). putting this in a separate gem would mean doing these things twice and possibly in a different way, forking would make updates difficult - so I'll probably stick to my monkey patch extension thingy :monkey: opening up `Geocoder::Lookup.street_services=` actually helps with that.

and apart from that I was keen to share my code :)

btw Directions comes with a pretty cool feature: if you pass coordinates, the response will contain reverse geocoded addresses, and if you pass address strings, the response will contain their coordinates - so if you need both geocoding / reverse geocoding AND directions you can skip using the Geocoding API and take the results from your Directions call.

**Comment by TrangPham** [comment]
@lipanski You can create a gem which depends on and requires `geocoder` gem. :smile: That way you'll be able to rely on some of the API key passing and error handling that geocoder already provides.

**Comment by lipanski** [comment]
yes, @TrangPham that will be the next move :)

**Comment by zachfeldman** [comment]
@lipanski did you ever build this gem? Would you be willing to open source your code regardless?

**Comment by lipanski** [comment]
@zachfeldman no, I didn't. it's still in our code base and got a bit tailored for our own needs. if I've got some time, I'll take it out but no promises.

**Comment by zachfeldman** [comment]
@lipanski cool, I ended up using the google_directions gem instead. Thanks for the reply though!
