### ISSUE TITLE
request.safe_location in released gem?

### ISSUE THREAD

**Issue by Chris-VorData** [alexreisner/geocoder#821]
While experimenting with IP geocoding I followed the readme and tried using request.safe_location.  This caused an exception, and upon further inspection I realized this method isn't in the version of the gem I am using (1.2.0), nor in the latest (1.2.7).

I'm curious when this method will be made available in the released version of the gem.

**Comment by alexreisner** [comment]
It will be in version 1.2.8, to be released very soon (hopefully this week).

**Comment by alexreisner** [comment]
Gem version 1.2.8 just released.
