### ISSUE TITLE
Mapquest query url defaulting to licensed version

### ISSUE THREAD

**Issue by mgraulich** [alexreisner/geocoder#824]
I have not added licensed: true to Geocoder.configure and I am still routed to the licensed endpoint... **http://www.mapquestapi.com/geocoding/v1/address** instead of **http://open.mapquestapi.com/geocoding/v1/address**. This is causing the Geocoding API's response was not valid JSON error.

**Comment by mgraulich** [comment]
Solved it.. maybe just add that **open: true** is required in the configuration so no one else runs into this. Thanks.

**Comment by alexreisner** [comment]
Thanks, you're right. Just fixed the readme.
