### ISSUE TITLE
adding constraints on distance

### ISSUE THREAD

**Issue by guyisra** [alexreisner/geocoder#826]
Can I do something like

```Venue.near('New York').where("distance > 3 AND distance < 5")```

Right now I am getting

```PG::UndefinedColumn: ERROR:  column "distance" does not exist```

**Comment by slamere** [comment]
Based and tested with mysql, `distance` isn't available in the `where` clause.  You could use `having` but a better option would be to modify your near call to something like:

`Venue.near('New York', 5, min_radius: 3)`

Refer to the source at:
https://github.com/alexreisner/geocoder/blob/8ba90c98712c23cdce72a0a85e05d73690ac54ad/lib/geocoder/stores/active_record.rb#L38-L49
and
https://github.com/alexreisner/geocoder/blob/8ba90c98712c23cdce72a0a85e05d73690ac54ad/lib/geocoder/stores/active_record.rb#L114-L151
