### ISSUE TITLE
.near method not working properly.

### ISSUE THREAD

**Issue by xingle** [alexreisner/geocoder#828]
I got the NewYork coordinate using Geocoder.coordinates("NewYork").

.near scope's coordinate parameter had to be reversed to get correct result.

Not working:
Place.near([40.7127837, -74.0059413], 3, unit: :km).count #this is not working.

Working:
Place.near([40.7127837, -74.0059413].reverse, 3, unit: :km).count #but this one does.

I think that latitude and longitude order should be persistent for all case. like [lat, lon]

PS: I am using Mongoid and Rails 4

**Comment by vleango** [comment]
@xingle I had something similar to that. By doing a for each loop I was able to get the records properly.

**Comment by xingle** [comment]
I had to use where statement instead of .near method.
places  = Place.where(:coords => {"$near" => center.reverse , '$maxDistance' => radius.to_f * 1000})
