### ISSUE TITLE
Geocoder and Google Maps Address Accuracy

### ISSUE THREAD

**Issue by vleango** [alexreisner/geocoder#831]
Hello, when I enter this address: 〒460-0008 愛知県名古屋市中区栄3-23-5 ARROW SAKAE BLD 2F

I get from geocoder:
35.166923, 136.903681

From Google maps I get:
35.165000, 136.904100

Just wondering how can I get my address to be more accurate and resemble the Google Maps Coordinates?

Please Note: When I enter this address: 〒460-0008 愛知県名古屋市中区栄3-23-5

I get from geocoder:
35.164924, 136.904162

Which is very close to Google Maps....

**Comment by alexreisner** [comment]
Please see #718.

**Comment by vleango** [comment]
@alexreisner thank you for pointing it out
