### ISSUE TITLE
mapquest version 2 not working

### ISSUE THREAD

**Issue by anazar** [alexreisner/geocoder#833]
Specifying version 2 for mapquest is causing geocoder to throw the error:
```
Geocoding API's response was not valid JSON
```

Removing the version: 2 setting works fine.

**Comment by alexreisner** [comment]
Version 2 has never officially been released (see [discussion](http://developer.mapquest.com/web/products/forums/-/message_boards/message/487692;jsessionid=WkNWFWcAUEal5fp7BQ5l.3)). If requests to the API are no longer working, Geocoder support should probably be dropped.

@jezstephens any thoughts on this?

**Comment by TrangPham** [comment]
I agree that the configuration for mapquest lookup to use version 2 should be removed.

**Comment by alexreisner** [comment]
Version config has been removed.
