### ISSUE TITLE
Problem with Rspec when using 'open: true' option for Mapquest.

### ISSUE THREAD

**Issue by bood-pvb** [alexreisner/geocoder#835]
When I use the mapquest without `open: true` everything is fine.
But when I add `open: true`
```
# initializers/geocoder.rb
Geocoder.configure(
  cache: REDIS,
  cache_prefix: 'geocoder:',
  mapquest: {
    api_key: Rails.application.secrets.geocoder['mapquest'],
    open: true
  }
)
```
I got this:
```
# output
     Failure/Error: load = create(:load, origin_city: 'Parker',
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /home/pvb/.rvm/gems/ruby-2.2.1@shinnyrock/gems/geocoder-1.2.8/lib/geocoder/lookups/mapquest.rb:41:in `results'
     # /home/pvb/.rvm/gems/ruby-2.2.1@shinnyrock/gems/geocoder-1.2.8/lib/geocoder/lookups/base.rb:47:in `search'
     # /home/pvb/.rvm/gems/ruby-2.2.1@shinnyrock/gems/geocoder-1.2.8/lib/geocoder/query.rb:11:in `execute'
     # /home/pvb/.rvm/gems/ruby-2.2.1@shinnyrock/gems/geocoder-1.2.8/lib/geocoder.rb:21:in `search'
     # /home/pvb/.rvm/gems/ruby-2.2.1@shinnyrock/gems/geocoder-1.2.8/lib/geocoder/stores/base.rb:111:in `do_lookup'
     # /home/pvb/.rvm/gems/ruby-2.2.1@shinnyrock/gems/geocoder-1.2.8/lib/geocoder/stores/active_record.rb:259:in `geocode'

```
This occurs only in the tests, and only for `open: true`. In the console, everything works fine.
Rails 4.1.4; Geocoder 1.2.8
Thank you for your attention.

**Comment by TrangPham** [comment]
Hi @bood-pvb 

Could I ask you to clarify what you meant by `occurs only in the tests`. Do you mean the geocoder tests or your application's tests? If it's for your application tests, are you using `Geocoder.configure(:lookup => :test)` as shown in the readme?  

Thanks

**Comment by bood-pvb** [comment]
Hi @TrangPham,
In my application tests. I'll try to make a new project and reproduce the bug.
I guess that the problem is not the geocoder but my application.
Thank you for the response.

**Comment by plicjo** [comment]
Hey @bood-pvb,  did to you get this figured out?

**Comment by bood-pvb** [comment]
Yes. I did. In general, the problem is caching.
For some reasons my Redis contains cached queries for `open.mapquestapi.com` but not for `mapquestapi.com`. But the strange thing is that the cached responses are wrong(or something like that)

```
    def results(query)
      return [] unless doc = fetch_data(query)
      return doc["results"][0]['locations'] if doc['info']['statuscode']
```
**doc[info]** looks correct:
`{"copyright"=>{"text"=>"© 2015 MapQuest, Inc.", "imageUrl"=>"http://api.mqcdn.com/res/mqlogo.gif", "imageAltText"=>"© 2015 MapQuest, Inc."}, "statuscode"=>0, "messages"=>[]}`

but **doc[results]** is nil.

I don't have time to figure it out properly, I just turned off the caching for test environment.

So, i think that it's not a bug. Thanks.
