### ISSUE TITLE
geoip2 and maxminddb do not work

### ISSUE THREAD

**Issue by zekus** [alexreisner/geocoder#836]
the maxminddb result set do not support the fetch method. The latest version of the maxminddb gem includes a "to_hash" method that perhaps is sueful to make the resultset compatible with the current geoip2 implementation again.
```ruby
[1] pry(main)> g = Geocoder.search "205.189.0.33"
[2] pry(main)> g.first.country
NoMethodError: undefined method `fetch' for #<MaxMindDB::Result:0x00000103ede6b8>
from /Users/zekus/.rvm/gems/ruby-2.1.2@archisnapper/gems/geocoder-1.2.8/lib/geocoder/results/geoip2.rb:36:in `country'
```

**Comment by TrangPham** [comment]
Thanks zekus. 

The change in maxminddb gem which caused this was: https://github.com/yhirose/maxminddb/commit/7b902ece6023d1844474802cbc663855ac33de81

Wherein `Hash(raw)` changed to `raw || {}`

`.fetch` is a method on Hash. Assuming that it worked previously to v0.1.7 of maxminddb gem. Then all that needs to be added is `to_hash` on `@data`. `to_hash` on a hash returns a hash, so this will support older and current versions of maxminddb gem as well as working with Hive::Geoip2.

**Comment by alexreisner** [comment]
Closing, thanks to #837.
