### ISSUE TITLE
Partial postcode search

### ISSUE THREAD

**Issue by kitation** [alexreisner/geocoder#838]
We have a Meeting Rails model with address and full postcode (example: "S1 4SA"). Doing `Meeting.near("S1 4SA")` returns the right results, but `Meeting.near("S1")` returns an empty result. 

We are using the default APIs. Search for "S1" on Google Maps works as expected. Is this an issue with the API?

**Comment by alexreisner** [comment]
Yep, it's an issue with the API, which does not return the same results as a Google Maps search (which is augmented with other data sources).
