### ISSUE TITLE
Caching returns nil

### ISSUE THREAD

**Issue by peteb** [alexreisner/geocoder#840]
After a while, geocoding lookups (for example `Geocoder::coordinates`) starts returning `nil` immediately without any network activity and when Redis caching is enabled. It's fixed by issuing a redis `flushall` command, so my bet is that something's weird with caching.
I *think* it only happens for some addresses (those already cached?)

Geocoder version: 1.2.7
Rails version: 4.1.4

**Comment by alexreisner** [comment]
It looks like we need a definition of `Geocoder::Lookup::Bing#valid_response?` that checks `doc['statusCode']`, not just the HTTP response code. Pull request welcome.

**Comment by peteb** [comment]
Alright, thanks. I'll take a shot at fixing this.

**Comment by peteb** [comment]
Should caching be affected by :always_raise? Because if I set that to :all, and catch Geocoder::ServiceUnavailable, the cache isn't updated. The cache is only updated with incorrect values when the error isn't raised, which seems to be how it works for Google lookups as well. I think this is unexpected behavior, would you agree?

**Comment by alexreisner** [comment]
Yes, I agree. Good question. Raising the exception stops execution before the response can be added to the cache. But the cache should reject such responses regardless of whether an exception is raised. Again, this should be addressed in `Geocoder::Lookup::Bing#valid_response?`.
