### ISSUE TITLE
question: mapquest free via geocode command line?

### ISSUE THREAD

**Issue by tony-kerz** [alexreisner/geocoder#842]
```
Geocoder.configure(:mapquest => {:open => true})
```
is there anyway to tell the command line to use mapquest open api...?

**Comment by TrangPham** [comment]
Currently there is not, the command line options are all defined in https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/cli.rb

@alexreisner Do you think that we should be adding an option to configure a specific lookup? There a a few that have special options.

**Comment by alexreisner** [comment]
@TrangPham I'm open to this idea, but to anyone interested in submitting a pull request: let's discuss the approach before spending too much time on code. I want to make sure we limit the number of command line options added to achieve this.

**Comment by tony-kerz** [comment]
so, kicking the tires on a couple of providers, and also this morning attempting to make command line call to `:google_premier` and have similar question. i did try:
```
geocode -s google_premier -k "<a key> <a client> <a channel>" "<an address>"
```
and that didn't seem to work, so could be another case for 'special options'....

**Comment by tony-kerz** [comment]
actually, disregard the above, that space separated syntax works great for the multi-part google-premier key, i originally had a copy-paste mishap ;)
