### ISSUE TITLE
Question: Large number of address

### ISSUE THREAD

**Issue by kittrCZ** [alexreisner/geocoder#846]
Hi, 
my apologies for spamming your Issues section, but I have question regarding large number of records which I need to process with Geocoder and I haven't found better place where to ask.

I have currently database with around 600k records and every record has address in this format - _'751 Diamond St, San Francisco, CA 94114'_ and from this address I need to obtain longitude and latitude for every each one of them.

I've tried already __Bing__ and __Google APIs__, but as you might think, the limit is problem when using Google and I can't afford to pay for business version. So, I switched to Bing and it works fine, but I'm having issues with that also - for some reason it seems like the Bing API is not working properly, because I'm getting large number of responses: ___Bing Geocoding API error: Service Unavailable___. 

I have tried several approaches. For instance, I call Bing API simply by code:
```
query = row['adr'] # Where address is in following format: '751 Diamond St, San Francisco, CA 94114'
Geocoder.search(query).first 
```
And when calling this in loop, I'm getting following responses:
```
Bing Geocoding API error: Service Unavailable
Inserting: 751 Diamond St, San Francisco, CA 94114
Bing Geocoding API error: Service Unavailable
Bing Geocoding API error: Service Unavailable
Inserting: 1768 Divisadero St, San Francisco, CA 94115
Inserting: 2135 3rd St, San Francisco, CA 94107
Bing Geocoding API error: Service Unavailable
```

This is related to this [code](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/bing.rb#L59) and I don't know, how to resolve this, because I can see these responses frequently. Do you have any suggestions on resolving this issue?

__Questions__
  * Does someone have experience with processing such amount of data? 
  * Is there any option to accomplish it for free in feasible time period? 
  * Do you know about any other service which provides trustworthy data?
  * _Bonus question: Why the hell is this kind of service so expensive?:)_

Thank you for all advices and suggestions.

----
[Bing API - Error Codes & Responses](http://api-portal.anypoint.mulesoft.com/microsoft/api/bing-maps-geocode-service-api/docs/responses)

**Comment by kittrCZ** [comment]
@alexreisner Why did you close it? I think this is not a bad question. Do you have any advice on this?

**Comment by alexreisner** [comment]
I closed it because it's not a Geocoder issue/bug, but rather a property of all available geocoding services. A better place to ask is StackOverflow, where you'll get a lot more eyes on it anyway.

I don't really have any suggestions. Geocoding services are expensive and rate limited because there's a tremendous amount of work that goes into creating and maintaining them. Companies can't just give unlimited service away for free.

**Comment by rafamvc** [comment]
Having the same issue, and google brought me here instead of SO. Did you ever figure out what was going on?

**Comment by kittrCZ** [comment]
@rafamvc Well I dockerize the code and distributed it to several workers with different IP addresses and Access Keys. But I still see the issue and didn't waste more time with that. I just hammered the API with requests unless it was all resolved.
