### ISSUE TITLE
Opt out from extending Active Record

### ISSUE THREAD

**Issue by morgoth** [alexreisner/geocoder#851]
Currently it's impossible to not load AR extensions in Rails apps.
Would you consider a change to extend AR just by including explicit some geocoder module?
Something like:
```
class User < ActiveRecord::Base
  include Geocoder::ActiveRecord
end
```
If no, maybe option in configuration to opt out from it would be possible to add?

**Comment by alexreisner** [comment]
Yes, that seems reasonable. I would consider a pull request.

**Comment by morgoth** [comment]
Which version do you prefer?
The first one looks more clear, but it would be backward incompatible.
I believe this also apply to mongoid and mongomapper extensions

**Comment by alexreisner** [comment]
Definitely don't want to introduce anything that would break anyone's app. Maybe configuration is the way to go.

**Comment by morgoth** [comment]
I tried with adding config, but looks like it's impossible. `Geocoder.configure` is usually placed in initializer, where the rails application is already loaded, thus it's after the gem configuration done in `Railtie`, where we would like to opt out based on user set config.

I'm also not sure what would be the best way of deprecating it, if we decide to switch to explicit extend:
```
class User < ActiveRecord::Base
  extend Geocoder::Model::ActiveRecord
end
```

**Comment by alexreisner** [comment]
While I acknowledge the benefits of this, I don't like the idea of requiring an explicit extend. First priority is not to break apps (which includes deprecating things). But like I said, this is desirable functionality and I remain open to a pull request.

Closing for now.
