### ISSUE TITLE
Confidence or quality indicator?

### ISSUE THREAD

**Issue by slead** [alexreisner/geocoder#856]
Awesome plugin - thanks for writing it.

Are you able to provide a measure of the geocode's confidence level or quality indicator? eg, If you input an address of "6", you get the coordinates (33.8166949, -116.5147457).

Clearly this should have a lower quality rating than a fully-qualified address.

**Comment by alexreisner** [comment]
Some APIs (eg, Yahoo) return a "quality" attribute, and some don't. The Geocoder gem has no way of evaluating quality of results outside of what's returned by a geocoding request.
