### ISSUE TITLE
Valid lookup error for geoip2

### ISSUE THREAD

**Issue by sayem** [alexreisner/geocoder#857]
I'm trying to use my local GeoIP2 database for making IP lookups with geocoder, but I keep getting this error: 

`ActionView::Template::Error (Please specify a valid lookup for Geocoder (:geoip2 is not one of: :dstk, :esri, :google, :google_premier, :yahoo, :bing, :geocoder_ca, :geocoder_us, :yandex, :nominatim, :mapquest, :ovi, :baidu, :test, :freegeoip, :maxmind).)`

This is on Rails 4.2.1 and Ruby 2.1.5. Added both geocoder and maxminddb to my Gemfile. And I'm configuring the initializer the same way mentioned on the Readme: 

```ruby
Geocoder.configure( ip_lookup: :geoip2, geoip2: { file: File.join('folder', 'GeoLite2-City.mmdb') } )
```

I noticed that when I simply go to irb, require the geocoder and maxminddb gems, and configure my geolite database, doing a Geocoder.search(ip-address) query goes through successfully using that MaxMind DB. I'm only running into that error within Rails for some reason...

**Comment by alexreisner** [comment]
What version of geocoder is in your Rails app's `Gemfile.lock`?

**Comment by sayem** [comment]
geocoder (1.1.9)

**Comment by alexreisner** [comment]
You'll need to upgrade to 1.2.6 or later to use :geoip2.
