### ISSUE TITLE
Geocoder::Calculations.distance_between returns distance in km.

### ISSUE THREAD

**Issue by ajinkyaghorpade** [alexreisner/geocoder#858]
The documentation for Geocoder::Calculations.distance_between method mentions that the distance is returned in miles ->
"# distance (in miles) between Eiffel Tower and Empire State Building
Geocoder::Calculations.distance_between([47.858205,2.294359], [40.748433,-73.985655])
 => 3619.77359999382"

I tried the method to calculate distance between two points as follows -
Geocoder::Calculations.distance_between([1.3075366324333333,103.76218967612083],[1.306306,103.76228100000003])
 => 0.13721615685642177

Calculated same distance in movable-type.co.uk and following were the results 
Distance: 	0.1372 km (to 4 SF*)
Initial bearing: 	175°45′25″
Final bearing: 	175°45′25″
Midpoint: 	01°18′25″N, 103°45′44″E

Notice that the distance of 0.1372 is in km not in miles. The distance in miles using the haversine formula is 0.0852145259814396.
I think similar issue exists in the near method perhaps because same distance calculation procedure is followed there.

Please give it a look. 
Thanks!

**Comment by alexreisner** [comment]
The method will actually use whatever units you have set in `Geocoder.configure(units: ...)`. Documentation might need to be updated...
