### ISSUE TITLE
After putting in Stub, can only use Stubs

### ISSUE THREAD

**Issue by jdkealy** [alexreisner/geocoder#859]
According to docs, I should be able to put in a stub, and if it's not defined, it will look it up like normal. I wasn't sure where to define the stubs. I tried in both an initializer and just in IRB, but both examples had the same issue  "ArgumentError: unknown stub request xxx " 

irb(main):003:0> Geocoder.configure(:lookup => :test)

=> {:timeout=>3, :lookup=>:test, :ip_lookup=>:freegeoip, :language=>:en, :http_headers=>{}, :use_https=>false, :http_proxy=>nil, :https_proxy=>nil, :api_key=>nil, :cache=>nil, :cache_prefix=>"geocoder:", :basic_auth=>{}, :logger=>:kernel, :always_raise=>[], :units=>:mi, :distances=>:linear}

irb(main):005:0* Geocoder::Lookup::Test.add_stub(
irb(main):006:1*   "New York, NY", [
irb(main):007:2*     {
irb(main):008:3*       'latitude'     => 40.7143528,
irb(main):009:3*       'longitude'    => -74.0059731,
irb(main):010:3*       'address'      => 'New York, NY, USA',
irb(main):011:3*       'state'        => 'New York',
irb(main):012:3*       'state_code'   => 'NY',
irb(main):013:3*       'country'      => 'United States',
irb(main):014:3*       'country_code' => 'US'
irb(main):015:3>     }
irb(main):016:2>   ]
irb(main):017:1> )

=> [{"latitude"=>40.7143528, "longitude"=>-74.0059731, "address"=>"New York, NY, USA", "state"=>"New York", "state_code"=>"NY", "country"=>"United States", "country_code"=>"US"}]

irb(main):018:0> Geocoder.search("Paris")
ArgumentError: unknown stub request Paris

**Comment by alexreisner** [comment]
Don't you mean to use:

    Geocoder.search("New York, NY")

?

**Comment by jdkealy** [comment]
No, I mean... I thought the Geocoder would look up Paris because Paris is not defined as a stub. How do U get geocoder to look up all the non-defined stubs when requested ?

**Comment by alexreisner** [comment]
That's not how the :test lookup works. I think I see where [the README](https://github.com/alexreisner/geocoder#testing-apps-that-use-geocoder) may have confused you:

    Any query that hasn't been explicitly stubbed will return that result.

That sentence refers to the default stub set the example just above it.

**Comment by alexreisner** [comment]
README has been edited for clarity.
