### ISSUE TITLE
Issue after adding API Key

### ISSUE THREAD

**Issue by jasonrhalpern** [alexreisner/geocoder#860]
I have used geocoder in my app for a little while in development and just added the API Key that I got from them (license) to Geocoder.rb. Then my app started returning 'Google Geocoding API error: request denied' whenever it made a request to Google. The only thing that changed was adding the :api_key to the initializer and also adding :lookup => google. Any reason why that would cause an issue?

**Comment by alexreisner** [comment]
Try adding `:use_https => true` to your config.

**Comment by jasonrhalpern** [comment]
Perfect, that did it. This gem is awesome by the way, very much appreciated.
