### ISSUE TITLE
Here maps multi reverse geocode

### ISSUE THREAD

**Issue by andreimc** [alexreisner/geocoder#862]
https://developer.here.com/rest-apis/documentation/geocoder/topics/resource-multi-reverse-geocode.html

Hey I am just wondering how hard it would be to add multi reverse geocode ?

I haven't look how the results are structured but assuming you could have a multi mode where you just return an array of results?

**Comment by alexreisner** [comment]
I'm open to a pull request for this, but it probably requires (or at least _should_ use) a new method. It's also a feature that's only supported by one lookup (AFAIK) so I don't see it as high priority and would want the implementation to be as slim as possible.
