### ISSUE TITLE
Geocoder failing in Postgres / Rails 4.1

### ISSUE THREAD

**Issue by lacostenycoder** [alexreisner/geocoder#869]
Geocoder not working.... everything is failing.  This just started

TypeError - nil can't be coerced into Float:
  geocoder (1.2.6) lib/geocoder/calculations.rb:54:in `*'
  geocoder (1.2.6) lib/geocoder/calculations.rb:54:in `latitude_degree_distance'
  geocoder (1.2.6) lib/geocoder/calculations.rb:217:in `bounding_box'
  geocoder (1.2.6) lib/geocoder/stores/active_record.rb:129:in `near_scope_options'
  geocoder (1.2.6) lib/geocoder/stores/active_record.rb:41:in `block (2 levels) in included'
 ....

And even basic calculation in Rails console throw same error:

Geocoder::Calculations.distance_between([47.858205,2.294359], [40.748433,-73.985655])
# => TypeError: nil can't be coerced into Float

**Comment by lacostenycoder** [comment]
Found unrelated error causing this... please disregard

**Comment by karlwilbur** [comment]
@lacostenycoder I'm seeing the same thing on a new project. Can you share the 'unrelated' cause that you found?

Everything seems to be set up the same as my other working installation of Geocoder.

**Comment by karlwilbur** [comment]
Ah ha! I found my problem. I had an incorrect value in my initializer. I had:
```ruby
# config/initializers/geocoder.rb
Geocoder.configure(
  ...
  # set default units to miles:
  units: :miles,
  ...
)
```

...when I should have:
```ruby
# config/initializers/geocoder.rb
Geocoder.configure(
  ...
  # set default units to miles:
  units: :mi,
  ...
)
```
