### ISSUE TITLE
Geocoder manipulating queries with has_many association. 

### ISSUE THREAD

**Issue by aditya01933** [alexreisner/geocoder#874]
I am using Geocoder Gem, it is showing wired behavior.

I have Location model

    class Location < ActiveRecord::Base
    has_many :events
    geocoded_by :address
    after_validation :geocode
    def full_address
        "#{postal_code}, #{city}, #{street}"
      end
    end

and Event model

    class Event < ActiveRecord::Base
        belongs_to :location
        accepts_nested_attributes_for :location
    end

I want to find all events nearby the current user's location.

I tried following steps to find nearby locations..

    nearby_loc = current_user_location.nearby

it is returning all nearby "locations" of current users location

Then I tried 

    nearby_loc.events

but it is giving me error

    NoMethodError: undefined method `events' for #<ActiveRecord::Relation::ActiveRecord_Relation_Location:0x0000000958c088>
      
    
Please help me ...

**Comment by alexreisner** [comment]
`nearby_loc` is an `ActiveRecord::Relation` of `Location` objects. You'll have to call `events` on each member, eg:

    nearby_loc.map(&:events).flatten.uniq

But note that this is not very performant. Alternatively you can try the technique proposed by @mgates in #26.
