### ISSUE TITLE
Lookup Yandex - Geocoding API's response was not valid JSON.

### ISSUE THREAD

**Issue by ZuevEvgenii** [alexreisner/geocoder#878]
Test request: 

`Geocoder::Lookup.get(:yandex).send(:fetch_raw_data, Geocoder::Query.new("New York"))`

Response: 

`Geocoder: HTTP request being made for http://geocode-maps.yandex.ru/1.x/?format=json&geocode=New+York&plng=en
 => "<html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>nginx/1.6.3</center>\r\n</body>\r\n</html>\r\n" `

Geocoder version 1.2.9

**Comment by alexreisner** [comment]
This was fixed by #876. Please install from current `HEAD` until the next version is released (will be very soon).

**Comment by tilthouse** [comment]
FYI: Setting `:use_ssl` in the configuration did not do any thing. However, `:use_https` worked.

**Comment by alexreisner** [comment]
@tilthouse thanks! You are correct. My mistake.
