### ISSUE TITLE
Any simple way to get the full street address (street number + route)?

### ISSUE THREAD

**Issue by ylluminate** [alexreisner/geocoder#880]
I've been poking about here and it appears that in order to get the full street address we kind of have a hit and miss scenario.  I find that sometimes the `route` field contains the `street_number` and sometimes it does not.  I haven't found a rhyme or reason to this, but my ultimate goal is to simply get some very well defined fields:
* address (street_number + route / street)
* city
* state
* zip
* latitude
* longitude

I'm doing something along the following lines to get these fields, but like I said, I find that I'm really hitting odd issues that I suspect are a result of not using your library properly:
```    
result = Geocoder.search(full_address_to_verify)
    if result != []
      street_address = result[0].address_components[1]["long_name"]
      city = result[0].address_components[2]["long_name"]
      state = result[0].address_components[5]["long_name"]
      zip = result[0].address_components[7]["long_name"]
    end  
```

Is there a cleaner and more reliable way to do this?

**Comment by alexreisner** [comment]
This actually has to do with the way Google returns results. Geocoding and street addresses are very complicated and it's not always possible to return all fields for all coordinates. You might want to try a different geocoding service. If you're doing address verification maybe take a look at SmartyStreets?
