### ISSUE TITLE
Geocoded by related address

### ISSUE THREAD

**Issue by bighoax** [alexreisner/geocoder#882]
I'm using this gem with mysql database, and I want to get the students nearby each other. And I have in my Student model :

```
has_one :address
geocoded_by :address
```

And in my address:

```
belongs_to :student
reverse_geocoded_by :latitude, :longitude
```

When I do this:

```
Student.near([40.71, -100.23], 20)
```

I get this error :

```
ActiveRecord::JDBCError: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'students.latitude' in 'field list':
```

I don't have `lat/lng` in my `students` table, I have it in the `addresses` table, so what am I doing wrong here? Looking to get nearby students

**Comment by alexreisner** [comment]
These might be helpful: #874, #294, #26.
