### ISSUE TITLE
Licence details wrong for OSM sources

### ISSUE THREAD

**Issue by systemed** [alexreisner/geocoder#883]
README.md currently states "Data licensed under CC-BY-SA (you must provide attribution)" for Nominatim and OpenCageData. This was once the case, but since September 2012, OpenStreetMap data has actually been licensed under the Open Database Licence.

Linking to openstreetmap.org/copyright is the accepted standard for explaining OSM licence terms.

**Comment by alexreisner** [comment]
Thanks for pointing this out! Fixed by the above commit.

**Comment by systemed** [comment]
Thanks!
