### ISSUE TITLE
How to do Geocoding multiple times in 1 Model?

### ISSUE THREAD

**Issue by montecillodavid** [alexreisner/geocoder#884]
Ive got from_address and to_address which uses `Model Configuration` 

This is inside my Route Base Model

geocoded_by :from_address, :latitude  => :from_lat, :longitude => :from_lon 
after_validation: geocode

geocoded_by :to_address, :latitude  => :to_lat, :longitude => :to_lon 
after_validation: geocode

The problem is I can only get the to_address -> latitude and longitude NOT the from 
I need help , how to solve this?

**Comment by alexreisner** [comment]
You'll have to write your own callback and do the lookups in that method (see #784 for an example).
