### ISSUE TITLE
[Question] Does .near affect quota usage?

### ISSUE THREAD

**Issue by cristianrosu** [alexreisner/geocoder#888]
Hi, I just wanted to know if .near method geocodes the passed param, and if so, it adds up to the daily limit usage enforced by Google? Thanks in advance for the answers/

**Comment by alexreisner** [comment]
If you pass something that needs to be geocoded (ie, a street address) then yes, it will be geocoded and count towards your quota. If you pass an array of coordinates there will be no geocoding.
