### ISSUE TITLE
MySQL server version for the right syntax to use near 

### ISSUE THREAD

**Issue by joshuawatson** [alexreisner/geocoder#890]
I used this method 

    Model.near("location", 10)

but im getting this error.

    Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') BETWEEN 0.0 AND 20)  ORDER BY distance ASC' at line 1: SELECT spree_store_locations.*, MOD(CAST((ATAN2( ((spree_store_locations.longitude - 80.2707184) / 57.2957795), ((spree_store_locations.latitude - 13.0826802) / 57.2957795)) * 57.2957795) + 360 AS decimal), 360) AS bearing FROM `spree_store_locations` INNER JOIN `spree_cities` ON `spree_cities`.`id` = `spree_store_locations`.`city_id` INNER JOIN `spree_states` ON `spree_states`.`id` = `spree_store_locations`.`state_id` INNER JOIN `spree_countries` ON `spree_countries`.`id` = `spree_store_locations`.`country_id` WHERE (spree_store_locations.latitude BETWEEN 12.902815878816254 AND 13.262544521183747 AND spree_store_locations.longitude BETWEEN 80.08606119708678 AND 80.45537560291324 AND () BETWEEN 0.0 AND 20)  ORDER BY distance ASC
    ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') BETWEEN 0.0 AND 20)  ORDER BY distance ASC' at line 1: SELECT spree_store_locations.*, MOD(CAST((ATAN2( ((spree_store_locations.longitude - 80.2707184) / 57.2957795), ((spree_store_locations.latitude - 13.0826802) / 57.2957795)) * 57.2957795) + 360 AS decimal), 360) AS bearing FROM `spree_store_locations` INNER JOIN `spree_cities` ON `spree_cities`.`id` = `spree_store_locations`.`city_id` INNER JOIN `spree_states` ON `spree_states`.`id` = `spree_store_locations`.`state_id` INNER JOIN `spree_countries` ON `spree_countries`.`id` = `spree_store_locations`.`country_id` WHERE (spree_store_locations.latitude BETWEEN 12.902815878816254 AND 13.262544521183747 AND spree_store_locations.longitude BETWEEN 80.08606119708678 AND 80.45537560291324 AND () BETWEEN 0.0 AND 20)  ORDER BY distance ASC

**Comment by alexreisner** [comment]
It looks like the `distance` calculation is not being included in the query. Are you passing any options to `.near`? (Can you please copy/paste an actual console session that produces the error? Hard to debug without details.)

**Comment by joshuawatson** [comment]
@alexreisner it is working on Ubuntu 14.04, when i tested in Ubuntu 12.04 it not working .

Thanks,
Joshva
