### ISSUE TITLE
When geocoding fails after updating an address the latitude / longitude remains

### ISSUE THREAD

**Issue by fschwahn** [alexreisner/geocoder#892]
Hi,
I'm using geocoder with ActiveRecord, as follows:

```ruby
class Address < ActiveRecord::Base
  geocoded_by :full_address
  after_validation :geocode, if: :full_address_changed?
  ...
end
```

When a valid address was entered in the past (and therefore latitude and longitude are set), and the address is changed to an invalid address (thus geocoding fails), the old latitude / longitude values remain. Is there any possibility to catch this and set latitude/longitude to nil when geocoding failed?

All the best,
Fabian

**Comment by fschwahn** [comment]
For the record, I solved it as follows:

```ruby
class Address < ActiveRecord::Base
  geocoded_by :full_address
  after_validation :geocode_or_reset_coordinates, if: :full_address_changed?
  ...

  private

    def geocode_or_reset_coordinates
      if geocode.nil?
        self.latitude = nil
        self.longitude = nil
      end
    end
end

```

**Comment by shakycode** [comment]
@fschwahn Where do you get `full_address_changed?` from?

**Comment by fschwahn** [comment]
@shakycode I have several columns (line1, line2, city, zipcode, etc.), and this function just or's together all the dirty-methods:

```
def full_address_changed?
  line1_changed? || line2_changed? || city_changed? || ...
end
```

**Comment by shakycode** [comment]
@fschwahn figured it was something like that, appreciate the explanation. :+1:
