### ISSUE TITLE
Bulk geocoding with ActiveRecord silent failure

### ISSUE THREAD

**Issue by l3iodeez** [alexreisner/geocoder#894]
I am trying to reverse geocode a list of coordinates in my model "Sites", and save the city, state and zip of each site to my model. I set everything up per the readme, but when I run "bundle exec rake geocode:all CLASS=Site SLEEP=0.25 BATCH=100" nothing happens, no error message or anything, and no geocoding. 

EDIT:
Reverse geocoding works properly when I create or update a site record, its just the rake job that is failing. 

site.rb : 

        class Site < ActiveRecord::Base
        reverse_geocoded_by :latitude, :longitude do |obj,results|
             if geo = results.first
             obj.city    = geo.city
             obj.zip = geo.postal_code
             obj.state = geo.state_code
             end
         end	
         after_validation :reverse_geocode  # auto-fetch address
         end

**Comment by alexreisner** [comment]
The rake task is for (forwards) geocoding only. Would be open to a pull request adding reverse geocoding, though.
