### ISSUE TITLE
Option to require only needed lookups

### ISSUE THREAD

**Issue by dgilperez** [alexreisner/geocoder#898]
Hi!

I was playing with [derailed_benchmarks](https://github.com/schneems/derailed_benchmarks) to benchmark the memory usage of my app and I realized *geocoder* is one of the most mem-consuming gems in my bundle. This is the derailed output, cut off at 0.8MiB.

    geocoder: 5.9883 MiB
      geocoder/lookup: 5.1445 MiB
        geocoder/lookups/maxmind: 1.4063 MiB
          csv: 1.2539 MiB

The reason for such a footprint is that geocoder is requiring any possible lookup method, even if the app will not use it. I was thinking in a way to require only the lookup methods I was actually going to use, and I found they are hardcoded in [Geocoder::Lookup](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookup.rb). 

Do you think reopening that module and changing `street_services` and `ip_services` is the way to go? Any better idea? Will it actually work? If so, would you accept a PR that adds this feature as a configuration option?

Thanks!

**Comment by alexreisner** [comment]
Hmm...I just checked out derailed_benchmarks and I get the following (similar on multiple projects):

    geocoder: 1.3203 MiB
      geocoder/lookup: 1.2578 MiB
        geocoder/lookups/maxmind: 0.3828 MiB
          csv: 0.332 MiB

Nevertheless, thanks for this, and I am interested in keeping Geocoder's memory use low. It used to be that only the configured lookups would be loaded, but for performance and usability reasons that was changed a couple of years ago. If you can describe your solution in a little more detail (what do you mean by "reopening" Geocoder::Lookup?) I'm open to discussion, but I don't want to lose the performance and usability benefits of loading all the lookups on init. Keep in mind that lookups may not all be specified at load time but selected and configured while the app is running.

**Comment by dgilperez** [comment]
Thanks for the fast response. Actually, I'm seeing varying outputs for derailed_benchmarks depending on the CUT_OFF value, the project or at each execution of the command on the same project ... for the latter, I see values ranging from 6MiB to 2.8MiB. I don't know why is that. 

Anyway, I still think adding the ability to selectively load lookups should improve the memory footprint. I was thinking in a configuration option for Geocoder with the list of the `street_services` and `ip_services` enabled, that would default to the lists now hardcoded [here](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookup.rb#L22). 

Roughly sketched and without knowing the internals of Geocoder, that's what I thought:

    # config/initializers/geocoder.rb
    Geocoder.configure(
      street_services_enabled: [:google, :bing, :mapquest],
      ip_services_enabled: [baidu_ip, :freegeoip]
    )

And in `Lookup``

    # lib/geocoder/lookup.rb
    module Geocoder
      module Lookup
        def street_services
          @street_services ||= Geocoder.config.street_services_enabled
        end

        def ip_services
          @ip_services ||= Geocoder.config.ip_services_enabled
        end
      end
    end

    # lib/geocoder/configuration.rb
    module Geocoder
       class Configuration
          # modify OPTIONS constant
          
          # move defaults from lookup.rb to a default here
          def set_defaults
             # ...
             @data[:street_services_enabled] = [:dstk, :esri, :google, ...]
             @data[:ip_services_enabled] = [:baidu_ip, :freegeoip, ...]
          end
       end
    end

That way, `Geocoder::Lookup.all_services` will have a restricted set of lookups, and only those would be required [here](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookup.rb#L22), thus reducing required classes.

Does any of this make sense?

**Comment by alexreisner** [comment]
By the way, Geocoder used to require lookups only as needed. That changed with #305. (cc @TrangPham)

**Comment by TrangPham** [comment]
@dgilperez Thanks for bringing this up!

We have reverted to the old method of requiring the lookups upon their usage. 

After the changes I am seeing:
  geocoder: 1.1484 MiB
    geocoder/request: 0.4648 MiB
      rack/request: 0.4453 MiB
        rack/utils: 0.3398 MiB
    geocoder/lookup: 0.3672 MiB

:dancer:
