### ISSUE TITLE
Merge two models in a many-to-many relation in rails using postgres

### ISSUE THREAD

**Issue by tobiasfeistmantl** [alexreisner/geocoder#905]
Used versions:
Geocoder - 1.2.9
Rails - 4.2.2
Ransack - 1.6.6

I have the following many-to-many relationship:

    class CompanyLocation < ActiveRecord::Base
        has_many :product_availabilities, foreign_key: :company_location_id
        has_many :products, through: :product_availabilities
    end

    class ProductAvailability < ActiveRecord::Base
        belongs_to :product
        belongs_to :location, class_name: "CompanyLocation", foreign_key: :company_location_id
    end

    class Product < ActiveRecord::Base
        has_many :availabilities, class_name: "ProductAvailability"
        has_many :locations, through: :availabilities
    end

I'm using the geocoder gem to get locations near the users position and the ransack gem to find products by a specific name.

I'm trying to merge the results, to get the products near a specific location:

    Product.ransack({ product_name: "SOME PRODUCT NAME" }).result.joins(:locations).merge(CompanyLocation.near(UserSession.last.coordinates))

But instead of the full products, I'm getting this result without the name, description or anything useful of the product:

    => #<ActiveRecord::Relation [#<Product id: 1, created_at: "2015-08-31 11:51:51", updated_at: "2015-08-31 11:51:51">, #<Product id: 1, created_at: "2015-08-31 11:51:51", updated_at: "2015-08-31 11:51:51">, #<Product id: 2, created_at: "2015-08-31 11:51:51", updated_at: "2015-08-31 11:51:51">, #<Product id: 2, created_at: "2015-08-31 11:51:51", updated_at: "2015-08-31 11:51:51">]>

Here the sql query:

    SELECT company_locations.*, 6371.0 * 2 * ASIN(SQRT(POWER(SIN((47.726645 - company_locations.latitude) * PI() / 180 / 2), 2) + COS(47.726645 * PI() / 180) * COS(company_locations.latitude * PI() / 180) * POWER(SIN((10.683412 - company_locations.longitude) * PI() / 180 / 2), 2))) AS distance, MOD(CAST((ATAN2( ((company_locations.longitude - 10.683412) / 57.2957795), ((company_locations.latitude - 47.726645) / 57.2957795)) * 57.2957795) + 360 AS decimal), 360) AS bearing FROM "products" INNER JOIN "product_availabilities" ON "product_availabilities"."product_id" = "products"."id" INNER JOIN "company_locations" ON "company_locations"."id" = "product_availabilities"."company_location_id" WHERE (company_locations.latitude BETWEEN 47.546780678816255 AND 47.90650932118374 AND company_locations.longitude BETWEEN 10.416022748982739 AND 10.950801251017262 AND (6371.0 * 2 * ASIN(SQRT(POWER(SIN((47.726645 - company_locations.latitude) * PI() / 180 / 2), 2) + COS(47.726645 * PI() / 180) * COS(company_locations.latitude * PI() / 180) * POWER(SIN((10.683412 - company_locations.longitude) * PI() / 180 / 2), 2)))) BETWEEN 0.0 AND 20)  ORDER BY distance ASC
As database system I'm using the Postgres.app in development and Rails 4.2.2

If I merge the products with company locations which where not found with geocoder but with a where condition it works.

    Product.ransack({ product_name: "SOME PRODUCT NAME" }).result.joins(:locations).merge(CompanyLocation.where(id: 1))

    SELECT "products".* FROM "products" INNER JOIN "product_availabilities" ON "product_availabilities"."product_id" = "products"."id" INNER JOIN "company_locations" ON "company_locations"."id" = "product_availabilities"."company_location_id" WHERE "company_locations"."id" = $1

    => #<ActiveRecord::Relation [#<Product id: 1, name: "Product 0", price_in_cent: 0, status: 0, created_at: "2015-08-31 11:51:51", updated_at: "2015-08-31 11:51:51", product_picture: "bfed1c5d-7fe8-4a58-92b4-7f8d9bc62179.jpg", order_link: nil, description: "0 Lorem ipsum dolor sit amet, consectetur adipisic...", count: 0, company_location_id: 2, creator_id: 2>, #<Product id: 2, name: "Product 1", price_in_cent: nil, status: 0, created_at: "2015-08-31 11:51:52", updated_at: "2015-09-01 15:10:29", product_picture: "6ae0d7f2-322d-4d11-8a67-8a55e47738ae.jpg", order_link: "", description: "1 Lorem ipsum dolor sit amet, consectetur adipisic...", count: 0, company_location_id: 1, creator_id: 2>]>

Is there maybe a bug in the geocoder gem?

**Comment by alexreisner** [comment]
I'm not familiar with the Ransack gem. Could you please try to isolate the problem more specifically within Geocoder so that it's more easily reproducible? Alternatively, try posting this to StackOverflow where more people will see it. It's probably also worth taking a look at the SQL Geocoder uses to accomplish its tasks and seeing how that might conflict with other parts of the queries you're generating.

**Comment by macfanatic** [comment]
I can confirm that this is a problem even without ransack (although I'm actually trying to solve the same problem outlined above).

```ruby
class User
  has_one :profile, inverse_of: :user, dependent: :destroy
end

class Profile
  has_one :address, as: :addressable, dependent: :destroy, required: true
end

class Address
  # geocoded
end
```

When running a query attempting to fetch users that have an address nearby, the `SELECT` part of the clause only contains information from the `addresses` table, and nothing about selecting from `users` or `profiles`.

```ruby
User.joins(profile: :address).merge(Address.near([lat, lng], 20).to_sql
# => e BETWEEN -104.01899941084797 AND 185.44456681084796 AND addresses.longitude BETWEEN -264.9477847465863 AND 116.93590214658624 AND (3958.755864232 * 2 * ASIN(SQRT(POWER(SIN((40.7127837 - addresses.latitude) * PI() / 180 / 2), 2) + COS(40.7127837 * PI() / 180) * COS(addresses.latitude * PI() / 180) * POWER(SIN((-74.00594130000002 - addresses.longitude) * PI() / 180 / 2), 2)))) BETWEEN 0.0 AND 10000) ORDER BY distance asc
```

I was able to solve the issue by specifying the `SELECT` clause explicitly, as outlined in the README under [Known Issue](https://github.com/alexreisner/geocoder#known-issue).

**This actually works**
```ruby
User.joins(profile: :address).merge(Address.near([lat, lng], 20, select: 'addresses.*, users.*, profiles.*').to_sql
```

Not the most elegant solution.  The suggestion of using `preload` didn't work for me here.
