### ISSUE TITLE
Mapquest key signup URL has changed

### ISSUE THREAD

**Issue by roychri** [alexreisner/geocoder#920]
The key signup url you have on the readme for Mapquest no longer works.
I think the right/new one is :
https://developer.mapquest.com/plans

More details about the recent changes:
http://devblog.mapquest.com/2015/08/17/mapquest-free-open-license-updates-and-changes/

**Comment by alexreisner** [comment]
Thanks! 25a45f9c9f3a61e0f68de83a1938ce01771d5ff9
