### ISSUE TITLE
undefined method `near' for #<Job:0x007fab13a1d6d0>

### ISSUE THREAD

**Issue by lucasstorti** [alexreisner/geocoder#926]
Hey, how are you?

I am having this issue. Here is my code

<% if @profession.include? job.profession.downcase && job.near(@user.coordinates)%>

Both, User and Job models have the geocoded_by, any suggest of what it can be?

Thanks!

**Comment by alexreisner** [comment]
You're calling `.near` on an instance of `Job`. It should be called on the `Job` class itself (eg: `Job.near(...)`).
