### ISSUE TITLE
Bulk rake not working

### ISSUE THREAD

**Issue by dfalling** [alexreisner/geocoder#927]
The after_validation hook is working great for me, but I can't get the bulk task to work.

When I run `rake geocode:all CLASS=Business SLEEP=0.25` in my Rails project, it finishes silently, but none of my models have been updated.  `Business.not_geocoded` returns the items I want updated, so I'm not sure what's going on.

How should I go about troubleshooting this?

Thanks!

**Comment by alexreisner** [comment]
How I would troubleshoot: look at the code executed in the Rake task and try running it in a console to see if geocoding is successful or, if not, why it failed.

**Comment by dfalling** [comment]
That got it.  Still no errors, but it showed me the save function isn't writing my lat/long back to the model.  Thanks!
