### ISSUE TITLE
.near unaffected by lookup stubs

### ISSUE THREAD

**Issue by ndelage** [alexreisner/geocoder#928]
**Problem**
`.near` doesn't appear to honor stubbed lookups.

**Test Scenario**
I've stubbed out a two zip codes:
```
> Geocoder::Lookup::Test.stubs
=> {"90291"=>[{:latitude=>33.9934, :longitude=>-118.4652}], "90401"=>[{:latitude=>34.0137, :longitude=>-118.4938}]}
```

And have an address model saved in the DB with the stubbed coordinates of the 2nd zip code (90401):
```
> Address.find(2)
=> #<Address:0x007fe6972472c0
 id: 2,
 street_address: nil,
 unit_number: nil,
 city: nil,
 state: nil,
 zip_code: "90401",
 created_at: Mon, 19 Oct 2015 10:50:40 CDT -05:00,
 updated_at: Mon, 19 Oct 2015 10:50:40 CDT -05:00,
 latitude: 34.0137,
 longitude: -118.4938>
```

Searching for address records using `.near` **with lat/long coordinates** returns the matching address record:
```
2.2.2 (#<Search::LocalInstructorSearch:0x007fe68efca9f0>):0 > Address.near([34.0137, -118.4938], 1)
=> [#<Address:0x007fe697b7fd10
  id: 2,
  street_address: nil,
  unit_number: nil,
  city: nil,
  state: nil,
  zip_code: "90401",
  created_at: Mon, 19 Oct 2015 10:50:40 CDT -05:00,
  updated_at: Mon, 19 Oct 2015 10:50:40 CDT -05:00,
  latitude: 34.0137,
  longitude: -118.4938>]
```

But searching with a zip code doesn't return the matching address:
```
> Address.near("90401", 1)
=> []
```

The existing "90401" stub appears to be working:
```
> Geocoder.search("90401")
=> [#<Geocoder::Result::Test:0x007fe697c25418 @cache_hit=nil, @data={:latitude=>34.0137, :longitude=>-118.4938}>]
```

**Comment by ndelage** [comment]
I've narrowed down the issue after looking at the `.near` scope implementation.

The scope first tries to determine the coordinates of the location argument. The following method call should return the stubbed coordinates, not `[0.0, 0.0]`:
```
> Geocoder::Calculations.extract_coordinates(location)
=> [0.0, 0.0]
```

Investigating further, `.extract_coordinates` calls `Geocoder.coordinates(location)`, which is also returning `[0.0, 0,0]`:
```
> Geocoder.coordinates("90401")
=> [0.0, 0.0]
```

Here's the `coordinates` [method](https://github.com/alexreisner/geocoder/blob/30f29bf5818788f67da527e3da0cde27e1bbbf7d/lib/geocoder.rb#L28):
```
##
# Look up the coordinates of the given street or IP address.
#
def self.coordinates(address, options = {})
  if (results = search(address, options)).size > 0
    results.first.coordinates
  end
end
```

`.coordinates` calls `.search`, which appears to return my stubbed result:
```
> Geocoder.search(location)
=> [#<Geocoder::Result::Test:0x007fe697b1ef38 @cache_hit=nil, @data={:latitude=>34.0137, :longitude=>-118.4938}>]
```

But calling `.first.coordinates` on the stubbed result is returning `[0.0, 0.0]`:
```
> Geocoder.search(location).first.coordinates
=> [0.0, 0.0]
```

Is this a bug in the gem? Or have I made a mistake in my stubbing?

**Comment by ndelage** [comment]
Doh! The keys for stubs must be strings **not symbols**. The `[0.0, 0.0]` was the result of the [coordinates method](https://github.com/alexreisner/geocoder/blob/30f29bf5818788f67da527e3da0cde27e1bbbf7d/lib/geocoder/results/base.rb#L30) in `Result::Base`:

```ruby
##
# A two-element array: [lat, lon].
#
def coordinates
  [@data['latitude'].to_f, @data['longitude'].to_f]
end
```

Any opposition to a PR that converts all stub keys to strings, so the interface supports both strings & symbols? At a minimum I think we should update the README.

**Comment by alexreisner** [comment]
Ah, ok. Let's just update the README. Auto-conversion sounds like overkill. Thanks!

**Comment by TrangPham** [comment]
I have added a note in the README. 

Thank you for bringing this issue up!

**Comment by ndelage** [comment]
Awesome! thanks @TrangPham

**Comment by naw** [comment]
Forcing string keys for test lookup stubs seems to be an unnecessary restriction. 

Latitude and longitude work fine with stubs built from symbols ---  for the particular case in this original issue (`near`), the underlying problem is that `Geocoder::Result::Test` doesn't define its own `coordinates` method.

`Geocoder::Result::Test` already defines getter methods for `latitude` and `longitude` (which work for both strings and symbols), so we could solve this with something trivial like:

```ruby
def coordinates
  [latitude, longitude]
end
```

Would you be open to such a PR?

Alternatively, if you really don't want to support symbol keys, would you be open to a PR that disallows them, rather than just a README note that says not to use them?

Thank you.

**Comment by alexreisner** [comment]
At the moment I can't think of a reason not to allow symbols other than potential confusion/unrealistic-ness of test code (in a real app your query would never be a symbol). But I think there there is a case to be made for supporting the use of symbols. @TrangPham any thoughts on this?
