### ISSUE TITLE
geocoder distance_to method brings Google API:  over query limit.

### ISSUE THREAD

**Issue by lucasstorti** [alexreisner/geocoder#929]
Hey Alex, how are you?

I saw some posts addressing this issue, but they were old and you said that this problem would be fixed.
(that's why I am asking a new question). I am using the following code:

@jobs = @jobs.sort { |x,y| x.distance_to(user.address) <=> y.distance_to(user.address) }

Which is a simple way to sort jobs by its distance from a user, right?
But when I run it, I get the following error:
Google Geocoding API error: over query limit.

Any idea of how I can solve this?

Thanks man!

**Comment by alexreisner** [comment]
Hmmm...I don't believe this is (or was ever) a Geocoder bug. Make sure to follow the README instructions very carefully. If you're using a key you must also use HTTPS (latest Geocoder release does this for you). Either way, as the error message says, you may be hitting your request limit with the Google API. If you don't think this is the case, please post more details about your configuration (eg, your `Geocoder.configure` block) and the environment in which you're using Geocoder (eg: shared hosting? local dev machine?).
