### ISSUE TITLE
Add Mapbox lookup

### ISSUE THREAD

**Issue by AndyDangerous** [alexreisner/geocoder#931]
I have [worked on a lookup](https://github.com/AndyDangerous/geocoder/tree/mapbox) using [mapbox](https://www.mapbox.com/developers/api/geocoding/) as the geocoding service for a personal project. Would that be a good addition to this project? If so then I will open a PR. Any thoughts or feedback from this community would be great.

Thanks!

**Comment by alexreisner** [comment]
Yep! Would like to see that. See #617 and #591 for good examples of adding lookups.
