### ISSUE TITLE
Depends on `Net::OpenTimeout` not available in Ruby 1.9.3

### ISSUE THREAD

**Issue by paulmenzel** [alexreisner/geocoder#935]
Geocoder 1.2.11 throws a name error in `geocoder-1.2.11/lib/geocoder/lookups/base.rb:286:in `rescue in make_api_request'` with Ruby 1.9.3.

```
$ bundle exec ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
```

**Comment by paulmenzel** [comment]
The fix should be similar to [the one in quickpress](https://github.com/alexdantas/quickpress/commit/bdf4e2ffc7337ac97546cecc9ae970283cc3dbcb).

**Comment by alexreisner** [comment]
I think this was handled by #922. New version needs to be released (will do soon).

**Comment by paulmenzel** [comment]
Indeed. Closing as duplicate of #922.
