### ISSUE TITLE
MySQL Not Working on Travis

### ISSUE THREAD

**Issue by alexreisner** [alexreisner/geocoder#937]
See [the build](https://travis-ci.org/alexreisner/geocoder/builds/88168897) for details. It works with JRuby but not Rubinius or classic. Seeing load errors, but slightly different for each Rails version:

    # Rails 3.2
    /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/rubygems_integration.rb:266:in `block in replace_gem': Please install the mysql2 adapter: `gem install activerecord-mysql2-adapter` (can't activate mysql2 (~> 0.3.10), already activated mysql2-0.4.1. Make sure all dependencies are added to Gemfile.) (LoadError)

    # Rails 4.1
    /home/travis/.rvm/gems/ruby-2.2.0/gems/activerecord-4.1.13/lib/active_record/connection_adapters/connection_specification.rb:190:in `rescue in spec': Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)

    # Rails 4.2
    /home/travis/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec': Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)

@TrangPham any thoughts?

**Comment by TrangPham** [comment]
The last time I see the build green was this build: 
`v1.2.10 Prepare for release of gem version 1.2.10.` 
https://travis-ci.org/alexreisner/geocoder/builds/79198086

I don't see a change around there that might have this affect. I will take a peak into the gemfiles.

**Comment by TrangPham** [comment]
:3 Can be closed.
