### ISSUE TITLE
How to use km for default.

### ISSUE THREAD

**Issue by anhnvbk93** [alexreisner/geocoder#939]
Hi, sir. could you show me how to set distance unit to km  intead of using mile. Thanks
Example: my_location.distance.round(2)

**Comment by jrumbut** [comment]
You can either call `Geocoder.configure(:units => :km)` before creating my_location or, if you're using Rails, you can put this line in your initializer: `units: :km`

Hope this helps!

**Comment by alexreisner** [comment]
This is covered in the README as it relates to:

* [a single `near` query](https://github.com/alexreisner/geocoder#location-aware-database-queries)
* [lookup configuration](https://github.com/alexreisner/geocoder#geocoding-service-lookup-configuration)

**Comment by anhnvbk93** [comment]
thank you all
