### ISSUE TITLE
geocoded_by postal_code or by zip_code

### ISSUE THREAD

**Issue by 0ldtimer** [alexreisner/geocoder#940]
Wait for the dumb question.... We recently added US locations to our app and we'd like to geocode by CDN postal code OR by US zip codes.  Is it possible to do something like this (which of course doesn't appear to work at the moment for us):

`geocoded_by (:postal_code ? :postal_code : :zip_code) do |obj,results|`

Thanks!

**Comment by alexreisner** [comment]
I think this is what you're looking for:

    geocoded_by :postal_code_or_zip_code

    def postal_code_or_zip_code
      postal_code || zip_code
    end
