### ISSUE TITLE
Mapbox coordinates reversed?

### ISSUE THREAD

**Issue by marcusat** [alexreisner/geocoder#942]
For the results from Mapbox, I think the interpretation of the @data["geometry"]["coordinates"] results should be reversed, as they return [longitude, latitude].

Likewise for reverse geocoding queries they expect the query string to be {lon},{lat}.json

**Comment by alexreisner** [comment]
Are you sure, according to [the documentation](https://www.mapbox.com/developers/api/geocoding/), it returns data in [Carmen GeoJSON format](https://github.com/mapbox/carmen/blob/master/carmen-geojson.md) which appears to return `[lat,lon]`, though they're not explicit about that. Are you seeing different results? If so, it would seem like a mistake that Mapbox will correct (?).

**Comment by marcusat** [comment]
Thanks for the rapid response.  Looking at the Carmen link you send though, both the examples and text seem to say [lon,lat]?  Eg [-97.7559964, 30.3071816] must be [lon,lat] and "center...Array of the form [lon,lat]"

**Comment by alexreisner** [comment]
Ack! Sorry, you're right. This kind of thing should probably be reflected in the tests... Open to pull request (would be great to add test that fails with current code).

**Comment by alexreisner** [comment]
Fixed by #946.

**Comment by marcusat** [comment]
Thanks Alex!
