### ISSUE TITLE
near in mongodbb

### ISSUE THREAD

**Issue by sahin** [alexreisner/geocoder#945]
starting to get 
 The .near method will be removed for MongoDB-backed models in Geocoder 1.3.0. Please use MongoDB's built-in query language instead

Is geocoder suggesting a new method for near that use mongodb native 
built-in query lang.

**Comment by alexreisner** [comment]
Yes. Or, Mongoid provides a wrapper around the built-in language:

http://mongoid.github.io/en/mongoid/docs/querying.html#geo_near
