### ISSUE TITLE
Search: site-wide search doesn't filter by location

### ISSUE THREAD

**Issue by rstacruz** [alexreisner/geocoder#948]
When searching the site using the search bar (`/search`), you don't have a filter-by-location.

![pasted_image_11_19_15__4_26_pm](https://cloud.githubusercontent.com/assets/74385/11263000/52f9cb06-8eda-11e5-95b6-8039527d46a3.png)

However, when searching from the articles (`/articles/search`), the location filter is available.

![pasted_image_11_19_15__4_27_pm](https://cloud.githubusercontent.com/assets/74385/11263010/76e3ec0e-8eda-11e5-9015-69d0d8cb1140.png)

This is an issue because according to Brennan, the spec should've been "searching from the homepage should let me search articles related to my location".

**Comment by alexreisner** [comment]
Hey, did you post this (and #947) on the wrong project?

**Comment by rstacruz** [comment]
embarassing :| sorry!

**Comment by rstacruz** [comment]
embarassing :| sorry!

**Comment by alexreisner** [comment]
Haha! No worries at all.
