### ISSUE TITLE
Geocoder.coordinates bug

### ISSUE THREAD

**Issue by stevenjwolfman** [alexreisner/geocoder#952]
Geocoder.coordinates("65 11th Avenue, New York, NY 10011, USA") yields [40.7143528, -74.0059731]
In google, (https://www.google.com/maps/place/65+11th+Ave,+New+York,+NY+10011/@40.7426699,-74.0104227,17z/data=!3m1!4b1!4m2!3m1!1s0x89c259c0c1c39065:0x2fe23f578972315b) it yields [40.742662, -74.008245]
Clearly there is a discrepancy.

**Comment by alexreisner** [comment]
Please see #718

**Comment by stevenjwolfman** [comment]
@alexreisner If I put any address into geocoder it returns the same exact GPS coordinates
(byebug) Geocoder.coordinates("New Orleans")
[40.7143528, -74.0059731]
(byebug) Geocoder.coordinates("Holllywood, California")
[40.7143528, -74.0059731]
Clearly there is something major wrong with the system

**Comment by alexreisner** [comment]
Hmmm... Can you post your `Geocoder.configure` block?

**Comment by stevenjwolfman** [comment]
@alexreisner (byebug) Geocoder.configure
nil
Its not working in my testing framework and the testing framework of my coworker on her computer but it works in my rails console

**Comment by alexreisner** [comment]
Is there something in your test framework that's intercepting/caching network activity?

**Comment by stevenjwolfman** [comment]
I looked it up... someone made a default stub in my system... I'm sorry for bothering you. Thanks for your time.
