### ISSUE TITLE
coordinates/to_coordinates not working with yesterday's release

### ISSUE THREAD

**Issue by whoteaches** [alexreisner/geocoder#959]
Hey Alex,
I just upgraded to geocoder 1.2.13 (was 1.2.12), and I get errors on coordinates:
Example from console:

    a = "76.91.184.67"

in version 1.2.12:

    Geocoder.coordinates(a) => [34.1379, -118.3919] 

in version 1.2.13:

    Geocoder.coordinates(a)
    NoMethodError: undefined method `to_hash' for ["city", {"geoname_id"=>5399438, "names"=>{"en"=>"Studio City"}}]:Array

Also:

    Geocoder.to_coordinates(a)
    NoMethodError: undefined method `to_coordinates' for Geocoder:Module

Could you please advise?
Thanks!

**Comment by alexreisner** [comment]
Could you post your `Geocoder.configure` block? And also the first few lines of backtrace (including line numbers) with your error?

Also, `to_coordinates` should be called on a geocodable object, not on the `Geocoder` module.

**Comment by alexreisner** [comment]
Please see #962
