### ISSUE TITLE
Geocoding API not responding fast enough (only in production)

### ISSUE THREAD

**Issue by brendon** [alexreisner/geocoder#96]
I'm getting this message when trying to call Geocoder.search either in the rails app, or at the console, but only in production mode:

Geocoding API not responding fast enough (see Geocoder::Configuration.timeout to set limit).
 => []

Development mode works fine (on the same machine and using the same user account). I'm running Ubuntu Desktop 11.04.

I just also tried on my mac and the same problem happens there. Is this a bug?

**Comment by SebFalque** [comment]
Hello,
I had the same issue (working in development and not on production servers) and increasing the timeout solved the issue.
Thanks !

**Comment by monicao** [comment]
It is worrying that it could take the geocoding services as much as 15 seconds to geocode the IP.

Does anyone have any information about which service is fastest?

**Comment by pitops** [comment]
hmm this problem seems to persist after all these years..what is the root cause of this? It worked like 1 month ago.

**Comment by ryanwanger** [comment]
It's been brutally slow for me too in the last week or two (in production only). Had to move it into javascript so it wasn't tying up the whole page (which, of course, we should have done long ago).

@tomeric Can you explain more about changing the DNS servers?

**Comment by tomeric** [comment]
I'm sorry @ryanwanger, but that comment was made almost 5 years ago, so I can't remember the specifics anymore.

**Comment by ryanwanger** [comment]
Welp, it was worth a try. :-)

**Comment by aymericbouzy** [comment]
I have the same problem, and I'm using heroku in production (it's still a small project ...), I'm not sure I'll be able to change the DNS servers ...

**Comment by FNGR2911** [comment]
Just if somebody got the same issues: I've figured out that the little bad body [Little Snitch ](https://www.obdev.at/products/littlesnitch/index-de.html) was my problem in Dev ;)

**Comment by edap** [comment]
@ryanwanger I'm having the same problem. Did you manage to fix it?

**Comment by kpandya91** [comment]
If anyone else is having the same problem on Mac (development), I had to turn off ipv6 (`networksetup -setv6off "Wi-Fi"`) for it to work with Google.

**Comment by modusss** [comment]
I have the same problem here in development. Sometimes is ok, and sometimes even 60 seconds of timeout (in geocoder.rb file) don't run. Obs: i'm using ubuntu.

**Comment by MJEGOMJEGO** [comment]
@modusss , did you find the solution ?

**Comment by v2lrf** [comment]
> @modusss , did you find the solution ?

Hey yes it seems to work have o look on the process here; 
but it's not a good idea to keep that setup always like this .
This issue is may be caused by the world quarantine
[setup ipv6](https://www.privateinternetaccess.com/helpdesk/kb/articles/do-i-need-to-disable-ipv6-traffic-on-my-mac-computer)

**Comment by MJEGOMJEGO** [comment]
Thanks @v2lrf ! What do you mean by the world quarantine ?  Where did you get this info ?
I saw this problem happens frequently since many years !
