### ISSUE TITLE
Invalid location for ip with google ip_lookup

### ISSUE THREAD

**Issue by aashish** [alexreisner/geocoder#960]
I am getting invalid location for ip with google ip_lookup
The following is the code
```
 
 :020 >   Geocoder.configure(:ip_lookup=>:google)
 => {:timeout=>3, :lookup=>:google, :ip_lookup=>:google, :language=>:en, :http_headers=>{}, :use_https=>false, :http_proxy=>nil, :https_proxy=>nil, :api_key=>nil, :cache=>nil, :cache_prefix=>"geocoder:", :always_raise=>[], :units=>:mi, :distances=>:linear} 
 :021 > 
 :030 >   Geocoder.search("115.111.228.178").first.address
 => "Selim Özer, 2373. Sk., 71300 Kırıkkale Merkez/Kırıkkale, Turkey" 
 :031 > 
 :032 >   Geocoder.search("173.194.41.231").first.address 
 => "Yeşilyurt, 41. Sk., 49200 Muş Merkez/Muş, Turkey" 
 :033 >
```

with reference to iplocation.net 
for ip 173.194.41.231 the location is California, US. 
for ip 115.111.228.178 the location is Hyderabad, IN. 

Are you getting same error. 

Thanks,
Aashish

**Comment by alexreisner** [comment]
The problem is that there are two different kinds of lookups: street and IP address. Google is for street addresses. Please try one of the services listed in the [IP address services section of the readme](https://github.com/alexreisner/geocoder#ip-address-services).
