### ISSUE TITLE
Bug in Geoip2 lookup

### ISSUE THREAD

**Issue by mromulus** [alexreisner/geocoder#962]
Starting with 1.2.13, geoip2 with hive_geoip2 lookup results have data in wrong format, giving error:

```
NoMethodError: undefined method `to_hash' for #<Array:0x007f12bad47de8>
[GEM_ROOT]/gems/geocoder-1.2.13/lib/geocoder/results/geoip2.rb, line 60
```

The error occurs due to Array() cast in geoip2.rb at https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/geoip2.rb#L40

which transforms hive geoip result into array that does not have to_hash. Test suite does not seem to catch it, as the result is always mocked in correct format

**Comment by alexreisner** [comment]
@davydovanton this looks related to #955

**Comment by alexreisner** [comment]
Reverted 97b6bb948f9c29, which should fix this.
