### ISSUE TITLE
Issue with Rails 5 beta - Geocoder::Request can't be initialized

### ISSUE THREAD

**Issue by simzen85** [alexreisner/geocoder#966]
I just upgraded my app to Rails 5 beta and it seems that Geocoder::Request can't be initialized, hence request.location (using in my View) returned this 

"undefined method `location' for #<ActionDispatch::Request:0x007f91127f3280>"

Can someone help me with this ? Tks

**Comment by TrangPham** [comment]
Yes, could you give us more information on the bug you are seeing? Specifically:
1) What is your rails, ruby and geocoder versions?
2) Could you post the whole console log for your error?

Thanks

**Comment by simzen85** [comment]
@TrangPham 
Rails : 5.0.0.beta1
Ruby : 2.3.0
Geocoder : 1.2.14

log

App 4253 stdout: NoMethodError - undefined method `location' for #<ActionDispatch::Request:0x007fcc8372b530>:
App 4253 stdout:   app/views/home/index.html.slim:180:in `block in _app_views_home_index_html_slim___3830065459718013949_70258207558240'
App 4253 stdout:   actionview (5.0.0.beta1) lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
App 4253 stdout:   actionview (5.0.0.beta1) lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
App 4253 stdout:   actionview (5.0.0.beta1) lib/action_view/helpers/capture_helper.rb:39:in `capture'
App 4253 stdout:   actionview (5.0.0.beta1) lib/action_view/helpers/capture_helper.rb:153:in `content_for'

**Comment by simzen85** [comment]
@TrangPham were you able to reproduce this or do you need any other info from me ? Tks

**Comment by TrangPham** [comment]
@simzen85 I cannot reproduce the issue. I believe there is something wrong specifically your configuration and/or environment. 

Steps to try to reproduce:
1 - Use ruby 2.3.0 and rails 5.0.0.beta1
2 - rails new test_project
3 - added gems to gemfile: sqlite3, redis, geocoder
4 - added geocoder config
```ruby
Geocoder::Configuration.timeout = 4
Geocoder::Configuration.lookup = :google
Geocoder::Configuration.cache = Redis.new
Geocoder::Configuration.cache_prefix = "geocoder-test:"
```

5 - added place model
```ruby
class Place < ApplicationRecord
	geocoded_by :address   # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates
end
```
```ruby
class CreatePlaces < ActiveRecord::Migration[5.0]
  def change
    create_table :places do |t|

      t.string :address
      t.float :latitude
      t.float :longitude
      t.timestamps
    end
  end
end
```

6 - tested using rails console:
```ruby
thu-mbp:rails50 thu$ rails c
PlacesRunning via Spring preloader in process 47864
Loading development environment (Rails 5.0.0.beta1)
2.3.0 :001 > Place.all
  Place Load (1.4ms)  SELECT "places".* FROM "places"
 => #<ActiveRecord::Relation []>
2.3.0 :002 > p = Place.new(address: '792 Gladstone Ave, Ottawa, Ontario, K1R6X2')
 => #<Place id: nil, address: "792 Gladstone Ave, Ottawa, Ontario, K1R6X2", latitude: nil, longitude: nil, created_at: nil, updated_at: nil>
2.3.0 :003 > p.save!
   (0.2ms)  begin transaction
  SQL (1.3ms)  INSERT INTO "places" ("address", "latitude", "longitude", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?)  [["address", "792 Gladstone Ave, Ottawa, Ontario, K1R6X2"], ["latitude", 45.4061245], ["longitude", -75.70760589999999], ["created_at", 2016-01-17 15:05:24 UTC], ["updated_at", 2016-01-17 15:05:24 UTC]]
   (0.9ms)  commit transaction
 => true
2.3.0 :004 > Place.first
  Place Load (1.5ms)  SELECT  "places".* FROM "places" ORDER BY "places"."id" ASC LIMIT ?  [["LIMIT", 1]]
 => #<Place id: 1, address: "792 Gladstone Ave, Ottawa, Ontario, K1R6X2", latitude: 45.4061245, longitude: -75.70760589999999, created_at: "2016-01-17 15:05:24", updated_at: "2016-01-17 15:05:24">
2.3.0 :005 >
```

**Comment by simzen85** [comment]
@TrangPham can you try to create a view and access .location from there (refer to my first post) ? 

The error is that ActionDispatch::Request doesn't understand .location (since Geocoder::Request wasn't initialized), so your steps to reproduce weren't sufficient

**Comment by TrangPham** [comment]
Ah sorry I did not fully understand the use case.

For your use case you have a Request object which includes Geocoder::Request? And you're passing this to the view in your controller? Is that the use case you have?

**Comment by simzen85** [comment]
@TrangPham 
"a Request object which includes Geocoder::Request? And you're passing this to the view in your controller" yes, and this is the default behaviour in Geocoder with previous Rails.

In more detail, you can try to insert this line in config/application.rb

config.middleware.use Geocoder::Request

There is an error when Geocoder::Request can't be initialized.

**Comment by TrangPham** [comment]
Cannot reproduce issue for request.location:

Additional steps to reproduce:
1. add into geocoder config
```ruby
Geocoder::Configuration.ip_lookup = :freegeoip
```
2. create PlaceRequest class
```ruby
module PlaceHelper
	class PlaceRequest < Rack::Request
		include Geocoder::Request
		def initialize(ip)
			super({'REMOTE_ADDR' => ip})
		end
	end
end
```
3. create controller
```ruby 
class PlaceController < ApplicationController
	include PlaceHelper
	def index
		@request = PlaceRequest.new('74.200.247.59')
		@location = @request.location
	end
end
```
4. add in view
```ruby
Request.location
<%= @request.location %>

Location
<%= @location %>
```
5. add in routes
```ruby 
resources :place
```
6. run rails server and go to localhost:####/place
```pre
Request.location #<Geocoder::Result::Freegeoip:0x007fa2e99f21d8> Location #<Geocoder::Result::Freegeoip:0x007fa2e99f21d8>
```

**Comment by TrangPham** [comment]
@simzen85 


Your issue is that you're not using Rack::Request. Geocoder::Request is included in previous versions of geocoder but only ever for Rack::Request. https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/request.rb#L81

If I change my controller to use `ActionDispatch::Request` then it does give me the error you're seeing: 
```
undefined method `location' for #<ActionDispatch::Request:0x007fa2f131f538>
```
Since geocoder does not include Geocoder::Request onto ActionDispatch::Request , if you want to continue using ActionDispatch::Request and get `.location` then please include Geocoder::Request in your ActionDispatch::Request.

**Comment by alexreisner** [comment]
This does appear to be a problem with the way Geocoder is being loaded. I can reproduce by creating a clean 5.0.0beta1 app and calling `request.location` from a controller action.

**Comment by simzen85** [comment]
@TrangPham tks for your suggestion, I can fix the problem by inserting this line in config/application.rb

ActionDispatch::Request.send :include, Geocoder::Request

but maybe there is a long-term fix for it ? Thanks.

**Comment by TrangPham** [comment]
@alexreisner Could you post what your controller action looks like? I want to understand why I was not able to reproduce. Was I using request.location incorrectly?

**Comment by alexreisner** [comment]
@TrangPham It's just a one-liner:

    def test
      @loc = request.location
    end

I think the problem was that you created a `@request` object, rather than working with the one in the controller.

**Comment by TrangPham** [comment]
Issue was caused by this change: https://github.com/rails/rails/commit/529136d670c46bd66b56c519d4f51ed8f86c75b1 (September 4th 2015) ActionDispatch::Request stopped inheriting from Rack::Request

Note that https://github.com/rails/rails/commit/319ae4628f4e0058de3e40e4ca7791b17e45e70c (Jan 27, 2009) ActionController::Request was changed to ActionDispatch::Request. This happened since rails 3 and geocoder does not actively support rails 2. So we can safely do the following:

**Beginner task:**

Include Geocoder::Request in ActionDispatch::Request instead of Rack::Request https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/request.rb#L81L83
