### ISSUE TITLE
Google request denied.

### ISSUE THREAD

**Issue by jgoodall628** [alexreisner/geocoder#969]
Hello,
I am currently getting Google Geocoding API error: request denied. for any geocoding that I do. I believe this is to do with the fact that I am using Telize for ip lookup and google for address lookup. Telize requires that :api_key be set in the config file and I believe this is causing that api key to be sent to google during normal address searches causing the error. Is there any way to fix this?

My config file:
Geocoder.configure(
  # geocoding service
  lookup: :google,

  # geocoding service request timeout (in seconds)
  timeout: 30,

  # default units
  units: :mi,

  ip_lookup: :telize,
  api_key: Rails.application.secrets.telize_key

)

**Comment by TrangPham** [comment]
Yes - see the README: https://github.com/alexreisner/geocoder#geocoding-service-lookup-configuration

I think you could do:
```ruby
Geocoder.configure(
# geocoding service
lookup: :google,

# geocoding service request timeout (in seconds)
timeout: 30,

# default units
units: :mi,

ip_lookup: :telize,

# specific to telize only
:telize => {
  :api_key: Rails.application.secrets.telize_key
}
)
```
