### ISSUE TITLE
Fix Warnings During Tests

### ISSUE THREAD

**Issue by alexreisner** [alexreisner/geocoder#976]
I'm seeing the following warnings appear during tests with Ruby 2.3.0:

    lib/geocoder/lookups/base.rb:182: warning: constant Geocoder::Lookup::Base::TimeoutError is deprecated
    lib/geocoder/lookups/base.rb:182: warning: constant Geocoder::Lookup::Base::TimeoutError is deprecated
    test/unit/error_handling_test.rb:44: warning: constant ErrorHandlingTest::TimeoutError is deprecated
    test/unit/error_handling_test.rb:49: warning: constant ErrorHandlingTest::TimeoutError is deprecated
    test/test_helper.rb:126: warning: constant Geocoder::Lookup::Base::TimeoutError is deprecated

And also this warning/error (with multiple Ruby versions):

    Geportail.lu Geocoding API error

**Comment by TrangPham** [comment]
Beginner task: 

1) Isolate the test which causes `Geportail.lu Geocoding API error` to be printed out.
Start by running the tests one-by-one and checking output for tests in https://github.com/alexreisner/geocoder/blob/master/test/unit/lookups/geoportail_lu_test.rb

2) Determine if the error should occur

3) If error should occur then change the silence it in the test (see https://github.com/alexreisner/geocoder/pull/843 as an example)
If error should not occur then fix the test

**Comment by TrangPham** [comment]
Thanks for the fixes @lime and @rehan-work (#979) :dancer:
