### ISSUE TITLE
Oracle Issue

### ISSUE THREAD

**Issue by jayhuber** [alexreisner/geocoder#977]
If you wish your gem to have greater database visibility; Oracle does not have PI() available in sql.  But, in its place you can use "asin(1)*2" or "acos(-1)" which I believe will work for the other database systems too.  I was able to manually run the query with this change - and will either monkey patch or make a copy of them gem.  

Yes - Oracle with Rails, its not as bad as people think.

**Comment by TrangPham** [comment]
Hi @jayhuber,

Thanks for bringing this up. We welcome you to make the change directly and create a pull-request. All the sql databases that we currently support are all tested on Travis so just make sure that the build is green and you're good to go. :)

**Comment by alexreisner** [comment]
PR still welcome, closing this for now due to inactivity.
