### ISSUE TITLE
Latitude Longitude are String 

### ISSUE THREAD

**Issue by syedali90** [alexreisner/geocoder#978]
We have Lat-long in our database as String .. Will this make any difference in result of near query ?

**Comment by TrangPham** [comment]
It should not make a difference since the near functions call .to_f on the lat and long in the underlaying sql queries.

**Comment by alexreisner** [comment]
However it will make a difference if you're trying to query lat/lon columns that contain strings. That probably won't work, since the values are used in mathematical calculations.
