### ISSUE TITLE
Mongoid: .near doesn't work with scopes

### ISSUE THREAD

**Issue by gjb83** [alexreisner/geocoder#98]
**Environment**

* Ruby 1.9.2
* Rails 3.1.0.rc5
* MongoDB 1.8.2
* Mongoid 2.0.2

`.near` works as expected when called against a model:

```
> Item.near('London', 50)
=> #<Mongoid::Criteria
  selector: {:coordinates=>{"$nearSphere"=>[-0.1262362, 51.5001524], "$maxDistance"=>0.012630230737833089}},
  options:  {},
  class:    Item,
  embedded: false>
```

However, the following error occurs if I call `.near` against a scope:

```
> i = Item.all
=> #<Mongoid::Criteria
  selector: {},
  options:  {},
  class:    Item,
  embedded: false>

> i = i.near('London', 50)
ArgumentError: wrong number of arguments (2 for 1)
	from /usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/mongoid-2.0.2/lib/mongoid/criterion/inclusion.rb:137:in `near'
	from (irb):7
	from /usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/railties-3.1.0.rc5/lib/rails/commands/console.rb:45:in `start'
	from /usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/railties-3.1.0.rc5/lib/rails/commands/console.rb:8:in `start'
	from /usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems/railties-3.1.0.rc5/lib/rails/commands.rb:40:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

It appears that the `.near` method from geocoder is being replaced by the standard Mongoid method.

**Comment by msquitieri** [comment]
It seems like there is a conflict between the geocoder scope `:near` (found [here](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/stores/mongo_base.rb#L15)) and mongoid's method `near` (found [here](https://github.com/mongoid/origin/blob/master/lib/origin/selectable.rb#L334))

Is there a way to reconcile the two?

**Comment by alexreisner** [comment]
See #832.
