### ISSUE TITLE
GeoLite2 (:geoip2) request.location.ip returns nil

### ISSUE THREAD

**Issue by alereisan** [alexreisner/geocoder#981]
Hi, I have set up geocoder to do the IP lookup locally with [GeoLite2](https://github.com/alexreisner/geocoder#geolite2-geoip2) (I am using the free GeoLite2-Country.mmdb binary database). 

It works pretty good for my needs, but I can't use `request.location.ip` anymore, to return the visitors IP address. It returns nil.

`request.location.country_code` works btw (returns "AT" = country code for my country)

**Comment by TrangPham** [comment]
Hi @alereisan 

You should be able to get the ip from `request.ip` directly. This will be the ip that was used to query the GeoipLite2 database. The `request.location` is the returned data of the query.

**Comment by alereisan** [comment]
works perfectly, thanks!
