### ISSUE TITLE
Is it possible to query "near" multiple locations?

### ISSUE THREAD

**Issue by Carpela** [alexreisner/geocoder#983]
I'm trying to optimise some queries and need to run an OR search against multiple locations. 
Wondering if I can reduce the number of queries (am currently running them in parallel) by only searching once but taking into account multiple locations.

**Comment by alexreisner** [comment]
Take a look at the [`Geocoder::Sql` module](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/sql.rb). I think you should be able to use it to assemble a custom query with multiple near conditions.

**Comment by dlamichhane** [comment]
Is there any luck? @Carpela
