### ISSUE TITLE
Yahoo Geocoding API error: 500 (non 200 status code from backend: 404).

### ISSUE THREAD

**Issue by dchapman1988** [alexreisner/geocoder#988]
```
>> Geocoder::Configuration.lookup = :yahoo
>> Geocoder::Configuration.api_key = [YAHOO_PLACEFINDER_KEY, YAHOO_PLACEFINDER_SECRET]
>> Geocoder.search("1600 Pennsylvania Ave NW, Washington, DC 20500")
Yahoo Geocoding API error: 500 (non 200 status code from backend: 404).
=> []
```

Is anyone else having this issue? I've had this gem running in a legacy app for over 5 years, and this started happening EOB yesterday.

**Comment by alexreisner** [comment]
See #320 and #986. PlaceFinder was shut down over three years ago. BOSS will be shut down next month. Unfortunately you're going to have to find another geocoding service.

**Comment by jetheredge** [comment]
We are getting the same thing, we are using the Yahoo BOSS services. Looks like they are shutting down early.
