### ISSUE TITLE
Google premier issue with new premium plan users

### ISSUE THREAD

**Issue by cracadumi** [alexreisner/geocoder#994]
New Google map premier users don't need to specify a client_id anymore (since january 2016). 
Hence what should the api_key: argument look like in config ?
I have just specified the api key in the array (as I don't have any client ID) and I keep getting this error : 

> Geocoding API's response was not valid JSON: Unable to authenticate the request. Provided 'signature' is not valid for the provided client ID, or the provided 'client' is not valid.

Thanks

**Comment by cracadumi** [comment]
Fixed by using lookup: :google instead of :google_premier

**Comment by alexreisner** [comment]
Looks like there is a new ["Premium" plan](https://developers.google.com/maps/premium/overview#welcome-to-the-google-maps-apis-premium-plan) with different authentication requirements. A new service should probably be added. It's hard to tell whether `:google_premier` will continue to be supported--Google seems to have removed all references to it from their documentation.

**Comment by jlhonora** [comment]
We started with the Maps for Work license on March 2nd, 2016. `:google_premier` works perfectly with this gem, although we do have a client id.

**Comment by alexreisner** [comment]
@jlhonora thanks for the info.

**Comment by jsantos** [comment]
After specifying `api_key: <api_key>, <client_id>, <channel>`, I get the following (while reverse geocoding):

```
Geocoding API's response was not valid JSON: Unable to authenticate the request. Provided 'signature' is not valid for the provided client ID, or the provided 'client' is not valid.
The signature was checked against the URL: /maps/api/geocode/json?channel=<my_channel>&client=gme-<my_org>&language=en&latlng=1.3255032441%2C103.8858785163&sensor=false
If this does not match the URL you requested, please ensure that your request is URL encoded correctly. Learn more: https://developers.google.com/maps/documentation/business/webservices/auth
```

**Comment by kyleramirez** [comment]
@jsantos I'm using maps premium, and have a cryptographic key and a client ID ... but what is the channel part? I've tried lots of configurations to no avail. What configuration did you use that worked with Google Maps Premium?

**Comment by jsantos** [comment]
@kyleramirez The `channel` is meant to be used if you want to track your usage across different applications with [Channels data](https://developers.google.com/maps/premium/reports/usage-reports#channels).

I needed it but I don't think it's mandatory. In my case I define the channel as the base host of the app (as I have a different host per client project). That way I can track how much of my premium plan a specific client is consuming.

**Comment by kyleramirez** [comment]
@jsantos Much thanks. I just happened to figure it out, but without your tip I wouldn't have. For people using Google Maps OEM, I used

    Geocoder.configure(
      lookup: :google_premier,
      api_key: [
        "mycryptographickey=",
        "gme-myclientid",
        "anything"
      ],
      use_https: true
    )

**Comment by alexreisner** [comment]
Closing, because I think this is resolved, but please re-open if there are any lingering issues.
