### ISSUE TITLE
no way to catch empty and react on that

### ISSUE THREAD

**Issue by AaronGaim** [alexreisner/geocoder#999]
How can I find if the geocoded failed? and change `geocoded_by` to only `city, country` and not `street, city, country` as at the first try?

**Comment by TrangPham** [comment]
Hey @AaronGaim 

You can check if the geocode result was empty itself. 
```ruby
results = Geocoder.search('Ottawa, Canada')
if results.empty?
  # do something
end
```

Also the geocoded_by will take whatever you pass it. This can be set in your model.
For example if the model has fields `city` and `country`:
```ruby
geocoded_by :city, :country
```

Does this answer your questions?

**Comment by AaronGaim** [comment]
Thank you @TrangPham
What I what to do is in the model:

    class Test < ActiveRecord::Base
        geocoded_by :address, :city, :country
        after_validation :geocode, if: ->(obj){ obj.latitude.blank? || obj.address_changed? }
        after_validation :cordcreated?

        def cordcreated?
              results = Geocoder.search(:address, :city, :country)
              if results.empty?
                  geocoded_by :city, :country            ### run it again but without `address`
              end
        end

**Comment by TrangPham** [comment]
Awesome! Glad I could help :+1:
